### ISSUE TITLE
Newlines are removed from description

### ISSUE THREAD

**Issue by btilford** [nestjs/swagger#1038]
## I'm submitting a...
[X] Bug report

## Current behavior
Swagger/OpenAPI supports markdown content within the `description` text however somewhere along the processing newlines are being removed from the string which limits the usefulness of using markdown.

## Expected behavior
Newlines are preserved within `description` strings.

## Minimal reproduction of the problem with instructions
Example controller
```
@Controller('/')
export class ExampleController {

  @ApiOperation({
     summary: 'Plain text',
     description: `## Ping Pong

Will you get a **pong** response?`
   })
   @Get('/')
   async ping():Promise<{text:string}> { return {text: 'pong'};}
}
```
## What is the motivation / use case for changing the behavior?
Developing public facing APIs that need to have more than 1 line of documentation.

## Environment

```
"@nestjs/common": "~7.5.1",
"@nestjs/swagger": "~4.7.2",
```

 
For Tooling issues:
- Node version: v12.16.3
- Platform:  Linux

Others:
I've been able to workaround this using `<br>` but this isn't ideal.

**Comment by kamilmysliwiec** [comment]
I believe this should be reported in the `swagger-ui-express` package https://github.com/scottie1984/swagger-ui-express as we simply pass the `description` parameter down to this library
