### ISSUE TITLE
Reusing the classes

### ISSUE THREAD

**Issue by rajashekhargundeti** [nestjs/swagger#1059]
we have a class called Range.

We would like to reuse the same definition in DTOs of request and response. our requirement is 
min and max attribute of Range class are optional in the request and mandatory in the response we send.

export class Range {
    @ApiModelProperty({ type: Number, required: false })
    @IsOptional()
    @IsNumber()
    public min: number

    @ApiModelProperty({ type: Number, required: false })
    @IsOptional()
    @IsNumber()
    @IsMoreThan("min", {
        message: "max can't be less than min"
    })
    public max: number
}

We ended up defining two classes(RequestRange and ResponseRange] with same attributes for every similar situation.

How do we solve this problem?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
