### ISSUE TITLE
Module is broken with @nestjs/common@7.6.0

### ISSUE THREAD

**Issue by tadejstanic** [nestjs/swagger#1081]
## Current behavior
After upgrading @nestjs/common to v7.6.0, swagger module doesn't work anymore. The problem is that in `common` package function `validatePath` was removed - https://github.com/nestjs/nest/commit/bead1f4a57c9ad1b8dd28ce620a05b3d4d518453#diff-a963f02276dde5355d25ee914a9e9f914b96f28b56f47806db68499fb1a2961eL8 

on which Swagger module is relied on.

## Environment
Nest version: 7.6.0
Nest Swagger: 4.7.5

**Comment by vtrphan** [comment]
i have this problem too

**Comment by pietrovismara** [comment]
Same here

**Comment by vtrphan** [comment]
can anyone suggest a workaround?

**Comment by pietrovismara** [comment]
@vtrphan Downgrade your @nestjs dependencies to version 7.5.5, except @nestjs/swagger which I have at version 4.7.5

**Comment by kamilmysliwiec** [comment]
Fixed in @nestjs/common@7.6.1
