### ISSUE TITLE
[Bug] `Example` field of ApiModelProperty && ApiModelPropertyOptional not setting swagger example value

### ISSUE THREAD

**Issue by tatianajiselle** [nestjs/swagger#1091]
Referenced issues/MRs: 
https://github.com/nestjs/swagger/issues/125#issuecomment-619392783_
https://github.com/nestjs/swagger/pull/128 
https://github.com/nestjs/swagger/commit/ff170b52538e517c0585835263f6936e6ab54284 

Expected behavior:
Setting either decorator `@ApiModelProperty`  or `@ApiModelPropertyOptional` with example field should allow NestJS Swagger to populate the example field with the given string.

Actual behavior:
Setting either decorator results in the model still generating as an example.

Example code snippet:
```
  @Post('/message')
  @ApiConsumes('application/json')
  @ApiResponse({ status: 200, description: 'Message published' })
  @ApiModelPropertyOptional({
    example: JSON.stringify({
      type: 'type',
      source: 'source',
      payload: {
        offer: {
          id: 'id12345',
        },
      },
    }),
  })
```
expected example value:
```
{
  "type": "type",
  "source": "source",
  "payload": {
    "offer": {
      "id": "id12345"
    }
  }
}
```

actual example value: 
```
{
  "source": "string",
  "type": "string",
  "payload": {}
}
```

**Comment by kamilmysliwiec** [comment]
`@ApiModelProperty` (`@ApiProperty` in the latest version) is not supposed to be used on the method level. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
