### ISSUE TITLE
ApiModelProperty groups

### ISSUE THREAD

**Issue by Jorgevillada** [nestjs/swagger#11]
Hi,

thank you with your contribution of nest and swagger.

I have a question, is there a possibility that the properties with the decorator ` @ApiModelProperty ` support groups?

Similar to class-validator groups https://github.com/typestack/class-validator#validation-groups.

```javascript
export class MyClass {

    @ApiModelProperty({ groups: ["edit"] })
    id: string;

    @ApiModelProperty({ groups: ["edit", "create"] })
    name: string;

    @ApiModelProperty({ groups: ["edit", "create"] })
    description: string;

}
```
in controller
```javascript
@ApiImplicitBody({ required: true, type: MyClass, name: "name", groups:["create"]  })
//or
@ApiResponse({ status: 200, description: "OK", type: MyClass, groups:["edit"] })


```
or is there an alternative to not show all the attributes in a response or body? Currently I am creating additional classes.

Thanks

**Comment by ericzon** [comment]
Is there any plan to implement this? I think it should be really useful to avoid repetition.

**Comment by oaoit** [comment]
Its a very useful functionality. Hope will add future.

**Comment by otroboe** [comment]
I would be interested in this feature too !
I don't know what the better way to transform my model depending on the controller method. Interceptor ? Manual transformer ?

**Comment by aequasi** [comment]
What did you end up going with @otroboe ?

**Comment by otroboe** [comment]
@aequasi I did custom transformers, not the best, but the simplest I guess :-/

**Comment by aequasi** [comment]
Any way we can get this moving @kamilmysliwiec ? This is a super handy feature that i'd love to have available here.

**Comment by frozenex** [comment]
+1

**Comment by angelo3593** [comment]
+1

**Comment by NicklasWallgren** [comment]
+1

**Comment by ruscon** [comment]
ping ?

**Comment by ruscon** [comment]
Is there any solution to this issue other than creating a separate DTO?

**Comment by Jamie452** [comment]
+1

**Comment by kamilmysliwiec** [comment]
In the latest release (4.5.0), we added `PartialType`, `OmitType`, and `PickType` functions which can mimic the behavior of built-in TypeScript types (respectively `Partial`, `Omit`, and `Pick`).

Example:

```typescript
class CreateUserDto {
  @ApiProperty()
  email: string;

  @ApiProperty()
  password: string;

  @ApiProperty()
  firstName: string
}
```

and to create the `UpdateUserDto` class based on the `CreateUserDto`, but with all properties marked as optional, use the following code:

```typescript
export class UpdateUserDto extends PartialType(CreateUserDto) {}
```

If you want to exclude, let's say, the `email` property (because, for instance, email has to be unique and cannot be modified), compose `OmitType` and `PartialType` functions, as follows:

```typescript
export class UpdateUserDto extends PartialType(OmitType(CreateUserDto, ['email'])) {}
```
