### ISSUE TITLE
[Feature Request] Generate a static web site

### ISSUE THREAD

**Issue by marcelfalliere** [nestjs/swagger#110]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Currently, the only way to browse the documentation is to start he nodejs server, and navigate to what is configured in `SwaggerModule.setup('/swagger', app, document);` ...

## Expected behavior / Feature request
It would be ideal to be able to generate a static web site that contains all the swagger documentation. Why ? My use case is to make the API documentation public, but starting a nodejs server (with all the implication : mongo, some other stuff...) is, I'm sure you'll understand, not the same as hosting a simple web page with apache or nginx.

What I have in mind is something like this :
`npm run swagger:generate`
that will **press** the runtime swagger site to a folder, let's call it `swagger_dist`, that will have an index.html, a css, and all necessary html static assets to display the documentation.

Maybe this actually exists, but I haven't found anything through google.

## Environment

<pre><code>
Nest version: 5.0.0
Nest/Swagger version : 2.0.2
 
For Tooling issues:
- Node version: v9.11.1
- Platform:  Mac

Others:
-
</code></pre>

**Comment by marcelfalliere** [comment]
Found a solution !

Create an alternative `main.ts` that starts the nestjs server with `const document = SwaggerModule.createDocument(app, options);`. In `path.resolve(process.cwd(), 'swagger', 'swagger.json')` you'll find `swagger.json` that will be generated. Duplicate this file, then stop the server. Then use the node module `swagger-generate` to generate an `index.html`. 

It doesn't look as slick as the runtime index.html generated by this repo... but it does the trick.

**Comment by demostenes1509** [comment]
> Found a solution !
> 
> Create an alternative `main.ts` that starts the nestjs server with `const document = SwaggerModule.createDocument(app, options);`. In `path.resolve(process.cwd(), 'swagger', 'swagger.json')` you'll find `swagger.json` that will be generated. Duplicate this file, then stop the server. Then use the node module `swagger-generate` to generate an `index.html`.
> 
> It doesn't look as slick as the runtime index.html generated by this repo... but it does the trick.

Would you mind pasting this code, please ? Thanks

**Comment by daikiojm** [comment]
It was possible to output swagger.json with the following code.

```ts
import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { AppModule } from './app.module';
import * as path from 'path';
import { writeFileSync } from 'fs';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const options = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
  const document = SwaggerModule.createDocument(app, options);
  const outputPath = path.resolve(process.cwd(), 'swagger.json');
  writeFileSync(outputPath, JSON.stringify(document), { encoding: 'utf8'});

  await app.close();
}
bootstrap();
```

and see swagger.json
