### ISSUE TITLE
How to create custom plugin for reducing boilerplate code?

### ISSUE THREAD

**Issue by sulthanprovab** [nestjs/swagger#1144]
Does anyone have an idea about the nestjs plugins like ( for reducing boilerplate code )

@nestjs/swagger and @nestjs/graphql

eg:-

export class CreateUserDto {
@ApiProperty()
email: string;

@ApiProperty()
password: string;

@ApiProperty({ enum: RoleEnum, default: [], isArray: true })
roles: RoleEnum[] = [];

@ApiProperty({ required: false, default: true })
isEnabled?: boolean = true;
}

To

export class CreateUserDto {
email: string;
password: string;
roles: RoleEnum[] = [];
isEnabled?: boolean = true;
}

using

"compilerOptions": {
"plugins": ["@nestjs#3310/swagger"]
}

The above is working fine and also I need to use custom annotations with custom datatypes like the following

@InputType()
export class UsersSorting {

@Field(type => BaseSorting, { nullable: true })
name: BaseSorting;

@Field(type => BaseSorting, { nullable: true })
email: BaseSorting;
}

To

@InputType()
export class UsersSorting {

name: BaseSorting;

email: BaseSorting;
}

Note: I have the custom datatype like the following

import { registerEnumType } from "@nestjs#3310/graphql";

export enum BaseSorting {
ASC = "",
DESC = "DESC"
}
registerEnumType(BaseSorting, {
name: "BaseSorting", // this one is mandatory
description: "ascending or descending order", // this one is optional
});

**Comment by kamilmysliwiec** [comment]
Tracking this here https://github.com/nestjs/docs.nestjs.com/issues/975
