### ISSUE TITLE
Add swagger-ui-express and express as optionalDependencies

### ISSUE THREAD

**Issue by chriswoodle** [nestjs/swagger#1155]
## I'm submitting a...

[ x] Bug report

Please add `swagger-ui-express` and `express` as `optionalDependencies` to `package.json`, and probably also the fastify libraries. Basically any library that is loaded with `require()` that isn't in `dependences`

```json
    "optionalDependencies": {
        "swagger-ui-express": 4.1.6,
        "express": 4.17.1
    }
```

## Current behavior
When using Yarn2 PnP pnpMode: strict

Running a project that uses @nestjs/swagger causes these two errors:

```
Error: @nestjs/swagger tried to access swagger-ui-express, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: swagger-ui-express (via "swagger-ui-express")
Required by: @nestjs/swagger@virtual:2e4cb0595f9ad4225538d59e3595a6b5e6a8809d034737d43d9aa2e617b2caae65f33724658ce0a806c2cd8fb035c423acf187fe2419ae608ab
7e10644587687#npm:4.7.12 (via C:\xxxxxxxxx\.yarn\$$virtual\@nestjs-swagger-virtual-19a50d414e\0\cache\@nestjs-swagger-npm-4.7
.12-2b0b173971-90a7dc2c72.zip\node_modules\@nestjs\swagger\dist\)
......
```

```
Error: swagger-ui-express tried to access express (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and 
unsound.

Required package: express (via "express")
Required by: swagger-ui-express@virtual:19a50d414ea61722ddd093e308f5fe02abbe176b31d122b78ae52821da2b56978b3fd7c3707f6f21a8e895f20857049d411eeb9bedcb3bcc
fc9b62ad5cb6c33a#npm:4.1.6 (via C:\xxxxxxx\.yarn\$$virtual\swagger-ui-express-virtual-5569fbddf2\0\cache\swagger-ui-express
-npm-4.1.6-1400f0d081-ded7c3cc5d.zip\node_modules\swagger-ui-express\)
Ancestor breaking the chain: @nestjs/swagger@virtual:2e4cb0595f9ad4225538d59e3595a6b5e6a8809d034737d43d9aa2e617b2caae65f33724658ce0a806c2cd8fb035c423acf
187fe2419ae608ab7e10644587687#npm:4.7.12
.......
```

## Expected behavior
There should be no error.

## Minimal reproduction of the problem with instructions
Follow instuctions [here](https://docs.nestjs.com/openapi/introduction), but instead of using npm, use Yarn2 (`yarn set version berry`)

## Environment

<pre><code>
Nest version: 7.6.7
 
For Tooling issues:
- Node version: 12.16.1
- Yarn: 2.3.2
- Platform:  Windows, WSL

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Added in this commit https://github.com/nestjs/swagger/commit/23ceef8a0545c8e7ed8a47aa644c19a99ed877d7 This change will be published in the next release
