### ISSUE TITLE
Slow Rendering

### ISSUE THREAD

**Issue by figux01** [nestjs/swagger#1161]
We just added swagger to our nestjs project, and now when we try to reach the swagger docs, for every single entity, the rendering take more than 5 seconds i don't know why. Did someone else get this issue ? I need help.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
