### ISSUE TITLE
"setGlobalPrefix" value isnt used in generated Swagger Doc

### ISSUE THREAD

**Issue by mfw-59** [nestjs/swagger#12]
If you are setting a specific string via the 'setGlobalPrefix' method when you bootstrap your app, the generated Swagger documentation doesn't seem to have this string as part of the URL in the various 'POST' and 'GET' endpoints.  For example, trying to 'execute' the Swagger endpoint would fail b/c the URL isnt correct.

In my case, I would expect the URL to be "/api/cats" but the Swagger doc has it as just "/cats".

```
async function bootstrap() {
    const app = await NestFactory.create(ApplicationModule);

    // Prepend 'api' to every route
    app.setGlobalPrefix("api");

    // Swagger
    const options = new DocumentBuilder()
    .setTitle("My Test API")
    .setDescription("This is a test")
    .setVersion("1.0")
    .build();
    const document = SwaggerModule.createDocument(app, options);
    SwaggerModule.setup("/docs", app, document);

    await app.listen(5001, () => {
        console.log("Typescript Nest app & Express server running on port 5001");
    });
}
```

**Comment by mildbreakfast** [comment]
You can set base path for your open api document:
```
document.setBasePath('/api');
```

**Comment by mfw-59** [comment]
Got it.  This indeed works.  Thx!
