### ISSUE TITLE
Javascript support through the flow library. is possible?

### ISSUE THREAD

**Issue by juandav** [nestjs/swagger#121]
In the documentation says that swagger only supports typescript is it possible to use flow so that this lack of support is added?

swagger(only typescript) => https://docs.nestjs.com/recipes/swagger
flow(JS STATIC TYPE CHECKER) => https://flow.org/

**Comment by kamilmysliwiec** [comment]
There is no plan to provide a flow support in the nearest future.. I'm pretty sure that it would bring too much needless overhead to the library.
