### ISSUE TITLE
openapi does not display nullable schemas

### ISSUE THREAD

**Issue by zaunermax** [nestjs/swagger#1211]
## Current behavior
When using the openapi feature i noticed, that some of my nested DTOs are not correctly shown when it is nullable:

![image](https://user-images.githubusercontent.com/15246773/108211274-cc98d580-712c-11eb-80ad-c9ddea59c651.png)

when removing `nullable: true` - the DTO is displayed correctly.

## Input Code
```ts
@ApiProperty({ type: LogisticsPartnerDTO, nullable: true })
customer!: Nullable<LogisticsPartnerWithLocationRes>;
```

## Expected behavior
I would expect, that the type is shown in the Swagger Docs even though it is nullable.

## Environment

<pre><code>
"@nestjs/common": "7.6.12",
"@nestjs/core": "7.6.12",
"@nestjs/swagger": "^4.7.13",
</code></pre>

**Comment by zaunermax** [comment]
@kamilmysliwiec I added a test repro repo [here](https://github.com/zaunermax/nest-openapi-bug-repro)

you can see, the reference is broken in this screenshot when looking at the api documentation
![image](https://user-images.githubusercontent.com/15246773/108354384-a84efe80-71e9-11eb-9bb2-1e9c0f4640e4.png)

**Comment by zaunermax** [comment]
I tried to research this a bit and stumbled upon [this issue](https://github.com/OAI/OpenAPI-Specification/issues/1368). Seems to be a known problem of the openapi spec 3.0.*

When using nullable, a schema combination of `nullable` and `allOf` is created:

```
"nested": {
  "nullable": true,
  "allOf": [
    { "$ref": "#/components/schemas/NestedDTO" },
  ]
}
```

which seems to be a common practise but is wrong according to the specification (according to people in the linked issue) - therefore the openapi swagger ui does not display that correctly or not at all.

It seems that the openapi spec 3.1.* got rid of `nullable` alltogether so one could write smth like that:
```
"nested": {
  "oneOf": [
    { type: "null" },
    { "$ref": "#/components/schemas/NestedDTO" }
  ]
}
```

I am therefore not sure, if this issue is still actionable or not. One suggestion could be to switch `allOf` to `oneOf` which is kind of "weird" but at least it shows the referenced type :thinking: 

```
"nested": {
  "nullable": true,
  "oneOf": [
    { "$ref": "#/components/schemas/NestedDTO" },
  ]
}
```

**Comment by lkostrowski** [comment]
Hi @kamilmysliwiec , is there any plan to bump this package to OAS 3.1?

**Comment by kamilmysliwiec** [comment]
We'll bump as soon as the underlying packages (https://www.npmjs.com/package/swagger-ui-dist or `fastify-swagger`) support it as well!

**Comment by kdawgwilk** [comment]
Looks like progress is being made on the new Swagger editor to support OpenAPI 3.1 https://github.com/swagger-api/swagger-ui/issues/5891#issuecomment-1240769951 

https://swagger.io/blog/introducing-the-new-swagger-editor/

**Comment by lironshmuel** [comment]
@kamilmysliwiec oas 3.1 for swagger has already been released: https://swagger.io/blog/swagger-support-for-openapi-3-0-and-openapi-3-1/. any plans to support the 3.1 format in @nestjs/swagger?

**Comment by ivanpondal** [comment]
For anyone having this same issue, I worked around it by manually specifying the type through the annotation:
```
@ApiProperty({ nullable: true, type: Number })
subscription_id: number | null;
```

**Comment by darioackermann** [comment]
> @kamilmysliwiec oas 3.1 for swagger has already been released: https://swagger.io/blog/swagger-support-for-openapi-3-0-and-openapi-3-1/. any plans to support the 3.1 format in @nestjs/swagger? you can also see swagger-ui supports 3.1: https://github.com/swagger-api/swagger-ui/tree/v5.0.0

Any update on this?

**Comment by ivanpondal** [comment]
> For anyone having this same issue, I worked around it by manually specifying the type through the annotation:
> 
> ```
> @ApiProperty({ nullable: true, type: Number })
> subscription_id: number | null;
> ```

why the downvotes? I'm giving a workaround until it gets fix, not even a maintainer 🤷

**Comment by darioackermann** [comment]
> > For anyone having this same issue, I worked around it by manually specifying the type through the annotation:
> > ```
> > @ApiProperty({ nullable: true, type: Number })
> > subscription_id: number | null;
> > ```
> 
> why the downvotes? I'm giving a workaround until it gets fix, not even a maintainer 🤷

Unfortuantely this does not work on my end :/

**Comment by zaunermax** [comment]
> why the downvotes? I'm giving a workaround until it gets fix, not even a maintainer 🤷

Because your answer shows that you must've not understood the issue or you didn't read thoroughly enough through the messages/issue. The code you provided is the exact code I've used which causes the issue. That's why you got a downvote because you pinged us with something which has nothing to do with the issue 😉

**Comment by ivanpondal** [comment]
You're correct - I was not using nested types, however the fact that it did work with primitive types may be a hint to further troubleshoot the underlying issue. A reply clarifying would have worked - but hey, whatever floats your boat!
