### ISSUE TITLE
Export interfaces at the root level

### ISSUE THREAD

**Issue by weeco** [nestjs/swagger#123]
These interfaces can only be imported using package submodules:

SwaggerBaseConfig,
SwaggerDocument

```ts
import {
    SwaggerBaseConfig,
    SwaggerDocument
} from "@nestjs/swagger/dist/interfaces";
```

They should be exported at the root level instead

**Comment by kamilmysliwiec** [comment]
Fixed by this commit: https://github.com/nestjs/swagger/commit/f8592f25f36d3e3dc02c65a1ffcc8566ee755c05
Will be available in the incoming release.

**Comment by kamilmysliwiec** [comment]
`2.3.0` is available already
