### ISSUE TITLE
How to add Example values

### ISSUE THREAD

**Issue by weeco** [nestjs/swagger#125]
How can I add example values for responses (and parameters?), like this:

![https://i.imgur.com/U85M3D0.png](https://i.imgur.com/U85M3D0.png)

I expected an "example" property in the `ApiResponse` and `ApiOperation` decorator, but it's not existent. Am I missing something?

**Edit:** I noticed that Nest/swagger could add example values automatically using the method response types which are DTO classes. Therefore I added a Dto as response type, unfortunately that didn't build the example values either.

**Comment by kamilmysliwiec** [comment]
`@ApiResponse()` takes both `type` and `isArray` property. Create a response dto (using `@ApiModelProperty()` and nest will automatically create your response schema example

**Comment by weeco** [comment]
Is there any code example for this? What I understood is that I am supposed to do it that way:

```ts
@Get('/')
@ApiResponse({status: 200, type: ExampleResponseDto, description: 'xy'})
public getExample(): ExampleResponseDto {
  return example;
}

@ApiModelProperty() // Ts says "Unable to resolve signature of class decorator when called as an expression
class ExampleResponseDto {
  public name: string;
}
```

What am I doing wrong?

**Comment by weeco** [comment]
Ok doesn't it make sense to create an own decorator for the properties in a respons dto? As developer I can see tons of possible options like `required`, `description` and so on which won't be used in Swagger anyways. So what about creating a decorator which only offers actual available options?

**Comment by kamilmysliwiec** [comment]
Sounds good. Would you like to create a pull request?

**Comment by weeco** [comment]
Alright, got you. I'll submit a PR next weekend probably, along with the documentation issue you have referenced to this issue. Thanks for your quick responses.

If you want me to work on the logger documentation as well, take a look at this issue please: https://github.com/nestjs/docs.nestjs.com/issues/128

**Comment by nartc** [comment]
There’s an example property on @ApiModelProperty which you can use. It does not really make sense to put an example property on @ApiResponse. Most of the time, ApiResponse has a reference to an existing schema which is your Dto, hence it makes sense to put the example values on the Dto instead of having another example property for -@ApiResponse
