### ISSUE TITLE
classValidatorShim option not working for CLI plugin in multi-app monorepo, but introspect comments & basic functionality works, git repo inside with reproduction

### ISSUE THREAD

**Issue by sebastiangug** [nestjs/swagger#1256]
[x ] Bug report

class validator shim for CLI plugin does not add information for DTO's market with @Length() or any other class-validator decorators I have tried

## Minimal reproduction of the problem with instructions
https://github.com/sebastiangug/class-validator-shim-test

yarn install
nest start
navigate to: http://localhost:3000/documentation/#/default/AppController_getHello
expand "schema"

Versions: 
```
"dependencies": {
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/swagger": "^4.7.16",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.3",
    "swagger": "^0.7.5",
    "swagger-ui-express": "^4.1.6"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.5.1",
    "@nestjs/schematics": "^7.1.3",
    "@nestjs/testing": "^7.5.1",
    "@types/express": "^4.17.8",
    "@types/jest": "^26.0.15",
    "@types/node": "^14.14.6",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.6.1",
    "@typescript-eslint/parser": "^4.6.1",
    "eslint": "^7.12.1",
    "eslint-config-prettier": "7.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "jest": "^26.6.3",
    "prettier": "^2.1.2",
    "supertest": "^6.0.0",
    "ts-jest": "^26.4.3",
    "ts-loader": "^8.0.8",
    "ts-node": "^9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.0.5"
  },
```

Quick screenshots: 

![image](https://user-images.githubusercontent.com/27768313/111011640-f80c8a00-8391-11eb-8a6b-2843ef25140a.png)
![image](https://user-images.githubusercontent.com/27768313/111011669-06f33c80-8392-11eb-8cef-6b67fd59afea.png)
![image](https://user-images.githubusercontent.com/27768313/111011670-0c508700-8392-11eb-99c6-a5cff989a65f.png)

**Comment by sebastiangug** [comment]
Reproduction with non-monorepo nestjs project, turned off/on webpack exact same result as above: https://github.com/sebastiangug/test-swagger

**Comment by kamilmysliwiec** [comment]
Currently, the `classValidatorShim` only checks for the following decorators: `Min`, `Max`, `MinLength`, `MaxLength`. We gotta mention this in the docs. Let's track this here https://github.com/nestjs/docs.nestjs.com/issues/1843
