### ISSUE TITLE
Bug - Swagger - Properties from inner DTO are expanded

### ISSUE THREAD

**Issue by yuval-hazaz** [nestjs/swagger#1299]
## Current behavior
I have an action that gets an object in the query. The object has an optional property which itself is an object with a required property. In the swagger UI, the inner required property shows as required incorrectly at the level action (without its parent property):

```typeScript
 class childObject {
  @swagger.ApiProperty({
    required: true,
    type: String,
  })
  requiredInnerProp!: string;
}

class parentObject {
  @swagger.ApiProperty({
    required: false,
    type: childObject,
  })
  optionalChildProp?: childObject;
}

 @common.Get("/action")
  async getWithChildObjectInQuery(
    @common.Query() query: parentObject
  ): Promise<string> {
    return "";
  }
```

![image](https://user-images.githubusercontent.com/43705455/114544811-d0943000-9c63-11eb-9977-cde41f19ba80.png)

I also tried to add ApiQuery decorator like this:
```typeScript
@common.Get("/action")
  @swagger.ApiQuery({
    required: false,
    style: "deepObject",
    explode: true,
    type: parentObject,
  })
  async getWithChildObjectInQuery(
    @common.Query() query: parentObject
  ): Promise<string> {
    return "";
  }
```
but then I see both properties

![image](https://user-images.githubusercontent.com/43705455/114545514-bc046780-9c64-11eb-9601-c32802f0437e.png)

## Input Code
Link to repo with reproducable code

https://github.com/yuval-hazaz/nest-swagger-child-prop

## Expected behavior

I expect to see two only the optional parameter of type object with inner required property

## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: v15.13.0  
- Platform:  Mac & Windows

Others:
reproduced on your sample swagger project

**Comment by yuval-hazaz** [comment]
Can anyone confirm or direct me what I am doing wrong?

**Comment by yuval-hazaz** [comment]
no one?

**Comment by yuval-hazaz** [comment]
After some further investigation, I found the way to do it correctly.


Instead of @query I used @ApiQuery with style:"deepObject" and explode:true.
I also had to remove @Query and use @Req to get the query values - otherwise all the parameters were listed twice on the open-api Json

```diff
   @Get("/action")
+ @ApiQuery({
+   type:parentObject,
+   style:"deepObject",
+    explode:true
+ })
   async getWithChildObjectInQuery(
+   @Req() request: Request
-    @Query() query: parentObject
   ): Promise<string> {
     const query :parentObject = request.query
     console.log(query);
    
     return "";
  }

```

When using this method I see the parameters correctly in the open-api json and on swagger UI
This looks good:
![image](https://user-images.githubusercontent.com/43705455/117444539-48433b00-af42-11eb-95d9-be6edfc85901.png)

But, there is still a minor issue in Swagger UI - 
When I use this value, it is sent incorrectly to the server (as an immediate parameter called "rquiredInnerLoop"
```
{
    "requiredInnerProp": "string"
}  
```

Instead, I have to use this value for it to work correctly (note the additional "optionalChildPop" object although it is the name of the parameter

```
{
   "optionalChildProp":
   {
       "requiredInnerProp": "string"
   }
}  
```
![image](https://user-images.githubusercontent.com/43705455/117444744-8cced680-af42-11eb-97f9-7a9e9a00fe5a.png)

**Comment by kamilmysliwiec** [comment]
Thaks for sharing @yuval-hazaz! Is there anything we should do on our side then?

**Comment by laurynas-wn** [comment]
Would be great to have an option to overwrite @Query generated params.
