### ISSUE TITLE
Implicit vs Explicit

### ISSUE THREAD

**Issue by galkowskit** [nestjs/swagger#13]
https://writingexplained.org/implicit-vs-explicit-difference

Shouldn't decorators like `@ApiImplicitParam` be called `@ApiExplicitParam`? If I want to state explicitly what I want in Swagger... it's explicit. Implicit would rather be when `SwaggerModule` tries to imply what the params/body is.

Right...?

**Comment by kamilmysliwiec** [comment]
Hi @galkowskit,
That's what I thought, but this module is strongly inspired by this https://github.com/swagger-api/swagger-core/wiki/annotations#apiimplicitparam-apiimplicitparams

**Comment by galkowskit** [comment]
Hm. Okey then. It's just a bit confusing. I was actively not using those annotations and looking for a way to explicitly state the parameter documentation. Well, I guess if it should be that way then this can be closed.
