### ISSUE TITLE
Swagger does not correctly show schema for nested response data

### ISSUE THREAD

**Issue by pvogel1967** [nestjs/swagger#1323]
## Current behavior

Consider the Cat sample, but the cat entity contains a "preferredFood" field that is the cat's preferred food as a "Food" entity and the Food entity, in turn, contains a field "vendor" that is a Vendor entity that supplies the food.  When rendering swagger for the Cat API, we see the details of the preferredFood field's object, but we see only that the "vendor" field is an object, but no details about that object.

![image](https://user-images.githubusercontent.com/1844599/116947816-8be03100-ac32-11eb-97d8-dbe6f2518dfb.png)

## Input Code

https://github.com/pvogel1967/11-swagger

## Expected behavior

```
Cat > {
    age , etc.
    preferredFood > {
         weight, etc.
         vendor > {
             name: string
                        example: Purina
                        The name of the vendor
             address: string
                         example: 1600 Pennsylvania Ave, N.W., Washington, DC. 20500
                         The mailing address of the vendor
          }
    }
}              
```                        

## Environment

<pre><code>
Nest version: 7.6.15

 
For Tooling issues:
- Node version: 14.15.5  
- Platform:  Mac

Others:

</code></pre>

**Comment by ruifernando7** [comment]
any update on this? i'm facing the same issue

**Comment by cybercarnage** [comment]
Something wrong with schemas. Temporary solution. You can use oneOf keyword and getSchemaPath method: 
`@Type(() => YourClass)
@ValidateNested()
@ApiProperty({
  description: 'Test',
  oneOf: [{ $ref: getSchemaPath(YourClass) }],
  type: () => YourClass,
})
public readonly yourField? YourClass;`

**Comment by vietkute02** [comment]
> Something wrong with schemas. Temporary solution. You can use oneOf keyword and getSchemaPath method:
> 
> ```ts
> @Type(() => YourClass)
> @ValidateNested()
> @ApiProperty({
>   description: 'Test',
>   oneOf: [{ $ref: getSchemaPath(YourClass) }],
>   type: () => YourClass,
> })
> public readonly yourField: YourClass;
> ```
> 
> Docs: https://docs.nestjs.com/openapi/types-and-parameters

Nothing change when update this temporary solution

**Comment by ayoubgm** [comment]
Any updates on this issue !!!

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by xlmnxp** [comment]
same here, is there a way to fix it?

**Comment by ph55** [comment]
The problem is that the title somehow get erased.
Setting the title manually will fix the issue.

# No title:
```ts
  @ApiProperty({
    type: StoreAvailability,
    description: 'Store availability configuration',
  })
  availability!: StoreAvailability;
```
<img width="602" alt="image" src="https://github.com/nestjs/swagger/assets/1386622/58cc892e-f338-455e-ac8a-1083d312d02d">

# With title:
```ts
  @ApiProperty({
    type: StoreAvailability,
    title: 'StoreAvailability',
    description: 'Store availability configuration',
  })
  availability!: StoreAvailability;
```
<img width="596" alt="image" src="https://github.com/nestjs/swagger/assets/1386622/079e2e68-8392-4f43-b2cd-a12e0cb2ceb2">

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/nest/issues/8369
