### ISSUE TITLE
PartialType from @nestjs/swagger not being picked up in E2E tests

### ISSUE THREAD

**Issue by mitsos1os** [nestjs/swagger#1326]
@kamilmysliwiec It didn't work for me, `@nestjs/swagger` `PartialType` was still ignored in my e2e tests.

But still, I've managed to make `@nestjs/swagger/plugin` work properly using the steps provided in the [article](https://dev.to/nestjs/using-the-nestjs-cli-graphql-plugin-for-e2e-testing-4dpb) posted by @jmcdo29

_Originally posted by @abramyk-mv in https://github.com/nestjs/nest/issues/5264#issuecomment-791349999_

-------------------

I too have stubbed in the exact same issue and I could not make **ts-jest** accept the proposed configuration in [NestJS Docs](https://docs.nestjs.com/openapi/cli-plugin#integration-with-ts-jest-e2e-tests) and it was quite frustrating. The trick is that **jest** uses a cache directory for holding its build output.
If you clear this, then it will pick up the plugin normally.

In order to find the cache directory of **jest**:
1. In your root project folder run ` npx jest --showConfig `
2. There you should see two keys: `cache: true` and `cacheDirectory: <PATH_OF_JEST_CACHE>`

Mine was **/tmp/jest_rs**.  Upon emptying it, everything worked ok.

I believe this should be added to the docs as well

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by mitsos1os** [comment]
> Would you like to create a PR for this?

Will do so as soon as I find some time!

**Comment by renatocron** [comment]
I'm having this issue, but I'm on version @nestjs/swagger 7.1.4 with @nestjs/core 10.0.5

I already try to remove the cache, renaming the DTO, but the test still fails if I do not add @IsOptional for one of the extended classes. 
Should just removing the cache be sufficient to solve this issue, or is necessary to follow `AST transformer` file? in the docs it says:
> To enable the plugin, create the following file in your e2e tests directory:

but it doesn't says which file name this file should have, how ts-ts-jest would know about this file?

Thanks
