### ISSUE TITLE
How to change swagger interface when using FastifyAdapter?

### ISSUE THREAD

**Issue by pktai** [nestjs/swagger#1396]
Hi everyone, currently when I use nestjs/swagger and FastifyAdapter to register, but in your module the options object in SwaggerModule.setup is ignored. when can you update this code ?

file main.ts:

    const fAdapt = new FastifyAdapter();
    
    fAdapt.register(fastifyRateLimit, {
      max: Number(process.env.RATE_LIMIT_MAX),
      timeWindow: process.env.RATE_LIMIT_TIME_WINDOW,
    });
    const document = SwaggerModule.createDocument(app, options);
  
    SwaggerModule.setup('documents', app, document);

file swagger-module.js:

    static setup(path, app, document, options) {
        const httpAdapter = app.getHttpAdapter();
        if (httpAdapter && httpAdapter.getType() === 'fastify') {
            return this.setupFastify(path, httpAdapter, document);
        }
        return this.setupExpress(path, app, document, options);
    }

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
