### ISSUE TITLE
'Try it out' does not work correctly, the wrong value is sent in the header 'Accept'

### ISSUE THREAD

**Issue by VaCool** [nestjs/swagger#1404]
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 

When I hit the API via Postman (or any other external client, I can manage the headers) everything works correctly with the correct values

When using the Swagger UI generated by this package 'Accept' header always send wrong value. It should send 'application/json'' in the header, but it always sends 'application/ocr.v1+json'.

I use @ApiHeader:
@ApiHeader({
  name: 'Accept',
  description: 'API version',
  example: Versions.v1,
  required: true,
  schema: { enum: [Versions.v1], default: Versions.v1 },
})

export enum Versions {
  v1 = 'application/ocr.v1+json',
}

Also add screenshots from swagger.
<img width="1440" alt="Screenshot 2021-06-24 at 16 15 37" src="https://user-images.githubusercontent.com/25550723/123269440-a8e50200-d507-11eb-874f-cb50ce8230f2.png">
<img width="1440" alt="Screenshot 2021-06-24 at 16 16 16" src="https://user-images.githubusercontent.com/25550723/123269451-aaaec580-d507-11eb-9b1e-20c9636e678b.png">

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the `swagger-ui-dist` library
