### ISSUE TITLE
Error version 5

### ISSUE THREAD

**Issue by orlandoji** [nestjs/swagger#1433]
hi i got an error trying to configure version 5 @nestjs/swagger

![imagen](https://user-images.githubusercontent.com/1786710/124992025-0dc05200-e008-11eb-89c5-a870dd931826.png)

**Comment by jmcdo29** [comment]
Is your `@nestjs/common` and `@nestjs/core` up on version 8? Can you provide a minimum reproduction?

**Comment by orlandoji** [comment]
> 
> 
> Is your `@nestjs/common` and `@nestjs/core` up on version 8? Can you provide a minimum reproduction?

hi, my version is 7
![imagen](https://user-images.githubusercontent.com/1786710/124993588-2cbfe380-e00a-11eb-8b62-0198992de948.png)
should i upgrade to version 8?

**Comment by jmcdo29** [comment]
If you're using `@nestjs/swagger@5`, then yes, you should upgrade

**Comment by orlandoji** [comment]
> 
> 
> If you're using `@nestjs/swagger@5`, then yes, you should upgrade

thank you so much

**Comment by nartc** [comment]
@orlandoji does updating to NestJS 8 solve the issue for you?

**Comment by orlandoji** [comment]
> @orlandoji does updating to NestJS 8 solve the issue for you?

Yes 👍
