### ISSUE TITLE
@ApiProperty add ability to validate response

### ISSUE THREAD

**Issue by redwert** [nestjs/swagger#1474]
## I'm submitting a...

[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request

## Current behavior
Currently nestjs hasn't ability to validate response.

## Expected behavior
It would be great to have ability to validate response using class validator or nestjs-joi acording to passed dto in @ApiResponse like it implemented in @Body decorator.

**Comment by jmcdo29** [comment]
https://github.com/nestjs/swagger/issues/1468#issuecomment-887241310
