### ISSUE TITLE
Default dto wrapper for response

### ISSUE THREAD

**Issue by redwert** [nestjs/swagger#1484]
## I'm submitting a...

[x] Feature request
</code></pre>

## Current behavior
Currently nestjs/swagger generates response schema based on dto provided to @ApiResponse.
Let's imaging the case when all success responses all over the project have the next structure
`{
    data: {....} // response data,
    error: null,
}`

In this case we need to have similar things for all controllers:
`
class ResponseDataDto{
@ApiProperty({ ... })
someProperty: string
}

class ResponseWrapperDto{
 @ApiProperty({ type: ResponseDataDto })
  data: ResponseDataDto
  
  @ApiProperty({ example: null, description: 'Error message', nullable: true })
  error: string
}

// in controller
@ApiResponse({status: 200})
`
It would be great to have an ability to define a default wrapper schema in one place for success/unsuccessful  responses

For example in main.ts
`
const options = new DocumentBuilder()
      .setTitle(title)
      .setDescription(description)
      .setVersion('1.0')
      **.setResponseWrapper(
      [
       {status: 200, schema: successWrapperDto, targetKey: 'data'},
       {status: 500, failWrapperDto, targetKey: 'error'},
      ]
      )**
      .addBearerAuth()
      .build()
      
const document = SwaggerModule.createDocument(app, options, { include: [ module ] })
....      
`
And use @ApiResponse() like:
@ApiResponse({status: 200, type: [SomeDto]}) // for arrays
@ApiResponse({status: 200, type: SomeDto}) // for object

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
