### ISSUE TITLE
generate default ApiOkResponse from controller action return values

### ISSUE THREAD

**Issue by Darkein** [nestjs/swagger#152]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
default generated response only return http code.
![image](https://user-images.githubusercontent.com/4948463/47363779-ebf7d300-d6d7-11e8-9478-e7ea795ba012.png)

## Expected behavior
It would be great if example for ok response could be automatically generated from action return value. For exemple:
```javascript
  @Get(':id')
  async get(@Param('id', new ParseIntPipe()) id: number): Promise<Form> {
    return await this.formService.getById(id);
  }
```

would generate the same response than:
```javascript
  @Get(':id')
  @ApiOkResponse({ type: Form})
  async get(@Param('id', new ParseIntPipe()) id: number): Promise<Form> {
    return await this.formService.getById(id);
  }
```

to have something like this in swagger:
![image](https://user-images.githubusercontent.com/4948463/47363815-0336c080-d6d8-11e8-9b96-84ef1ee09b76.png)

## What is the motivation / use case for changing the behavior?
just having code less verbose :)

It's possible for the request, I would love to have the same behavior for the response ! 

Thanks!

**Comment by kamilmysliwiec** [comment]
Unluckily, TypeScript reflection system is not that powerful yet. For now, the compiler will emit only `Promise` metadata, without a generic type (`Form` in this case) which makes impossible to automatically reflect response classes.
