### ISSUE TITLE
@nestjs/swagger calls process.exit on failure to load fastify-swagger

### ISSUE THREAD

**Issue by Ginden** [nestjs/swagger#1530]
## I'm submitting a...

* [ ] Regression 
* [x] Bug report
* [ ] Feature request
* [ ] Documentation issue or request

## Current behavior

Failure to load `fastify-swagger` results in calling of `process.exit`, because that's what `loadPackage` method from `@nestjs/common/utils/load-package.util` do. It's called from [`lib/swagger-module.ts:95`](https://github.com/nestjs/swagger/blob/857c055698418de52c29a118bc81c6316b49ea5f/lib/swagger-module.ts#L95).

## Expected behavior

It should throw error that can be handled.

## Minimal reproduction of the problem with instructions

```
  const fastifyAdapter = new FastifyAdapter();
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    fastifyAdapter,
    {
      abortOnError: false, // I specified this option
    },
  );
    const config = new DocumentBuilder()
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup(documentationPath, app, document, {});
  await app.listen(6704, '0.0.0.0');
  ```

This fails if `fastify-swagger` is not installed.

## What is the motivation / use case for changing the behavior?

I want to be in control when and if my process terminates.

Moreover, `process.exit` can result in failure without logs, if `bufferLogs` is set to `true`.

## Environment

<pre><code>
@nestjs/common@8.0.6
@nestjs/swagger@5.0.9
</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
