### ISSUE TITLE
Support `openapi-snippet` or document request snippet usage

### ISSUE THREAD

**Issue by RobertLowe** [nestjs/swagger#1545]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[X] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Swagger module UI snippet only shows request snippets for `curl`

## Desired behavior
Swagger module to support additional snippets utilizing `openapi-snippet`, so different targets may be auto-generated.

## What is the motivation / use case for changing the behavior?
When you have an organization with lots of developers/stakeholders with different skills-sets (data-science, backend, etc), it's useful to provide a snippet in their most used language. 

I purpose we support `openapi-snippet` (https://www.npmjs.com/package/openapi-snippet) or document how to utilize it, or document how to add additional request snippets.

The library currently supports:

- `shell_curl` (default)
- `shell_httpie`
- `shell_wget`
- `swift_nsurlsession` (default)
- `c_libcurl` (default)
- `csharp_restsharp` (default)
- `go_native` (default)
- `java_okhttp`
- `java_unirest` (default)
- `javascript_jquery`
- `javascript_xhr` (default)
- `node_native` (default)
- `node_request`
- `node_unirest`
- `objc_nsurlsession` (default)
- `ocaml_cohttp` (default)
- `php_curl` (default)
- `php_http1`
- `php_http2`
- `python_python3` (default)
- `python_requests`
- `ruby_native` (default)

Thank you for your time in considering this request.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
