### ISSUE TITLE
The automatically generated swaager document cannot copy the URL

### ISSUE THREAD

**Issue by mojiehui** [nestjs/swagger#1546]
## Current behavior

Because the generated document interface is a button tag, the button tag cannot be copied. Normally, the div tag can be copied. Do you need to add some special configurations or anything else.

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
