### ISSUE TITLE
@ApiProperty 's operation is not correct on OpenApi, Swagger queries are not sending

### ISSUE THREAD

**Issue by p29hieu** [nestjs/swagger#1586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Minimum reproduction code

https://github.com/p29hieu-sub-projects/nestjs-swagger

### Steps to reproduce

Proplem: When i use `ApiProperty` decorator from nestjs/swagger, i can't use them on OpenApi.

 I created a dto file like:
 ```js
 export class GetProductsDto implements IGetProductsDto {
  @ApiProperty({
    example: 37.7752315,
  })
  @IsNotEmpty()
  latitude: number;

  @ApiProperty({
    example: -122.418075,
  })
  @IsNotEmpty()
  longitude: number;
}
 ```
 
 then, i used it:
 
```js
 @ApiQuery({
      type: GetProductsDto,
    })
  @Get("products")
  async getProducts(@Query() query: GetProductsDto): Promise<any> {
    return {
      data: [],
    };
  }
```
In my browser:
![image](https://user-images.githubusercontent.com/55887941/135848880-53cd3880-8185-4594-b4fd-b94e201c858f.png)

When i press `Try it out` and `Excecute` buttons: 
![image](https://user-images.githubusercontent.com/55887941/135849132-76b818fd-f158-4383-897f-19c0b2c2b655.png)

Input fields have been filled but the error still occurs. 

When i use `required: false` in `ApiProperty`
 ```js
 export class GetProductsDto implements IGetProductsDto {
  @ApiProperty({
    example: 37.7752315,
    required: false
  })
  @IsNotEmpty()
  latitude: number;

  @ApiProperty({
    example: -122.418075,
    required: false
  })
  @IsNotEmpty()
  longitude: number;
}
 ```
 Then I press `Try it out` and `Excecute` buttons again,
 In `Curl`, the params is not true:
 
![image](https://user-images.githubusercontent.com/55887941/135852433-0b5747b3-d3d9-411c-b635-f7098d4d0e4b.png)

Please give me some help. Thanks!

```json
  @nestjs/cli: "^8.0.0",
  OS: ubuntu 20.04
 Browser: Microsoft Edge Version 94.0.992.38 
```
 

### Package version

^5.0.9

### NestJS version

^8.0.0

### Node.js version

14.17.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by nartc** [comment]
Have you tried not using `ApiQuery` there?

**Comment by kamilmysliwiec** [comment]
Please, report this issue in this repository https://github.com/swagger-api/swagger-ui

**Comment by p29hieu** [comment]
> Have you tried not using `ApiQuery` there?

yes, I tried that but it didn't work

**Comment by mathis-m** [comment]
Workarround, put this in your `main.ts` it will make the parameters distinct:
```ts
const document = SwaggerModule.createDocument(app, options);
  const distinctParams : (arr: any) => (ParameterObject | ReferenceObject)[] = 
    (arr) => [...new Map(arr.map(item => [item.in + item.name + item.$ref, item])).values()] as (ParameterObject | ReferenceObject)[]
  for (const path in document.paths || {}) {
    const pathObj = document.paths[path]
    const methodParams = [
      {key: "get", params: pathObj.get?.parameters},
      {key: "put", params: pathObj.put?.parameters},
      {key: "post", params: pathObj.post?.parameters},
      {key: "delete", params: pathObj.delete?.parameters},
      {key: "options", params: pathObj.options?.parameters},
      {key: "head", params: pathObj.head?.parameters},
      {key: "patch", params: pathObj.patch?.parameters},
      {key: "trace", params: pathObj.trace?.parameters},
    ]
    if(pathObj.parameters) {
      document.paths[path].parameters = distinctParams(document.paths[path].parameters)
    }
    methodParams.forEach((x) => {
      if(x.params) {
        document.paths[path][x.key].parameters = distinctParams(document.paths[path][x.key].parameters)
      }
    })
  }

  SwaggerModule.setup('/docs', app, document);
```

_Originally posted by @mathis-m in https://github.com/swagger-api/swagger-ui/issues/7539#issuecomment-938268189_
