### ISSUE TITLE
`layout` not supported

### ISSUE THREAD

**Issue by tlan16** [nestjs/swagger#1589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

cannot specify `layout` option. 

```typescript
  SwaggerModule.setup('api', app, document, {
    uiConfig: {
      defaultModelsExpandDepth: -1,
      layout: 'BaseLayout', // <-- typescript error here
    },
  });
```

```
➜  bug-nestjs-swagger git:(main) ✗ yst
yarn run v1.22.15
$ nest start
src/main.ts:24:7 - error TS2322: Type '{ defaultModelsExpandDepth: number; layout: string; }' is not assignable to type 'Partial<{ deepLinking: boolean; displayOperationId: boolean; defaultModelsExpandDepth: number; defaultModelExpandDepth: number; defaultModelRendering: string; displayRequestDuration: boolean; ... 8 more ...; validatorUrl: string; }>'.
  Object literal may only specify known properties, and 'layout' does not exist in type 'Partial<{ deepLinking: boolean; displayOperationId: boolean; defaultModelsExpandDepth: number; defaultModelExpandDepth: number; defaultModelRendering: string; displayRequestDuration: boolean; ... 8 more ...; validatorUrl: string; }>'.

24       layout: 'BaseLayout',
         ~~~~~~~~~~~~~~~~~~~~

Found 1 error(s).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Minimum reproduction code

https://github.com/tlan16/bug-nestjs-swagger

### Steps to reproduce

1. `yarn start`
2. error shown
3. suppress typescript error on this line: https://github.com/tlan16/bug-nestjs-swagger/blob/d9bb2af54d8f63b5ba41f9f2bbbe049a657984c7/src/main.ts#L24
4. go to [http://localhost:3000/api/static/index.html](http://localhost:3000/api/static/index.html)
5. swagger ui shows fine. No top bar showing spec url means the `layout: 'BaseLayout',` is effective. 

### Expected behavior

No typescript error. 

### Package version

5.1.0

### NestJS version

8.0.9

### Node.js version

16.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Want to make a PR to update the types?

**Comment by tlan16** [comment]
PR created :point_up:

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/1590
