### ISSUE TITLE
class-transformer shim

### ISSUE THREAD

**Issue by Sufiane** [nestjs/swagger#1608]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When using `@Type` from `class-transformer`  along with the swagger pluggin, such types are not interpreted correctly.

```typescript
export class MyDto {
  @IsNotEmptyObject()
  @ValidateNested()
  @Type(() => OtherDto, {
    keepDiscriminatorProperty: true,
    discriminator: {
      property: 'type',
      subTypes: [
        { value: option1Dto, name: enum.VALUE_1 },
        { value: option2Dto, name: enum.VALUE_2 },
      ],
    },
  })
  paymentInfos: option1Dto | option2Dto;
}
```

This forcing us to redeclare this type in an other class/file and to use @ApiBody in our route controller for example

### Describe the solution you'd like

having a classValidatorShim option like for class-transformer.

We could imaginer something like: classTransformerShim for instance.

### What is the motivation / use case for changing the behavior?

Will allow us to avoid duplicate "complex" DTO declaration, unecessary swagger decorators.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
