### ISSUE TITLE
An error occurs if two classes depend on each other cyclically

### ISSUE THREAD

**Issue by muyu66** [nestjs/swagger#161]
An error occurs if two DTO classes depend on each other cyclically

```
File user.ts

class User {
  @ApiModelProperty({ description: 'User ID' })
  id: string;
  @ApiModelProperty({ description: 'Books', type: Book, isArray: true })
  books?: Book[];
}

File book.ts

class Book {
  @ApiModelProperty({ description: 'Book ID' })
  id: string;
  @ApiModelProperty({ description: 'Users', type: User, isArray: true })
  users?: User[];
}
```

Error: 
```
 Could not render this component, see the console.
 
 TypeError: Cannot read property 'anyOf' of undefined
```

how to resolve? Please help me.

this is my minior program:
https://github.com/muyu66/minior-swagger

npm install && npm start
127.0.0.1:3000 is API interface
127.0.0.1:3000/doc is DOCUMENT

**Comment by nartc** [comment]
Can I see where you implement these two classes?

**Comment by muyu66** [comment]
> Can I see where you implement these two classes?

this is my minior program:
https://github.com/muyu66/minior-swagger

npm install && npm start
127.0.0.1:3000 is API interface
127.0.0.1:3000/doc is DOCUMENT

**Comment by kamilmysliwiec** [comment]
Looks like a duplicate issue #63
