### ISSUE TITLE
defaultVersion is not reflected in generated endpoint URLs (new versioning API)

### ISSUE THREAD

**Issue by ConstantinePoltyrev** [nestjs/swagger#1631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When defining the API versioning with defaultVersion the generated endpoint URLs are not accounting for the version prefix:

`  app.enableVersioning({
    type: VersioningType.URI,
    defaultVersion: '1',
  });
`

### Minimum reproduction code

https://github.com/shprota/swagger-example

### Steps to reproduce

1. yarn
2. yarn start:dev
3. open http://localhost:3007/api
4. Default controller is explicitly annotated with a version and is callable
5. Cats controller uses the defaultVersion and trying to execute it from the generated document leads to 404

### Expected behavior

URLs of the endpoints be correct accounting for defaultVersion parameter.

### Package version

5.1.3

### NestJS version

8.1.1

### Node.js version

14.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
yeah. I guess this is related to the following

https://github.com/nestjs/swagger/blob/c4492d448bbe7667cb609d9b2724d7acf4dc1547/lib/swagger-explorer.ts#L270-L277

I'm trying to fix it already (since I've added this feat on Nest). Thank you!

**Comment by micalevisk** [comment]
@ConstantinePoltyrev I prefer this one:

```
    if (versioningOptions?.type === VersioningType.URI) {
      return (
        Reflect.getMetadata(VERSION_METADATA, metatype) ??
        versioningOptions.defaultVersion
      );
    }
```

do you want to open the PR for this?

**Comment by ConstantinePoltyrev** [comment]
@micalevisk If you can open a PR from your fork, I would yield as I need to prepare a fork and a test env from the scratch.

**Comment by ConstantinePoltyrev** [comment]
Thank you, @micalevisk !
