### ISSUE TITLE
Using multiple @ApiExtensions results in only the first being rendered.

### ISSUE THREAD

**Issue by adworacz** [nestjs/swagger#1637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the Swagger CLI plugin and adding multiple `@ApiExtension`'s to a controller method, only one (the first) is rendered properly. Commenting out either one causes the other to be rendered correctly, so it's not a bug with how the extension is being created.

Example code:
```typescript
  @Put()
  @ApiExtension('x-special-extension', 'foo')
  @ApiExtension('x-extra-special-widget', { 'harry': 'potter' })
  putThing(): string {
    return 'hello world'
  }
```

Which produces:
```json
"put": {
        "x-special-extension": "foo"
}
```

### Minimum reproduction code

See above.

### Expected behavior

```json
"put": {
        "x-special-extension": "foo",
        "x-extra-special-widget": { "harry": "potter" }
}
```

### Package version

5.1.3

### NestJS version

8.0.11

### Node.js version

14.18.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by adworacz** [comment]
Lordy I missed this as well - looks like this PR will fix it: https://github.com/nestjs/swagger/pull/1525

**Comment by micalevisk** [comment]
I guess you can close this one

**Comment by adworacz** [comment]
Roger, closing.
