### ISSUE TITLE
Add a decorator to change the name of a schema component name, instead of using the DTO name.

### ISSUE THREAD

**Issue by adworacz** [nestjs/swagger#1638]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Being able to decouple the name of the schema component definition from the DTO name would be very helpful.

This is useful in organizations that use a large API where several teams contribute contracts that may include conflicting schema/component names. So instead of forcing devs to name their DTOs in a way that avoids conflicts, this would allow devs to use whatever name is desired for their DTOs but then override the published component name with something else.

### Describe the solution you'd like

Perhaps something like @ApiModel({ name: 'NonConflictingComponentName }), or something similar.

This could be added to classes, like so:

```typescript
@ApiModel({ name: 'TeamAExample' })
export class ExampleDto {
...
}
```

Which would produce:

```json
  "components": {
    "schemas": {
      "TeamAExample": {}
```

### Teachability, documentation, adoption, migration strategy

See above.

### What is the motivation / use case for changing the behavior?

See above. Effectively, multi-tenant gateways that combine OpenAPI contracts together.

**Comment by adworacz** [comment]
Oh wait! It looks like this exact pull request will solve this: https://github.com/nestjs/swagger/pull/983

That doesn't appear to be linked to any open issue, which is how I missed it. Should we leave this issue open or close it?

**Comment by micalevisk** [comment]
you can close this issue :)

**Comment by adworacz** [comment]
Roger, closing now.

**Comment by felixhagspiel** [comment]
@adworacz it looks like [#983](https://github.com/nestjs/swagger/pull/983) is still not merged. Have you found another solution for this?

**Comment by adworacz** [comment]
I have not, unfortunately. My team is still blocked on seeing the PR merged. I might take a crack at creating a fresh PR soon if it looks like the current one has too many conflicts.

**Comment by SBD580** [comment]
As a workaround you can do this:
```
class Example {
}

export { Example as ExampleDto }
```
This will leave your code the same but will cause the schemas to be with a different name
