### ISSUE TITLE
Swagger /api endpoint redirects to host

### ISSUE THREAD

**Issue by xXCalleManXx** [nestjs/swagger#164]
## I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

```
const server: Express = express();

const bootstrap = async (expressInstance: Express) => {
  const nestApplication = await NestFactory.create(AppModule, expressInstance, {
    logger: console
  });
  nestApplication.useGlobalPipes(new ValidationPipe());
  nestApplication.useGlobalInterceptors(new FirestoreFormatterInterceptor());
  nestApplication.useGlobalFilters(new HttpExceptionFilter());
  nestApplication.setGlobalPrefix('h4hosting-6f5c8/us-central1/widgets');
  nestApplication.enableCors({
    origin: '*'
  });
  const options = new DocumentBuilder()
    .setTitle('Hostman API')
    .setDescription('The official Hostman API')
    .setVersion('1.0')
    .setBasePath('h4hosting-6f5c8/us-central1/widgets')
    .setHost('localhost:5000')
    .build();
  const document = SwaggerModule.createDocument(nestApplication, options);
  SwaggerModule.setup('api', nestApplication, document);

  await nestApplication.init();
};

bootstrap(server);

exports.widgets = functions.https.onRequest(server);
```

This is how i set up the swagger document. When i go to http://localhost:5000/h4hosting-6f5c8/us-central1/widgets/api it redirects me to http://localhost:5000/api and therefore gets an 404 response.

## Expected behavior
It should not redirect but stay on http://localhost:5000/h4hosting-6f5c8/us-central1/widgets/api and serve the content from there

## Minimal reproduction of the problem with instructions
I use firestore functions wich make that prefix. See code above.

## Environment

<pre><code>
Nest version: 5.4.0
 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Windows, firestore simulator
</code></pre>

**Comment by kamilmysliwiec** [comment]
As far as I remember, `SwaggerModule` is not using a global prefix by default, and thus you have to explicitly pass `h4hosting-6f5c8/us-central1/widgets/api` path as a 1st parameter.

**Comment by xXCalleManXx** [comment]
That was also my first thought. If i understand you correctly this is what you mean.
`SwaggerModule.setup('h4hosting-6f5c8/us-central1/widgets/api', nestApplication, document);`
Wich give a 404 response from nest.

**Comment by xXCalleManXx** [comment]
Another thing that is weird is that while /api is redirecting to the host, /api-json is working without any problems

**Comment by kamilmysliwiec** [comment]
Your issue has nothing to do with Nest itself. I would suggest creating it in the `swagger-ui-express` repository instead (which is used by the `@nestjs/swagger` underneath) - https://github.com/scottie1984/swagger-ui-express/issues
