### ISSUE TITLE
First-level schema type in @ApiHeader is ignored or overwritten to string

### ISSUE THREAD

**Issue by simonkurka** [nestjs/swagger#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```typescript
@ApiHeader({ name: 'x-custom', schema: { type: 'array', items: { type: 'string' } } })
```
Results in `string[string]` OpenAPI specification.

### Minimum reproduction code

https://github.com/simonkurka/nestjs-apiheader-mwe

### Steps to reproduce

1. `npm i`
2. `npm start:dev`
3. See error at http://localhost:3000/api/#/default/AppController_getHello

### Expected behavior

It should result in `array[string]` in OpenAPI specification.

### Package version

5.1.4

### NestJS version

8.1.2

### Node.js version

16.11.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by simonkurka** [comment]
Setting the parameter type to `Array<string>` changes the behaviour, but this is wrong because of https://github.com/nestjs/nest/issues/8175

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by simonkurka** [comment]
At least I can try.
Would you check that I am following the guidelines and that there are no unwanted side effects if possible?
