### ISSUE TITLE
Add ability to pass a default bearer token with .addBearerAuth

### ISSUE THREAD

**Issue by john-manack** [nestjs/swagger#1654]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When setting up the swagger interactive API interface, the `.addBearerAuth` method in the `DocumentBuilder()` class does not have the ability to pass a default bearer token. This would be helpful to illustrate the authorization header in the curl request for testing the API, and allow the user to submit sample requests in the API without going through the extra steps of generating a sample token.

### Describe the solution you'd like

Add an extra option to the `.addBearerAuth` method to pass a bearer token as a string to populate the `Value` field in the `Authorization` login modal in the swagger UI. The solution would accomplish something similar to the `.preauthorizeApiKey` instance method in the non-nest swagger-ui ([see docs](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#instance-methods)).

Example of functionality using a new option called `value`:

```
 const swaggerConfig = new DocumentBuilder()
    .setTitle('Test API')
    .setDescription(description)
    .setVersion('1.0.0')
    .setBasePath()
    .addBearerAuth(
      {
        description: 'Default JWT Authorization',
        type: 'http',
        in: 'header',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        value: 'ThisIsASampleToken123'
      },
      'defaultBearerAuth',
    )
    .build();
```

### Teachability, documentation, adoption, migration strategy

When the Swagger UI is loaded, a bearer token is automatically populated in the Value field, and the user is logged in.

![image](https://user-images.githubusercontent.com/74992804/139876346-068c337f-e1bc-4fec-8acc-adf2adf457a6.png)

### What is the motivation / use case for changing the behavior?

Without the ability to automatically pass in a default token, users must go through additional steps to generate their own token to make sample API requests. By submitting a default token on the user's behalf, there is less friction for the user when learning API functionality.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by john-manack** [comment]
Here's an alternative solution (no PR needed). The method below was tested using @nestjs/swagger v.4.7.12. I cannot speak to other versions.

Step 1: Implement `.addBearerAuth`, but pass 'undefined` instead of an options object. A specific name is still needed to match the authorization to the controller and options in step 3.
```
export async function swaggerSetup(app: INestApplication) {
  const swaggerConfig = new DocumentBuilder()
    .setTitle('Your API Title')
    .setDescription('Your API description)
    .setVersion('1.0.0')
    .addBearerAuth(undefined, 'defaultBearerAuth')
    .build();
```

Step 2: Add `@ApiBearerAuth()` decorator at the top of each controller that is to be authorized with default token. Include the name provided as a string in `.addBearerAuth` in the parenthesis of the `@ApiBearerAuth()` decorator.

```
// controller.ts

@ApiBearerAuth('defaultBearerAuth')
@Controller('sample')
export class SampleController {
// controller code
}
```

Step 3: Pass auth options and default token as options object when setting up `SwaggerModule`. Note specifically that the first child property after `authAction` must exactly match the name assigned in Step 1 (in this case, `defaultBearerAuth`). Same goes for the string value of `name`. The token value goes in the `value` property.

```
const options = {
    swaggerOptions: {
      authAction: {
        defaultBearerAuth: {
          name: 'defaultBearerAuth',
          schema: {
            description: 'Default',
            type: 'http',
            in: 'header',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
          value: 'thisIsASampleBearerAuthToken123',
        },
      },
    },
  };

  SwaggerModule.setup(
    '/public/docs',
    app,
    document,
    options,
  );
```

**Comment by NikalMorgan713** [comment]
This do not work in relation to postman setting default value. I want to set a default value like in ApiHeader
    ApiHeader({
      name: 'x-id-token',
      schema: { type: 'string', default: '{{employee_access_token}}' },
    }),
