### ISSUE TITLE
Issue in generating client code with generics

### ISSUE THREAD

**Issue by garvit14** [nestjs/swagger#1660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a nestjs project in which I am using nestjs-swagger for generating open API spec. I am using that to auto-generate client code for typescript-axios. The issue is that the client code is not generating generics properly. In the attached github code, I want the return type of `findAll` API to be `AxiosPromise<PaginatedResponseOfCreateCatDto>` but it is generating `AxiosPromise<PaginatedDto & object>>` as return type.

This same thing is explained in nestjs docs here: https://docs.nestjs.com/openapi/operations#advanced-generic-apiresponse. I have reproduced exact same steps in https://github.com/garvit14/nest/tree/issue-with-generics-when-generating-client/sample/11-swagger but it is not working.

I am using https://github.com/OpenAPITools/openapi-generator for generating typescript-axios client. Command: `openapi-generator-cli generate -g typescript-axios  -i specFile.json -o .`. In the linked github repo I have added the code for generated client also: https://github.com/garvit14/nest/tree/issue-with-generics-when-generating-client/sample/11-swagger/src/genererated-client. I have tried this on node 10.24.1 and 12.22.6.

### Minimum reproduction code

https://github.com/garvit14/nest/tree/issue-with-generics-when-generating-client/sample/11-swagger

### Steps to reproduce

To start the application run:
1. `npm i`
2. `npm run start`

To generate client run:
1. `npm i -g openapi-generator-cli`
2. `curl http://localhost:3000/api-json -o specFile.json` // download open API specification file
3. `openapi-generator-cli generate -g typescript-axios -i specFile.json -o .`

### Expected behavior

Generated client should have ` AxiosPromise<PaginatedResponseOfCreateCatDto>` as return type.

### Package version

5.1.4

### NestJS version

8.1.2

### Node.js version

12.22.6

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
