### ISSUE TITLE
Support union type in swagger plugin

### ISSUE THREAD

**Issue by RageYL** [nestjs/swagger#1665]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, the swagger plugin is unable to to annotate union types properties with @ApiProperty({ enum: ... }), it only works with enum.

Prisma ORM generates union type instead of enum which forces us to annotate all Dto.

### Describe the solution you'd like

Detect union types and generate the corresponding @ApiProperty({ enum: ... }).

Unfortunately, after trying for a few hours, I lack the knowledge and time to submit a working PR.

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

Reduce boilerplate and maintainability.

**Comment by nartc** [comment]
Thanks for submitting the issue. Can you provide a sample repo so that I know what I'm working against?

**Comment by RageYL** [comment]
I was testing by declaring the following type, it is used exactly like an enum:
```
export type Status = 'enabled' | 'disabled'
```
and declared an attribute in my Dto with the type above:
```
status: Status
```
Do you still need a repo?

**Comment by nartc** [comment]
Thank you for providing that example. I just take a quick look at the AST with a `TypeAlias` and a property referencing that type:

```ts
export type Status = 'enabled' | 'disabled';

export class Foo {
   status: Status;
}
```

Unfortunately, at the moment the AST doesn't give enough information about the `TypeReference` that `status` is referencing. All it knows is that the type has a name of `Status` without giving any information about `enable` or `disable` (which I had hoped it did :( ). 

That said, I think this cannot be done at the moment.

**Comment by RageYL** [comment]
When I investigated, I was able to get the values by accessing the `type.types` array.

```
console.log(type.types.map(t => typeChecker.typeToString(t)))
```
This prints `['enabled', 'disabled']` for 'status: Status' and `['undefined', 'enabled', 'disabled']` for 'status?: Status'.

**Comment by nartc** [comment]
@RageYL if that's the case, then it can be supported. I haven't looked into the code yet, only tried things out in AST Explorer.

**Comment by nartc** [comment]
@micalevisk this is all I've got from ASTExplorer
![image](https://user-images.githubusercontent.com/25516557/141491754-3f16d863-1305-4d74-9ceb-525b43e93cc5.png)
![image](https://user-images.githubusercontent.com/25516557/141491758-47913323-a7fd-4217-a26f-005939a3553c.png)

**Comment by kamilmysliwiec** [comment]
There are no plans to support this feature atm. Thanks for investigating this issue @micalevisk & @nartc
