### ISSUE TITLE
Nestjs does not start when calling DocumentBuilder 

### ISSUE THREAD

**Issue by grinono** [nestjs/swagger#1674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Adding  nestjs swagger new DocumentBuilder() to the main file break Nest loading without any error message.
commeting the DocumentBuilder makes nest start just fine.

```

import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const options = new DocumentBuilder()
    .setTitle('API')
    .build()

  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('api', app, document);

  app.useGlobalPipes(new ValidationPipe());

  const port = process.env.PORT || 7000;
  await app.listen(port);
  console.log(`listening on http://localhost:${port}/graphql`);
}
bootstrap();

```

### Expected behavior

start nestjs

### Package version

5.1.4

### NestJS version

7.6.15

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
are you using `@nestjs/core` 7.6.15? then you shouldn't use the latest version of `@nestjs/swagger`. See:

https://github.com/nestjs/swagger/blob/9337b794aed631953849097830c51e5b820cdfa3/package.json#L57-L59

Try with `@nestjs/swagger@5.0.8` (or even better: upgrade your nestjs version as v7 is legacy)

---

Please provide a repo next time. Isn't that hard and will help the core team (and folks like me) to solve your issue faster :)

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) for support. If you believe this is a bug, please provide a [minimum reproduction repository](https://minimum-reproduction.wtf)
