### ISSUE TITLE
Possibility to add @ApiProperty for implicit property

### ISSUE THREAD

**Issue by pavelk** [nestjs/swagger#1680]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have the following schema for Mongoose:

```
@Schema({ timestamps: true })
export class Article extends Document {
  @ApiProperty({ required: true })
  @Prop({ required: true, unique: true })
  title: string;

  @ApiProperty()
  @Prop({ required: true })
  content: string;

  @ApiProperty()
  @Prop({ required: true })
  excerpt: string;
}
```

The schema does not contain redundant `_id` and `createdAt`, `updatedAt` (defined as `timestamps: true`).
I don't see how to add these items to the swagger documentation.

### Describe the solution you'd like

Possibility to add implicit properties.

### What is the motivation / use case for changing the behavior?

The possibility of complete documentation.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
