### ISSUE TITLE
ApiProperty decorator required property

### ISSUE THREAD

**Issue by antspk** [nestjs/swagger#1682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using `@ApiProperty` decorator should be able to provide raw definition as documented here: https://docs.nestjs.com/openapi/types-and-parameters#raw-definitions.

However if try to provide raw definition like this:
```typescript
@ApiProperty({
  type: 'object',
  required: ['name', 'status'],
  properties: {
    name: {
      type: 'string',
      example: 'ErrorName',
    },
    status: {
      type: 'number',
      example: '400',
    },
  },
})
```
It's doesn't accept `required` property as an array which I'm assuming it should if it were following the structure documented here: https://swagger.io/docs/specification/data-models/data-types/#required

### Minimum reproduction code

https://github.com/antspk/swagger-bug

### Steps to reproduce

1. `npm i`
2. uncomment `src/app.error.ts` line 8

### Expected behavior

It should allow providing `required` property as a string array which would map to the properties object.

### Package version

5.1.5

### NestJS version

8.2.2

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by loginov-rocks** [comment]
+1, gives error: `TS2322: Type 'string[]' is not assignable to type 'boolean'`

**Comment by micalevisk** [comment]
looks like this 'raw' definition wasn't designed to follow the OpenAPI spec(?)

You can see here:

https://github.com/nestjs/swagger/blob/9879ffa7c1027ef4b48df667c6b1def836140246/lib/interfaces/open-api-spec.interface.ts#L233

the real raw definition (I guess), is called `SchemaObject`

But then, the one used by `@ApiProperty` extends it but without the `required` field:

https://github.com/nestjs/swagger/blob/9879ffa7c1027ef4b48df667c6b1def836140246/lib/interfaces/schema-object-metadata.interface.ts#L4-L5
https://github.com/nestjs/swagger/blob/9879ffa7c1027ef4b48df667c6b1def836140246/lib/interfaces/schema-object-metadata.interface.ts#L8

**Comment by cleitinif** [comment]
+1

**Comment by omidh14** [comment]
+1

**Comment by dmiranda2791** [comment]
+1

**Comment by ondrejmoris** [comment]
+1

**Comment by rafakwolf** [comment]
+1

**Comment by Notalifeform** [comment]
+1

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/commit/92df1991c799f39503c6506d77b1145ee0fe804b
