### ISSUE TITLE
API Responses are not picked up by plugin

### ISSUE THREAD

**Issue by NickCellino** [nestjs/swagger#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It appears as though the API Responses are no longer being picked up by the plugin. All I see in the generated docs is:

<img width="1428" alt="Screen Shot 2021-11-23 at 10 15 37 PM" src="https://user-images.githubusercontent.com/6569270/143167495-5aa8af0b-47cb-484d-bd6c-b7b9f5bcac32.png">

when there should be a response there. 
  

### Minimum reproduction code

https://github.com/NickCellino/nestjs-swagger-bug-repro

### Steps to reproduce

1. clone repro repo
2. npm i
3. npm run start
4. go to localhost:3000/api and see the missing response

### Expected behavior

go to localhost:3000/api and see:
```
{
     greeting: "string"
}
```

### Package version

5.1.5

### NestJS version

8.1.1

### Node.js version

v14.15.5

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
`plugins` must lives under `compilerOptions`

![image](https://user-images.githubusercontent.com/13461315/143169421-21e56c1c-7150-4700-9155-c3bdfb32eaf4.png)
