### ISSUE TITLE
Generate Swagger Document from OpenAPI definitions in YAML or JSON 

### ISSUE THREAD

**Issue by hors-loi** [nestjs/swagger#1727]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Too many decorators on methods, properties of objects. 

### Describe the solution you'd like

Programmers write the OpenAPI definition file in YAML or JSON.
And when the NestJS application starts up, you can specify the file's path using SwaggerModule.
Then the app reads the file and generate the Swagger Document.

### Teachability, documentation, adoption, migration strategy

How to write OpenAPI Specification
https://swagger.io/docs/specification/basic-structure/

### What is the motivation / use case for changing the behavior?

Less Decorators kkkk

**Comment by jmcdo29** [comment]
Why not just pass the swagger document to `SwaggerModule.setup()`? The `document` parameter [referred to in the docs](https://docs.nestjs.com/openapi/introduction) is just the swagger.json held in memory and created via reading the decorators.
