### ISSUE TITLE
Support for using custom param decorators

### ISSUE THREAD

**Issue by Toxicable** [nestjs/swagger#1728]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

While trying to integrate this package, we were unable to get @nestjs/swagger to pick up out custom route param decorators.

### Describe the solution you'd like

Support for custom route param decorators could be added.
The problem is that this https://github.com/nestjs/swagger/blob/master/lib/services/parameter-metadata-accessor.ts#L69 parses custom decorators into NaN since `keyPair[0]` is a uuid from https://github.com/nestjs/nest/blob/master/packages/common/decorators/http/create-route-param-metadata.decorator.ts#L26 returns `NaN` , if we could detect this by possibly adding a new optional argument of type `RouteParamtypes` then the mapping would work.

### What is the motivation / use case for changing the behavior?

Easier interoperability between features from the different nestjs packages

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/issues/32
