### ISSUE TITLE
How to customize generic "«»" like Java, using allof/oneof $ref but the schemas in swgger UI are not displayed

### ISSUE THREAD

**Issue by XuChaow** [nestjs/swagger#1731]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

How to customize generic "«»" like Java, using allof/oneof $ref but the schemas in swgger UI are not displayed

![886BEA87-C2B9-423F-98DF-01353B2553A2](https://user-images.githubusercontent.com/29518526/146290652-89b5bdc4-3834-42ef-a245-574b396b03c2.png)

### Describe the solution you'd like

How to customize generic "«»" like Java, using allof/oneof $ref but the schemas in swgger UI are not displaye
![886BEA87-C2B9-423F-98DF-01353B2553A2](https://user-images.githubusercontent.com/29518526/146290670-f64669b6-436d-4ab3-9a91-6e6010f90312.png)
d

### Teachability, documentation, adoption, migration strategy

How to customize generic "«»" like Java, using allof/oneof $ref but the schemas in swgger UI are not displayed

### What is the motivation / use case for changing the behavior?

How to customize generic "«»" like Java, using allof/oneof $ref but the schemas in swgger UI are not displaye
![886BEA87-C2B9-423F-98DF-01353B2553A2](https://user-images.githubusercontent.com/29518526/146290694-723cc72d-6d95-4dce-a945-0be7cddb996c.png)
d

**Comment by micalevisk** [comment]
## :warning: We use GitHub Issues to track bug reports, feature requests and regressions

If you are not sure that your issue is a bug, you could:

- use our [Discord community](https://discord.gg/NestJS)
- use [StackOverflow using the tag `nestjs`](https://stackoverflow.com/questions/tagged/nestjs)
- If it's just a quick question you can ping [our Twitter](https://twitter.com/nestframework)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
