### ISSUE TITLE
Add support for array of arrays definition -> {type: [[PathModel]]}

### ISSUE THREAD

**Issue by myflowpl** [nestjs/swagger#174]
## I'm submitting a...

<pre><code>[x] Bug
[x] Feature request
</code></pre>

## Current behavior
I need to nest the type inside of array of arrays of the type, so my data loks like this
```typescript
const user: UserModel = {
  paths: [
    [{name: 'Europe'}, {name: 'Poland'}, {name: 'Lubelskie'}],
    [{name: 'Europe'}, {name: 'Spain'}, {name: 'Cannary'}],
  ],
};
```
my models definition
```typescript
export class PathModel {
  @ApiModelProperty()
  name: string;
}
export class UserModel {
  @ApiModelProperty({type: [[PathModel]]})
  paths: PathModel[][];
}
```
the result is empty object, swagger module does not process the type recursively
```json
"UserModel": {
  "type": "object",
  "properties": {
    "paths": {
      "type": "array",
      "items": {
        "type": ""
      }
    }
  }
},
```

## Expected behavior
the swagger output should be nested array of the type
```javascript
"UserModel": {
  "type": "object",
  "properties": {
    "paths": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
            "$ref": "#/definitions/PathModel"
         }
      }
    }
  }
},
```

## Environment
<pre><code>
"@nestjs/common": "^5.4.0",
"@nestjs/core": "^5.4.0",
"@nestjs/swagger": "^2.5.1",
</code></pre>

**Comment by kamilmysliwiec** [comment]
You can use *Raw definition* for that https://docs.nestjs.com/recipes/swagger#raw-definitions
If you want `PathModel` to be reflected by the swagger module, you can look at this https://docs.nestjs.com/recipes/swagger#extra-models
