### ISSUE TITLE
Secure the Swagger UI

### ISSUE THREAD

**Issue by HaaLeo** [nestjs/swagger#1740]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This feature request derives from #244. When publishing a swagger UI with a deployed API this could introduce [security risks](https://security.stackexchange.com/questions/211638/swagger-on-production-apis).

### Describe the solution you'd like

To address the problem above the @nestjs/swagger package should introduce a mechanism to secure the swagger UI endpoints. For example by simple user + password authentication or oauth2 integration

### What is the motivation / use case for changing the behavior?

@nestjs/swagger is awesome. With this feature we can make it more secure and developers can use it in production environments as well.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
