### ISSUE TITLE
Add possibility to expose @ApiProperty()

### ISSUE THREAD

**Issue by ymolchaniuk** [nestjs/swagger#1745]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Some endpoints doesn't return property

### Describe the solution you'd like

It will be cool if we will have possobility to add some groups maybe to @ApiProperty() or have something like @ApiExcludeProperty(options, excludeOptions)

### What is the motivation / use case for changing the behavior?

Endpoints
/api/test
/api/test2

Some entity
```typescript
@Entity()
export class Report {
    @PrimaryGeneratedColumn()
    @ApiProperty()
    id: number;
    
    @Column()
    @ApiExposeProperty({ format: 'date-time' }, 'test' )
    @Expose('test')
    date: string;
}
```

Controller should return date only in one endpoint /api/test, so this property should exist only in one endpoint in swagger doc

**Comment by jmcdo29** [comment]
Why not create a new DTO specifically for this route using the mapped types (like `OmitType`)?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
