### ISSUE TITLE
Unable to define a two-dimensional array data structure

### ISSUE THREAD

**Issue by t13219006372** [nestjs/swagger#1746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use the ApiProperty to decorate a 2-d array, but swagger-UI represents a 1-D array

### Minimum reproduction code

class TaskTable {   @ApiProperty({ title: '表头' })   header: string[]   @ApiProperty({ title: '内容' })   lines: string[][] }  export class GetTaskListRes extends ResponseData {   @ApiProperty({ type: TaskTable })   data!: TaskTable }

### Expected behavior

I just want to create a data structure with a two-dimensional array

### Package version

4.8.0

### NestJS version

7.6.17

### Node.js version

14.15.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by t13219006372** [comment]
![image](https://user-images.githubusercontent.com/63200345/147343204-cbebd4dc-24e9-46a0-ba7a-64144962d588.png)

![image](https://user-images.githubusercontent.com/63200345/147343257-38747abf-7707-4084-9169-1154dd998d69.png)
![image](https://user-images.githubusercontent.com/63200345/147343292-ea2f44b3-1d8d-4926-8e70-00207f94696a.png)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
