### ISSUE TITLE
@ApiModelProperty throw error when property type is a recursive 

### ISSUE THREAD

**Issue by lincolnlau** [nestjs/swagger#175]
class Person {
    @ApiModelProperty({description: 'children', type: [Person]})
    children: Person[]
}

in above situation,   exception below will be thrown.
UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

in this case, I must add id, and parentId to Person,   the relationship between parent and children is keep by id and parentId.  change the tree struct to array.

**Comment by kamilmysliwiec** [comment]
Duplicate #136
