### ISSUE TITLE
CLI plugin to automatically hide @Exclude() DTO properties

### ISSUE THREAD

**Issue by neoelvishsiao** [nestjs/swagger#1751]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

According to the CLI Plugin document:
`annotate all DTO properties with @ApiProperty unless @ApiHideProperty is used`

will also annotate those `@Exclude()` properties which causes problems because the value is excluded.

Have to manually add `@ApiHideProperty()`.

### Describe the solution you'd like

Option#1. Not annotate `@Exclude()` properties

Option#2. Automatically hide `@Exclude()` properties which can be part of classValidatorShim

### What is the motivation / use case for changing the behavior?

`@Exclude()` might be a missing feature of classValidatorShim

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
