### ISSUE TITLE
Allow "default" in `ApiResponse`

### ISSUE THREAD

**Issue by ph55** [nestjs/swagger#176]
From swagger docs:
https://swagger.io/docs/specification/describing-responses/

> You can use the default response to describe these errors collectively, not individually. “Default” means this response is used for all HTTP codes that are not covered individually for this operation.

```yaml
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        # Definition of all error statuses
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```

But `ApiResponse` only allows number
![image](https://user-images.githubusercontent.com/1386622/50386332-1290b500-06ed-11e9-8b88-61407d7cf584.png)

Add option for 'default' or expose `ApiDefaultResponse`

**Comment by kamilmysliwiec** [comment]
4.0.0 has been published
