### ISSUE TITLE
Feature Request : Plugin support for bigint

### ISSUE THREAD

**Issue by MatthieuLemoine** [nestjs/swagger#1768]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Using `bigint` as a DTO property type leads to a `Circular dependency error` when using the plugin to automatically annotate properties.

### Describe the solution you'd like

`BigInt/long` type is supported by Swagger https://swagger.io/docs/specification/data-models/data-types/#numbers using the `integer` type with the `int64` format.

If this is something you're willing to add to `@nestjs/swagger`, I can quickly create a PR as I made a working local patch already.

### What is the motivation / use case for changing the behavior?

For now it's possible to use `bigint` by manually annoting  the property.

The main issue is that the error is misleading which makes it hard to find the real cause.
Also I wasn't able to find a list of supported types without going through the source code.

**Comment by kamilmysliwiec** [comment]
Contributions are more than welcome! Feel free to create a PR

**Comment by kamilmysliwiec** [comment]
Awesome, thank you! Let's track this here https://github.com/nestjs/swagger/pull/1770
