### ISSUE TITLE
Option to add host to the swagger-json

### ISSUE THREAD

**Issue by nauta008** [nestjs/swagger#1769]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have an issue when I want to use the swagger-json endpoint as Azure App Service OpenAPI specification when used in Azure Api Management. It required the "host" property in the json specification, but the method to add the host has been removed in the newest version.

### Describe the solution you'd like

Add function setHost to the DocumentBuilder again. 

### What is the motivation / use case for changing the behavior?

Azure Api Management provide option to register OpenAPI json specification of App Services, but it requires the "host" property. The only option is to link the OpenAPI json specification by an url. It would by nice to link it to the generated <host>/swagger-json endpoint of the NestJS application.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
