### ISSUE TITLE
ApiProperty for unknown keys (dictionaries)

### ISSUE THREAD

**Issue by mxlpitelik** [nestjs/swagger#1771]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

If my schema is contain dictionaries (properties with unknown key) I dont know how create schema descriptions for it like here https://swagger.io/docs/specification/data-models/dictionaries/

Example:

```ts
class ColorDto {
  @ApiProperty()
  hex: string;
  
  @ApiProperty()
  rgb: string;
}

class RainbowDto {
  @ApiProperty()
  name: string;
  
  @???????
  colors: { [key: string] : ColorDto }
}

```

### Describe the solution you'd like

```ts
class ColorDto {
  @ApiProperty()
  hex: string;
  
  @ApiProperty()
  rgb: string;
}

class RainbowDto {
  @ApiProperty()
  name: string;
  
  @ApiAdditionalProperty({
     type: ColorDto
  })
  colors: { [key: string] : ColorDto }
}

```

### What is the motivation / use case for changing the behavior?

This is super often problem, and I dont know how to solve this trouble for now...

**Comment by amitzig** [comment]
+1
Any update on this matter?

**Comment by madmxg** [comment]
Workaround

```typescript
@Controller('api/v1/some-resource')
export class SomeResourceController {
  @ApiOkResponse({
    description: 'Some description.',
    schema: {
      type: 'object',
      example: {
        'key1': {
          name: 'string',
          date: 'string',
        },
        'key2': {
          name: 'string',
          date: 'string',
        },
      },
      additionalProperties: {
        $ref: '#/components/schemas/NameOfSomeDto',
      },
    },
  })
  public async readSomeResource() {}
}
```

**Comment by maxfriedmann** [comment]
Also works via @ApiProperty({additionalProperties: {$ref: "#/components/schemas/NameOfSomeDto"}});

**Comment by voidberg1** [comment]
Any updates on this? Unfortunately, it seems decorators cannot be attached to index signatures. :(

**Comment by iiian** [comment]
Use `Record<string, T>`. If you're pre-4.0 you're probably SOL.

```typescript
export class MyDto {
  @ApiProperty({ additionalProperties: { type: 'string' } });
  bag_of_fun: Record<string, string>;
}
```

**Comment by kervral** [comment]
While @Kibyra answer works for nested properties, we still can't declare class level indexed properties as swagger definition like this: 
```typescript
import { ApiProperty } from '@nestjs/swagger';

class ColorDto {
  // Can't apply decorator here
  [key: string]: unknown; 

  @ApiProperty()
  hex: string;

  @ApiProperty()
  rgb: string;
}
```

Can a class decorator could be considered allowing to add additional properties to the class ?

**Comment by Ethan199412** [comment]
ApiPropertyOptional could only help you make one layer, which means it could only solve Record<string, Dto>, but it can't solve Record<string, Record<string, Dto>>

**Comment by mwaeckerlin** [comment]
> While @Kibyra answer works for nested properties, we still can't declare class level indexed properties as swagger definition like this:
> 
> ```ts
> class ColorDto {
>   // Can't apply decorator here
>   [key: string]: unknown; 
> }
> ```

I'm having the same issue.

That's a typical use case: Have an object as parameter with a unique id as key and that maps to some content.

I haven't found a proper solution for this.

Example:

```export class CryptoAddress {
  WalletAddress?: string
  Memo?: string
  DestinationTag?: string
}

export class CryptoAddresses {
  // cannot add @ApiProperty(…) → decorators are not valid here
  [id: string]: CryptoAddress
}
```

I can then create a controller:

```
  ...
  public addresses: CryptoAddresses = {}
  @ApiExtraModels(CryptoAddress)
  @Get('addresses') @ApiResponse({status: 200, schema: {type: 'object', additionalProperties: {$ref: getSchemaPath(CryptoAddress)}}}) getAddresses(): CryptoAddresses {
    return this.addresses
  }
```

But I can't get a schema for `CryptoAddresses` to be created…

For me, it's important to get a proper schema definition, because the client generates it's types from the schema file.

Any idea / solution for this?

A possible solution would be to add something to create an arbitrary schema for an arbitrary type to solve all unhandled use cases, such as:
```
@ApiSchema({
    type: object,
    additionalProperties: $ref: getSchemaPath(CryptoAddress)
})
class CryptoAddresses {...}
```

**Comment by muka** [comment]
I used this for a generic object with some optional typed fieds

```typescript
class MyOptions {
  [key: string]: any
  @ApiPropertyOptional()
  someTypeField?: boolean
  // ...
}
@ApiExtraModels(MyOptions)

//...
@ApiPropertyOptional({
    type: 'object',
    allOf: [
      { $ref: getSchemaPath(MyOptions) },
      {
        type: 'object',
      },
    ],
  })
  options?: MyOptions;
```

generates in 

```typescript
options?: MyOptions & Record<string, unknown>;
```

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/commit/92df1991c799f39503c6506d77b1145ee0fe804b

In the next release, you'll be able to pass raw schema definition:

```ts
@ApiProperty({
  type: 'object',
  properties: {
    name: {
      type: 'string',
      example: 'ErrorName'
    },
    status: {
      type: 'number',
      example: '400'
    }
  },
  required: ['name', 'status']
})
rawDefinition?: Record<string, any>;
```

Or alternatively you can just use CLI Plugin to auto-introspect the schema for you https://docs.nestjs.com/openapi/cli-plugin
