### ISSUE TITLE
Added the ability to use a different decorator with PartialType

### ISSUE THREAD

**Issue by tuan231195** [nestjs/swagger#1796]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, when using PartialType, it will automatically apply IsOptional to all properties in the subclass.

https://github.com/nestjs/swagger/blob/master/lib/type-helpers/partial-type.helper.ts#L48

This can be undesirable because IsOptional allows null values and there is no way to override this behavior.

### Describe the solution you'd like

extends PartialType to take another argument for the decorator being applied instead of IsOptional.

e.g

```
extends PartialType(BaseClass, IsUndefinable)
```

### What is the motivation / use case for changing the behavior?

Not able to prevent null values when using PartialType

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
