### ISSUE TITLE
Rename package from swagger to openapi

### ISSUE THREAD

**Issue by PatrickWe** [nestjs/swagger#1799]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Swagger package Name ist outdated and WE should use @nestjs/openapi instead

### Describe the solution you'd like

Use @nestjs/openapi as package Name and AS npm dependency name

### What is the motivation / use case for changing the behavior?

Wrong naming

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
