### ISSUE TITLE
Swagger Redirection Breaking

### ISSUE THREAD

**Issue by MelvitaAndrade** [nestjs/swagger#1814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Getting the following error, on redirecting back from OAuth2 to the page where the request was sent from.
![image](https://user-images.githubusercontent.com/69793894/153472640-f6994fbe-7fce-45a7-850f-63b7a9f04788.png)

Verified the code with other projects using older versions with the same code, this issue does not seem to exist there

### Minimum reproduction code

https://github.com/MelvitaAndrade/Data-Store

### Expected behavior

It should have redirected to the swagger page after successful login

### Package version

5.2.0

### NestJS version

8.0.0

### Node.js version

16.11.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
