### ISSUE TITLE
[Raw Definiftions for Generics Schema] - Resolver error at path: Could not resolve reference: #/components/schemas/DTO

### ISSUE THREAD

**Issue by pedroampucweb** [nestjs/swagger#1816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I tried to follow the tutorial ([link](https://docs.nestjs.com/openapi/operations#advanced-generic-apiresponse)), on how to create a custom decorator response with generic DTO<T> class. However I cannot get swagger to recognize the generic model, I keep getting this error in swagger UI: 
```
"Resolver error at paths./findByTitle.post.responses.200.content.application/json.schema.allOf.0.$ref
Could not resolve reference: #/components/schemas/PaginatedDto"
```
I have tried to add the @ApiExtraModel, at the controller level, at the DTO model, on top of the ApiResponse decorator, and tried to use the extraModels options that swagger document builder provides, and I could never get this error to stop. 

Below is the UI error:
![image](https://user-images.githubusercontent.com/95145598/153504828-59ccdbea-5787-4ed2-b144-08d7bdc62aed.png)

The UI body and incomplete response, not here, that the Video entity is mapped by swagger in the "results" property, but the PaginateDTO, the generic one is not mapped:
![image](https://user-images.githubusercontent.com/95145598/153505464-6bc84ddc-72d9-47c8-86e2-e21e10ec095e.png)

If you call the service, you get the appropriate response object with the properties from PaginatedDTO:
![image](https://user-images.githubusercontent.com/95145598/153505307-433e5e57-e2a6-4a78-9930-3119b514953d.png)

I do not know how to solve this problem, any help would be greatly appreciated! 

Regards,
Pedro Miranda.

### Minimum reproduction code

https://github.com/pedroampucweb/generic-decorator

### Steps to reproduce

1. npm i
2. nest start

### Expected behavior

The PaginatedDTO should be mapped by swagger and presented at the UI response documentation. 

### Package version

5.2.0

### NestJS version

8.0.0

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
