### ISSUE TITLE
Import external openapi spec file in nest js for swagger

### ISSUE THREAD

**Issue by d33pakjangra** [nestjs/swagger#1817]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I don't see any option to import my external open api spec file in nest js for generating swagger ui.

### Describe the solution you'd like

Provide option for loading external json or yaml file

### What is the motivation / use case for changing the behavior?

I have already created the open api spec file. Don't want to use decorater in nestjs

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
