### ISSUE TITLE
Access swagger-ui after setup to initialize oauth2

### ISSUE THREAD

**Issue by deeeed** [nestjs/swagger#1828]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It is not possible to initialize ouath2 parameters.

Looking at the doc https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/
```
ui.initOAuth({
    clientId: "your-client-id",
    clientSecret: "your-client-secret-if-required",
    realm: "your-realms",
    appName: "your-app-name",
    scopeSeparator: " ",
    scopes: "openid profile",
    additionalQueryStringParams: {test: "hello"},
    usePkceWithAuthorizationCodeGrant: true
  })
```

### Describe the solution you'd like

Either SwaggerModule.setup() should return an instantiated swagger-ui or we should add configuration option that could trigger the setup of `ui.initOauth()`.

### What is the motivation / use case for changing the behavior?

Cannot pre configure oauth2 configuration such as clientId.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by julianklumpers** [comment]
You can achieve this with `swaggerOptions`

```ts
SwaggerModule.setup('api', app, document, {
  customSiteTitle: 'Your API',
  swaggerOptions: {
    oauth: {
      clientId: "your-client-id",
      clientSecret: "your-client-secret-if-required",
      realm: "your-realms",
      appName: "your-app-name",
      scopeSeparator: " ",
      scopes: "openid profile",
      additionalQueryStringParams: {test: "hello"},
      usePkceWithAuthorizationCodeGrant: true
    },
    persistAuthorization: true,
  },
});
```

**Comment by dmexs** [comment]
I agree updating TS interfaces would be helpful.

The linked documentation references the initOAuth method which is a different approach and would require access to the SwaggerUI instance as @deeeed asked for in the original post.

**Comment by kamilmysliwiec** [comment]
> I can look if I have the time to make a PR and make the TS interfaces more clear.

PRs are more than welcome 🙌

**Comment by jarpoole** [comment]
@julianklumpers Does the approach you outlined above still work in the latest version? I am running the latest (`6.0.5`) and adding an `oauth` object with a `clientId` property in it has no effect.

**Comment by julianklumpers** [comment]
@jarpoole 

Nope, that approach does not work anymore. You can use this now instead.

```ts
SwaggerModule.setup('api', app, document, {
    customSiteTitle: 'Koppert API',
    customJs: '/test.js',
    swaggerOptions: {
      persistAuthorization: true,
      oauth2RedirectUrl: 'http://localhost:4000/api/oauth2-redirect.html',
      initOAuth: {
        clientId,
        clientSecret,
        scopes: ['openid, profile'],
        appName: 'App name',
      },
    },
  });
```

[https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/)

Hope this helps

**Comment by jarpoole** [comment]
Works beautifully! Thank you so much for the tip!

**Comment by Branchverse** [comment]
Is there a working example to this?
Can't find the effects of the code or how to debug this.

What is the expected behaviour?

**Comment by dan-cooke** [comment]
Does anybody else find swagger to be just incredibly messy and have a terrible DX. 

I almost always advocate for GraphQL purely because of how annoying Swagger is to configure.
