### ISSUE TITLE
Getting jsonschema of single DTO Class (with all references included)

### ISSUE THREAD

**Issue by YanDevDe** [nestjs/swagger#1830]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently I'm having the trouble that I have to copy part of the jsonschema from "swagger/json" into the frontend application to verify the input forms. If something is changed in DTO class, I have to copy it again.

### Describe the solution you'd like

A new function to give you all necessary (not full one) jsonschema back for the given endpoint, for example we have following DTO class:

Contact.dto.ts
```ts
export class ContactDto {
	@ApiProperty({
		type: String,
		description: 'Users Email',
		example: 'john.doe@example.com',
		required: true,
	})
	email: string;

	@ApiProperty({
		type: String,
		description: 'Users Message',
		example: 'Lorem ipsum...',
		required: true,
	})
	message: string;
}
```

And at the controller:

Contact.controller.ts

```ts
export class ContactController {
    constructor(private readonly contactService: ContactService) {}

    @Post('contact')
    @ApiOperationId()
    @ApiBody({
        type: ContactDto,
        required: true,
    })
    @ApiCreatedResponse({
        description: 'Message successfully sent!',
        type: Boolean,
    })
    async contact(
        @Body() contact_dto: ContactDto,
    ): Promise<boolean> {
        // Make contract call with this.contactService
        return true;
    }
    
    @Get('contact/schema')
    async contact_schema(): Promise<any> {
        return getSchema(ContactDto); //Returns jsonschema with all $ref used for ContactDto, not the full schema one like from localhost:3000/swagger/json
    }
}
```

Now we have 2 endpoint, `/contract` for posting contact info and `/contact/schema` for getting schema for the body request.

### What is the motivation / use case for changing the behavior?

Advantage for this would be that you can automate & validate the form entries in frontend by having this schema from the backend. And if you changed something in the backend at DTO class, it will also be changed on frontend side.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
