### ISSUE TITLE
Is there a easy way to disable swagger in production mode but enable in development mode？

### ISSUE THREAD

**Issue by arfaWong** [nestjs/swagger#184]
What I do now is not to call the SwaggerModule.setup() in production mode.

**Comment by Wizp** [comment]
Add production env check and don't init SwaggerModule at all.

**Comment by arfaWong** [comment]
@Wizp 
How about the swagger annotation in controller and dto?

**Comment by kamilmysliwiec** [comment]
@arfaWong they shouldn't affect anything at all.

**Comment by demisx** [comment]
I have this:

```ts
 if (runEnv === RunEnvironment.Development) {
    const sw = await import('@nestjs/swagger')
    const swaggerOptions = new sw.DocumentBuilder()
      .setTitle('Sample API')
      .setVersion('0.1')
      .build()
    const document = sw.SwaggerModule.createDocument(app, swaggerOptions)
    sw.SwaggerModule.setup('docs', app, document)
  }
```

but, it still gets bundled into `main.js` during `ng build api --prod` and expects  `"swagger-ui-express"` and `"@nestjs/swagger"` npm modules to be present in the production docker image. Would be nice if there was a way to get rid of it completely in prod environment.
