### ISSUE TITLE
Do we have a dock configuration similar to swagger in Java environment

### ISSUE THREAD

**Issue by moewang0321** [nestjs/swagger#1840]
### Is there an existing issue that is already proposing this?

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

During development, we want to distinguish different specs according to different API functions, so that developers can quickly locate where they need them. In the latest version of @nest/swagger, all APIs are stacked in the same place. APITags alone is not convenient enough to locate.

### Describe the solution you'd like

In the Java version of swagger, you can define groups and specify the controller package through docket.

![image](https://user-images.githubusercontent.com/48441577/156340257-daf3b530-8c27-4896-890c-b9861dc11110.png)

### Teachability, documentation, adoption, migration strategy

We can add configuration when creating document, and obtain dto, controller and other required modules on the premise of using the current configuration

### What is the motivation / use case for changing the behavior?

In production,  the fe and be need to connect quickly through documents, and this configuration or function will greatly improve the work efficiency of both sides, without time-consuming and laborious search for the required API and rapid positioning by grouping.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
