### ISSUE TITLE
Support Stoplight Elements as alternative OpenApi UI

### ISSUE THREAD

**Issue by JacobLey** [nestjs/swagger#1854]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Presently, users can only use [Swagger UI](https://swagger.io/tools/swagger-ui/) to render OpenAPI UI.

That package is effectively blocking adoption of OpenAPI 3.1 https://github.com/nestjs/swagger/issues/1211#issuecomment-876253116

### Describe the solution you'd like

Users should be able to opt-in to using Stoplight Elements as an OpenAPI UI rather than Swagger UI.

Stoplight Elements: https://github.com/stoplightio/elements
Demo: https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/digitalocean/openapi/main/specification/DigitalOcean-public.v2.yaml#/

Stoplight Elements supports OpenAPI 3.1 natively.
It also gives developers more choices for rendering their API.

### Teachability, documentation, adoption, migration strategy

The actual usage of this package remains unchanged, it is purely a UI change.

It should result in a MINOR package change, as it is implementing a new feature.

Most likely the change would extend the [`SwaggerCustomOptions`](https://github.com/nestjs/swagger/blob/master/lib/interfaces/swagger-custom-options.interface.ts#L57) with a `{ stoplightElements: true }` option, with whatever other options are relevant (https://github.com/stoplightio/elements/blob/main/docs/getting-started/elements/html.md#configuration)

The documentation for [`setup`](https://docs.nestjs.com/openapi/introduction#setup-options) should be extended to include an example of using Stoplight Elements.

A new optional peer dependency on stoplight `@stoplight/elements` (or some express/fastify wrapper) would be added.

This functionality should be opt-in (default to Swagger UI). When 3.1 is implemented, if Swagger UI still does not support it, it may need to default to Stoplight Elements.

### What is the motivation / use case for changing the behavior?

Largest motivation is to unblock OpenAPI 3.1, which is supported by Stoplight Elements.

Secondary motivation is to provide an alternative UI, which some Developers may choose if they prefer it.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
