### ISSUE TITLE
The Get request does not carry authorization

### ISSUE THREAD

**Issue by Q-J-Brilliant** [nestjs/swagger#1859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/101537665/159423051-bb5f93f9-9c61-4c7f-aedd-662a1032b1a9.png)
![image](https://user-images.githubusercontent.com/101537665/159423130-72e1c154-d3da-4976-a1ad-c0f6096ff0ce.png)

### Minimum reproduction code

1

### Expected behavior

Can carry

### Package version

5.2.0

### NestJS version

8.4.0

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
