### ISSUE TITLE
"Module not found" run-time error, if the project directory name contains non-ASCII characters

### ISSUE THREAD

**Issue by retnag** [nestjs/swagger#1868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I get following error when I start the server:
```
$ npm start                 
> server@0.0.1 start
> nest start

Error: Cannot find module '/home/xyz/Documents/Programozás/2022/project/src/AType'
Require stack:
- /home/xyz/Documents/Programozás/2022/project/dist/app.controller.js
- /home/xyz/Documents/Programozás/2022/project/app.module.js
- /home/xyz/Documents/Programozás/2022/project/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/xyz/Documents/Programozás/2022/project/dist/app.controller.js:31:46)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

### Minimum reproduction code

https://github.com/retnag/nestjs-swagger-apostrophe-in-path-error

### Steps to reproduce

1. Create a Directory, that contains a non-ASCII character in its name (I have tested it with "é" and "á". Example: "Programozás")
2. `cd` into it, and clone the [reproduction code](https://github.com/retnag/nestjs-swagger-apostrophe-in-path-error) into it. The goal here is, to have a non-ASCII character in the full path of the projects Filenames.
3. run `npm i` as usual
4. `npm start`

Key requirements provided by the [linked](https://github.com/retnag/nestjs-swagger-apostrophe-in-path-error) repo:
1. The full Path of where the project resides contains a non-ASCII character.
2. The [swagger cli-plugin](https://docs.nestjs.com/openapi/cli-plugin#using-the-cli-plugin) is enabled
3. The explicit or inferred return-type of a controller function, that handles an endpoint, is a class imported from another file in the project. 

### Expected behavior

I would expect the server to start without the error. I spent hours figuring out what's going on here, tests ran fine. Typescript compilation runs fine. I have tracked down the error to the following line in the emitted code by typescript (file: dist/app.controller.js:31): 
```
openapi.ApiResponse({ status: 201, type: require("/home/xyz/Documents/Programoz\u00E1s/2022/project/src/AType").AType })
```
Notice the \u00E1s Unicode escape sequence in the file path string. Now the "Module not found" error makes sense, since this directory really doesn't exist....

Also, and this might be a separate Issue altogether, I would expect a relative path here, as this absolute path is only going to be valid on the developer machine, ergo the build will fail with this error on any other machine It's deployed to.

### Package version

5.2.1

### NestJS version

8.0.0

### Node.js version

14.19.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

This was successfully reproduced on another machine on Windows.

I guess this is not a high-priority issue, as a simple workaround would be not to use Unicode characters in your directory structure, but guys, its 2022 :'), things like this really shouldn't be an issue anymore, I just lost hours debugging this, as I never had suspected a user error, or a circular dependency somwhere. Please fix this.

BUT: the fact that there is a full, dev-environment relevant absolute path emittet there, which will break the server in a production environment, kinda seems like a dealbreaker to me!

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by psam44** [comment]
I experienced the same issue, with a 'é' character in the path leading to the project.
With a replacement by a simple 'e', the module name is back to an absolute form, as expected:
`openapi.ApiResponse({ status: 200, type: require("./device.entity").Device }),`

Windows, Nestjs 9.2.1, Node 18.13.0

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2745
