### ISSUE TITLE
CLI plugin doesn't work

### ISSUE THREAD

**Issue by sinnrrr** [nestjs/swagger#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It just does not work at all.

### Minimum reproduction code

https://github.com/sinnrrr/debug/tree/nestjs-swagger-plugin-prefix

### Steps to reproduce

npm install
npm run start:dev

### Expected behavior

- `/api` should have a description and example in the specification (should have been parsed comment) 
- DTOs should have fields

### Package version

5.2.1

### NestJS version

8.4.3

### Node.js version

17.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
