### ISSUE TITLE
SwaggerModule ignores global prefix

### ISSUE THREAD

**Issue by sinnrrr** [nestjs/swagger#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`app.setGlobalPrefix('/api')` is made, and only then `SwaggerModule.setup('docs', app, document)`
now, it should be available at `/api/docs`, but it doesn't, it is spawned on `/docs`

I've tried explicitly setting `ignoreGlobalPrefix` to `false`, but that didn't help:
```
SwaggerModule.createDocument(app, config, {
    ignoreGlobalPrefix: false,
});
```

### Minimum reproduction code

https://github.com/sinnrrr/debug/tree/nestjs-swagger-plugin-prefix

### Steps to reproduce

npm install
npm start:dev

### Expected behavior

Do not ignore the global prefix and spawn it on `/api/docs` instead of `/docs`

### Package version

5.2.1

### NestJS version

8.4.3

### Node.js version

17.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
