### ISSUE TITLE
Add a better way of UI customization (customCSS and/or customJS)

### ISSUE THREAD

**Issue by OSA413** [nestjs/swagger#1881]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I've been trying to implement an SSO (OAuth2) login on the API page opening, unfortunately I only found how to add it to headers, so that's not exactly what I needed. After some search I found that it's possible to customize page with `customCss`, `customCssUrl`, and `customJs` which with some effort should help me solve my issue.

Unfortunately, it ["accepts absolute or relative path. Value must be the public url of the js file"](https://www.npmjs.com/package/swagger-ui-express). So I'll have to write a pure JS script and put it somewhere on backend to accomplish my goal.

### Describe the solution you'd like

For example, it can accept a function that will be converted to a JS file.
Or it can accept a function and run it directly after the API page is loaded.

Or probably improve the feature as it was done with `customCss`
https://github.com/scottie1984/swagger-ui-express/pull/9

### What is the motivation / use case for changing the behavior?

To simplify UI customization.

**Comment by kamilmysliwiec** [comment]
Not sure if I'm following. What's precisely doable with the `swagger-ui-express` now that is not possible with `@nestjs/swagger`?

**Comment by OSA413** [comment]
It looks like it's problem (not big actually) with `swagger-ui-express`. Both `swagger-ui-express` and `@nestjs/swagger` can do what I need but it requires an extra step (I need to place a js script in an API path to make it accessible).

The feature I suggest is to pass a function instead of path to the js script (without removing option of providing path to a script).

**Comment by kamilmysliwiec** [comment]
> It looks like it's problem (not big actually) with swagger-ui-express.

In this case, I'd suggest reporting this issue there and we'll align once it's fixed upstream.
