### ISSUE TITLE
Wrong DTO parsing using keyof as field type

### ISSUE THREAD

**Issue by yanmarinich** [nestjs/swagger#1885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have created  ArticleQueryDto with decorators from class-validator library for my GET endpoint:

// article.controller.ts

<img width="674" alt="Screenshot 2022-04-10 at 23 01 45" src="https://user-images.githubusercontent.com/21159971/162635410-fa0fedbf-ca7a-4c54-817f-bc409fa3e3d3.png">

// article-query.dto.ts

<img width="400" alt="Screenshot 2022-04-10 at 23 01 08" src="https://user-images.githubusercontent.com/21159971/162635394-f13727e7-6fe9-462a-841b-a1714ea45180.png">

Pay attention to the type of "orderBy" field. it is string. In this case everything works fine. Swagger sees 2 params:

<img width="617" alt="Screenshot 2022-04-10 at 23 00 16" src="https://user-images.githubusercontent.com/21159971/162635368-7c59b26c-ff0f-4497-adf2-b47837135941.png">

But if I want to use keyof ArticleDto to prevent setting values that don't exist in ArticleDto. Like this:

<img width="378" alt="Screenshot 2022-04-10 at 23 09 01" src="https://user-images.githubusercontent.com/21159971/162635709-0ae21650-859b-4e41-9353-d9128c056661.png">

Swagger refuses to see orderBy param at all:

<img width="516" alt="Screenshot 2022-04-10 at 23 11 00" src="https://user-images.githubusercontent.com/21159971/162635779-a5077314-570f-4f7a-9988-0aeff30c05e9.png">

The only solution I found was specifying the field with @ApiProperty({ type: 'string' }):

<img width="446" alt="Screenshot 2022-04-10 at 23 12 11" src="https://user-images.githubusercontent.com/21159971/162635817-5f5e6a18-bd8d-4c14-843a-6b5dae41a267.png">

In this case swagger can see 2 params and orderBy param has type string:

<img width="545" alt="Screenshot 2022-04-10 at 23 12 59" src="https://user-images.githubusercontent.com/21159971/162635845-eded9914-f258-49d6-84f2-07f3f6121dc5.png">

### Minimum reproduction code

https://github.com/yanmarinich/swagger-issue

### Steps to reproduce

1. npm i
2. npm run start:dev
3. go to localhost:3333/swagger
4. see bug in getArticles endpoint

### Expected behavior

I at least expect to see orderBy param in swagger

### Package version

5.2.1

### NestJS version

8.0.0

### Node.js version

14.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
