### ISSUE TITLE
Above tags visible in Swagger UI when using multiple specifications

### ISSUE THREAD

**Issue by iveselin** [nestjs/swagger#190]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When using multiple swagger specifications, lower one has tags and models of all upper ones
![image](https://user-images.githubusercontent.com/26610958/52351982-07d77880-2a2c-11e9-80dd-7e7a205560e9.png)

## Expected behavior

Every specification should have only selected tags and corresponding models

## Minimal reproduction of the problem with instructions

[Sample](https://github.com/iveselin/nestswaggerbug)
## What is the motivation / use case for changing the behavior?

Documentation should be separated by modules, this way its confusing with empty tags for above created tags

## Environment

<pre><code>
Nest version: 5.7.0
Nest swagger: 2.5.1

 
For Tooling issues:
- Node version: 10.15.0
- Platform:  Windows

Others:

</code></pre>

**Comment by 4haohansen2033** [comment]
you need to clone document_base when init document in DocumentBuilder constructor.
class DocumentBuilder {
  constructor() {
    // this.document = document_base_1.documentBase;
    this.document = JSON.parse(JSON.stringify(document_base_1.documentBase))
}

**Comment by VinceOPS** [comment]
I can confirm the same behavior with `@nestjs/swagger` 2.5.1 and Nest 5.4

**Comment by AtoianAvetik** [comment]
I can confirm the same behavior with @nestjs/swagger 3.0.2 and Nest 6.0

**Comment by kamilmysliwiec** [comment]
Fixed thanks to #261
