### ISSUE TITLE
[next] Major release notes & plans

### ISSUE THREAD

**Issue by kamilmysliwiec** [nestjs/swagger#191]
The `@nestjs/swagger` is one of the most widely used `@nestjs` packages under the `@nestjs` organization.  So far it works pretty great - we have a declarative way to easily generate OpenAPI specification using decorators placed near to our DTOs/routes, we cover 3/4 potential use-cases providing a quite simple API to interact with.

However, the current model of this library doesn't fit the requirements which we should set ourselves in order to ensure that we provide the best quality for developers. Let me list a number of them.

- massive redundancy (lots of decorators that shouldn't be required)
- lack of consistency (if we want to change our property to an optional one, we very likely have to add `@IsOptional()` - for the validation purposes, change the decorator to `@ApiModelPropertyOptional()` and add a question ? mark by the end of the property name)
- no generics support 
- no interfaces support
- no auto-response schemas generation
- lack of flexibility (hard to add custom rules/decorators/interpreters)
- no circular-dependencies support

The main reason for all of these outlined issues is weak TypeScript reflection capability. Hence, the library itself will be very likely rewritten and will use TypeScript AST to support all these amazing features out-of-the-box.

I have created this issue in order to share plans with you as well as encourage you to share your personal experiences with this library - if there is something else that was very troublesome/unsupported so far, please, let me know here - we can work on the design specification together.

**Comment by nartc** [comment]
Is OpenAPI 3.0 taken into consideration?

**Comment by 19majkel94** [comment]
> The main reason for all of these outlined issues is weak TypeScript reflection capability. Hence, the library itself will be very likely rewritten and will use TypeScript AST to support all these amazing features out-of-the-box.

Just wondering: will it require a pre-compilation step (or running by a CLI like the yoga2)? 
Or you plan to generate the definitions files on the fly like a graphql definition classes in the graphql module? 🤔

**Comment by kamilmysliwiec** [comment]
I'd like to add 2 possible ways: (1) pre-compilation step (very likely exposed as a plugin to the official CLI as well) (2) generate metadata on the fly and very likely store metadata in a separate file.

**Comment by Lomkex1** [comment]
Thanks for the update 🙏, I really thought this module was dying.

I would like to see the following supported in the next version:

1. multipart-formdata file upload support with additional parameters.

2. OpenAPI 3 Specs.

**Comment by dantman** [comment]
> The main reason for all of these outlined issues is weak TypeScript reflection capability. Hence, the library itself will be very likely rewritten and will use TypeScript AST to support all these amazing features out-of-the-box.

TypeORM seems to do pretty well at extracting basic type data from TypeScript. And seems to use reflect-metadata to add metadata for columns.

Instead of a pre-compile step or metadata file, what if we tried using the same kind of technique as TypeORM?

For example we could wrap class-validator as `@nestjs/class-validator` (or `@nestjs/validator`?) and provide variants that also apply decorator metadata. e.g. The `IsOptional` from the nestjs class-validator wrapper would apply the class-validator's IsOptional as well as decorating the metadata with an isOptional metadata value. Then the swagger generator would be able to read that metadata and mark the property as optional within the model.

This may be better than pure-typescript, because it would be possible for the `@IsEmail()` decorator to apply a `format: 'email'` metadata that would be passed along to Swagger. Which is not something that would be available based on types.

**Comment by kamilmysliwiec** [comment]
@dantman `typeorm` uses the same technique as `@nestjs/swagger` is using right now. It's still very limited.

**Comment by MumblesNZ** [comment]
+1 for the support for OpenAPI 3.0, great work on nestjs in general BTW =).

**Comment by nartc** [comment]
@kamilmysliwiec Do you have a projection of how long the rewrite's going to take? Sorry I'm getting too excited I had to ask

**Comment by lukeautry** [comment]
@kamilmysliwiec Check out the work at [tsoa](https://github.com/lukeautry/tsoa); it does use the TypeScript compiler API to generate routes and a swagger spec from TypeScript code. I imagine a lot of the code you need for this project has already been implemented there in some form.

**Comment by vellengs** [comment]
@kamilmysliwiec 
https://github.com/thiagobustamante/typescript-rest-swagger
It's good to recognize ts types.

**Comment by vellengs** [comment]
https://github.com/vellengs/nest-swagger
I made a basic works version from typescript-rest-swagger

**Comment by johannesschobel** [comment]
My biggest wish for the update would be:
* OpenAPI 3.0
* deeply nested Query params (e.g., `?page[size]=100&page[number]=5` ). This would be available in OA3

Thank you so much for your hard work!

**Comment by RDeluxe** [comment]
For now we have been using [class-validator-jsonschema](https://www.npmjs.com/package/class-validator-jsonschema) to generate the swagger doc of our body and parameters using class-validator annotations.

Having both the documentation and validation in sync is pretty neat.

**Comment by mjgp2** [comment]
I was the original feature requester :)

This was the hack I came up with

```import { ArgumentMetadata, BadRequestException, Injectable, PipeTransform } from '@nestjs/common';
import { getValidator } from '_/main';
import { ClassType } from 'class-transformer/ClassTransformer';

@Injectable()
export class SwaggerValidationPipe implements PipeTransform {
    constructor(private readonly type: ClassType<any>) { }

    public transform(value: any, metadata: ArgumentMetadata) {
        const validator = getValidator();
        const swaggerDefinitionName = '#/definitions/' + this.type.name;
        if ( validator.validate(swaggerDefinitionName, value) ) {
            return value;
        }
        throw new BadRequestException(validator.errors, 'INVALID_INPUT');
    }
}```

**Comment by nartc** [comment]
Any update on the rewrite progress?

**Comment by GillesWHC** [comment]
Any progress on generics support?

**Comment by ulrichb** [comment]
+1 for Open API 3.0 because it has a much better security description (For example explicit [Bearer Auth](https://swagger.io/docs/specification/authentication/bearer-authentication/) instead of the "API Key header workaround".)

**Comment by chchrist** [comment]
We are investigating Typescript and nestjs as a tech stack for our node services and open api 3 is a requirement. It would be great to get an update. any update :)

**Comment by jmls** [comment]
yeah, a big plus here for this ... I was wondering why my parameters were being marked as "any" ;)

**Comment by ruscon** [comment]
@dantman 
> > The main reason for all of these outlined issues is weak TypeScript reflection capability. Hence, the library itself will be very likely rewritten and will use TypeScript AST to support all these amazing features out-of-the-box.
> 
> TypeORM seems to do pretty well at extracting basic type data from TypeScript. And seems to use reflect-metadata to add metadata for columns.
> 
> Instead of a pre-compile step or metadata file, what if we tried using the same kind of technique as TypeORM?
> 
> For example we could wrap class-validator as `@nestjs/class-validator` (or `@nestjs/validator`?) and provide variants that also apply decorator metadata. e.g. The `IsOptional` from the nestjs class-validator wrapper would apply the class-validator's IsOptional as well as decorating the metadata with an isOptional metadata value. Then the swagger generator would be able to read that metadata and mark the property as optional within the model.
> 
> This may be better than pure-typescript, because it would be possible for the `@IsEmail()` decorator to apply a `format: 'email'` metadata that would be passed along to Swagger. Which is not something that would be available based on types.

Today I also thought about this option and found your post :)
But, the most important thing for me is to support the validation groups in the swagger. 
Otherwise, too much duplicate code is obtained.

**Comment by Ganitzsh** [comment]
Any news on this? It doesn't appear in the milestones for 7.0.0, can we hope to have this in the near future?

**Comment by kamilmysliwiec** [comment]
See more here https://github.com/nestjs/swagger/pull/355.

**Comment by kamilmysliwiec** [comment]
PR has been merged, `next` version has been published. More information soon.
Migration steps (if you want to try it now):  https://github.com/nestjs/swagger/pull/355#issuecomment-547925879

To install run `npm i @nestjs/swagger@next`. Note: remember to update `@nestjs/common`, `@nestjs/core` and `typescript` as well to ensure that you're using the latest versions.

**Comment by hugoblanc** [comment]
> PR has been merged, `next` version has been published. More information soon.
> Migration steps (if you want to try it now): [#355 (comment)](https://github.com/nestjs/swagger/pull/355#issuecomment-547925879)
> 
> To install run `npm i @nestjs/swagger@next`. Note: remember to update `@nestjs/common`, `@nestjs/core` and `typescript` as well to ensure that you're using the latest versions.

swagger next cause nestjsx to break because of the abscence of ApiModelProperty 
```shell
/home/hugo/Documents/programming/wild-api/node_modules/@nestjsx/crud/lib/crud/validation.helper.js:23
            ApiModelProperty(options)(target, propertyKey);
```

**Comment by nartc** [comment]
@hugoblanc I’d suggest creating an issue over at nestjsx/crud repository

**Comment by johannesschobel** [comment]
Dear @hugoblanc , i think, this is (at least for now) perfectly fine, as the new major release for this package (`@nestjs/swagger`) is not officially released. Furthermore, some decorators may change for the final release..

In this context, the `@nestjsx/crud` package must adapt, if the `@nestjs/swagger` package is finally released.. Please note, that these packages are maintained by 2 different organizations!

**Comment by itamarco** [comment]
> @kamilmysliwiec Check out the work at [tsoa](https://github.com/lukeautry/tsoa); it does use the TypeScript compiler API to generate routes and a swagger spec from TypeScript code. 

I have created this demo repo of [nestjs with tsoa integration](https://github.com/SSCIsrael/nestjs-tsoa-integration). It required a [slight changes in tsoa](https://github.com/SSCIsrael/tsoa) in order to support colon path params.

It does support interfaces and it auto generating response types based on function return type.
