### ISSUE TITLE
ApiExtraModels support of enums

### ISSUE THREAD

**Issue by Mansi1** [nestjs/swagger#1911]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Use ApiExtraModels with enumartions

### Describe the solution you'd like

export enum Env {
    dev = 'DEV',
    locale = 'LOCALE',
    prod = 'PROD',
}

@Controller('v1/supplier')
@ApiExtraModels(Env)
export class TestController {

### What is the motivation / use case for changing the behavior?

i want to use enums also in frontend and see in open-api to the change

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
