### ISSUE TITLE
Property should be nullable when applying partialType 

### ISSUE THREAD

**Issue by omidh28** [nestjs/swagger#1916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using `partialType` on a DTO class, All of their properties change to `T | undefined`.

### Minimum reproduction code

https://github.com

### Steps to reproduce

```typescript
class CreateNamespaceDto {
  @ApiProperty()
  @IsNotEmpty()
  @IsString()
  readonly name!: string;
}

export class UpdateNamespaceDto extends PartialType(CreateNamespaceDto) {}

const dto: UpdateNamespaceDto = {
  name: null, //Type 'null' is not assignable to type 'string | undefined'.
}
```

### Expected behavior

`partialType` adds `@IsOptional` decorator to all properties which indicates that a property may be undefined or **null** however current behavior  only includes `undefined` and not `null`.

expected type is `T | undefined | null`

### Package version

5.2.1

### NestJS version

8.4.3

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
