### ISSUE TITLE
ApiParam should have property 'in'

### ISSUE THREAD

**Issue by EJBroeders** [nestjs/swagger#1917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The OpenAPI specs state that parameters should have an 'in' property to state how the param should be filled in. See [1](https://swagger.io/docs/specification/describing-parameters/). However, in the decorator code of ApiParam, this field is omitted from the options object. See [2](https://github.com/nestjs/swagger/blob/166e7661b7bcfa18b504005ac18b4fffdd87043f/lib/decorators/api-param.decorator.ts#L11). Hence, it's impossible to use the decorator to specify a parameter which is specified as a query, and not as a path.

Links:
1. https://swagger.io/docs/specification/describing-parameters/
2. https://github.com/nestjs/swagger/blob/166e7661b7bcfa18b504005ac18b4fffdd87043f/lib/decorators/api-param.decorator.ts#L11

### Minimum reproduction code

https://github.com/nestjs/swagger/blob/166e7661b7bcfa18b504005ac18b4fffdd87043f/lib/decorators/api-param.decorator.ts#L11

### Expected behavior

That this code works:
```
@ApiParam({ name: 'userId', example: 'Foo', type: string, in: 'query' })
checkUser(@Query('userId') userId: string): string { /* stub*/}
```

### Package version

5.2.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Isn't that what `@ApiQuery()` is for? And `@ApiParam()` is for the URL parameters?

**Comment by EJBroeders** [comment]
Ah, missed that, thanks! 😄 Maybe we can update the documentation and provide some additional examples for these decorators?
