### ISSUE TITLE
Swagger Module should be able to read a swagger from file

### ISSUE THREAD

**Issue by gastoncastineira** [nestjs/swagger#1930]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

At my current company we started using NestJS recently for our NodeJS APIs. We´re currently working on a script to automatize project generation with controllers, services and dtos completed from a yaml/json swagger in file (wich we'd be more than happy to share once finished), but the fact that we are obligated to fill up the decorators for the swagger-ui to work makes it redundant.

### Describe the solution you'd like

```js
import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const config = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api', app, document);

  await app.listen(3000);
}
bootstrap();
```
That's from the docs. The should be a way to pass a filepath somewhere there and create the swagger module with all its paths a schemas from that

### What is the motivation / use case for changing the behavior?

We also use Java with Spring Boot and .NET for other APIs, and both have openAPI generators built by openAPI that do this generation of the project from a swagger file. The argument to use it, wich i agree with, is that it keeps the code cleaner by deferring all data of the swagger to a single file instead of forcing you to mantain extra code with annotations across multiple files. I don't see why NestJS shouldn't give us the possibility of this as well.

**Comment by jmcdo29** [comment]
There's currently no direct support for a file path, **but** you can read the file using the `fs` module and pass in the swagger JSON instead of having to build the document via decorators.

```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const swaggerDoc = JSON.stringify(fs.readFileSync('./path/to/swagger.json').toString())
  SwaggerModule.setup('api', app, swaggerDoc);
  await app.listen(3000);
}
```
