### ISSUE TITLE
Support for @fastify/swagger

### ISSUE THREAD

**Issue by ChaseOxide** [nestjs/swagger#1936]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

[fastify-swagger](https://www.npmjs.com/package/fastify-swagger) has been deprecated and renamed to [@fastify/swagger](https://www.npmjs.com/package/@fastify/swagger).
Right now if we run the code with fastify-swagger, we get these annoying messages

```
[FST_MODULE_DEP_FASTIFY-SWAGGER] FastifyWarning.fastify-swagger: fastify-swagger has been deprecated. Use @fastify/swagger@6.0.0 instead.
[FST_MODULE_DEP_FASTIFY-STATIC] FastifyWarning.fastify-static: fastify-static has been deprecated. Use @fastify/static@5.0.0 instead.
```

### Describe the solution you'd like

Support for @fastify/swagger would be nice.
It can be either supporting both fastify-swagger (for backward compatibility) and @fastify/swagger, or just @fastify/swagger.

### What is the motivation / use case for changing the behavior?

To allow users use the more updated version of fastify-swagger

**Comment by jmcdo29** [comment]
https://github.com/nestjs/swagger/pull/1928

**Comment by HaaLeo** [comment]
@jmcdo29 do you already know when this will be released? :)
