### ISSUE TITLE
Support class-transformer

### ISSUE THREAD

**Issue by dmitryb-dev** [nestjs/swagger#1942]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Nest documentation mentions class-transformer in docs [serialisation](https://docs.nestjs.com/techniques/serialization), but swagger plugin doesn't support this.

### Describe the solution you'd like

It's pretty similar to how the official swagger repo implements it for the Java Jackson. To support Exclude and Include it's possible to check not only for a @ApiHideParameter but for those decorators too. A property name resolving should consider the "name" field of Expose options too. 
The expose groups are similar to the JsonVIew, the official swagger impl has a context available among parsers and it generates different models for different JsonView (groups). So basically when a @TransformInstanceToPlain is found on a property or controller, it should check groups mentioned in options and if no metadata for this class found - it should generate new metadata for given groups list. Another way to implement this - to create an instance of class with some random data, apply given TransformInstanceToPlain and chekh which fields is present in a result (in this case it would be easy to suppoort versions too).

### Teachability, documentation, adoption, migration strategy

It would require additional mentioning in the docs for swagger plugin with a list of limitations. (Now it also would be nice to have some warning about current limitations, because it's pretty confusing to have some feature in the docs that isn't supported in another feature)

### What is the motivation / use case for changing the behavior?

1. Be consistent. So If something is mentioned in docs, swagger plugin should support it or have some warning about limitations regarding that.
2. `@Expose` decorator is much more powerful and allows to hide nested properties when returning response in opposite to mapped-types

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
