### ISSUE TITLE
Bearer auth doesn't work

### ISSUE THREAD

**Issue by mruknowme** [nestjs/swagger#1943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Bearer token UI is not showing. Alway defaults to Basic auth.

### Minimum reproduction code

https://docs.nestjs.com/openapi/security#bearer-authentication

### Steps to reproduce

```typescript
// ...
const swaggerConfig = new DocumentBuilder()
    .addBearerAuth()
    .build();

const document = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup(globalPrefix, app, document);

 // ....
 // In controller
 @ApiBearerAuth() // added to controller class
 // ....
```

<img src="https://i.ibb.co/tDLKNpg/Screen-Shot-2022-06-06-at-1-47-49-pm.png">
<img src="https://i.ibb.co/sKjJMVj/Screen-Shot-2022-06-06-at-1-46-55-pm.png">

### Expected behavior

Should show dialog/modal for bearer auth

### Package version

5.2.1

### NestJS version

8.4.6

### Node.js version

17.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by devstack-be** [comment]
Could you share your entire repo?
I tried this on mine project and it's working perfectly.

Best regards

**Comment by RyanHedges** [comment]
I believe this relates to this issue in swagger UI - https://github.com/swagger-api/swagger-ui/issues/7926

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
