### ISSUE TITLE
Generate Server Code Stubs from Existing Swagger File

### ISSUE THREAD

**Issue by ToJen** [nestjs/swagger#1947]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

N/A

### Describe the solution you'd like

Nest comes with code to swagger UI. Oftentimes a project already has a swagger file in hand and it'd be better to generate the types and server code stubs from that rather than writing it by hand. This exists in 

How can a tool like [swagger-codegen](https://github.com/swagger-api/swagger-codegen) or others be integrated into Nest.js?

### Teachability, documentation, adoption, migration strategy

`nest g resource --fromSpec "./api/swagger.yaml"`
`nest g co --fromSpec "./api/swagger.yaml" --path "pets/dogs"`

The output will then be files containing the code stub for handling the request (up to the controller level, not service).

### What is the motivation / use case for changing the behavior?

- Provide similar development experience from
- Normal practice at large enterprises with Java's Spring or [Go Swagger](https://goswagger.io/#generate-an-api-server)
- Validation step before running unit tests

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
