### ISSUE TITLE
fastify-swagger has been deprecated. Use @fastify/swagger@6.0.0 instead.

### ISSUE THREAD

**Issue by alexNerazim** [nestjs/swagger#1948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have the issue that is related in that pr  https://github.com/nestjs/swagger/pull/1908 but here seems that it´s closed and fixed, but i still having the issue. So I would like to know if its already fixed and merged and need to update something or not yet.

### Minimum reproduction code

https://github.com/nestjs/swagger/pull/1908

### Expected behavior

Package @fastify/swagger  upgraded

### Package version

5.2.1

### NestJS version

8.0.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
