### ISSUE TITLE
JSON Swagger documents are sent with an unexpected content-type

### ISSUE THREAD

**Issue by IodizedGabe** [nestjs/swagger#1964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When requesting a swagger document, the returned content-type is `text/json`, rather than `application/json`.

This causes an issue for certain test libraries (e.g. `superagent`), which would otherwise be able to parse the response body as a JSON object. Currently, the swagger document is sent as a plain text string, meaning that the response would need to be manually parsed in order to be treated as a JSON object.

This appears to be caused by this: https://github.com/nestjs/swagger/blame/207de336c9fb1c29cf8d5150edfa97a82e6bea43/lib/swagger-module.ts#L86-L87

Where previously, the response was sent back with `.json()`, which ostensibly set the correct headers.
https://github.com/nestjs/swagger/commit/b666b3ec6cd41569d507b9196a5a83aacc3d5107#diff-29da6edbbb6f154de93db1c6c7a9e0e59e015605ebccf9fe1b84d26dbfb03e74L81

### Minimum reproduction code

https://github.com/IodizedGabe/nestjs-swagger-content-type

### Steps to reproduce

1. `yarn install`
2. `yarn test:e2e`

### Expected behavior

The test case should pass; `response.body` is expected to be a valid and populated object.

### Package version

6.0.1

### NestJS version

9.0.1

### Node.js version

14.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jessemyers** [comment]
As far as I'm aware, `application/json` is the official  mime type and `text/json` is [not even valid](https://www.iana.org/assignments/media-types/media-types.xhtml#text).

**Comment by IodizedGabe** [comment]
Thanks!
