### ISSUE TITLE
[6.0.1]Problem with deployment on a subroute proxied by nginx

### ISSUE THREAD

**Issue by CatsJuice** [nestjs/swagger#1965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I migrated my project's `@nestjs/swagger` dependency from `5.2.1` to `6.0.1`, everything works locally but not on a subrouting proxied by `nginx`.

In the [minimum reproduction code](https://github.com/CatsJuice/nest-swagger-on-nginx-path), I start a nginx server by docker locally, and config as:

```conf
server {
  listen       3100;
  root html;
  index index.html index.htm;

  location /api/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 60;
    proxy_read_timeout 600;
    proxy_send_timeout 600;
    proxy_pass http://10.211.55.2:3000/;
  }
```

It works both [http://localhost:3000](http://localhost:3000) and [http://localhost:3100/api/](http://localhost:3100/api/) that I can get `hello world`.

However accessing  [http://localhost:3100/api/docs](http://localhost:3100/api/docs) not working properly.
The Swagger `index.html` can be loaded and I can see `Swagger UI` on the browser tab, the static resources is not loaded correctly:

<img width="826" alt="CleanShot 2022-07-09 at 08 05 51@2x" src="https://user-images.githubusercontent.com/39363750/178083658-ecc0b00e-deb6-48f1-9082-8c150c0eea78.png">

excpted `/api/docs/swagger-ui.css`, got `/docs/swagger-ui.css`.

Everything works when using fastify with `@nestjs/swagger@5.2.x` before, I found the `SwaggerModule.setup` function was changed: [5.2.1...6.0.1](https://github.com/nestjs/swagger/compare/5.2.1...6.0.1).

It seems that the `finalPath` in `SwaggerModule.setup` function directly replace html template in [constants.ts](https://github.com/nestjs/swagger/blob/e64a4835858c43c4e6e8906fda6331deb24a800a/lib/swagger-ui/constants.ts). In that case, how can I set the base static file path to replace with `<% baseUrl %>`? I have tried `useGlobalPrefix: true` and `app.setGlobalPrefix('api')` but the endpoints must accessed by `/api/api/`. Refer to [swagger-module.ts](https://github.com/nestjs/swagger/blob/e64a4835858c43c4e6e8906fda6331deb24a800a/lib/swagger-module.ts), it seems that the only way to affect `<% baseUrl %>` is the `globalPrefix` or `path`.

I've been working on this for hours without finding a solution, can u give me som advice?

### Minimum reproduction code

https://github.com/CatsJuice/nest-swagger-on-nginx-path

### Steps to reproduce

1. `yarn`
2. `yarn start:dev`
3. May need to config `.nginx/conf/3100.conf`
4. `docker-compose up -d`
5. Visit [http://localhost:3100/api/docs](http://localhost:3100/api/docs)

### Expected behavior

Make it possible to custom `<% baseUrl %>` prefix  in `index.html`

### Package version

6.0.1

### NestJS version

9.0.0

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Panzer1119** [comment]
But now i am getting these errors and if i revert your commit it works for me.

![image](https://user-images.githubusercontent.com/23016343/178275036-26c41160-d29d-45ed-9799-254a0f824368.png)

**Comment by kamilmysliwiec** [comment]
cc @flamewow 🙌

**Comment by CatsJuice** [comment]
@Panzer1119 I tried and found that `localhost:3333/api/api` works but `localhost:3333/api/api/` does not. This is because static resources are loaded via relative paths. Maybe I'm missing something, there might be a better solution.

**Comment by CatsJuice** [comment]
@Panzer1119 I would like to confirm if you can access it properly without the `/` at the end of the path, like `http://localhost:3333/api`

**Comment by Panzer1119** [comment]
> 

It doesn't work for me.

**Comment by Panzer1119** [comment]
An absolute path would get appended after the hostname e.g. `/api/docs` would make `http://127.0.0.1:3333/api/docs`, but `./api/docs` would make `http://127.0.0.1:333/SOME_SUB_PATH_WHERE_YOU_ARE/api/docs`.

**Comment by Panzer1119** [comment]
If you enable the `app.setGlobalPrefix('api');` in your minimum reproduction code and use `proxy_pass http://YOUR_IP:3000/api/;` for nginx instead of `proxy_pass http://YOUR_IP:3000/;` then everything works without your fix.

**Comment by CatsJuice** [comment]
@Panzer1119 😀 Thank you for your patient explanation, I was enlightened and I am sorry for causing you some trouble. After all that, I thought it best to roll back the changes I had made.

**Comment by Panzer1119** [comment]
> @Panzer1119 😀 Thank you for your patient explanation, I was enlightened and I am sorry for causing you some trouble. After all that, I thought it best to roll back the changes I had made.

No problem 😄
