### ISSUE TITLE
multipart/form-data 数组请求

### ISSUE THREAD

**Issue by abing258** [nestjs/swagger#1975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

当使用@ApiConsumes('multipart/form-data')

export class FilesAuthRightDto {
  @ApiProperty({ description: 'accountList', type: [String] })
  accounts: string[];
}
接收到的accounts是字符串不是数组

### Minimum reproduction code

无

### Steps to reproduce

![image](https://user-images.githubusercontent.com/45306202/178414094-916786be-d5f4-42f6-996f-ef76f26db1a1.png)
![image](https://user-images.githubusercontent.com/45306202/178414131-84c6795c-276c-4b51-b87b-9cd48a1d51d0.png)

### Expected behavior

应该得到 accounts: '["dasdasdassa","asdasdasd","dasdasdas"]',
但是得到：accounts: 'eqweqweqwstring,stringeqweqweqw,stringeqweqweqwe',

### Package version

5.2.1

### NestJS version

8

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
