### ISSUE TITLE
@Matches() decorator crashes app with ≥@nestjs/swagger@6.0.0

### ISSUE THREAD

**Issue by noftaly** [nestjs/swagger#1979]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

5.2.1 -> 6.0.0

### Describe the regression

If there is an `@Matches()` decorator (from class-validator) in one of your dto, then the whole app crashes with
```
./node_modules/js-yaml/lib/dumper.js:868
      throw new YAMLException('unacceptable kind of an object to dump ' + type);
            ^
YAMLException: unacceptable kind of an object to dump [object RegExp]
    at writeNode (./node_modules/js-yaml/lib/dumper.js:868:13)
    at writeBlockMapping (./node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (./node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (./node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (./node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (./node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (./node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (./node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (./node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (./node_modules/js-yaml/lib/dumper.js:731:10)
```

### Minimum reproduction code

```ts
export class CreateCatDto {
  @Matches(/[a-zA-Z0-9]*/)
  readonly name: string;
}
```

repo : https://github.com/noftaly/nestjs-swagger-repro

### Expected behavior

Do not crash

### Other

I have just updated the @nestjs/ monorepo so it is not dependent of anything else, and many people on discord reported this issue too in #swagger

Thank you for your time

**Comment by Panzer1119** [comment]
I narrowed the problem down to line L118
https://github.com/nestjs/swagger/blob/1048a323ad66c800ab46794fee594a0e3b580ca3/lib/swagger-module.ts#L118-L128

There the document is converted into yaml (as well as into json and html).

But the converted document will also print out the `@Matches(...)`, but in the `js-yaml` [documentation](https://www.npmjs.com/package/js-yaml) it says

> **dump (object [ , options ])**
> Serializes object as a YAML document. Uses DEFAULT_SCHEMA, so **it will throw an exception if you try to dump regexps** or functions. However, you can disable exceptions by setting the skipInvalid option to true.

So it cannot convert your `@Matches(/[a-zA-Z0-9]*/)` because its a regex expression and fails.

**Comment by Panzer1119** [comment]
The regular expression gets kinda skipped in the generated json, so maybe we could set `skipInvalid` to `true` and also skip it in the generated yaml document.

```ts
const yamlDocument = jsyaml.dump(document, { skipInvalid: true }); 
```

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/1980

**Comment by DaleCooper3** [comment]
Out of curiosity, in the case of an example like @Matches(/[a-zA-Z0-9]*/), can you not just treat this like @Matches('[a-zA-Z0-9]*')?

It doesn't crash either way, but the Swagger document that gets generated with the first option is invalid/weird. (It just has pattern: {})
