### ISSUE TITLE
Swagger oauth2 incorrect redirect URL oauth2-redirect.html 

### ISSUE THREAD

**Issue by Tushar1998** [nestjs/swagger#1988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to Implement Oauth2 for swagger docs security, It seems that in chrome it works perfectly, but on firefox behavior is different 

Oauth 2 redirect URL is different 

Current Behavior after starting api server
On Swagger Authorizing Enter client id and Authorize

So the redirect url in chrome comes /swagger prefix -> /swagger/oauth2-redirect but in brave and firefox it doent cant say for safari browser

I dont know whether it is a bug in swagger core or nestjs swagger
Use Auth0 for Authorization with openId Connect

### Minimum reproduction code

https://github.com/Tushar1998/ultimate-monorepo.git

### Steps to reproduce

> git checkout swagger_bug_reproduce

> npm i 

> npm run start:dev

Then go to each browser and Authorize Swagger with client Id `IyPFkApOR9RckwdbKrZC6Blnjtgr1D8Z`

### Expected behavior

On Successfull Authorization of Client 
In FireFox - Redirect Url /swagger/oauth2-redirect.html?code=vsnvsvivk
In Brave - Redirect Url /swagger/oauth2-redirect.html?code=skjkjsdv

### Package version

6

### NestJS version

9

### Node.js version

16.16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Chorme - v103
Firefox - v102
Brave - 1.41 (chromium 103)

Linux Fedora 36 RHEL 9

**Comment by flamewow** [comment]
@Tushar1998 hey, thanks for reporting the issue. Do you know if it was working in prev version of nestjs/swagger - v5?

**Comment by Tushar1998** [comment]
For Previous Version of nestjs 8.2.6 and @nestjs/swagger 5.1.5 version it was working correctly on every browser..and node version was 16.13.2

**Comment by Tushar1998** [comment]
Updating to version 6.0.4 fixes the issue
