### ISSUE TITLE
defaultExpanded feature to make it not expanded

### ISSUE THREAD

**Issue by muratj** [nestjs/swagger#2000]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Goal: to make each tag not expanded by default (defaultExpanded: false)

### Describe the solution you'd like

add a property for document builder defaultExpanded or docExpantion

### What is the motivation / use case for changing the behavior?

to see all swagger-ui tags not expanded by default! expand only the one I want!

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
