### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:1:1)

### ISSUE THREAD

**Issue by alifakoor** [nestjs/swagger#2002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi
I use @nestjs/swagger^6.0.4, and when I want to see the swagger's page, I got this errors
`
Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-bundle.js:1:1)
Uncaught SyntaxError: Unexpected token '<' (at swagger-ui-standalone-preset.js:1:1)
Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload (swagger-ui-init.js:210:7)
`

I don't know why, it works until two days ago, and I didn't change anything in my code.

### Minimum reproduction code

https://github.com/smartmakran/backend

### Expected behavior

show the swagger's page

### Package version

6.0.4

### NestJS version

8.2.1

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Any ideas on what might be causing this @flamewow ?

**Comment by flamewow** [comment]
> Any ideas on what might be causing this @flamewow ?

gonna check out reproduction repo, no ideas for now

**Comment by flamewow** [comment]
@alifakoor please provide step-by-step instructions on how to observe the issue, it's not clear how to use min reproduction repo you provided

**Comment by alifakoor** [comment]
> @alifakoor please provide step-by-step instructions on how to reproduce the issue, it's not clear how to use min reproduction repo you provided

I ran these command for install dependencies and run the project
`
npm i
npm run start:dev
`
and then opened [http://localhost:3300/swagger](http://localhost:3300/swagger) on the browser.
NOTE: the Mongodb must be run on port 27017

**Comment by sylee-twc** [comment]
> > @alifakoor please provide step-by-step instructions on how to reproduce the issue, it's not clear how to use min reproduction repo you provided
> 
> I had a stupid mistake, it's ok right now. thanks.

I'm stupid too.
I have the same problem.
How did you solve it?

**Comment by alifakoor** [comment]
> > > @alifakoor please provide step-by-step instructions on how to reproduce the issue, it's not clear how to use min reproduction repo you provided
> > 
> > 
> > I had a stupid mistake, it's ok right now. thanks.
> 
> I'm stupid too. I have the same problem. How did you solve it?

I had a mistake in my route name

**Comment by pogo420** [comment]
What mistake can you please explain. I am seeing the same issue.

**Comment by alifakoor** [comment]
> What mistake can you please explain. I am seeing the same issue.

I wrote down my route incorrectly.
