### ISSUE TITLE
formdata with object or array of object showing string format and giving error

### ISSUE THREAD

**Issue by nitinmagdumvista** [nestjs/swagger#2005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

export class **ContainerCategoryDTO** {
  @ApiProperty({ type: String })
  @IsString()
  name: string;

  @ApiProperty({ type: String })
  @IsString()
  value: string;
}

export class **LanguageDTO** {
  @ApiProperty({ type: String })
  @IsNotEmpty()
  @IsString()
  en_US: string;
}

export class **CreateContainersDTO** {
  @ApiProperty()
  @Type(() => LanguageDTO)
  @IsString()
  name: LanguageDTO;

  @ApiProperty()
  @IsArray()
  @ArrayNotEmpty()
  @Type(() => **ContainerCategoryDTO**)
  @ValidateNested({ each: true })
  category: **ContainerCategoryDTO**[];

  @ApiProperty({ type: 'string', format: 'binary' })
  **file**: any;

  @ApiProperty({ type: Boolean, required: false })
  @IsOptional()
  isEnabled: boolean;
}

/**
   * create container
   * @param file
   * @param createContainersDTO
   * @param user
   * @param request
   */
  @UseInterceptors(FileInterceptor('file'))
  @Post('v1/containers')
  **@ApiConsumes('multipart/form-data')**
  **@ApiBody({ type: CreateContainersDTO })**
  @ApiOperation({ summary: 'Create Container' })
  @ApiCreatedResponse({
    description: 'Container was successfully created',
    type: [Containers],
  })
  @ApiBadRequestResponse({ description: 'Bad request' })
  @ApiUnauthorizedResponse({ description: 'Not authorized' })
  @ApiInternalServerErrorResponse({ description: 'Internal Server Error' })
  @ApiConflictResponse({ description: 'Confict' })
  @ApiForbiddenResponse({ description: 'Forbidden' })
  @ApiInternalServerErrorResponse()
  async createContainers(
    @UploadedFile() file: Express.Multer.File,
    **@Body() createContainersDTO: CreateContainersDTO,**
    @UserExtractor() user: UserDTO,
    @Req() request: Request,
  ): Promise<Containers> {
    
         try {
            if (!file) {
              throw new BadRequestException('Image file is required');
            }
            console.log('createContainersDTO', createContainersDTO);
           } catch(err) {
             console.log("error",err)   
           }
}

![Screen Shot 2022-07-28 at 12 05 07 AM](https://user-images.githubusercontent.com/109283064/181347075-4d879360-6fd9-48c3-80e6-496906d9b819.png)

### Minimum reproduction code

https://github.com/nestjs/swagger/issues/new?assignees=&labels=needs+triage%2Cbug&template=Bug_report.yml

### Expected behavior

its should accept array of container object that is  
[{
   name:"test name",
   value:"test value"
} ]

but it is throwing error

### Package version

^5.2.0"

### NestJS version

^8.0.0"

### Node.js version

14.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
