### ISSUE TITLE
Explorer don't display on   "@nestjs/swagger": "6.0.4", 

### ISSUE THREAD

**Issue by morbargig** [nestjs/swagger#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Update package (on NX workspace)

<img width="453" alt="image" src="https://user-images.githubusercontent.com/51287453/182026299-1004734b-f7a1-4300-9ad5-93b7ed174b7b.png">

explorer flag set to true

<img width="536" alt="image" src="https://user-images.githubusercontent.com/51287453/182026319-92e8ba3d-18f6-4667-9642-62d201fc9082.png">

explorer input with display none
and not working, on previous version  “@nestjs/swagger”: “^5.2.1”, it worked 

<img width="771" alt="image" src="https://user-images.githubusercontent.com/51287453/182026385-8677785d-6bcd-435d-a8c4-082d5e95155f.png">

### Minimum reproduction code

https://github.com/morbargig/nx

### Expected behavior

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/51287453/182026881-fa71ab71-b53a-4ca9-aadf-f6ffb376a129.png">

### Package version

6.0.4

### NestJS version

9.0.7

### Node.js version

v16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
cc @flamewow this sounds like another regression(?)

**Comment by flamewow** [comment]
@kamilmysliwiec yeah, created fix PR

**Comment by morbargig** [comment]
> @kamilmysliwiec yeah, created fix PR

Thanks guys appreciate!

**Comment by kamilmysliwiec** [comment]
Fixed in 6.0.5
