### ISSUE TITLE
Can't send body with get request

### ISSUE THREAD

**Issue by morbargig** [nestjs/swagger#2014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Send some get request with body swagger will show error 
when I run the command on terminal, it worked
```bash 
$  curl -X 'GET' \
                                                                  'http://localhost:8080/api/checkup' \
                                                                  -H 'accept: application/json' \
                                                                  -H 'Content-Type: application/json' \
                                                                  -d '{
                                                              "name": "string"
                                                            }'
true⏎                                               
```

error "Undocumented | TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body."

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/51287453/182140134-4e3864bc-780d-4b29-8063-c12b9011ed22.png">

### Minimum reproduction code

https://github.com/morbargig/nx

### Expected behavior

```bash 
$  curl -X 'GET' \
                                                                  'http://localhost:8080/api/checkup' \
                                                                  -H 'accept: application/json' \
                                                                  -H 'Content-Type: application/json' \
                                                                  -d '{
                                                              "name": "string"
                                                            }'
true⏎                                               
```

Some as the terminal command output 
with no errors, not once I had used get request with body

### Package version

6.0.4

### NestJS version

9.0.7

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
