### ISSUE TITLE
Closed bug

### ISSUE THREAD

**Issue by morbargig** [nestjs/swagger#2015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In this link, I open a bug which give error when send body within GET request on swagger execute code by the browser
I showed that on curl request on the CLI it worked because get request normally don't have body but it those possible.
Send me to discord chat isn’t going to fix the bug…
So please recheck this bug report because I have no intent to write it again.

https://github.com/nestjs/swagger/issues/2014#issue-1324277845

### Minimum reproduction code

https://github.com/morbargig/nx

### Expected behavior

Make get request on swagger works,
because for some reason it crash and give this error 
“Undocumented | TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.”

Consider the curl or fetch call, run the browser how my effect this error mine was 

Google Chrome
Version 103.0.5060.134 (Official Build) (x86_64)

### Package version

6.0.4

### NestJS version

9.0.7

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
[This is a very well written out answer about why `GET` requests should **not** contain a body.](https://stackoverflow.com/a/983458/9576186). It's not that they can't, it's that there's no rules around a GET request with a body, and thus the body should be ignored.
