### ISSUE TITLE
CLI plugin is not working

### ISSUE THREAD

**Issue by ragokan** [nestjs/swagger#2018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Swagger CLI plugin does not provide types without decorators.

![image](https://user-images.githubusercontent.com/63511519/182867087-5eb1746c-b557-42ab-9bd6-bb42dbff999e.png)

As you can see here, I implemented it according to the docs. 

![image](https://user-images.githubusercontent.com/63511519/182867225-c2d080d4-81ab-4d22-a901-811864aed04b.png)

![image](https://user-images.githubusercontent.com/63511519/182867249-bfd8cb9f-8f17-4b52-9f6f-a9679339380e.png)

At the time I started using this plugin, I had this problem only for minutes, after deleting node_modules/lock file and installing packages then the app, it was magically fixed. But sadly this time it is not fixed. I also tried downgrading versions, trying Fastify Swagger instead of Express, nothing works. 

I also tried running nest build, etc. Sadly nothing worked.

### Minimum reproduction code

https://github.com/ragokan/ratata

### Steps to reproduce

1. npm install
2. npm run db:sync
3. npm run dev
4. Go to http://127.0.0.1:8000/api-docs

### Expected behavior

I expect to see the types on Swagger UI.

### Package version

6.0.5

### NestJS version

9.0.8

### Node.js version

18.7.0

### In which operating systems have you tested?

- [X] macOS
- [x] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Move the class definition to it's own file with the suffix `.dto.ts`. This tells the swagger plugin to actually look at it [as we have documented](https://docs.nestjs.com/openapi/cli-plugin#overview)

> Please, note that your filenames must have one of the following suffixes: ['.dto.ts', '.entity.ts'] (e.g., create-user.dto.ts) in order to be analysed by the plugin.

**Comment by ragokan** [comment]
> Move the class definition to it's own file with the suffix `.dto.ts`. This tells the swagger plugin to actually look at it [as we have documented](https://docs.nestjs.com/openapi/cli-plugin#overview)
> 
> > Please, note that your filenames must have one of the following suffixes: ['.dto.ts', '.entity.ts'] (e.g., create-user.dto.ts) in order to be analysed by the plugin.

Hey, when you check other one, it is in **post.entity.ts**, but still it is also not typed.

![image](https://user-images.githubusercontent.com/63511519/182871897-722665db-9b09-408c-b661-229a77ce46d8.png)

It was typed before.

**Comment by jmcdo29** [comment]
You don't specify what `@Get()` returns, it's left to Typescript to imply, so it won't be properly reflected. You can see in the `POST /api/post` that the body is properly displayed and typed out.

For further support, please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
