### ISSUE TITLE
Generate Swagger UI from `.json` file

### ISSUE THREAD

**Issue by fityannugroho** [nestjs/swagger#2020]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have define my API documentation in a `.json` file using openAPI v3. Can I host it with `@nestjs/swagger`? 

### Describe the solution you'd like

I think `SwaggerModule` must have a method like `setupFromJson()` that have one parameter to take the path of `openapi.json` file.

The implementation may be like this:

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { SwaggerModule } from '@nestjs/swagger';

const app = await NestFactory.create(AppModule);
const docsPath = 'api.json';
SwaggerModule.setupFromFile('api', app, docsPath);
```

### What is the motivation / use case for changing the behavior?

Some developers may using "**Design First**" approach that define the API docs before start coding. So, it would be a waste of time to define the document using the decorators.

Reference: [Design First or Code First: What’s the Best Approach to API Development? ](https://swagger.io/blog/api-design/design-first-or-code-first-api-development/)

**Comment by jmcdo29** [comment]
You can already pass the open API JSON to `SwaggerModule.setup()`. Just load up the json via the `fs` module or a `require ` statement and you're good to go.
