### ISSUE TITLE
Redirect Url no longer using document path

### ISSUE THREAD

**Issue by DanielAeon** [nestjs/swagger#2024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When setting up the Auth in the swagger before version 9 it use to set the redirect url to the serverURL/SwaggerPath/oauth2-redirect.htm

Now is is returning to serverURL/oauth2-redirect.htm no matter what configuration changes I put in to tell it to use the path as /swagger

### Minimum reproduction code

https://github.com/nestjs/swagger

### Steps to reproduce

const swaggerConfig = new DocumentBuilder()
		.addOAuth2(
			{
				type: 'oauth2',
				flows: {
					implicit: {
						authorizationUrl: `${CONFIG.auth.authUrl}/authorize`,
						tokenUrl: CONFIG.auth.audience,
						scopes: CONFIG.auth.scope,
					},
				},
				scheme: 'bearer',
				bearerFormat: 'JWT',
				in: 'header',
			},
			'Authorization',
		)
		.setTitle('API')
		.setBasePath('/')
		.setDescription('The API description')
		.setVersion('1.0')
		.build();

	const document = SwaggerModule.createDocument(app, swaggerConfig);
	SwaggerModule.setup('', app, document, {
		swaggerOptions: {
			baseUrl: '/',
			showCommonExtensions: true,
			filter: true,
			persistAuthorization: false,
			displayRequestDuration: true,
			tryItOutEnabled: true,
			tagsSorter: 'alpha',
			operationsSorter: 'alpha',
			// oauth2RedirectUrl: `http://localhost:3000/swagger/oauth2-redirect.html`,
		},
		initOAuth: { clientId: CONFIG.auth.clientId, scopes: CONFIG.auth.scope },
	});

### Expected behavior

Should be including the path in the url

### Package version

6.0.5

### NestJS version

9.0.8

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by DanielAeon** [comment]
How exactly do I do that? without paying for an Auth provider to prove my point? which would then be my private information needing to be used. What I can tell you is this worked 1 day ago, and since I upgraded it no longer works properly.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/issues/1828#issuecomment-1208651518

**Comment by DanielAeon** [comment]
What I can tell you is this SwaggerModule.setup('servername', app, document, {}).
Server name attribute is now longer being added to the return_uri address. before it would be /servername/static/oauth2-redirect.htm not its just putting /oauth2-redirect.htm and not adding /servername.

**Comment by kamilmysliwiec** [comment]
@flamewow would you like to look into this issue? Not sure if there were any breaking changes regarding OAuth flow

**Comment by rghoshfinaxys** [comment]
I'm also having this issue. 
I set up my swagger with:

```typescript
const config = new DocumentBuilder()
    .setTitle('My application')
    .setDescription('My API description')
    .setVersion('1.0')
    .addTag('my tag')
    .addBearerAuth(
      {
        type: 'openIdConnect',
        openIdConnectUrl: "<my provider>/.well-known/openid-configuration",
      }
    )
    .build();
  const document = SwaggerModule.createDocument(app, config);
```

The authorization does go to the provider, but afterwards I'm redirected to what seems to be a static `oauth2-redirect.html` uri.

**Comment by flamewow** [comment]
@DanielAeon can you please check by opening the swagger URL with a slash at the end? 
e.g. your swagger URL is HTTP://localhost:3000/api-docs, try opening HTTP://localhost:3000/api-docs/ and see if you'll get different results
