### ISSUE TITLE
The type mapping utility functions are composable is wrong？？

### ISSUE THREAD

**Issue by lucy091** [nestjs/swagger#2025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The type mapping utility functions are composable is wrong？？

variable b have all the properties of EmployeeEntity.
but expect only have optional employeeName and  employeeDomain property 

![image](https://user-images.githubusercontent.com/33422728/184104934-79ca2cf2-d0ed-4b72-b2a7-c0cab9561f24.png)

### Minimum reproduction code

no git repository

### Expected behavior

mapping utility functions are composable

### Package version

6.0.4

### NestJS version

9.0.0

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by lucy091** [comment]
https://codesandbox.io/s/funny-stitch-pjpc1f?file=/src/test.dto.ts

![image](https://user-images.githubusercontent.com/33422728/184274177-7d8ebe74-9904-4847-8119-44b3d5b1120f.png)

**Comment by jmcdo29** [comment]
Add `as const` to your keys array and this works as expected. I assume it's a Typescript issue of without the `as const` Typescript just sees `string[]` so all of the keys are accepted, but when you add `as const` Typescript _knows_ what keys will be used and you get an error when trying to access any of the other keys

**Comment by lucy091** [comment]
oh yeah!! Add as const to your keys array and this works as expected! thanks
