### ISSUE TITLE
The @IsIn decorator option `each` is not picked up by the CLI plugin

### ISSUE THREAD

**Issue by hissalht** [nestjs/swagger#2027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the `@IsIn` decorator in a DTO, the `each` option is ignored.

```typescript
const COLORS = ['Blue', 'Red', 'Green'];

export class CreatePersonDto {
  @IsArray()
  @IsIn(COLORS, { each: true })
  favoriteColors: string[];
}
```

The `favoriteColors` field is documented to be a single string instead of an array of strings.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/7683740/184278588-f8f44826-ee0f-4e5a-a975-ff433f23650f.png">

### Minimum reproduction code

https://github.com/hissalht/Reproduction-nestjs-swagger-plugin-ignoring-the-each-option

### Steps to reproduce

1. `yarn install`
2. `yarn start:dev`
3. Open `localhost:3000/api`

### Expected behavior

The `favoriteColors` property shoud be an array of strings

### Package version

6.0.5

### NestJS version

8.4.7

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
