### ISSUE TITLE
Write swagger.json to disk on build?

### ISSUE THREAD

**Issue by manuschillerdev** [nestjs/swagger#2029]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently I am starting up a dev server in our pipeline to extract the swagger definition, since I need the artifact to build an API Client for my API with https://www.npmjs.com/package/openapi-typescript-codegen.

```typescript
    const config = new DocumentBuilder()
        .setTitle("My Service")
        .setDescription("Documentation for the API for my Service")
        .addTag("health")
        .build();

    const document = SwaggerModule.createDocument(app, config);
    fs.writeFileSync("swagger-api.json",JSON.stringify(document) );
    SwaggerModule.setup("swagger", app, document);
```

### Describe the solution you'd like

It would be nice if writing the file to disk could be a side effect of the build task instead.

### What is the motivation / use case for changing the behavior?

Generating API-Clients automatically prevents a whole lot of errors in contrast to integrating the endpoints manually. It also offers the possibility for static analysis for contracts between services.

**Comment by manuschillerdev** [comment]
As a workaround we introduced an environment variable on CI, build the app, start the server and immediately exit the process after the export.
```typescript
  // main.ts
  const config = new DocumentBuilder()
    .setTitle("My Service")
    .setDescription("Documentation for the API for my Service")
    .addTag("health")
    .build();

  const document = SwaggerModule.createDocument(app, config);
  fs.writeFileSync("swagger-api.json",JSON.stringify(document) );
  SwaggerModule.setup("swagger", app, document);

  // NestJS builds the Swagger Docs dynamically at runtime based on the decorators and
  // decorator metadata.
  // In CI we only want to export the swagger json, so we build the app, and bootstrap the
  // application. We do not want the server to do anything more than bootstrapping,
  // so we immediately exit the process once the export is done.
  if(process.env.EXPORT_SWAGGER_JSON) process.exit(0);

  const port = app.get(ConfigService).get("APP_PORT") ?? 3001;
  await app.listen(port, "0.0.0.0");
```

on CI (pseudo)
```bash
pnpm build && EXPORT_SWAGGER_JSON=true pnpm start # -> swagger-api.json is 
``` 

is there a more elegant way to to this?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
