### ISSUE TITLE
Requesting nestjs/swagger implementation of swagger-ui-express customJsStr option

### ISSUE THREAD

**Issue by Branchverse** [nestjs/swagger#2037]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Followup to original [issue](https://github.com/nestjs/swagger/issues/1881#issue-1197257342)

Issue was closed on April 11th

Swagger-ui-express added desired function on May 13th [commit](https://github.com/scottie1984/swagger-ui-express/commit/ec32130c14789c901d3e2d3e0d2a73a1c65e1be4)

This functionality is not yet implemented in nestjs/swagger v6.0.5 release

### Describe the solution you'd like

Implementation of the aforementioned functionality into nestjs/swagger

### What is the motivation / use case for changing the behavior?

The current option customJs requires a public url path for a js file, meaning you have to dedicate an endpoint in the api to serve the File.

It is way more lightweight and convenient to just pass the file as a string.

Being up to date with swagger-ui-express functionalities.

**Comment by flamewow** [comment]
Would you like to submit the PR?


side note: in swagger-ui-express those param names are kind of messed up
```
<% customJs %>
<% customJsStr %>
<% customCssUrl %>
<style>
  <% customCss %>
</style>
```
I'd rather:
rename customJs -> customJsUrl
rename customJsStr -> customJs
keep customCssUrl & customCss, but that's kind of a breaking change. 
WDYT @kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
Yeah, it's indeed not ideal @flamewow. We can't introduce a breaking change without releasing another major version though. Let's track this here https://github.com/nestjs/swagger/pull/2039
