### ISSUE TITLE
Requesting nestjs/swagger implementation of WebSocketGateway

### ISSUE THREAD

**Issue by MikhaelGerbet** [nestjs/swagger#2038]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It should be good if Nestjs Swagger can support the websocket @SubscribeMessage to make a helpfull documentation

### Describe the solution you'd like

The goal is to use ` @ApiTags('Ressource name)` to display all @SubscribeMessage in Swagger

### What is the motivation / use case for changing the behavior?

In fact, when we use Nestjs to make an api Websocket, it's not confortable to share the messages list and data returned

**Comment by flamewow** [comment]
@MikhaelGerbet openAPI (swagger) is built for HTTP, if you need to document event-based system I'd recommend taking a look at https://github.com/flamewow/nestjs-asyncapi

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
