### ISSUE TITLE
Swagger CLI Plugin -- ArrayMinSize/ArrayMaxSize

### ISSUE THREAD

**Issue by DaleCooper3** [nestjs/swagger#2042]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

classValidatorShim does not appear to recognize ArrayMinSize and ArrayMaxSize class validator decorators. When using the Swagger plugin, we still have to use @ApiProperty({minItems:x}) when enforcing Array sizes.

### Describe the solution you'd like

Map ArrayMinSize and ArrayMaxSize to minItems and maxItems values automatically.

### What is the motivation / use case for changing the behavior?

Consistency in behavior with the classValidatorShim.

**Comment by kamilmysliwiec** [comment]
> classValidatorShim does not appear to recognize ArrayMinSize and ArrayMaxSize class validator decorator

That's correct.

We currently don't plan to support these decorators.

Please search through some of our old issues on this (this has been discussed several times in the past).
