### ISSUE TITLE
Write according to the example of the official website, run error

### ISSUE THREAD

**Issue by greenking19** [nestjs/swagger#2043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is an example of the official website

`reults` in `PaginatedDto` are not used `@ApiProperty()`
```typescript
export class PaginatedDto<TData> {
  @ApiProperty()
  total: number;

  @ApiProperty()
  limit: number;

  @ApiProperty()
  offset: number;

  results: TData[];
}

export class CatDto {
  @ApiProperty()
  name: string;

  @ApiProperty()
  age: number;

  @ApiProperty()
  breed: string;
}

export const ApiPaginatedResponse = <TModel extends Type<any>>(
  model: TModel,
) => {
  return applyDecorators(
    ApiOkResponse({
      schema: {
        allOf: [
          { $ref: getSchemaPath(PaginatedDto) },
          {
            properties: {
              results: {
                type: 'array',
                items: { $ref: getSchemaPath(model) },
              },
            },
          },
        ],
      },
    }),
  );
};

@ApiPaginatedResponse(CatDto)
async findAll(): Promise<PaginatedDto<CatDto>> {}
```

Prompts when running:
```
throw new Error(`A circular dependency has been detected (property key: "${key}"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").`);
```
I tried to fix it and found that as long as the `results` used `@ApiProperty()` would not be reported
👇 👇code:
```typescript
export class PaginatedDto<TData> {
  @ApiProperty()
  total: number

  @ApiProperty()
  limit: number

  @ApiProperty()
  offset: number

  @ApiProperty()
  results: TData[]
}
```
Why is that?

### Minimum reproduction code

https://github.com/greenking19/swagger-bug

### Steps to reproduce

1. `npm install`
2. `npm run start:dev`

### Expected behavior

no bug

### Package version

^6.0.5

### NestJS version

^9.0.0

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
