### ISSUE TITLE
Properties declared throught "constructor shorthand" do not appear in Swagger UI

### ISSUE THREAD

**Issue by tsimbalar** [nestjs/swagger#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the `@nestjs/swagger` plugin, with classes that use "constructor shorthand" (i.e. properties declared inline with the constructor cf https://dev.to/satansdeer/typescript-constructor-shorthand-3ibd ), in the generated OpenAPI doc, properties declared in constructor are missing.

### Minimum reproduction code

https://github.com/tsimbalar/nest-constructor-shorthand-repro

### Steps to reproduce

1. `npm install`
2. `npm run start:dev`
3. `open http://localhost:3000/api`

### Expected behavior

Under the `/example/shorthand` endpoint, the example value should contain a property `items`, like for the `/example` endpoint.

i.e. currently `shorthand` looks like this : 
![image](https://user-images.githubusercontent.com/160544/187189333-1d3e7d89-e705-47ae-a721-e9267a86794c.png)

but we expect it to look like this (the one without shorthand behaves ok): 

![image](https://user-images.githubusercontent.com/160544/187189403-b035d86f-f90d-4749-b228-9cc55a353cf2.png)

### Package version

6.1.0

### NestJS version

9.0.0 (but also happened with 8)

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by tsteuwer-accesso** [comment]
This happens with extending classes as well:

```

export class Price {
	@IsNumber({
		allowInfinity: false,
		allowNaN: false,
	})
	@ApiProperty({
		example: '52.31',
	})
	total: number;
}

export class CustomerType {
	@IsInt()
	@ApiProperty({
		example: 543,
	})
	id: number;
}

export class PackageData {
	@IsString()
	@ApiProperty({
		description: 'The display name of the package.',
	})
	name: string;

       @ApiProperty({
              description: 'Pricing information'
       })
       price: Price;

        /**
	 * Customer Types
	 */
	@ApiProperty({
		description: 'The customer types of the package.',
                type: CustomerType,
                isArray: true,
	})
	customerTypes: CustomerType[];
}

export class PackageDto extends Entity<number, PackageData, PackageRelationships> {
	constructor(id: number, attributes: PackageData, relationships: PackageRelationships, links: RelationshipLink) {
		super(new EntityData(EntityName.PACKAGE, id, attributes, relationships, links));
	}
}
```
This produces the same result as above even though the generics are passed in and Entity is a class, not a interface.

```
{}
```

**Comment by iSeiryu** [comment]
Same on Windows and Ubuntu.
This works but not desired (too much code):
```typescript
export class Product {
  id: string;
  name: string;

  constructor(
    id: string,
    name: string,
  ) {
    this.id = id;
    this.name = name;
  }
}
```

Desired
```typescript
export class Product {
  constructor(
    public id: string,
    public name: string,
  ) { }
}
```

Replacing `public` with `readonly` does not work either.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/2687
