### ISSUE TITLE
an Include Endpoint instead of Exclude Endpoint approach for building API clients. 

### ISSUE THREAD

**Issue by RoadToML** [nestjs/swagger#2059]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently if you have a large codebase with several 100s of API endpoints and routes spanning multiple controllers, we need to apply a `@ApiExcludeController` and `@ApiExcludeEndpoint` to each that you don't need.

### Describe the solution you'd like

I think a better approach would be is to have a exclude all endpoints by default instead. This will allow users to `@ApiIncludeController` and `@ApiIncludeEndpoint` to the routes the users require.

### What is the motivation / use case for changing the behavior?

We have a very large code base and it is increasing everyday. We only want to create a client for specific endpoints and the Include All approach cases there to be a lot of boiler plate code which isn't needed. Most software architectures and practices also follow a Exclude by default approach so this was odd to see the opposite with swagger.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
