### ISSUE TITLE
OpenAPI CLI plugin does not add the response decorator to the endpoints with proper statut and type

### ISSUE THREAD

**Issue by Xoto1162** [nestjs/swagger#2061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I started a new project with NestJS 9 and I have a problem with the generation of the swagger. I am using the CLI plugin to generate automatically the spec but it seems that the plugin doesn´t add the response decorator with the type

I created a simple example to show the problem :

```typescript
// My controller
import { Body, Controller, Post } from '@nestjs/common';
import { AppService } from './app.service';
import TestDto from './dto/test.dto';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Post('test')
  getHello(@Body() dto: TestDto): TestDto {
    return dto;
  }
}

// My entity returned by the route of my controller

import { IsAlphanumeric, Length } from 'class-validator';

export default class TestDto {
  @IsAlphanumeric()
  @Length(4, 30)
  username: string;
}
```

But when I check the swagger I don´t have the specification for the response

![image](https://user-images.githubusercontent.com/13108023/187587936-8edd1148-61dd-41c0-80a7-2b0d3698a43b.png)

I also trieed to update and old project with Nest 8 where it worked, and after the update to nest 9 I have the same issue.

### Minimum reproduction code

https://gitlab.com/t9348/backend

### Expected behavior

Should have the detailled response type in Swagger

### Package version

6.1.0

### NestJS version

9.0.11

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
