### ISSUE TITLE
Some feature of swagger plugin are not working anymore

### ISSUE THREAD

**Issue by Xoto1162** [nestjs/swagger#2065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Some functionnality of the swagger plugin are not working. I already opened an issue but it was closed and you said to post on Discord. After my post on Discord it seems that we are several people to encouter this issue.

My project is a brand new project generated with Nest CLI 9.1.1. I also tried to update an older project created 4 months ago with Nest 8 to see if the problem will appear. After updating the dependencies, the older project encoutered the same issue.

Behind the list of all the functionnalities listed in the doc with a check or a cross depending if the feature is working or not.

- :heavy_check_mark: annotate all DTO properties with @ApiProperty unless @ApiHideProperty is used
- :heavy_check_mark: set the required property depending on the question mark (e.g. name?: string will set required: false)
- :interrobang: set the type or enum property depending on the type (supports arrays as well)
- :heavy_check_mark: set the default property based on the assigned default value
- :x: set several validation rules based on class-validator decorators (if classValidatorShim set to true)
- :x: add a response decorator to every endpoint with a proper status and type (response model)
- :x: generate descriptions for properties and endpoints based on comments (if introspectComments set to true)
- :x: generate example values for properties based on comments (if introspectComments set to true)

### Minimum reproduction code

https://github.com/Xoto1162/demo-bug-swagger-plugin

### Steps to reproduce

1. `npm install`
2. `npm run start:dev`
3. open you navigator to `localhost:3000/api`

### Expected behavior

According to the documentation and my code, I should have all the feature of the plugin working (comment introspection, response decorator added, validation rules bassed on class-validator decorators)

![image](https://user-images.githubusercontent.com/13108023/187794901-5529f698-9230-43d9-8b99-51e76d339678.png)

`nest-cli.json`

```typescript
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/swagger",
        "options": {
          "classValidatorShim": true,
          "introspectComments": true
        }
      }
    ]
  }
}

```

`app.controler.ts`

```typescript
import {Body, Controller, Get, Post} from '@nestjs/common';
import { AppService } from './app.service';
import AppDto from "./dto/app.dto";

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  /**
   * Comment instrospection is not working
   */
  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  /**
   * An other comment instrospection test
   */
  @Post()
  postApp(@Body() appDto: AppDto): AppDto {
    return new AppDto();
  }
}

```

`app.dto.ts`

```typescript
import {MaxLength} from "class-validator";

export default class AppDto {
    @MaxLength(50)
    name?: string = "MyApp"
}
```

### Package version

6.1.0

### NestJS version

9.0.11

### Node.js version

16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Looks like this is an artifact of the fact that Typescript 4.8.0 changed the AST, and so the plugin isn't quite reading the same as it used to. If you install `typescript@~4.7` you get the same behavior as you used to.

Typescript **does not** follow semver, and often makes breaking changes on "minor" updates, so this isn't too surprising, but it is incredibly annoying

**Comment by Xoto1162** [comment]
> Looks like this is an artifact of the fact that Typescript 4.8.0 changed the AST, and so the plugin isn't quite reading the same as it used to. If you install `typescript@~4.7` you get the same behavior as you used to.
> 
> Typescript **does not** follow semver, and often makes breaking changes on "minor" updates, so this isn't too surprising, but it is incredibly annoying

Thank you very much it is working with downgrading typescript to 4.7.x

Will you do something to support Typescript 4.8 ?

**Comment by kamilmysliwiec** [comment]
Fixed in this PR https://github.com/nestjs/swagger/pull/2067
