### ISSUE TITLE
swagger is not generating curl url with correct utf8 characters

### ISSUE THREAD

**Issue by Rosnaldo** [nestjs/swagger#2072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I make a Get HTTP Request with an email param it generates like this: 
`http://localhost:3000/v1/andreytsuzuki%40gmail.com`
And it should be like this:
`http://localhost:3000/v1/andreytsuzuki@gmail.com`

It is replacing `@` by `%40`

### Minimum reproduction code

https://github.com/Rosnaldo/nestjs_git_issue

### Steps to reproduce

Install packages
`npm i`

Run locally
`npm run start:dev`

Open swagger documents in the browser
`localhost:3000/docs`

Make `v1/email` request with an valid email like `andreytsuzuki@gmail.com`

The result should be:

```
curl -X 'GET' \
  'http://localhost:3000/v1/andreytsuzuki%40gmail.com' \
  -H 'accept: */*'
```

### Expected behavior

And it should be like this:
```
curl -X 'GET' \
  'http://localhost:3000/v1/andreytsuzuki@gmail.com' \
  -H 'accept: */*'
```

### Package version

^9.0.0

### NestJS version

^9.0.0

### Node.js version

v18.7.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
