### ISSUE TITLE
[discussion]: Allow import DTOs from packages

### ISSUE THREAD

**Issue by KillWolfVlad** [nestjs/swagger#2076]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

My previous issues https://github.com/nestjs/swagger/pull/1553 and https://github.com/nestjs/swagger/issues/1620 was closed, but I think that this is a misunderstanding and together we can resolve this problem.

### Is your feature request related to a problem? Please describe it

Hi! We use NestJS to build microservices. And we like to share dtos between services. But dtos from node_modules doesn't exists in result swagger.

### Describe the solution you'd like

I created a two repos to reproduce this issue:
- https://github.com/KillWolfVlad/nest-swagger-v6-dtos-from-node_modules-issue-dtos (**dtos builded using `@nestjs/cli` and `@nestjs/swagger` plugin and have all metadata**)
- https://github.com/KillWolfVlad/nest-swagger-v6-dtos-from-node_modules-issue

I think we need just delete this lines:

https://github.com/nestjs/swagger/blob/69a4127e764492080fb5737132a01a237d0566f2/lib/plugin/visitors/controller-class.visitor.ts#L256-L258

### Teachability, documentation, adoption, migration strategy

We can create a section to describe how to create packages with dtos.

### What is the motivation / use case for changing the behavior?

Allow share dtos between services and BFF as example.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
