### ISSUE TITLE
PickType is not behaving the same when array is passed instead of list of keys

### ISSUE THREAD

**Issue by fr1sk** [nestjs/swagger#2084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have the following DTO

```ts
class TestDto {
  @ApiProperty({ type: String, required: true })
  @IsString()
  @IsDefined()
  id: string;

  @ApiProperty({ type: String, required: true })
  @IsString()
  @IsDefined()
  testId: string;

  @ApiProperty({ type: String, required: true })
  @IsNumber()
  value: number;
}
```

I want to create new DTO using `PickType` that will only have `id` and `testId`.

if I do it like this everything works as expected ✅

```ts
class SmallerTestExpectedDto extends PickType(TestDto, ["id", "testId"]) {}
const smallerTestExpected: SmallerTestExpectedDto = {
  id: "id",
  testId: "test",
};
```

but if I store fields that I want to pick in array, I am getting an error that the `value` is required, even if I didn't include it in the `PickType` ❌

```ts
class SmallerTestUnexpectedDto extends PickType(TestDto, SMALLER_TEST_DTO_REQUIRED_FIELDS) {}
const smallerTestUnexpected: SmallerTestUnexpectedDto = {
  id: "id",
  testId: "test",
};

```

exact error:
`Property 'value' is missing in type '{ id: string; testId: string; }' but required in type 'SmallerTestUnexpectedDto'.`

### Minimum reproduction code

https://gist.github.com/fr1sk/47314ccf1283eeacbb678409f7ced3d0

### Expected behavior

When I store values in array and destructure, to behave same as I passed array to `PickType`

### Package version

8.0.0

### NestJS version

8.0.0

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Add `as const` if you don't want to duplicate things. All that Typescript knows is that it could be _any_ keys of `TestDto`. If you use `as const` then it knows it's only _these_ keys which makes the compiler happy

**Comment by fr1sk** [comment]
> Add `as const` if you don't want to duplicate things. All that Typescript knows is that it could be _any_ keys of `TestDto`. If you use `as const` then it knows it's only _these_ keys which makes the compiler happy

thanks for the response! I didn't manage to make it work with `as const` 🤷🏻‍♂️ can you provide a working example?

**Comment by jmcdo29** [comment]
> > Add `as const` if you don't want to duplicate things. All that Typescript knows is that it could be _any_ keys of `TestDto`. If you use `as const` then it knows it's only _these_ keys which makes the compiler happy
> 
> thanks for the response! I didn't manage to make it work with `as const` 🤷🏻‍♂️ can you provide a working example?

You'd have to get rid of the`Array<keyof TestDto>` because that is for _all_ keys, when you only need _some_ of them. This is just how Typescript works. You can still use a saved array, or use utility types and exclude/pick the fields you don't/do need.
