### ISSUE TITLE
Using type enum from third party imported npm package causes "is not defined by 'exports'"

### ISSUE THREAD

**Issue by tobias-jueschke** [nestjs/swagger#2087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a simple nestjs dto class importing an enum type from a third party npm package.

```
import { OrderStatus } from '@company/common';

export class OrderListItemDto {
  @IsEnum(OrderStatus)
  @IsNotEmpty()
  public status: OrderStatus;
}
```

In the @company/common modul the enum is exported as follows:

```
export enum OrderStatus {
  NEW = "new",
}
```

running the app cause the following error:

```
Error: Package subpath './dist/enums/order-status.enum' is not defined by "exports" in /home/user/data/oms-order-service/node_modules/@company/common/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:729:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function._OPENAPI_METADATA_FACTORY (/home/user/data/oms-order-service/dist/orders/dtos/order-list-item.dto.js:20:202)
```

If I change the type of the property to `string`and keep the import the app start successfully. If I use the enum not in *.dto files the enum works fine.

### Steps to reproduce

https://stackblitz.com/edit/nestjs-typescript-starter-bbgorc?file=package.json,src%2Fmain.ts,nest-cli.json,src%2Fdtos%2Fcats.dto.ts,src%2Fapp.controller.ts,src%2Fapp.service.ts

### Expected behavior

APP runs with imported enum from third party npm package.

### Package version

6.0.5

### NestJS version

9.0.9

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by tobias-jueschke** [comment]
I found out that the nestjs/swagger [cli plugin](https://docs.nestjs.com/openapi/cli-plugin) causes the problem. If I remove the plugin it works as expected.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by tobias-jueschke** [comment]
Here is the link to reproduction https://stackblitz.com/edit/nestjs-typescript-starter-bbgorc?file=package.json,src%2Fmain.ts,nest-cli.json,src%2Fdtos%2Fcats.dto.ts,src%2Fapp.controller.ts,src%2Fapp.service.ts

**Comment by k1llabee** [comment]
Having the same issue
Looks like nest js swagger plugin creates code in a compiled bundle like "require("package/internal")"

**Comment by gradam** [comment]
Im experiencing the same issue when using monorepo and importing DTOs from shared packages

**Comment by bibitoo** [comment]
I also encountered similar problem, im my case the package path is absolute path. I move the project to a none unicode character path  and it work.

**Comment by icco** [comment]
> https://stackblitz.com/edit/nestjs-typescript-starter-bbgorc?file=package.json,src%2Fmain.ts,nest-cli.json,src%2Fdtos%2Fcats.dto.ts,src%2Fapp.controller.ts,src%2Fapp.service.ts

@kamilmysliwiec the description has a stackblitz and this is still an issue.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/3029

**Comment by Michsior14** [comment]
This should be reopened after recent reverts.

**Comment by mstr-brightside** [comment]
Issue persists, package versions:

```
"@nestjs/axios": "^4.0.0",
"@nestjs/common": "^11.1.3",
"@nestjs/config": "^4.0.2",
"@nestjs/core": "^11.1.3",
"@nestjs/jwt": "^11.0.0",
"@nestjs/passport": "^11.0.5",
"@nestjs/platform-express": "^11.1.3",
"@nestjs/platform-socket.io": "^11.1.3",
"@nestjs/swagger": "^11.2.0",
"@nestjs/typeorm": "^11.0.0",
"@nestjs/websockets": "^11.1.3",
```

the enum import issue itself can be solved with changing the tsconfig `module` prop, but seems like "commonjs" is the default necessary value for Nest.

**Comment by atachh** [comment]
For anyone still facing this issue in 2026, create a new file inside your Nest.js app and re-export the enum like this:
```
import { MyEnum as LibMyEnum } from '@my-libs/enums';

type Cloned<T> = {
  [K in keyof T]: T[K];
};

export const MyEnum = {
  ...LibMyEnum,
};

export type MyEnum = Cloned<LibMyEnum>;
```

This essentially re-creates the enum and clones the type erasing any direct references to the library. You can now use this enum in any DTO:

```
import { MyEnum } from '../../common/enums'

export class MyDTO {
  @IsEnum(MyEnum);
  prop: MyEnum;
}
```
