### ISSUE TITLE
Reduce the bundle size of @nestjs/swagger

### ISSUE THREAD

**Issue by phoenix741** [nestjs/swagger#2092]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hi,

I use webpack (with nest cli) to bundle the application and node_modules dependency in one js file for a lambda.

I use @nestjs/swagger to put decorators on DTO and have a specific js program that read all to generate a json swagger file.

In the main lambda, i don't need using the swagger-ui-dist ihm.

The swagger-ui-dist add 1Mb to the bundle size.

I would like to reduce the bundle size (and the time to the lambda starting)

### Describe the solution you'd like

I would like two evolutions :

  * Creating a json without the need of installing swagger-ui-dist
  * Quickwin : loading the swagger-ui-dist only when the SwaggerModule is loaded (lazy loading). This will permit that when only annotations are used  (@ApiHideProperty, @PickType ...) , we don't need to have swagger-ui-dist in our bundle.
  * Another Quickwin : loading js-yaml only when the SwaggerModule is loaded (to remove 100ko)
  * For lodash : don't import the full library but only part used (import pick from 'lodash/pick') (lodash take from 500ko to 700ko)

### What is the motivation / use case for changing the behavior?

https://docs.nestjs.com/faq/serverless explain how to use nestjs to create lambda, but i would like to have a smallest lambda to improve starting time of nestjs.

**Comment by kamilmysliwiec** [comment]
> Creating a json without the need of installing swagger-ui-dist

This is already feasible since 6.1.1 https://github.com/nestjs/swagger/commit/4aea702ef0d11571b29ddb56babb478ff036e15b

Feel free to create PRs for other tiny improvements, PRs are more than welcome!
