### ISSUE TITLE
Ability to map JS/ TS types to Swagger types

### ISSUE THREAD

**Issue by ahmedNY** [nestjs/swagger#2106]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

as you know on JS data type number can hold integers or floats values , swagger supports data type number & integer, 

using swagger-cli plugin to generate schema, it's will be awesome if we could set default swagger data type to integer for all number variables 

### Describe the solution you'd like

```
{
  "name": "@nestjs/swagger",
  "options": {
    "introspectComments": true,
    "defaultJsNumber": "integer"
  }
}
```

Add new "defaultJsNumber" option to nest-cli.js

### What is the motivation / use case for changing the behavior?

this will help generating much accurate clients from swagger files,

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? NOTE: This isn't really related to the NestJS CLI Plugin
