### ISSUE TITLE
Add inheritance support for external library annotations in PartialType()

### ISSUE THREAD

**Issue by tatianajiselle** [nestjs/swagger#2111]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

https://github.com/nestjs/swagger/blob/491b168cbff3003191e55ee96e77e69d8c1deb66/lib/type-helpers/partial-type.helper.ts#L25 Annotations are inherited for transformer and validator but not from external libraries such as Automapper. This renders the feature unusable as type definitions need to be overloaded into the DTO classes to re-annotate properties for automapping.

### Describe the solution you'd like

Annotations from external libraries such as Automapper should be inherited into PartialType().

### Teachability, documentation, adoption, migration strategy

Usage is the same, except that support is carried over for external libraries--> property annotations on an entity class is inherited IN FULL to a DTO class with the properties all set as optional. Rather than removing the annotations and inheriting selectively.

### What is the motivation / use case for changing the behavior?

Stripping/selectively carrying over annotations from a class's existing annotation can defeat the purpose of PartialType().

**Comment by micalevisk** [comment]
I don't think there's a generic way to do that.

We only have that working for `class-validator` and `class-transformer` because we know what are the things that we should be looking for. See: https://github.com/nestjs/mapped-types/blob/master/lib/type-helpers.utils.ts
