### ISSUE TITLE
Swagger Plugin not working

### ISSUE THREAD

**Issue by Tharun-coder** [nestjs/swagger#2120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On enabling swagger plugin in nest-cli.json, fields are not displayed in swagger scheme without providing   @ApiProperty()
, but as per documentation it is mentioned @ApiProperty() is not needed ([Reference](https://docs.nestjs.com/openapi/cli-plugin))
`{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/swagger",
      }
    ]
  }
}`

### Minimum reproduction code

NA

### Expected behavior

Without providing @ApiProperty() for each fields swagger should automatically show the schema as per documentation.

### Package version

6.1.2

### NestJS version

9.0.0

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by Tharun-coder** [comment]
https://github.com/Tharun-coder/nest-prisma-blog - Please check out in create-post-dto.ts file, it is not showing body field in schema. Thanks!!!

**Comment by jmcdo29** [comment]
Cloned, installed, ran the `build` command and checked the output in the `dist/posts/dto/create-post.dto.js` file

```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreatePostDto = void 0;
const openapi = require("@nestjs/swagger");
const swagger_1 = require("@nestjs/swagger");
const class_validator_1 = require("class-validator");
class CreatePostDto {
    static _OPENAPI_METADATA_FACTORY() {
        return { title: { required: true, type: () => String, minLength: 3 }, body: { required: true, type: () => String, minLength: 3 }, authorId: { required: true, type: () => String } };
    }
}
__decorate([
    (0, class_validator_1.IsNotEmpty)(),
    (0, class_validator_1.IsString)(),
    (0, class_validator_1.MinLength)(3),
    (0, swagger_1.ApiProperty)(),
    __metadata("design:type", String)
], CreatePostDto.prototype, "title", void 0);
__decorate([
    (0, class_validator_1.IsNotEmpty)(),
    (0, class_validator_1.IsString)(),
    (0, class_validator_1.MinLength)(3),
    __metadata("design:type", String)
], CreatePostDto.prototype, "body", void 0);
exports.CreatePostDto = CreatePostDto;
//# sourceMappingURL=create-post.dto.js.map
```

There's a proper `_OPENAPI_METADATA_FACTORY` that has the expected properties and their metadata. 

That swagger UI also has all the properties there
![image](https://user-images.githubusercontent.com/28268680/196004993-0b5ea6ac-770d-4f32-b537-9373141eb6b1.png)

So with your reproduction, I can't reproduce the problem you're facing
