### ISSUE TITLE
Swagger runs locally, but not when deployed to Cloud

### ISSUE THREAD

**Issue by jakobwgnr** [nestjs/swagger#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In a cloud environment (azure), when i try to reach the swagger endpoint, white screen and an error appears in the browser log
![image](https://user-images.githubusercontent.com/18501893/195977900-f2496513-cf15-4bdf-ad39-d6dfbb6d670d.png)

When trying the same locally everything works fine...
This setup is ~2 years old and everything worked fine until like beginning of sept. 2022 so I guess this is some package issue.
I cannot provide a minimum reproduction code as this is not reproducable in local environment...

I have a BaseDto that every Dto is extending from
![image](https://user-images.githubusercontent.com/18501893/195977946-018e8fec-de51-4126-80e9-43e723dd1b7a.png)

I also have tried to add BaseDto as an extraModel which didn't help
![image](https://user-images.githubusercontent.com/18501893/195978045-feb70420-3491-412e-b7e9-a6f3bc8927f0.png)

Hopefully someone can help here (also tried discord before).

Thank you in Advance! BR, Jakob

### Minimum reproduction code

n/a

### Expected behavior

Swagger should work.

### Package version

6.1.2

### NestJS version

9.1.4

### Node.js version

local: 16.3.2; Azure: 16 LTS 

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Not sure but this might be related to your changes 🤔 @flamewow

**Comment by flamewow** [comment]
@jakobwgnr can you check the network tab and see if any of the requests are blocked/failed?

If it works locally, my best guess is smth related to cloud proxying/routing. In the latest version, some of the requests to access assets were changed, which might conflict with your cloud config.
If you can bring more context on that side, that would be great.

**Comment by jakobwgnr** [comment]
Hey guys! Thanks for your initial check
Cloud:
![image](https://user-images.githubusercontent.com/18501893/197742936-cbea0f44-acf0-4e28-90bb-b6fa6ab53d86.png)

local:
![image](https://user-images.githubusercontent.com/18501893/197743637-b4af3ef6-dea8-435f-918d-0efef17a3088.png)

Differences I've seen in the network tab is "documentation/" vs. "documentation" and that in "react dom" isn't loaded in the cloud env.

Does that help?

**Comment by flamewow** [comment]
@jakobwgnr response sizes are different 🤔 , are you running identical versions locally and in the cloud?

**Comment by jakobwgnr** [comment]
@flamewow 
Hmm - App-versions are the same..

![image](https://user-images.githubusercontent.com/18501893/197748642-e34a257a-bbe6-43eb-924c-5db2399db781.png)

![image](https://user-images.githubusercontent.com/18501893/197748739-6f7841cc-ad16-4d5d-a551-47d1e5ad7ddf.png)

There is a difference how the sources are shown.
![image](https://user-images.githubusercontent.com/18501893/197749510-3a23c573-e075-4d70-83f4-641966253f33.png)

![image](https://user-images.githubusercontent.com/18501893/197749758-b8e86b14-51c9-4166-ba44-75e112fd1551.png)

I will now compare the sources side-by-side, but takes some time

**Comment by jakobwgnr** [comment]
@flamewow @kamilmysliwiec apologies - The title here is somehow misleading...
I can reproduce the problem also locally when I don't run the dev server, but when I run the built version...

**Comment by flamewow** [comment]
> @flamewow @kamilmysliwiec apologies - The title here is somehow misleading...
> I can reproduce the problem also locally when I don't run the dev server, but when I run the built version...

If you could come up with reproduction repo, would be awesome

**Comment by jakobwgnr** [comment]
@flamewow thanks - a minimal repro-repo with my setup is working. Hence, I don't think this is a package issue. 
Guess I need to go through my codebase once again and maybe I've already found sth.... I'll close this issue. Thank you for your help.

**Comment by SanteeMarcel** [comment]
@jakobwgnr what was ultimately the source of the problem? I am running into the exact same problem, but with Google Cloud Run.

**Comment by jakobwgnr** [comment]
Hey @SanteeMarcel ! Sorry - Haven't been active through the holidays. 

The problem ultimately wasn't the deployment itself. I could reproduce the issue locally when building the application with `npm run build` and run it. 
The issue was that I was using a wrong class in one of my swagger decorators.... Hard to find, but I searched the changes I did between the last version where it was still working till now to find it.

**Comment by regohiro** [comment]
Having the same issue here. 
I was able to load Swagger locally by setting the port manually:
```ts
// main.azure.ts
export async function createApp(): Promise<INestApplication> {
  const app = await NestFactory.create(AppModule);
  app.setGlobalPrefix('api');

  const config = new DocumentBuilder()
    .setTitle('title')
    .setDescription('description')
    .setVersion('version')
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('docs', app, document, {
    useGlobalPrefix: true,
  });

  await app.init();
  app.listen(7071); // default azure func port

  return app;
}
```

```sh
yarn build && func host start --port 7071
```

However, not on the cloud because there is no way to know or specify the port.

**Comment by bariskes11** [comment]
I think I run into same issue struggling to solve days passed by here is my issue post 
[issue details](https://github.com/nestjs/swagger/issues/2604)
any help would be really really nice!

**Comment by SanteeMarcel** [comment]
@bariskes11 it was ultimately an permission issue to me, unrelated to nestjs.

**Comment by bariskes11** [comment]
any permission checks you'd recommend ? on azure cloud

**Comment by SanteeMarcel** [comment]
> any permission checks you'd recommend ? on azure cloud

Check if you are accessing it with the right service account

**Comment by bariskes11** [comment]
I'm not sure if I  have any permission problem, but if it makes sense to you I'm deploying this as a Function App but I also tried to deploy it as Web App since it's an API it does not work when I try to deploy it into a Web App
since Function apps don't serve files I also tried to load swagger UI files but didn't work or maybe I couldn't do it. so I'm still stuck with that :(

**Comment by rousnay** [comment]
You should add custom CSS & JS files like this:

`SwaggerModule.setup('/swagger', app, swaggerDocument, {
    customCssUrl:
      'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui.min.css',
    customJs: [
      'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.js',
      'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.js',
    ],
});`
