### ISSUE TITLE
DTO extension does not result in schema composition

### ISSUE THREAD

**Issue by GithubUser8080** [nestjs/swagger#2128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Extending dto classes, and even using mapped types does not result in the expected OpenApi AllOf composition

Each openapi schema seems to have a copy of its own properties and the base class properties

### Workaround issues

I tried the nestjs mapped types package and encountered the following issues

- PartialType makes base fields optional, while all base class fields are required
- IntersectionType creates a copy of all properties instead of using allOf to refer to the base class

### Minimum reproduction code

https://gist.github.com/GithubUser8080/18d54530cdeb35222401c6e9e1f1012f

### Steps to reproduce

1. Use DTOs that extend a base DTO (gist provided)
2. Create a nestjs project with a controller returning the extending class (MyEmployeeDto)
3. Use the @nestjs/swagger package with the typescript plugin, and generate a swagger document

### Expected behavior

The resulting openapi schemas should contain the allof keyword to combine each class with the base class

### Package version

6.1.2

### NestJS version

9.0.0

### Node.js version

14.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by GithubUser8080** [comment]
https://codesandbox.io/s/funny-borg-m1mzon

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for further questions. We are using GitHub to track bugs, feature requests, and potential improvements.
