### ISSUE TITLE
TypeScript strictNullChecks does not process DTO's with nullable fields correctly

### ISSUE THREAD

**Issue by bvanleeuwen1995** [nestjs/swagger#2129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When enabling strictNullCheck in typescript and setting a DTO with for example a string | null field type definition the Swagger module does not load the fields in query parameters are optional and in a response body the type is not set to string but to object.

When the variable is marked as optional using ? in the DTO then the field is added as an optional field to the query parameters and to the response DTO.

### Minimum reproduction code

https://github.com/bvanleeuwen1995/nestjs-swagger-nullable-optional-example

### Steps to reproduce

Install project dependencies of provided repository and run start:dev. 

There are two requests defined in the project, with which uses the DTO with the nullable fields and one that has them defined as optional fields. Both should behave the same (and do behave the same when disabling stictNullChecks please remove dist folder after changing).

### Expected behavior

Nullable fields should be handled the same as optional fields when having stictNullChecks enabled.

### Package version

6.1.2

### NestJS version

9.1.4

### Node.js version

16.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I did come across a issue mentioning the same problem (from what I can tell) and is marked as resolved and somebody mentioning that is was not resolved. https://github.com/nestjs/swagger/issues/462

**Comment by micalevisk** [comment]
an workaround: define the type explicitly like this:  
`@ApiPropertyOptional({ type: String, nullable: true })`

**Comment by voinik** [comment]
How come more people haven't faced this problem yet? I recently set `strict: true` in my tsconfig and am now running into this. A sizable project like mine now needs to specify the explicit type for all nullable fields like this in order to wor around this bug? This increases the odds of human error even more. Is there no other workaround to this?

**Comment by kamilmysliwiec** [comment]
![image](https://github.com/user-attachments/assets/df88c51d-2ec4-4de1-87c8-f35bca903bd8)

produces:

![image](https://github.com/user-attachments/assets/8f44bfbb-44d9-4e34-ae52-f22160b301ea)

it sounds like this issue should be fixed now
