### ISSUE TITLE
Incorrect Open-API definition when using @All(...) route decorator

### ISSUE THREAD

**Issue by timoklingenhoefer** [nestjs/swagger#2143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the @All(...) route decorator in a controller and then generating the `swagger.json` from that, it will result in a definition like this:

```typescript
@Controller('proxy')
export class ProxyController {

  @All('*')
  public async proxy(...) {...}
}
```

```json
"/proxy/*": {
      "all": {...}
}
```

When opening this in the [Swagger Editor](https://editor.swagger.io/) it shows an error like:

> Structural error at paths./proxy/*
should NOT have additional properties
additionalProperty: all

According to the [Open-API specification](https://spec.openapis.org/oas/latest.html#path-item-object) `all` is indeed not allowed there, only `get`, `post`, ...

### Minimum reproduction code

https://github.com/timoklingenhoefer/swagger_bug

### Steps to reproduce

1. create new app
2. create controller like the one above
3. create swagger.json by adding this to the `bootstrap` function
```typescript
    const app = await NestFactory.create(ApplicationModul);
    const document = SwaggerModule.createDocument(app, new DocumentBuilder().build()););

    fs.writeFileSync('swagger.json', JSON.stringify(document, null, 2));
```
4. open `swagger.json` in the swagger editor
5. see error

### Expected behavior

Not sure how a correct definition would look like. 

Maybe copy-pasting the content of what would be the `all` block to `get`, `post`, ... blocks.

### Package version

6.1.3  (latest)

### NestJS version

9.1.6   (latest)

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2145
