### ISSUE TITLE
@ApiParams does not pass value to correct for validation

### ISSUE THREAD

**Issue by thurairaj** [nestjs/swagger#2151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm having trouble with `@ApiParam` with class-validator. The value passed in parameter is not correct value to validated. 

For example 
```
@Controller('sample')
export class AppController {
  @ApiParam({ name: 'slug', type: String })
  @Post(':slug/')
  postHello(@Param('slug') slug: SlugDto): string { return 1;  }
}
```

```
export class SlugDto {
    @IsString()
    @IsNotEmpty()
    slug: string;
}
```
In this case, swagger do create a field for slug and the value that I put for `slug` should be validated properly. But, when I put any value in the `slug` field in swagger,  I'm getting validation error. When I try `@ApiParam({ name: 'slug', type: SlugDto })` , there is no input field for `slug`. 

Either `@ApiParam` is generating input field which is not binding to correct request object or validation is not happening correctly.

### Minimum reproduction code

https://github.com/thurairaj/bug-report/blob/main/src/app.controller.ts

### Steps to reproduce

1. `npm i`
2. `npm start:dev`
3. Go to `http://127.0.0.1:3111/docs/bug#/sample/AppController_postHello`
4. Put any value in `slug` parameter
5. See the error.

### Expected behavior

Shouldn't have any error if the slug has value. 

### Package version

6.1.3

### NestJS version

8.0.0

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

None

**Comment by jmcdo29** [comment]
Your `@Param('slug')` should be `@Param()` so that the DTO can be properly validated and documented in swagger  with your `@ApiParam()`. 

For further support please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
