### ISSUE TITLE
Support @name for comment introspection

### ISSUE THREAD

**Issue by Sylphide** [nestjs/swagger#2152]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When using @nestjs/swagger in combination with class-transformer, if we @Expose a property and change it's name, we have to add an @ApiProperty with the appropriate name.

### Describe the solution you'd like

Add support to @name in comment introspection for @ApiProperty

### What is the motivation / use case for changing the behavior?

It would be nice to support @name in the comment introspection to avoid the need to use @ApiProperty when transforming the property name.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Sylphide** [comment]
I can, however, it might take a bit to familiarize myself with the code.
Could you point me to the code parsing the comment blocks?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/2155
