### ISSUE TITLE
"introspectComments" always generate empty description breaks custom decorator shorthand

### ISSUE THREAD

**Issue by bangbang93** [nestjs/swagger#2153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

set `introspectComments: true`
in the generated js file
```javascript
tslib_1.__decorate([
    openapi.ApiOperation({ description: "" }),
    (0, common_1.Get)('lot'),
    (0, nestjs_util_1.ApiSummary)('根据产品和批号获取自动分析报告'),
    (0, swagger_1.ApiOkResponse)({ type: analysis_dto_1.AnalysisResDto }),
    openapi.ApiResponse({ status: 200, type: Object }),
    tslib_1.__param(0, (0, common_1.Query)()),
    tslib_1.__param(1, (0, nestjs_util_1.OrgId)()),
    tslib_1.__metadata("design:type", Function),
    tslib_1.__metadata("design:paramtypes", [analysis_dto_1.AnalysisGetByLotQueryDto, String]),
    tslib_1.__metadata("design:returntype", Promise)
], AnalysisController.prototype, "getByLot", null);
```
`ApiSummary` is my short-hand decorator for 
```typescript
export const ApiSummary = (summary: string): MethodDecorator => ApiOperation({summary})
```
Used to if there is no comment for route method, no `openapi.ApiOperation({ description: "" })` will be generated.

### Minimum reproduction code

https://gist.github.com/bangbang93/4a1203683bffa3a4c241c611e689b5b1

### Expected behavior

Not genereating `openapi.ApiOperation({ description: "" })`, so as not to overwrite the summary properties.

### Package version

^6.1.3

### NestJS version

^9.1.6

### Node.js version

v18.12.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
