### ISSUE TITLE
example property is missing in header

### ISSUE THREAD

**Issue by andkom** [nestjs/swagger#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I specify `example` property for `@ApiHeader` decorator, it does not generate example field for header parameter in the output json.

### Minimum reproduction code

```javascript
@ApiHeader({
  name: 'X-My-Header',
  description: 'My custom header',
  required: true,
  example: 'test',
})
```

### Steps to reproduce

1. add @ApiHeader decorator with example field
2. there is no example for header in the output schema

### Expected behavior

example field should exist in the output json

### Package version

6.1.3

### NestJS version

9.1.6

### Node.js version

16.13

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
