### ISSUE TITLE
Swagger issue with lambda usage

### ISSUE THREAD

**Issue by ghost** [nestjs/swagger#2157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I trigger my lambda via API GATEWAY, I receive 404 for swagger.css, ... Nothing was changed in my code, only updated the package version! After the downgrade to version 8.1.2 everything works as expected!
![Screenshot from 2022-11-04 13-27-58](https://user-images.githubusercontent.com/61708720/199962512-246355cf-6f45-4f17-852e-45d87a951cae.png)

### Minimum reproduction code

-

### Steps to reproduce

Install the latest @nestjs/swagger version 8.1.3, try to open via Lambda

### Expected behavior

Return Swagger page
![Screenshot from 2022-11-04 13-31-34](https://user-images.githubusercontent.com/61708720/199962717-6ca677ba-4393-432e-9587-9e4d959d20ad.png)

### Package version

8.1.3

### NestJS version

9.1.6

### Node.js version

14.17.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by micalevisk** [comment]
the latest version of `@nestjs/swagger` is 6.1.3, so we don't know which package exactly you're changing.

I've been using `@nestjs/core` v8.4.7 and `@nestjs/swagger` 5.2.1 just fine with AWS Lambda.

**Comment by ianzone** [comment]
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

Hi, I have a similar issue and here is the repo https://github.com/ianzone/serverless-nestjs-template/tree/lambda-authorizor-swagger-issue

1. pnpm i
2. pnpm run start
3. go to http://localhost:3000/dev/docs

**Comment by micalevisk** [comment]
I believe that this is a setup issue...

My lambda handler looks like this:

![image](https://user-images.githubusercontent.com/13461315/213522022-e4b7c410-6584-417a-9442-3e3ba109ae5e.png)

**Comment by ianzone** [comment]
> 

so I tried this, but it still doesn't work
```
export const handler: Handler = async (
  event: APIGatewayEvent,
  context: Context,
  callback: Callback,
) => {
  if (event.path === '/docs') {
    event.path = '/docs/'
  }
  if (event.path.includes('swagger-ui')) {
    event.path = `/docs${event.path}`
  }
  cachedServer = cachedServer ?? (await bootstrap());
  return cachedServer(event, context, callback);
};
```
and I'm not sure why to change the path on the fly. it would change the path to like `/docs/docs/swagger-ui-bundle.js` and it doesn't seem to make sense.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
