### ISSUE TITLE
Support setting global Header

### ISSUE THREAD

**Issue by CodyTseng** [nestjs/swagger#2158]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am writing a multi-tenant application. This program distinguishes different tenants by the `x-tenant-id` in the request `Header`. So I need to set Header to all API.

BTW, I solved it now with `DocumentBuilder()addSecurity()`. But it is not very convenient to use. Because all API's Header have the same value in swagger-ui.

### Describe the solution you'd like

I think we can add a function to `DocumentBuilder` to set global Header.

### What is the motivation / use case for changing the behavior?

It would be nice to support setting global Header.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by CodyTseng** [comment]
Sure, but I need some time to get familiar with the code.

And I just learned that using `addSecurity()` can't add security to all API XD. Now I solve this problem by defining a `@MyController` decorator like this 😂:

```typescript
export const MyController = (prefix: string) =>
  applyDecorators(Controller(prefix), ApiHeader(...));
```

I'll add `DocumentBuilder().globalParameter()` function to set `DECORATORS.GLOBAL_API_PARAMETERS` metadata. And modify the `explorers/api-parameters.explorer.ts #exploreApiParametersMetadata`. What do you think? 🤔

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2176
