### ISSUE TITLE
Accept multiple Javascript and CSS imports

### ISSUE THREAD

**Issue by Luku1806** [nestjs/swagger#2161]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

For integrating a Swagger plugin I need to be able to include external Javascript.
This works for exactly one because the SwaggerCustomOptions accept exactly one URL for external Javascript via the customJs property.
If I want to use a second Swagger plugin or want to include other Javascript code there is no direct way without "hacking".

### Describe the solution you'd like

The properties of the SwaggerCustomOptions can be expanded to also accept arrays of URLs and even inline code.
This means I want to make customJs, customJsStr and customCssUrl also accept an array of strings.

The following shows the usage of the customJs property (which i would like to be also accept an array) to load the Javascript that has to be referenced in the plugins array:
```ts  
const customOptions: SwaggerCustomOptions = {
  customJs: 'https://unpkg.com/swagger-ui-plugin-hierarchical-tags',
  swaggerOptions: {
    plugins: [
      () => (window as any).HierarchicalTagsPlugin,
    ],
    persistAuthorization: true,
    oauth: {
      clientId: clientId,
      usePkceWithAuthorizationCodeGrant: true,
    },
  },
};
```
This is the changed, non breaking version:
```ts  
const customOptions: SwaggerCustomOptions = {
  customJs: [
    'https://unpkg.com/swagger-ui-plugin-hierarchical-tags',
     'https://example.com/other-needed-code'    
  ],
  swaggerOptions: {
    plugins: [
      () => (window as any).HierarchicalTagsPlugin,
    ],
    persistAuthorization: true,
    oauth: {
      clientId: clientId,
      usePkceWithAuthorizationCodeGrant: true,
    },
  },
};
```

### What is the motivation / use case for changing the behavior?

This change removes the constraint to only being able to import one external script, one external css and one inline script.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2162
