### ISSUE TITLE
Array of enums not working as expected

### ISSUE THREAD

**Issue by mrsolarius** [nestjs/swagger#2179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Adding an array of enums with the ApiQuery does not seem to work correctly. For example, given the following enum:
```ts
export enum UserRole {
  GHOST = "ghost",
  CANDIDATE = "candidate",
  LITOPIEN = "litopien",
  BAN="ban",
  REFUSED = "refuse",
  LITOGOD = "litogod",
}
```
I want to use this with a model property as follows:
````ts
  @Get('by-roles')
  @ApiQuery({
    name:'userRoles',
    enum:UserRole,
    isArray:true
  })
  async getUserByRoles(@Query('userRoles')userRoles:UserRole[]=[UserRole.GHOST])
  ````

This does not render as a multi select in swagger UI like you can see here : 
![image](https://user-images.githubusercontent.com/45536184/203625505-8aa8ac90-fdc9-418d-bf31-b98f7c3ac595.png)

Also in the json file it looks like that :
```json
"/api/users/by-roles":{
         "get":{
            "operationId":"UsersController_getUserByRoles",
            "parameters":[
               {
                  "name":"userRoles",
                  "required":true,
                  "in":"query",
                  "schema":{
                     "type":"array",
                     "items":{
                        "type":"string"
                     }
                  }
               }
            ],
```

### Minimum reproduction code

If you really need one, please let me know, I will provide one ^^

### Expected behaviour

I expect the json to looks like that : 
```json
"/api/users/by-roles":{
      "get":{
        "operationId":"UsersController_getUserByRoles",
        "parameters":[
          {
            "name":"userRoles",
            "required":true,
            "in":"query",
            "schema":{
              "type":"array",
              "items":{
                "type":"string",
                "enum":[
                  "ghost",
                  "candidate",
                  "litopien",
                  "ban",
                  "refuse",
                  "litogod"
                ]
              }
            }
          }
        ]
```

And the swagger ui to look like this :
![image](https://user-images.githubusercontent.com/45536184/203627069-3524e130-ed49-4342-8dcd-7cf92a3a25ea.png)

### Package version

@nestjs/swagger : 6.1.3

### NestJS version

9.0.0

### Node.js version

v16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

If I do this : 
```ts
@Get('by-roles')
  @ApiQuery({
    name:'userRoles',
    enum:UserRole,
    isArray:true
  })
  async getUserByRoles(@Query()userRoles:UserRole[]=[UserRole.GHOST])
  ```
  I got the correct JSON, but userRoles is not an array of UserRole But a weird object that looks like that : 
  ```
  { userRoles: [ 'ghost', 'candidate', 'litopien', 'litogod' ] }
  ````
  Also if I juste send one parameter it juste return without array like that :
  
```
  { userRoles: 'ghost' }
  ````
My example is extremely close to this doc example : https://docs.nestjs.com/openapi/types-and-parameters#enums

**Comment by orlandohohmeier** [comment]
Ran into the same and would argue this isn't just an issue with enums but how nestjs handles arrays of query parameters. It doesn't always pass an array of "users roles" to the respective handler but either the enum or an array of the enum. The same applies to other arrays of query parameters.

`/api/users/by-roles?userRoles=ghost -> userRoles:UserRole`
`/api/users/by-roles?userRoles=ghost&userRoles=candidate -> userRoles:UserRole[]`
 
Following the above one could reason that this should work and indeed it does fix the problem:

```ts
@Get('by-roles')
@ApiQuery({
  name:'userRoles',
  enum:UserRole,
  isArray:true
})
async getUserByRoles(@Query('userRoles')userRoles: UserRole | UserRole[] = [UserRole.GHOST]){
// ...
}
```

Adding a line to ensure that `usersRoles` is indeed always an array of values and we're good to go.

```ts
const _userRoles: UserRole[] = Array.prototype.concat(userRoles)
```

But following the same logic for plain array query params and things break while the value is either an array or a singular value.

```ts
@Get('foo')
public async getFoo(@Query('bar') bar: string | string[]) {
  const _bar: string[] = Array.prototype.concat(bar)
  // ...
}
```

So this needs to be written as follows, which is kinda confusing and inconsistent. 

```ts
@Get('foo')
public async getFoo(@Query('bar') bar: string[]) {
  const _bar: string[] = Array.prototype.concat(bar)
  // ...
}
```

I'd expect that in all cases arrays of query parameters are passed as arrays no matter the number of items. At least the types should always match what is passed without breaking anything. Hope this helps.

N.B. I haven't double-checked any of the code examples in this comment as the respective issue looked a little different in my case.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/commit/31eb40f420b7d910e06936b9e2b381262b4a210e
