### ISSUE TITLE
Unused import of "@nestjs/swagger" in source

### ISSUE THREAD

**Issue by Inoir** [nestjs/swagger#2183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you use the plugin in an library to share DTO`s between server and client, youre forced to use "introspectComments": true, so server decorators not applied on the client code.
If you just build a class library with nest cli with swagger configured to use introspectComments and dont use any decorators out of the package, there is still an import/require on the build files. so code in the client tries to import lot of nest stuff and fails.
Since this import is not even used this seems unnecessary and makes everything used with swagger module unusable on client side

Import looks like this if you build ESNext:

```
import * as openapi from "@nestjs/swagger";
```

### Minimum reproduction code

https://gist.github.com/Inoir/c1a960c1698c284d1f8f792234bc81c1

### Steps to reproduce

Build the file provided without any module just as lib

### Expected behavior

Generated code doesnt have this unused import and is useable in client code

### Package version

6.1.3

### NestJS version

9.2.0

### Node.js version

v14.18.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Current workaround: Run eslint with unused plugin and let eslint remove the unneeded import. feels weird.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. If you want more details on why we need to eagerly add this import, please, search through old issues - this has been discussed a few times in the past.
