### ISSUE TITLE
OAuth2, inForm type, custom endpoint definition

### ISSUE THREAD

**Issue by szkumorowski** [nestjs/swagger#22]
Hello, 

I'm trying to include some additional paramters mostly in relation to OAuth 2 specification.
https://swagger.io/docs/specification/authentication/oauth2/

With actual state there is no possiblity to include custom parameters type:
` @ApiImplicitParam({name: 'grant_type', type: 'formData'})`
As it defaults to 'path', could you allow to include any other without fallback to default one ?

Even so, sometimes would be great to just no use any of provided decorators, but simply kind of one
`ApiCustom(CustomDefinitions.SwaggerEndpointDefinition)` where nest swagger will not generate any definition for endpoint but simply use pure provided definition.

**Comment by ericzon** [comment]
I'm in the same situation, with the current configuration is not possible to work with oauth2 type. @szkumorowski did you have any improvement on this?


Thank you

**Comment by szkumorowski** [comment]
Yes, I found a way to modify document generated by nest before it server started, tommorow I will provide example
