### ISSUE TITLE
DTOs with generic type lead to: A circular dependency has been detected

### ISSUE THREAD

**Issue by schealex** [nestjs/swagger#2208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We have just migrated from an older nestjs version to the current one and for some reason swagger is compaining about some of our DTOs now. Here is an example DTO:

```ts
export class PaginationResponseDto<T> implements IResponseMessages {
  currentPage: number;
  skippedRecords: number;
  totalPages: number;
  hasNext: boolean;
  content: T[];
  payloadSize: number;
  totalRecords: number;
  messages: IResponseMessage[] = [];
}
```

The error when starting nestjs is this:

````
A circular dependency has been detected (property key: \"content\"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers (\"type: () => ClassType\").","stack":"Error: A circular dependency has been detected (property key: \"content\"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers (\"type: () => ClassType\").
````

We have tried different approches to refactor the `content` `ApiProperty` definition but to no avail.

### Minimum reproduction code

https://github.com/schealex/nestjs-swagger-issue-min-reproduction

### Steps to reproduce

pnpm i
npm run start:dev

look at the reproduction repo readme for more info

### Expected behavior

Have the nestjs app atlease start and ideally show the dto's in the swagger ui

### Package version

6.1.3

### NestJS version

9.2.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
