### ISSUE TITLE
If I include the name of an HTML element in my function description, it get's rendered instead of the text getting escaped

### ISSUE THREAD

**Issue by codr1** [nestjs/swagger#2228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If my method has a description that includes the name of an HTML element such as `<select>`, I get a select element rendered in the swagger

### Minimum reproduction code

-

### Steps to reproduce

Create a method.  
Add a description that includes an HTML element like `<select>`

### Expected behavior

I expect to see the text `<select>` in my method description and not an actual select control being rendered.

### Package version

4.8.2

### NestJS version

7.6.18

### Node.js version

16.3.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue here https://github.com/swagger-api/swagger-ui
