### ISSUE TITLE
Add "x-tokenName" property to type "SecuritySchemeObject"

### ISSUE THREAD

**Issue by goonerholic** [nestjs/swagger#2230]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Swagger ui supports "x-tokenName" property for oauth2 security and it is used in order to choose another field in json from OAuth response other than "access_token"(e.g. "id_token") https://github.com/swagger-api/swagger-ui/pull/2587

Currently, `x-tokenName` field is missing in `SecuritySchemeObject` interface

### Describe the solution you'd like

As `addSecurity` method in DocumentBuilder class just simply spread all properties to `document.components.securitySchemes`, just adding property `x-tokenName` to `SecuritySchemeObject` will do.

I tried it locally and confirmed that it works fine.

### What is the motivation / use case for changing the behavior?

I'm currently using aws congito authorizer and I have to send `id_token` instead of `access_token`.
If this feature added, config like below would work.

```typescript
const config = new DocumentBuilder().
  ...
  .addSecurity("Cognito", {
    type: "oauth2",
    "x-tokenName": "id_token",
    flows: {
      implicit: {
        ...
      }
    }
  )

```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2665
