### ISSUE TITLE
How to hide particular Schemas/models that are shown in end of swagger documentation page

### ISSUE THREAD

**Issue by gitSambhal** [nestjs/swagger#2234]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to hide **some** schemas from the Swagger documentation page. I have already checked the issue https://github.com/nestjs/swagger/issues/722 but it is for hiding all the schemas.

### Describe the solution you'd like

I would be better if there can be any decorator for DTO class to hide/exclude it from the schemas list.

### What is the motivation / use case for changing the behavior?

I want to show only few schemas in the doc page.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
