### ISSUE TITLE
API Versioning of type header is not supported

### ISSUE THREAD

**Issue by DCampagnola** [nestjs/swagger#2235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Enabling versioning with type "header", @nestjs/swagger doesn't generate the right documentation.
```ts
app.enableVersioning({
    type: VersioningType.HEADER,
    header: 'Accept-version',
  })
```
In the example I have two api in the same path with different versions
```ts
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  @Version('v1')
  getHello(@Query('old_example') example: string): string {
    return example;
  }

  @Get()
  @Version('v2')
  getHelloV2(@Query('example') example: string): string {
    return example;
  }
}
```
In the example above, I can call the v1 api with header 'Accept-Version': v1 and call the v2 api with header 'Accept-Version': v2.
This is the openapi generated:
```json
{
  "openapi": "3.0.0",
  "paths": {
    "/": {
      "get": {
        "operationId": "AppController_getHelloV2",
        "parameters": [
          {
            "name": "example",
            "required": true,
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  },
  "info": {
    "title": "Cats example",
    "description": "The cats API description",
    "version": "1.0",
    "contact": {}
  },
  "tags": [
    {
      "name": "cats",
      "description": ""
    }
  ],
  "servers": [],
  "components": {
    "schemas": {}
  }
}
```
It has only the v2 version.
<img width="1172" alt="Screenshot 2023-01-11 alle 11 26 31" src="https://user-images.githubusercontent.com/26798595/211782575-5561fa3c-c173-42cc-a4ac-0f6c92d7332c.png">
Also adding `ApiImplicitHeader` in each version doesn't resolve the issue

### Minimum reproduction code

https://github.com/DCampagnola/nestjs-swagger-header-versioning-bug/tree/main

### Steps to reproduce

1. `npm i`
2. `npm start:dev`
3. Navigate in `/api-json`

### Expected behavior

Generated api should include every version declared with the different docs

### Package version

6.1.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2063
