### ISSUE TITLE
ApiExtraModels does not include static properties

### ISSUE THREAD

**Issue by WarGreyGon** [nestjs/swagger#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Static properties are missing in swagger docs Schemas

```
export class AuthConstants {
	public static userMinLen: number = 4;
	public userMaxLen: number = 10;
}
```

<img width="205" alt="image" src="https://user-images.githubusercontent.com/24290388/211808400-b940d64f-25bb-4cad-89e8-06fbede9d901.png">

``` 
AuthConstants: {
    type: "object",
    properties: {
        userMaxLen: {
            type: "number",
            default: 10
        }
    },
    required: [
        "userMaxLen"
    ]
}
```

### Minimum reproduction code

NA

### Steps to reproduce

- Create a isolated class not directly used in a Controller (e.g.)

_libs\core\src\features\auth\auth.constants.ts_
```
export class AuthConstants {
	public static userMinLen: number = 4;
	public userMaxLen: number = 10;
}
```

- Configure CLI plugin in _nest-cli.json_

```
"plugins": [
	{
		"name": "@nestjs/swagger",
		"options": {
			"classValidatorShim": true,
			"introspectComments": false,
			"dtoFileNameSuffix": [
				".request.ts",
				".query.ts",
				".dto.ts",
				".entity.ts",
                                ".constants.ts"
			]
		}
```

- Add extraModels to **SwaggerModule** in _main.ts_

```
const document = SwaggerModule.createDocument(app, config, {
		extraModels: [AuthConstants],
	});
        SwaggerModule.setup('api/docs', app, document);
```

- run npm run build
- run npm run start
- open swagger page in _http://localhost:3001/api/docs/_ (In my case, by default will be _http://localhost:3001/_ I think)

### Expected behavior

Static property `public static userMinLen: number = 4;` should be reflected as well in swagger doc

### Package version

^5.2.1

### NestJS version

^8.0.0

### Node.js version

16.6.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

Using VS Code

**Comment by kamilmysliwiec** [comment]
That's the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
