### ISSUE TITLE
Can't add custom .css file to swagger 

### ISSUE THREAD

**Issue by ApplePieAndCrime** [nestjs/swagger#2249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My code
```js
  const customOptions: SwaggerCustomOptions = {
    customCssUrl: '/swagger-theme.css',
    customJs: './swagger.js',
    // customCss: '#header { display: none; }',
  };

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('/api/docs', app, document, customOptions);
```
customCss, customJs - also not working

all files are in src/ 
*also try replace to root

### Minimum reproduction code

 -

### Steps to reproduce

 -

### Expected behavior

 -

### Package version

^6.1.4

### NestJS version

^9.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
