### ISSUE TITLE
Add `Access-Control-Allow-Origin` header to JSON and Yaml express endpoints

### ISSUE THREAD

**Issue by OisinKyne** [nestjs/swagger#2258]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am trying to link to https://mysite.com/api-json in an OpenAPI explorer like this one https://redocly.github.io/redoc/ however this endpoint, represented by [this line](https://github.com/nestjs/swagger/blob/ae525047c27c4c0c4383b4db8ab6f433a510be4b/lib/swagger-module.ts#L121) doesn't have a permissive CORS header that lets this resource be loaded on another domain.  

<img width="355" alt="Screenshot 2023-01-28 at 17 41 58" src="https://user-images.githubusercontent.com/4981644/215282971-8910f552-f6dc-4e78-8ff2-33b35f6908f6.png">

### Describe the solution you'd like

Either an option to set it in the [custom options](https://github.com/nestjs/swagger/blob/master/lib/interfaces/swagger-custom-options.interface.ts), or that the swagger module would inspect if the nest/express `app` it is passed at construction has cors enabled, and respects that automatically. 

Drawbacks of allowing this or enabling CORS too readily is that other websites might host your API docs that you didn't permit. Hence I don't suggest we hardcode it in, as that it is not an ideal default to have on. 

### What is the motivation / use case for changing the behavior?

Being able to read the JSON (and Yaml) representations that nestjs/swagger automatically builds for you on other domains and OpenAPI viewers. Opening up easy optionality for what UI you want to use.

**Comment by kamilmysliwiec** [comment]
AFAIK you can just register a middleware in front of this route (that will handle CORS).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
