### ISSUE TITLE
Swagger plugin breaks Nest start when enums from local package are used

### ISSUE THREAD

**Issue by jehy** [nestjs/swagger#2265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have Nest setup with shared package:

package.json:
```
  "dependencies": {
    "@node-operations/shared": "file:../shared",
```

and it is configured in tsconfig.json:
```
  "paths": {
    "@node-operations/shared": [ "../shared" ]
  }
```

In nest-cli, I have swagger plugin enabled:
```

  "compilerOptions": {
    "deleteOutDir": true,
    "plugins": [
      {
        "name": "@nestjs/swagger"
      }
    ]
  }
```

Everything is fine when I build project. And when I start it in prodcution mode. But when I start it in dev mode, it fails with message like this:

```
> @node-operations/backend@1.0.0 start
> nest start

Error: Cannot find module '../../../../shared/dist/constants/OrderStatus'
Require stack:
- /web/node-operations/lp-proxy-backend/dist/src/order/response/syncOrderResponse.dto.js
- /web/node-operations/lp-proxy-backend/dist/src/integration/integration.controller.js
- /web/node-operations/lp-proxy-backend/dist/src/integration/integration.module.js
- /web/node-operations/lp-proxy-backend/dist/src/app.module.js
- /web/node-operations/lp-proxy-backend/dist/src/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at Module.patchedRequire [as require] (/web/node-operations/lp-proxy-backend/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Function._OPENAPI_METADATA_FACTORY (/web/node-operations/lp-proxy-backend/dist/src/order/response/syncOrderResponse.dto.js:25:143)
    at /web/node-operations/lp-proxy-backend/node_modules/@nestjs/swagger/dist/decorators/helpers.js:38:241
    at DecorateProperty (/web/node-operations/lp-proxy-backend/node_modules/reflect-metadata/Reflect.js:553:33)
    at Reflect.decorate (/web/node-operations/lp-proxy-backend/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/web/node-operations/lp-proxy-backend/dist/src/order/response/syncOrderResponse.dto.js:4:92)
```

I have this problem with enums only but it really blocks my work :(
Seems like a path issue - because plugin tries to find enum file in project `dist` but it does not exist there.
When I use same enums locally, there is no problem. But I need to share them between projects.

### Minimum reproduction code

none yet

### Steps to reproduce

1. Make nest project with swagger plugin enabled
2. Make local package with enum
3. Reference this enum in nest project code
4. `npm start`

### Expected behavior

I expect enums from local package to work as any other types.

### Package version

6.1.4

### NestJS version

9.2.1

### Node.js version

18.11.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jehy** [comment]
Ok, I finally found a workaround:
Add to tsconfig.json :

```
  "paths": {
    "@node-operations/shared": [ "../shared" ]
  }
```

change nest-cli.json from
```
  "sourceRoot": "src",
```
to
```
  "sourceRoot": "lp-proxy-backend/src",
```

and after that swagger finally can find everything on startup.
That's really unexpected that it only happens with enums, only with swagger module enabled and only in dev mode.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
