### ISSUE TITLE
Bug closed as a qustion

### ISSUE THREAD

**Issue by jehy** [nestjs/swagger#2266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi. Concerning bug https://github.com/nestjs/swagger/issues/2265 - that is clearly a bug, not a question. It's at least impolite to close it without any explanation and to send to community.

### Minimum reproduction code

https://github.com/nestjs/swagger/issues/2265

### Expected behavior

I expect moderator to write at least an explanation why he decided that it's not a bug.

### Package version

9

### NestJS version

9

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
