### ISSUE TITLE
Remove inheritance functions of Mapped types to avoid unexpected behaviours

### ISSUE THREAD

**Issue by kb05** [nestjs/swagger#2295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This problem has been discussed  before(for example: https://github.com/nestjs/swagger/issues/1945)

The problem is related to how mapped types & JS inheritance works, the method belongs to the parent class and the mapped type is not attached to the parent, so when you try to access the method the property appears as undefined (but the type in typescript is set as the parent method, so it appears as it has been defined).

It's a complex problem to solve, but my purpose is: why don't we remove all the functions of the resulted mapped type?

For example we have the partial type, which has a definition like this: 
```ts
export declare function PartialType<T>(classRef: Type<T>): Type<Partial<T>>;
```

So maybe we can specify the function like this: 
```ts
// 1 Transform the type to flag all the undesired keys as 'never'.
export type FlagExcludedType<Base> = {
  [Key in keyof Base]: Base[Key] extends Function ? never : Key
}

// 2 Get the keys that are not flagged as 'never'.
export type AllowedNames<Base> = FlagExcludedType<Base>[keyof Base]

// 3 Use this with a simple Pick to get the right interface, excluding the undesired type.
export type OmitType<Base> = Pick<Base, AllowedNames<Base>>

/**
 * Create a type that remove the function fields of the provided type.
 */
export type OmitFunctions<Base> = Pick<Base, AllowedNames<Base>>

export declare function PartialType<T>(classRef: Type<T>): OmitFunctions<Type<Partial<T>>>;
```
Note: Ignore the way that it extracted the functions, it's only a helper that I have in some projects, maybe it's not the best approach.

In my opinion, I think that could be a good approach, we could notify to the developer that the function will not be attached to the class and they will not find strange execution problems (like the function is not defined).

what is your opinion on this matter?

### Minimum reproduction code

https://github.com/Sylphide/nestjs-mapped-type-issue

### Expected behavior

The class should not show as has the method

### Package version

4.8.2

### NestJS version

7.6.18

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Feel free to create a PR for this issue. This wasn't our priority though since mapped types shouldn't really declare any methods.

**Comment by bojovypstros** [comment]
@kb05 https://github.com/nestjs/swagger/pull/2296 I have already started - but because of deps issue - if you wanna, we can remove mapped-types completely

**Comment by kb05** [comment]
Perfect, I going to try it,  I think that It should be easy but maybe could maybe conflict with other parts of the code.

**Comment by kb05** [comment]
Sorry I forgot about this issue, I just opened a new PR https://github.com/nestjs/mapped-types/pull/1027 , but instead of in this repository in mapped-type one, which is the repository where the problem affects.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/mapped-types/pull/1027
