### ISSUE TITLE
Could not resolve reference: Tried to resolve a relative URL, without having a basePath. path: '/my/relative/path' basePath: 'undefined'

### ISSUE THREAD

**Issue by vincent-ogury** [nestjs/swagger#2297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to add a $ref with a relative url, I've got this error in the UI:

```
Could not resolve reference: Tried to resolve a relative URL, without having a basePath. path: '/my/relative/path' basePath: 'undefined'
```

Here the property I use:
```
      my_field: {
        type: 'object',
        $ref: '/my/relative/path',
      },
```

### Minimum reproduction code

https://

### Steps to reproduce

1. define a ApiProperty with $ref and a relative url
2. open the NestJS Swagger UI

### Expected behavior

It should download the relative URL and not showing any error.

### Package version

6.2.1

### NestJS version

9.3.9

### Node.js version

v18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
