### ISSUE TITLE
[Question]: can we customize the css?

### ISSUE THREAD

**Issue by chanlito** [nestjs/swagger#23]
I look at https://github.com/scottie1984/swagger-ui-express and they have custom css support, what about nest?

**Comment by mildbreakfast** [comment]
You can't using default SwaggerModule.setup function, but it's possible if you manually use swagger-ui-express. Just pass custom css as a second argument to swaggerUI.setup function.
```js
expressApp.use('/swagger', swaggerUI.serve, swaggerUI.setup(document, { customCss: '#header { display: none; }' }));
```

**Comment by BruceHem** [comment]
@mildbreakfast this feature should be implemented with nest swagger module, customize css, title, etc.

**Comment by fwoelffel** [comment]
@chanlito see https://github.com/nestjs/swagger/pull/52

**Comment by kamilmysliwiec** [comment]
Merged
