### ISSUE TITLE
Serve Static Module

### ISSUE THREAD

**Issue by PatrykKuniczak** [nestjs/swagger#2301]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

IDN how to use swagger with:
Serve static
https://docs.nestjs.com/recipes/serve-static#serve-static

I think this feature didn't exist, i found a issue on stack, but nobody response:

https://stackoverflow.com/questions/72393000/nestjs-how-to-make-friends-2-modules-servestaticmoduleangular-and-swaggermo

That's for Angular, but Nest it's similar to this.

### Describe the solution you'd like

U can create that feature, if isn't exist right now, else give me a info about it :)

### What is the motivation / use case for changing the behavior?

That's good because i don't have info about that endpoint in Swagger UI, with the rest endpoints.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
