### ISSUE TITLE
Add routes manually

### ISSUE THREAD

**Issue by SmallhillCZ** [nestjs/swagger#2304]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

A generic route is defined using parameter, e.g. `@Get("/:dataset")`. The number of datasets is fixed, but not in the code, but by tables in database. I need to produce separate OpenAPI route for each dataset with response type inferred from the database.

### Describe the solution you'd like

 - Mark `/:dataset` route with `@ApiExcludeEndpoint`
 - Add manually route for each dataset which user has access to together with generating schema from the database

### What is the motivation / use case for changing the behavior?

Some APIs need more custom made OpenAPI docs, which are influenced by other things that source code. This can be showing different OpenAPI specs based on user's role or by source data from other microservice or database.

**Comment by kamilmysliwiec** [comment]
`SwaggerModule.createDocument(app, config)` returns a regular JavaScript object that you can manually alter as you wish/need (add routes/remove types/etc).
