### ISSUE TITLE
Could not render Dt, see the console. [examples property of ApiProperty decorator not work properly]

### ISSUE THREAD

**Issue by koreanddinghwan** [nestjs/swagger#2307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## current Error
![스크린샷 2023-02-24 02 46 25](https://user-images.githubusercontent.com/76278794/220987972-aa9d5d94-b621-42b6-8741-a996362ab5f9.png)

<br>

## Controller
![스크린샷 2023-02-24 02 46 44](https://user-images.githubusercontent.com/76278794/220988053-486564b9-219b-4397-b490-8835a4fc67dc.png)

<br>

## Dto 
![스크린샷 2023-02-24 02 46 57](https://user-images.githubusercontent.com/76278794/220988094-8f8809ba-9e26-41a1-b20e-19b120b6bc26.png)

### Minimum reproduction code

https://github.com/koreanddinghwan/nest

### Steps to reproduce

i think this error caused by examples property of ApiProperty.  
when i use `example` property instead of `examples`, it worked properly

## change examples into example
![스크린샷 2023-02-24 02 47 18](https://user-images.githubusercontent.com/76278794/220988187-2ae36767-a783-4d7f-b7f7-256b24cca863.png)

![스크린샷 2023-02-24 02 47 34](https://user-images.githubusercontent.com/76278794/220988240-78ca6e42-0921-4049-94e7-6d7d8b6e607b.png)

<br>

## then, work properly
![스크린샷 2023-02-24 02 47 51](https://user-images.githubusercontent.com/76278794/220988301-3699756a-2858-46de-b349-f4cf90e585af.png)

### Package version

6.1.4

### NestJS version

9.0.0

### Node.js version

18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

console error logs

![스크린샷 2023-02-24 02 51 02](https://user-images.githubusercontent.com/76278794/220989033-a03d4aa0-de21-4cef-81c6-255fb2d8435f.png)

**Comment by kamilmysliwiec** [comment]
Please report this issue here https://github.com/swagger-api/swagger-ui
