### ISSUE TITLE
TypError on string($binary) field type

### ISSUE THREAD

**Issue by PatrykKuniczak** [nestjs/swagger#2312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If i choose file, and cklick "Wybierz plik" (Select file) one more time, then cancel the windows explorer.

Then the file is not selected (Like on screen),

![image](https://user-images.githubusercontent.com/64608510/221663816-a56253ab-e4c6-4930-9c99-a19191c78141.png)

And i have error in the console:

![image](https://user-images.githubusercontent.com/64608510/221663897-3bc6cb21-1496-4f6c-8cf0-9b96d3eb998f.png)

And this loading from first screen is infinite.

I must refresh page, select file or something else, don't stop this infinite loading.

### Minimum reproduction code

if it's really needed i can do it later, cause no time now

i have 

```ts
@ApiConsumes("multipart/form-data")
```

on that endpoint and that's my DTO:

```ts
export class UpdateUserDto {
    @Length(5, 30)
    @IsAlphanumeric()
    @IsString()
    @Transform(({ value }) => value.replace(/\s/g, "").toLowerCase())
    username: string;

    @Allow()
    @ApiProperty({ type: "string", format: "binary", description: "File which contain .jpg/.jpeg/.png extension" })
    userAvatar?: UserAvatar;
}
```

### Expected behavior

Work correctly, don't infinity load on close windows explorer.

### Package version

6.2.1

### NestJS version

9.3.7

### Node.js version

19.6.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I using WebStorm 2022.3.2 on Windows 11

**Comment by kamilmysliwiec** [comment]
Please, report this issue here https://github.com/swagger-api/swagger-ui
