### ISSUE TITLE
@ApiHideProperty() Not hiding property

### ISSUE THREAD

**Issue by andyslack** [nestjs/swagger#2315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It's not hiding the function from swagger screen

### Minimum reproduction code

https://github.com/andyslack/swagger-api-hide-property-test

### Steps to reproduce

```
$ npm i -g @nestjs/cli
$ nest new swagger-api-hide-property-test
$ cd swagger-api-hide-property-test/
$ npm i @nestjs/swagger @juicyllama/nestjs-redoc
```

Update `main.ts`

```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger'
import { RedocModule, RedocOptions } from '@juicyllama/nestjs-redoc'

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const swagger_document = new DocumentBuilder()
  .setTitle(process.env.npm_package_name)
  .setVersion(process.env.npm_package_version)
  .addBearerAuth()
  .build()

  const redocConfig: RedocOptions = {
   title: process.env.npm_package_name
  }

  const document = SwaggerModule.createDocument(app, swagger_document)
  await RedocModule.setup('/docs', app, document, redocConfig)
  
  await app.listen(3000);
}
bootstrap();
```

Add `@ApiHideProperty()` to the controller endpoint

Run the app

```
$nest start
```

### Expected behavior

The endpoint should not show in /docs view but it does.

### Package version

6.2.1

### NestJS version

9.0.0

### Node.js version

19.6.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

You can see this running live here: 

App: https://andyslack-curly-space-acorn-pp65w44p6j36pvg-3000.preview.app.github.dev/

Docs: https://andyslack-curly-space-acorn-pp65w44p6j36pvg-3000.preview.app.github.dev/docs#operation/AppController_getHello

Or pull this repo: https://github.com/andyslack/swagger-api-hide-property-test into your own codespaces and fire it up

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
