### ISSUE TITLE
Support class generic with @ApiParam using class-validator DTO generate

### ISSUE THREAD

**Issue by truongtailee** [nestjs/swagger#2324]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

For reuse controller. I've define the `ControllerFactory` which is have CRUD basic as a below

```Node
export const ControllerFactory = <T, C, Q, P>(
  createDto: Type<C>,
  queryDto: Type<Q>,
  paramDto: Type<P>,
): Type<ICrudController<T, C, Q, P>> => {
  const createPipes = new AbstractValidationPipe({ whitelist: true, transform: true }, { body: createDto })
  const queryPipes = new AbstractValidationPipe({ whitelist: true, transform: true }, { query: queryDto })
  const paramPipes = new AbstractValidationPipe({ whitelist: true, transform: true }, { param: paramDto })

  class CrudController<T, C, Q, P> implements ICrudController<T, C, Q, P> {
    constructor(protected service: ICrudService<T, C, Q, P>) {}

    @ApiQuery({ type: queryDto })
    @Get()
    async getAll(@Req() req: IRequest, @Param(paramPipes) params: P, @Query(queryPipes) query: Q) {
      return this.service.getAll(req.user, params, query)
    }

    @ApiBody({ type: createDto })
    @Post()
    async create(@Req() req: IRequest, @Param(paramPipes) params: P, @Body(createPipes) body: C) {
      return this.service.create(req.user, params as any, body)
    }

    @ApiParam({ type: paramDto }) //Error in here
    @Get(':id')
    async getOne(@Req() req: IRequest, @Param(paramPipes) params: P) {
      return this.service.getOne(req.user, params)
    }
  }
  return CrudController
}
```

The paramDto example
```Node
export class ProductParamsDto {
  @Transform(({ value }) => value && +value)
  @IsNumber()
  id: number

  @Transform(({ value }) => value && +value)
  @IsNumber()
  tx: number

 ...more path parameters in here
}
```
The `@ApiQuery` & `@ApiBody` is working with DTO but only the @ApiParam is not. So can we have any guide to handling this case in `generic class`.

Thank any solution to fix this.

### Describe the solution you'd like

I try to using `applyDecorators` and loop each property in class DTO but it disappear when TS compiler to JS. So right now the only solution I think is declare the static method in `ParamDto` to handling this case

### What is the motivation / use case for changing the behavior?

If can I think the @ApiParam should support the DTO input

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
