### ISSUE TITLE
unable to fetch swagger-ui.css swagger-ui-bundle.js swagger-ui-standalone-preset.js favicon-32x32.png favicon-16x16.png

### ISSUE THREAD

**Issue by ianzone** [nestjs/swagger#2330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

failed to load static resources when running a bundled production build
![image](https://user-images.githubusercontent.com/20043230/224488534-b44c636f-1852-4ee8-b007-89d83d7eba72.png)

### Minimum reproduction code

https://github.com/ianzone/lambda-nestify

### Steps to reproduce

1. pnpm i
2. pnpm run start
3. go to http://localhost:4567/dev/docs?token=asdf

### Expected behavior

show the ui correctly

### Package version

6.2.1

### NestJS version

9.3.9

### Node.js version

v18.12.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
