### ISSUE TITLE
`@nestjs/swagger/plugin` can't display dto and endpoint info, while a controller extends another controller.

### ISSUE THREAD

**Issue by gylove1994** [nestjs/swagger#2360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`@nestjs/swagger/plugin` can't display dto and endpoint info, while a controller extends another controller.

I have some BaseService, BaseController, Dto, and Entity for other classes entend.

```ts
export class BaseController<
  BaseService extends BaseCRUDService,
  CreateDTO extends BaseDto,
  UpdateDTO extends BaseDto,
> {
  constructor(private readonly baseService: BaseService) {}
  @Post()
  create(@Body() createDto: CreateDTO) {
    return this.baseService.create(createDto);
  }
  @Get()
  findAll() {
    return this.baseService.findAll();
  }
  @Get(':id')
  findOne(@Param('id') id: string) {
    return this.baseService.findOne(id);
  }
  @Patch(':id')
  update(@Param('id') id: string, @Body() updateUserDto: UpdateDTO) {
    return this.baseService.update(id, updateUserDto);
  }
  @Delete(':id')
  remove(@Param('id') id: string) {
    return this.baseService.remove(+id);
  }
}
```
```ts
@Controller()
export class AppController extends BaseController<
  AppService,
  TestDto,
  TestDto
> {
  constructor(private readonly appService: AppService) {
    super(appService);
  }
}
```
It seems can't get any info on TestDto and AppController's endpoints.

### Minimum reproduction code

https://github.com/gylove1994/nestjs-swagger-plugin-bug-reproduce

### Steps to reproduce

1. yarn
2. yarn start:dev
3. open http://localhost:3000/api

### Expected behavior

automated generate dto and endpoint info.

### Package version

6.2.1

### NestJS version

9.3.12

### Node.js version

v18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by gylove1994** [comment]
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/47300853/227800771-c8323180-c8f7-4f03-a713-fc7a021a03ed.png">

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
