### ISSUE TITLE
Support setting the openapi version in DocumentBuilder

### ISSUE THREAD

**Issue by doblinger-extron** [nestjs/swagger#2361]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When generating OAS docs for my service, the [swagger-ui editor](https://editor-next.swagger.io/) returns errors for some of the nested objects.

The error: `allOf must be a non-empty array of schemas`.
![image](https://user-images.githubusercontent.com/85896036/227970098-5e7f508c-d480-4638-a36d-10f3c8b6658c.png)

If I change the openapi version to 3.1.0, the errors disappear.

### Describe the solution you'd like

I'd like to be able to set the openapi version through a DocumentBuilder `set` function 

```typescript
const config = new DocumentBuilder()
    .setOpenAPIVersion('3.1.0')
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
```
Or maybe a better option would be to produce the correct version of OAS automatically

### What is the motivation / use case for changing the behavior?

I'd like to be able to generate OAS documentation that does not contain errors in the [Swagger editor](https://editor-next.swagger.io/).

**Comment by Releef** [comment]
Why has this not been merged yet? [https://github.com/nestjs/swagger/pull/2516](url)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by jmls** [comment]
did this ever make it into the codebase ?

**Comment by mortezakarimi** [comment]
@doblinger-extron @jmls I do the following to update open API version

```typescript
SwaggerModule.setup(
    'api',
    app,
    { ...document, openapi: '3.1.0' })
```

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/3106
