### ISSUE TITLE
Add routes manually per user

### ISSUE THREAD

**Issue by SmallhillCZ** [nestjs/swagger#2367]
@kamilmysliwiec Sorry for creating new Issue, but by locking the old one right after your reply I can't follow it there anymore.

    `SwaggerModule.createDocument(app, config)` returns a regular JavaScript object that you can manually alter as you wish/need (add routes/remove types/etc).

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/swagger/issues/2304#issuecomment-1442900340_

Yes, you can add it do the doc this way, but since you need the `app` reference, which afaik cannot be injected in controller, you cannot use the output of `SwaggerModule.createDocument()` in response to user request and add custom paths. Or is there a way to inject the output of `createDocument()`?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
