### ISSUE TITLE
Decorator in applyDecorators does not work as expected

### ISSUE THREAD

**Issue by DanielSchnieders** [nestjs/swagger#2374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

I've created a function `SetDeleteDecorators` which applies multiple decorators:
https://github.com/DanielSchnieders/nestjs-decorator-problem/blob/main/delete-decorators.ts

When I use HttpCode(204) wihin that function, it does not work on the generated Swagger page.
<img width="1094" alt="swagger-does-not-work" src="https://user-images.githubusercontent.com/126172161/229729506-5300fa40-bd69-4dc0-8a1e-c68119572cbe.PNG">

When I remove the HttpCode(204) [line 12] from the function `SetDeleteDecorators` and directly use it in my Controller, it will remove the default status code 200 from the swagger page:
<img width="1072" alt="swagger-works" src="https://user-images.githubusercontent.com/126172161/229728877-298fcb3a-093a-490f-96af-b0d4aa3fb428.PNG">

### Minimum reproduction code

https://github.com/DanielSchnieders/nestjs-decorator-problem

### Steps to reproduce

install nestjs
start nestjs application
visit the generated swagger document

### Expected behavior

Status Code 200 should not be visible on the Swagger page.

### Package version

"@nestjs/swagger": "^6.3.0",

### NestJS version

"@nestjs/core": "^9.3.12"

### Node.js version

v18.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
NestJS Swagger CLI Plugin uses static analysis to determine if you have a custom HTTP status set on a specific route. If you don't, then it auto-applies 200 (which is the default). `applyDecorators` is a runtime construction - and so decorators you apply through that function won't be introspected by the plugin.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for further questions. We are using GitHub to track bugs, feature requests, and potential improvements.
