### ISSUE TITLE
Type Alias is not detected by  swagger tool

### ISSUE THREAD

**Issue by shubham1809** [nestjs/swagger#2375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have Used Type Alias in Request Param but Swagger UI is not displaying that.
export type a = number | string <does not work>
export type b = number <working>

### Minimum reproduction code

https://github.com/shubham1809

### Steps to reproduce

npm i

### Expected behavior

it should come in swagger UI.

### Package version

latest

### NestJS version

latest

### Node.js version

12.1.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

na

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
