### ISSUE TITLE
authorization is not being sent

### ISSUE THREAD

**Issue by gofreddo** [nestjs/swagger#2388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The authorization header isn't being sent.

<img width="2552" alt="Screenshot 2023-04-13 at 2 16 32 PM" src="https://user-images.githubusercontent.com/2431474/231874585-846be93d-63ba-4e75-9b5e-982744f7b2cc.png">

### Minimum reproduction code

Send a request with an authorization header

### Steps to reproduce

Send a request with an authorization header

### Expected behavior

The header should be sent.

### Package version

6.3.0

### NestJS version

9.0.0

### Node.js version

18.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
