### ISSUE TITLE
@swc/jest doesn't handle correctly swagger decorator in coverage

### ISSUE THREAD

**Issue by Ketlark** [nestjs/swagger#2393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I replace default jest transformer with swc ones, but when i run all tests, the coverage report indicate that some lines is not covered due to nestjs/swagger decorator

Here is picture from jest coverage report html : 
![image](https://user-images.githubusercontent.com/1526729/232310604-e1f97f3c-edca-4115-bd4c-ba23546c605e.png)

As you see, class-validator decorators are correctly handled but not these from nestjs/swagger package

Maybe is a build target difference ? es6 vs es2018 from class validator, both use TSC to build 

### Minimum reproduction code

.

### Expected behavior

Handle nestjs/swagger decorator in coverage report 

### Package version

6.3.0

### NestJS version

9

### Node.js version

16.20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the @swc/jest repository
