### ISSUE TITLE
oneOf parameter in ApiProperty  not showing in swagger document

### ISSUE THREAD

**Issue by iyjian** [nestjs/swagger#2412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to define a get request query schema as 

```
{
   name: {
    catName: string 
  }
}
```

or 

```
{
   name: {
    petName: string 
  }
}
```

but it does work, schema not show in swagger document.

the code definition as follows(can also refer to the mininum reproduction code): 

```javascript
import { Controller, Get, Query } from '@nestjs/common';
import {
  ApiExtraModels,
  ApiOperation,
  ApiProperty,
  getSchemaPath,
  refs,
} from '@nestjs/swagger';

class Pet {
  @ApiProperty()
  petName: string;
}

class Cat {
  @ApiProperty()
  catName: string;
}

@ApiExtraModels(Pet, Cat)
class HelloRequest {
  @ApiProperty({
    description: 'name',
    oneOf: [{ $ref: getSchemaPath(Pet) }, { $ref: getSchemaPath(Cat) }],
    type: () => Object
  })
  name: Pet | Cat;
}

@Controller()
export class AppController {
  constructor() {}

  @Get()
  @ApiOperation({
    summary: 'Hello',
  })
  getHello(@Query() helloRequest: HelloRequest) {
    return helloRequest;
  }
}
```

### Minimum reproduction code

https://github.com/iyjian/nestjs_swagger_missing_param.git

### Steps to reproduce

1. npm install
2. npm run start:dev
3. goto http://localhost:3000/swagger
4. request parameter `name` was not showing on swagger document.

### Expected behavior

request parameter `name` should be showing on swagger document.

### Package version

6.3.0

### NestJS version

9.4.0

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

## request parameter `name` was not showing on swagger document.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/466985/235119202-5c94da2d-77dc-4717-898a-032519668abd.png">

**Comment by rbideau** [comment]
I also had this issue and I worked around it by applying applying #2564 via [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2564
