### ISSUE TITLE
Supporting the readonly modifier for arrays for the Swagger plugin

### ISSUE THREAD

**Issue by ChristopherZhong** [nestjs/swagger#2413]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The `readonly` modifier when applied to arrays is not picked up or ignored by the Swagger plugin. The documentation produced does not show any examples in the responses section. If the `readonly` modifier is removed, the Swagger plugin works as expected.

Suppose the entity class is as follows.

```typescript
import { IsString, IsUUID, Length } from 'class-validator';

export class Example {
  /**
   * The ID of an Example.
   *
   * @example '4ff02953-14a2-45ae-87e8-2858776bb818'
   */
  @IsUUID()
  readonly id!: string;

  /**
   * The name of an Example.
   * 
   * @example 'Example'
   */
  @IsString()
  @Length(1, 255)
  readonly name!: string;
}
```

And the controller is as follows.

```typescript
import { Controller, Get, NotImplementedException } from '@nestjs/common';
import { Example } from './example.entity';

@Controller()
export class AppController {
  /**
   * Retrieve an Example.
   */
  @Get('example')
  example1(): Example {
    throw new NotImplementedException();
  }

  /**
   * Retrieve a list of Examples.
   *
   * The return type is `Example[]`.
   */
  @Get('examples1')
  examples1(): Example[] {
    throw new NotImplementedException();
  }

  /**
   * Retrieve a list of Examples.
   *
   * The return type is `readonly Example[]`.
   */
  @Get('examples2')
  examples2(): readonly Example[] {
    throw new NotImplementedException();
  }

  /**
   * Retrieve a list of Examples.
   *
   * The return type is `ReadonlyArray<Example>`.
   */
  @Get('examples3')
  examples3(): ReadonlyArray<Example> {
    throw new NotImplementedException();
  }
}
```

When viewing the API documentation (e.g., `localhost:3000/api`), the `examples1` shows the following in the responses section.

```json
[
  {
    "id": "4ff02953-14a2-45ae-87e8-2858776bb818",
    "name": "Example"
  }
]
```

However, the `examples2` and `examples3` are missing the examples in the responses section.

A minimal repo is at https://github.com/ChristopherZhong/sample-nestjs-swagger-readonly-arrays.

### Describe the solution you'd like

I would like the Swagger plugin to support the `readonly` modifier for arrays. This would result in the example showing up in both the `examples2` and `examples3` endpoints, just like the `examples1` endpoint.

The currently solution is to use the API decorator as follows.

```typescript
@ApiOkResponse({ isArray: true, type: Example })
```

### What is the motivation / use case for changing the behavior?

We use immutability a lot in the code. Arrays are typically marked as `readonly`.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Behavior-wise it makes 0 difference.
