### ISSUE TITLE
ApiProperty array of objects

### ISSUE THREAD

**Issue by imbenwolf** [nestjs/swagger#2418]
I can't get it to work, even with @iambpn's suggested solution. Here's my endpoint:

```ts
  @Get('cats')
  async cats(@Query() request: CatInput): Promise<CatDto> {
    return new Promise<CatDto>(() => {
        return {color: 'black', name: 'Abc'};
      }
    )
  }
```

I'd like `CatInput` to be properly rendered in Swagger It contains an array of objects called `infos`:

```ts
export class Info {
    public name: string;
    public color: string;
}

export class CatInput {
    public infos: Info[]
}
```
I'm using the nest swagger plugin.
Here're some of the options I tried:

1. No decorators added

```ts
export class Info {
    public name: string;
    public color: string;
}

export class CatInput {
    public infos: Info[]
}
```

![image](https://user-images.githubusercontent.com/10273406/188099699-2e6c04fd-a0c9-4ba1-92dc-69db5e2bf58b.png)

Swagger UI does not allows me to input multiple infos. Even the single one I provide is sent wrong, missing the name of the `infos` field.

2. Added `ApiProperty` decorator as suggested by @iambpn 

```ts
export class Info {
    public name: string;
    public color: string;
}

export class CatInput {
    @ApiProperty({isArray: true, type: Info})
    public infos: Info[]
}
```

![image](https://user-images.githubusercontent.com/10273406/188099982-75d52176-5e58-432e-928e-a8af846ca727.png)

I get exactly the same result as before. I cannot provide multiple infos.

3. Different form of `ApiProperty`

```ts
export class Info {
    public name: string;
    public color: string;
}

export class CatInput {
    @ApiProperty({isArray: true, type: [Info]})
    public infos: Info[]
}
```

![image](https://user-images.githubusercontent.com/10273406/188100309-4d300699-7eaf-4409-a4db-01291a59cd83.png)

Starts to look good. However, when I try to add an item:

![image](https://user-images.githubusercontent.com/10273406/188100965-d30544a6-988d-4831-8bd4-25db22f694ad.png)

Something is clearly wrong there, the swagger JSON is:

```json
"parameters": [
          {
            "name": "infos",
            "required": true,
            "in": "query",
            "schema": {
              "type": "array",
              "items": {
                "type": "array",
                "items": {
                  "type": "a"
                }
              }
            }
          }
        ],
```

The specification is definitely wrong. Where does it take the `type: "a"` from?

---

Am I missing something?
@kamilmysliwiec, let me know if I should create a new issue for this, this one seemed very similar to mine.

_Originally posted by @marcinjahn in https://github.com/nestjs/swagger/issues/780#issuecomment-1235234637_

**Comment by imbenwolf** [comment]
i'm still having this issue and would love to know if there is an update or if there is a solution. thx!

**Comment by iyjian** [comment]
better to have minimum reproduction code, i am having the same issue.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
