### ISSUE TITLE
Automatic DTO Generation and Payload Documentation for Extended Entities/Schemas

### ISSUE THREAD

**Issue by adeeldilmir** [nestjs/swagger#2434]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When extending entities or schemas in NestJS, there is currently no automatic way to generate corresponding DTOs and provide payload documentation based on the extended entity's properties. This leads to manual duplication of code and effort in maintaining separate DTO classes that mirror the entity/schema properties.

### Describe the solution you'd like

The desired solution is to have NestJS/Swagger automatically generate DTOs based on extended entities or schemas. When a DTO extends an entity/schema class, the framework should generate a corresponding DTO class that reflects the properties of the extended entity/schema. Additionally, Swagger should utilize these generated DTOs to provide accurate payload documentation in the Swagger UI, including the properties, validation rules, descriptions, and default values defined in the entity/schema or extended classes

### Teachability, documentation, adoption, migration strategy

To ensure ease of adoption and migration, it would be beneficial to provide clear documentation and examples demonstrating the usage of this feature. This could include guides on how to extend entities/schemas and automatically generate DTOs, as well as how to leverage the generated DTOs for payload documentation in Swagger. It would also be valuable to highlight any potential breaking changes, if applicable, and provide migration strategies or tools to facilitate the transition.

### What is the motivation / use case for changing the behavior?

The motivation behind this feature request is to improve developer productivity and reduce code duplication in API development with NestJS. By automating the generation of DTOs based on extended entities/schemas, developers can save time and effort in maintaining separate DTO classes. Furthermore, automatic payload documentation in Swagger based on the entity/schema properties would enhance the quality and clarity of the API documentation, leading to improved communication and understanding between API consumers and providers.

**Comment by adeeldilmir** [comment]
is there anyone who can resolve this as quickly as possible ,because  otherwise I have to define the dto of each endpoints,althogh my dto are extending entity(sql table) ,my nest app has 100 of endpoint(api). Previous developer  of my app has remove the api docs.

**Comment by adeeldilmir** [comment]
if any one has solution which is already working feel free to post .Thank you.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
