### ISSUE TITLE
Definitions based on TypeScript interfaces 

### ISSUE THREAD

**Issue by Ali1Ammar** [nestjs/swagger#2439]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

did we really had to write a class for each request and respose to let swagger detect it?

### Describe the solution you'd like

support typescript interface which is possible at compile time as tsoa is already use it and it work

in tsoa we just return any data from our orm/service (prisma as example) and tsoa generator will detect the schema and generate the swagger using cli command  (not at runtime)

as example of what i want is the below code
```ts
export const LoginAuthUser = z.object({
  email: z.string().email(),
  password: z.string().min(5),
});


@Post('/login')
  async login(
     @Body() body: LoginAuthUser,
  ) {
    return {"access_token":"token","refresh_token":"refresh_token"};
  }
```
then nest swagger should generate : 
![image](https://github.com/nestjs/swagger/assets/18378766/d0cce916-0e3b-4a46-9420-8f358d3a7210)

look how we did not write any class and the generator detect the type of response directly from the interface

this behavior is already made with tsoa and i think bring it to nestjs will be amazing

### What is the motivation / use case for changing the behavior?

better support for generating swagger without extra step

**Comment by Ali1Ammar** [comment]
this is a simple example of integrate tsoa with nestjs which take response and request from tsoa swagger json and merge it with nestjs swagger 
https://github.com/moh1434/nest-tsoa-exampe
 we want nestjs to generate this without need of tsoa at all

**Comment by Amorii1** [comment]
yes, this would be amazing feature to add !

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
