### ISSUE TITLE
Named numberic enum infers incorrect type

### ISSUE THREAD

**Issue by mothershipper** [nestjs/swagger#2445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Given the following setup:

```
enum MyEnum {
  One = 1,
  Two = 2,
}

class MyDto {
  @ApiProperty({
    enum: MyEnum,
  })
  public myWorkingEnum: MyEnum

  @ApiProperty({
    enum: MyEnum,
    enumName: 'MyEnum',
  })
  public myBrokenEnum: MyEnum
}
```

The resulting swagger spec will say myWorkingEnum is a number and myBrokenEnum is a string.

### Minimum reproduction code

https://codesandbox.io/s/node-ts-playground-forked-vtv09v?file=/src/index.ts

### Expected behavior

I'd expect both the named and unnamed enum to be a number

### Package version

6.3.0

### NestJS version

9.4.0

### Node.js version

16.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by quangtran88** [comment]
This is because of the hard-coded type is used when `enumName` is provided.
https://github.com/nestjs/swagger/blob/407f906e2b9e8ead8a2c569a8f82c47cb76e424a/lib/services/schema-object-factory.ts#L297
I created a PR https://github.com/nestjs/swagger/pull/2592
