### ISSUE TITLE
Could we add request duration time in @nestjs/swagger ?

### ISSUE THREAD

**Issue by TonyDo99** [nestjs/swagger#2448]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

25/05/2023

### Describe the solution you'd like

I was trying to find displayRequestDuration for using nestjs, but seem like it wasn't have

### What is the motivation / use case for changing the behavior?

For long time need to execute api, ex: handle file, report, transaction. Know more duration time we will know how long it been done. Like postman

**Comment by kamilmysliwiec** [comment]
Please, report this issue here https://github.com/swagger-api/swagger-ui
