### ISSUE TITLE
swagger ui v5.0.0

### ISSUE THREAD

**Issue by TrejGun** [nestjs/swagger#2469]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Swagger UI v5 was just released today! This issue is created to inform the community and keep track of developments

https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0

### Describe the solution you'd like

implement support for v5

### What is the motivation / use case for changing the behavior?

v5 is nice and shiny

**Comment by kamilmysliwiec** [comment]
There seem to be no breaking changes(?) 🤞

**Comment by billychannnnnn** [comment]
Quite need the latest version. Just ran into this issue: https://github.com/swagger-api/swagger-ui/issues/3494#issuecomment-653646087

**Comment by vpiskunov** [comment]
Also the issue to support showing multiple examples in case of `anyOf, oneOf, allOf` to be shown in Swagger UI would likely be resolved as per [https://github.com/swagger-api/swagger-ui/issues/3803](https://github.com/swagger-api/swagger-ui/issues/3803)

I see the PR here [https://github.com/nestjs/swagger/pull/2472](https://github.com/nestjs/swagger/pull/2472) - can this be safely used or merged? 

Really need the multiple / anyOf support! Thanks
