### ISSUE TITLE
ObjectId and other non-primitive Params are ignored

### ISSUE THREAD

**Issue by Clashsoft** [nestjs/swagger#2471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Endpoints with non-primitive parameters, e.g. `ObjectId`s, do not show the parameters.

```ts
  @Get(':id')
  async getUser(@Param('id', ObjectIdPipe) id: Types.ObjectId): Promise<User | null> {
    return this.userService.find(id);
  }
```

<img width="1447" alt="Screenshot 2023-06-13 at 12 51 58" src="https://github.com/nestjs/swagger/assets/4145923/3cb0084f-c6ee-4913-ba71-15eb3a9abb9e">

The only way to resolve this is to either a. use type `string` and convert in the body, or b. document the parameter manually using `@ApiParam({name: "id", type: String, ...}`.

### Minimum reproduction code

https://github.com/sekassel-research/stp-23-server

### Expected behavior

Either `ObjectId` and other non-primitive types (e.g. `Date`) should be treated as strings, or there should be a way to configure custom model replacements (see [here](https://stackoverflow.com/questions/58375613/swagger-shows-mongo-objectid-as-complex-json-instead-of-string))

### Package version

6.3.0

### NestJS version

9.4.2

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Clashsoft** [comment]
Related: https://github.com/nestjs/swagger/pull/1198

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
