### ISSUE TITLE
swagger-ui should not serve the Petstore example

### ISSUE THREAD

**Issue by tmtron** [nestjs/swagger#2475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* start the reproduction example 
* visit http://localhost:3000/api: it serves our example API as expected
* visit http://localhost:3000/api/api: it serves the Petstore example!?

### Minimum reproduction code

https://github.com/nestjs/nest/blob/master/sample/11-swagger/README.md

### Steps to reproduce

* start the reproduction example 
* visit http://localhost:3000/api: it serves our example API as expected
* visit http://localhost:3000/api/api: it serves the Petstore example!?

### Expected behavior

http://localhost:3000/api/api: should return HTML code 404

### Package version

6.3.0

### NestJS version

9.4.3

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
