### ISSUE TITLE
this library does not support Nestjs 10.0.0

### ISSUE THREAD

**Issue by xuegao-tzx** [nestjs/swagger#2476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

this library does not support Nestjs 10.0.0

### Minimum reproduction code

this library does not support Nestjs 10.0.0

### Expected behavior

this library does not support Nestjs 10.0.0

### Package version

6.3.0

### NestJS version

10.0.0

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

this library does not support Nestjs 10.0.0

**Comment by flowluap** [comment]
Same here

**Comment by mdwekat** [comment]
+1

**Comment by filipeversehgi** [comment]
+1

**Comment by shaungt1** [comment]
I am also having the same Issue 
npm ERR! Found: @nestjs/common@10.0.0
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^9.0.0" from @nestjs/swagger@6.3.0

**Comment by shaungt1** [comment]
9.5.0 CLI works just fine with swagger

**Comment by webIntegral** [comment]
+1

**Comment by oconr** [comment]
+1

**Comment by micalevisk** [comment]
come one guys, NestJS v10 was just released. There's no reason to spamming this GH Issue with those useless `+1` comments lol they are just noise to us.

There are few others packages of `@nestjs/*` with the same "issue". Just wait a bit more :)

Also, it's pretty clear that `@nestjs/swagger` v6.3.0 (which is the latest version as of now) does not support NestJS v10 here:

![image](https://github.com/nestjs/swagger/assets/13461315/f7732a52-6c27-414f-97d7-ff0962606ada)

**Comment by JamilAlhunity** [comment]
+1

**Comment by jmcdo29** [comment]
Yes, yes, thank you everyone with your "+1"'s, we're aware that the library needs an update to properly handle it.

Meanwhile your comments are almost spammy and incredibly disrupting. The new version will likely be out in a day or so, if not sooner, so please just have patience

**Comment by kamilmysliwiec** [comment]
Just published v7
