### ISSUE TITLE
[FR] validate inputs based on openapi annotations

### ISSUE THREAD

**Issue by cedvdb** [nestjs/swagger#2478]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues
- related https://github.com/nestjs/swagger/issues/171

### Is your feature request related to a problem? Please describe it

When using `@nestjs/swagger` the open api document is generated for swagger, without using any annotation on DTOs.

Such that required properties are inferred:

```ts
class SomeDto {
  requiredProperty: number;
}
```

However those properties are validated at that point and one has to add additional decorators, most notably from class-validator, to make those actually required.

### Describe the solution you'd like

The open api document should be used for validation. There is no need for additional redundancy as the openapi document should already contain the validation data. 

### What is the motivation / use case for changing the behavior?

Less redundancy

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
