### ISSUE TITLE
`default` values for properties are sent wrapped with the quotes

### ISSUE THREAD

**Issue by bruno-de-queiroz** [nestjs/swagger#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Whenever the class has a default string value, for example: `sort = 'createdAt DESC'`  the UI is sending the value with the single quotes.

### Minimum reproduction code

https://gist.github.com/bruno-de-queiroz/d77681da9b9eaf75c7f18bc438a98446

### Steps to reproduce

- npm i
- npm run start

### Expected behavior

Send the string value without the quotes

### Package version

7.0.10

### NestJS version

9.4.3

### Node.js version

20.3.1

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

This bug was not there in the previous version: 7.0.5

**Comment by kamilmysliwiec** [comment]
Fixed in v7.0.11
