### ISSUE TITLE
Array of multiple types in response not working

### ISSUE THREAD

**Issue by elSuperRiton** [nestjs/swagger#251]
Version : "@nestjs/swagger": "^2.5.1"

I'm trying to print out an API response with a list of various object types. I'm also trying to use class-transformer with discriminators but swagger prints out [{}]

```
export class GetPageDto extends WeakCreatePageDto {
  @ApiModelPropertyOptional({
    isArray: true,
  })
  @IsOptional()
  @IsArray()
  @Type(() => BaseBlockDto, {
    discriminator: {
        property: 'type',
        subTypes: [
            { value: GetBannerDto, name: 'banner' },
            { value: GetCampaignDto, name: 'campaign' },
        ],
    },
  })
  readonly blockList: GetBannerDto | GetCampaignDto;
}
```

Is there a way to define an array of multiple types ?

**Comment by arekbal** [comment]
Same observation today.
`@ApiModelPropertyOptional({ isArray: true, type: [StorageItemDto] }) readonly items: StorageItemDto[]`
leads to type being empty in .json.

**Comment by kamilmysliwiec** [comment]
@arekbal only first 2 are valid

**Comment by kamilmysliwiec** [comment]
@elSuperRiton we can't resolve union types, this is related to this issue https://github.com/nestjs/swagger/issues/191

**Comment by cjancsar** [comment]
@kamilmysliwiec what specifically from https://github.com/nestjs/swagger/issues/191 does not resolving union types have to do with so that I can follow along?
