### ISSUE TITLE
[Support ] How can I use NestJS decorators to wrap the schema into content/<media-type>?

### ISSUE THREAD

**Issue by mmmitit** [nestjs/swagger#2531]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

1. I want to create a JSON-formatted query based on the following information.
- https://swagger.io/docs/specification/describing-parameters/
![image](https://github.com/nestjs/swagger/assets/86104535/f2791f77-2795-4634-995f-34f067239411)

### Describe the solution you'd like

The request URL on the Swagger page is incorrectly written.

![image](https://github.com/nestjs/swagger/assets/86104535/3053434c-b693-4033-8a1e-0047437a2a1c)

Incorrect URL:
http://localhost:3000/?type=t-shirt&color=blue

Desired URL:
http://localhost:3000/?filter={"type":"t-shirt","color":"blue"

How can I write a decorator for the desired URL?"

### What is the motivation / use case for changing the behavior?

Currently, @nestjs/swagger is using the open api 3.0 version as the latest version (7.1.2). I want to make a request url in JSON-formatted query format using a decorator.

The current code is as follows.
```typescript
export class testFliterDto {
  @ApiProperty({
    example: '{"type": t-shirty,"color": blue }',
    description: 'filter',
    required: false,
    type: 'object',
  })
  filter: {
    type: string;
    color: string;
  };
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
