### ISSUE TITLE
Bug Report: Nested Properties Not Displayed in Swagger Documentation with Generic Types

### ISSUE THREAD

**Issue by AliRaZa1121** [nestjs/swagger#2540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using NestJS with the @nestjs/swagger package to generate Swagger documentation, the response structure for the BaseResponseDto is not displayed correctly in the Swagger documentation. Specifically, the nested class structure inside the data property of BaseResponseDto is not visible in the Swagger UI.

### Steps to Reproduce:

1. I defined the SuccessApiWrapperInterface and ErrorApiWrapperInterface interfaces as follows:

![image](https://github.com/nestjs/swagger/assets/62483196/10c74826-6be0-4f3b-9fe3-346be2fb8477)

2. I defined the BaseResponseDto class as follows:
 
![image](https://github.com/nestjs/swagger/assets/62483196/e9cac313-8906-43e8-9ac8-2b8277eb265b)

3. and then defined the LoginResponseDto class as follows:
![image](https://github.com/nestjs/swagger/assets/62483196/ae20cfd8-859f-4554-8111-1f81181e8316)

4. also defined the Login method in the auth controller as follows:

![image](https://github.com/nestjs/swagger/assets/62483196/f1cff7d8-ffd4-403e-a359-7dc644e1c7e1)

5. I also defined the custom decorators for Http Post Method

![image](https://github.com/nestjs/swagger/assets/62483196/a370326c-7106-4694-86cd-06d38ed0fa4b)

### Expected Behavior:
The Swagger documentation should display the response structure correctly for the BaseResponseDto class, including the nested class structure inside the data property.

### Actual Behavior:
The Swagger documentation displays the BaseResponseDto class correctly, but the nested class structure inside the data property is not visible in the Swagger UI.

### Current Response

![image](https://github.com/nestjs/swagger/assets/62483196/21c4537d-642d-4117-9457-bb9af8f3b33f)

 
 

### Minimum reproduction code

https://github.com/AliRaZa1121

### Expected behavior

The Swagger documentation should display the nested properties inside the data object of the generic response class, BaseResponseDto<T>, accurately representing the nested structure of the LoginResponseDto.

### Expected Reponse 

![image](https://github.com/nestjs/swagger/assets/62483196/fffbfa4e-cf2c-4687-9d25-5debbaf3062d)

### Package version

7.1.1

### NestJS version

9.0.0

### Node.js version

18.12.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
