### ISSUE TITLE
Bug Report: after running `setup`, you can view the source code of the application

### ISSUE THREAD

**Issue by destyk** [nestjs/swagger#2543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After starting  `SwaggerModule.setup`, you can view the source code of the application from the browser if you know the names of the files.

### Minimum reproduction code

https://gist.github.com/destyk/e3aac2f0e5f3b1c5f4666bfd6caefe1b

### Steps to reproduce

1. `SwaggerModule.setup('/api/docs', app, document, {useGlobalPrefix: true});`
2. The output file will be called `app.js`
3. Go to the browser at link `http://localhost:3000/api/docs/app.js` and see the source code of the file

### Expected behavior

I think that the source code, except for the developer, should not be seen by anyone :)

### Package version

6.3.0

### NestJS version

9.4.3

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
I cannot reproduce this in a `nest new` project.

Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by destyk** [comment]
> I cannot reproduce this in a `nest new` project.
> 
> Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
> 
> ## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
my mistake. I forgot to mention that I use `webpack` with my `webpack.config.js` file.

After building the application in this way, two problems appear, which you can reproduce using an example below:

1. Following the link `/api/docs`, there will be an empty page, since statics files cannot be loaded.
2. Following the link `/api/docs/main.js`, the source code will be displayed.

Link:
https://codesandbox.io/p/sandbox/vigilant-kate-p7mgmj?file=%2Fsrc%2Fmain.ts%3A1%2C1

**Comment by jmcdo29** [comment]
I believe this probably comes from how webpack bundles things together. Nest's default webpack config keeps all the dependencies out of the final bundle. I'll try to look into this.

**Comment by jmcdo29** [comment]
Right, Nest's webpack default config doesn't share this issue, in my test with a similar setup

**Comment by destyk** [comment]
> I believe this probably comes from how webpack bundles things together. Nest's default webpack config keeps all the dependencies out of the final bundle. I'll try to look into this.

It seems to me that the whole problem is in this line: https://github.com/nestjs/swagger/blob/d6c0551384891e10980dc9ea5e67769f5a2a8438/lib/swagger-ui/swagger-ui.ts#L31

It would be great to make it possible to override the path to `swagger-ui-dist`. This would solve those two issues when using `webpack`

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by destyk** [comment]
I'm sorry I'm off topic, but I wanted to ask: will https://github.com/nestjs/docs.nestjs.com/pull/2621?ysclid=lks1lk17qu335364379 be merged? I also need this changes.

Thanks!

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2544
