### ISSUE TITLE
it seems that **PartialType**, **PickType** and **OmitType** is not working while using the SWC compiler.

### ISSUE THREAD

**Issue by renatocron** [nestjs/swagger#2557]
@SpeedySH I'm facing the same issue, it seems that **PartialType**, **PickType** and **OmitType** is not working while using the SWC compiler.
I will use the default tsc compiler till this issue is fixed.
cc: @kamilmysliwiec

_Originally posted by @mhadi512 in https://github.com/nestjs/swagger/issues/2493#issuecomment-1627642157_
            

I follows the instructions, added the `await SwaggerModule.loadPluginMetadata(metadata);` on the swagger, and `PartialType` does indeed work (the attribute and validation is working as expected) however, the attribute is not marked as optional on the swagger (eg: the result is not the same as adding @IsOpicional() as expected when using the PartialType)

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project)..

**Comment by mhadi512** [comment]
At first, all Mapped Types wasn't working fine in Swagger docs, but after **v7.1.0** it was fixed.
But I didn't notice that PartialType is still empty.

![image](https://github.com/nestjs/swagger/assets/16844787/2cc9adf9-a9c8-48ff-990a-0842b466d2dd)

**Comment by kamilmysliwiec** [comment]
Minimum reproduction repository https://minimum-reproduction.wtf/

**Comment by renatocron** [comment]
I created repository: https://github.com/renatocron/nestjs-issue-2557

but I was not able to actually reproduce this issue of PartialType.
You can look at the repository to see if you can make any changes on your setup, @mhadi512 

Yesterday I was wrong about the swagger not detecting the types correctly, the indication of a required field is the red *.
Also, the typescript is also working:
![image](https://github.com/nestjs/swagger/assets/1919076/d4160977-db97-46af-9c0b-67dd21d39f85)
 
---
I will close this issue, but I have a question about the `metadata.ts` (and I think maybe here is more searchable than discord), should it be added to the `.gitignore`? 
if I remove it from the repository, during the `nest build` it fails because the file does not exists, and for some reason, even after configuring the `nest-cli.json` to use `swc` it only applies to nest start/start + watch ? if I add the option to force `-b swc` then the build change to swc but do finishes because it's missing the file. I was able to make this work if I add the watch flag to nest build, but that wold not work in CI because it would hang foverver

Should the swc be used to build the 'production' version at all? If not, should I create a tombstone metabase.ts for the production build just to make the import/loadPluginMetadata happy?

**Comment by mhadi512** [comment]
@renatocron Don't close yet, please run the code locally and open the swagger docs url, then check if the DTO which uses PartialType is working fine and not showing empty object as in my case.

Regarding the metadata file, I once asked @kamilmysliwiec , and he said this file **should be committed**. the NestJS docs doesn't have this info (at least when I checked it two weeks ago), so after changing routes or dtos, run start:dev to update this file, so you add it in the commit.

**Comment by renatocron** [comment]
![image](https://github.com/nestjs/swagger/assets/1919076/a5964e13-e17c-445d-9f9c-0dc6742c79c1)
both ways of extending is working:

```
export class AllFieldsRequired {
    @IsString()
    email: string;

    @IsString()
    name: string;
}

export class PartialAllThenPickEmail extends PickType(PartialType(AllFieldsRequired), ['email'] as const) {}

export class PickEmailThenPartial extends PartialType(PickType(AllFieldsRequired, ['email'] as const)) {}
```

---

About the file to be committed: alright, I usually not a fan of files that can be compiled to be committed when a build process exists, they only pollute and make merge's a little noiser
