### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by LeoFC97** [nestjs/swagger#2584]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No

### Describe the solution you'd like

Add to  class DocumentBuilder option to have themes such as: Dark Mode, LigthMode (current) and others.

### Teachability, documentation, adoption, migration strategy

New line:     setTheme(name: ThemesEnumerator): this;
![image](https://github.com/nestjs/swagger/assets/33994116/86e0e142-960c-4687-ae01-170925d8a2ec)

Users can use like this:
    .setTheme('dark')

![image](https://github.com/nestjs/swagger/assets/33994116/0a86acc5-35af-4be4-990b-5c922a4ebe2c)

### What is the motivation / use case for changing the behavior?

I dont want to hurt my eyes everytime I work 👀

**Comment by kamilmysliwiec** [comment]
https://github.com/swagger-api/swagger-ui/issues/5327
