### ISSUE TITLE
`@nestjs/swagger@^6.3.0` started breaking `nest build` without any changes (bumps,diffs, etc.)

### ISSUE THREAD

**Issue by pedroluiznogueira** [nestjs/swagger#2589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have asked a question in nest's discord earlier this week. I found a way to work around my issue, but I thought it would be helpful to report it in case anyone runs into this in the future.

- [Original discord question](https://discord.com/channels/520622812742811698/1025199348096700476)

```
the log error is something like:

 yarn build
$ nest build

 Error  Debug Failure. False expression: import= for internal module references should be handled in an earlier transformer.

error Command failed with exit code 1.
```

Additional information:
- I have not upgraded any dependencies, node version, typescript, etc.
- This started happening out of nowhere in any OS.
- We noticed that in our pipeline, because it was only happening on CI, because it would install dependencies and build fresh every time. Before that locally it wasn't reproducing because of the already installed node modules.

---

After troubleshooting, we found out what was the issue, bumping dependencies one at a time.

this version was working fine for weeks:

```
"@nestjs/swagger@^6.3.0":
  version "6.3.0"
  resolved "https://registry.yarnpkg.com/@nestjs/swagger/-/swagger-6.3.0.tgz#2963395a398374c25548a012eb15f03f53ad6e53"
  integrity sha512-Gnig189oa1tD+h0BYIfUwhp/wvvmTn6iO3csR2E4rQrDTgCxSxZDlNdfZo3AC+Rmf8u0KX4ZAX1RZN1qXTtC7A==
  dependencies:
    "@nestjs/mapped-types" "1.2.2"
    js-yaml "4.1.0"
    lodash "4.17.21"
    path-to-regexp "3.2.0"
    swagger-ui-dist "4.18.2"
```

and then we bumped to the next one:

```
"@nestjs/swagger@7.0.0":
  version "7.0.0"
  resolved "https://registry.yarnpkg.com/@nestjs/swagger/-/swagger-7.0.0.tgz#671adecdf11afb77fec64b23573f2ee0f8577031"
  integrity sha512-5/vPxCY7jA4aiZ24Byf76GpdCfnB1EqlvmWMjZEGTrZv2e3Yq8UexjAzJaMO+Kf8CkC5lfstkdy9myE9EqFstg==
  dependencies:
    "@nestjs/mapped-types" "2.0.0"
    js-yaml "4.1.0"
    lodash "4.17.21"
    path-to-regexp "3.2.0"
    swagger-ui-dist "5.0.0"
```

and it started working.

we tried bumping only @nestjs/mapped-types, and swagger-ui-dist "5.0.0", which are the only diffs, and it worked just fine. It seems like the issue is with "@nestjs/swagger@^6.3.0".

but that doesn't make any sense, as far as I know a lib version can't have any changes after it's been already deployed.

**I haven't been able to reproduce it in another repo, but I am trying to, maybe this is related to some other library that we use that when used together with @nestjs/swagger` it breaks**

Anyway, I wanted to open the issue in case anyone has any ideas what may be wrong before I can create a reproduction.

### Minimum reproduction code

...

### Expected behavior

No issue happening when using this version.

### Package version

6.3.0

### NestJS version

9.4.2

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
