### ISSUE TITLE
Add Option to use RapiDoc instead of Swagger-UI

### ISSUE THREAD

**Issue by wodka** [nestjs/swagger#2595]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Cleaner interface that shows full models for openapi

### Describe the solution you'd like

https://rapidocweb.com/

Here an explanation of differences between RapiDoc / Redoc and Swagger UI: https://github.com/rapi-doc/RapiDoc/issues/141

I would not add redoc here as it misses a playground / try out functionality.

### Teachability, documentation, adoption, migration strategy

I am thinking about something like: 

```ts
import { NestFactory } from '@nestjs/core';
import { RapiDocModule, DocumentBuilder } from '@nestjs/swagger';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const config = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
  const document = RapiDocModule.createDocument(app, config);
  RapiDocModule.setup('api', app, document);

  await app.listen(3000);
}
bootstrap();
```

### What is the motivation / use case for changing the behavior?

Cleaner interface that shows full models without to many clicks

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.

**Comment by kamilmysliwiec** [comment]
https://github.com/ojoanalogo/nestjs-redoc
