### ISSUE TITLE
Support dynamic type definition

### ISSUE THREAD

**Issue by RDeluxe** [nestjs/swagger#26]
I would like to be able to do : 

``` javascript
@ApiResponse({ status: HttpStatus.OK, description: 'Returns token and logged user', type: { user: User, token: String } })
  @Post('login')
  public async login( @Body() loginInformation: { email: string, password: string }) {
    const user = await this.userService.login(loginInformation.email, loginInformation.password);
    const token = await this.authService.createToken(user);
    return { user, token };
  }
```

Sadly both types are not taken into account in Swagger.

**Comment by RDeluxe** [comment]
For now I created classes (but they are a bit redundant, as this is for documentation only). I took a look at the source code, I guess that's doable.

A support for Partial<User> would be awesome too.

**Comment by mildbreakfast** [comment]
I believe classes are the only way to go, as interfaces are not accessible at run-time.

**Comment by RDeluxe** [comment]
Alrighty
