### ISSUE TITLE
Swagger UI does not work with Firebase Functions (a 404 Error)

### ISSUE THREAD

**Issue by DesmondFox** [nestjs/swagger#2600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Opening http://127.0.0.1:5000/app follows with a 404 error. The page is blank.
I tried to pass another path ('', '/') but it did not work too.

![image](https://github.com/nestjs/swagger/assets/19652078/dd16953d-965e-4174-b6f1-ea6a8019caa8)

The site works via Firebase Hosting with redirecting to the Functions:

firebase.json:
```
    "rewrites": [
      {
        "source": "/app",
        "function": "api"
      }
    ]
```

### Minimum reproduction code

https://gist.github.com/DesmondFox/b9a70c0f38d8c1a9e28f2bc54435a573

### Steps to reproduce

`npm run build && firebase emulators:start`

### Expected behavior

Visiting http://127.0.0.1:5000/app displays the Swagger UI.

### Package version

7.1.9 (7.1.8 does not work propertly too)

### NestJS version

10.0.0

### Node.js version

18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
