### ISSUE TITLE
Support @Expose() and @Exclude() or allow custom @ApiHideProperty() decorators

### ISSUE THREAD

**Issue by kurt-west** [nestjs/swagger#2603]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

With the CLI plugin not supporting the class-transformer `@Expose` and `@Exclude` and `@ApiHideProperty()` not being composable the developer experience is less than it could be.  

### Describe the solution you'd like

The optimal - IMO - solution would be to add a class-transformer shim that scans for `Expose` like the class-validator shim does and extends the array of decorators (currently only `ApiHideProperty`) used to skip a property to include `Exclude`. I see this idea has been shutdown multiple times.

The other option would be to add a plugin configuration option `hidePropertiesDecoratedWith` that is an array of strings that will be ignored when the plugin is processing. The exclusion logic already exists ([hidePropertyDecorator](https://github.com/nestjs/swagger/blob/3cdfce3b1f98429ab40d3dae508d9b4fe427d92f/lib/plugin/visitors/model-class.visitor.ts#L149C35-L149C65)) and supports an array of strings. The plugin options are locally available in the method ([visitPropertyNodeDeclaration](https://github.com/nestjs/swagger/blob/3cdfce3b1f98429ab40d3dae508d9b4fe427d92f/lib/plugin/visitors/model-class.visitor.ts#L139)) used to decide if a property is annotated or not. 

### What is the motivation / use case for changing the behavior?

Using class-transformer for validation and serialization is at the core of NestJS it would be great to improve the DE so the swagger module is intergraded with these core concepts. Also, selfishly I'm sick of seeing `@Exclude()` and `@ApiHideProperty` side-by-side or missing `@ApiHideProperty` and the property being shown in the documentation.

I'm happy to do a PR to support either or both of these changes.

**Comment by kurt-west** [comment]
> > The optimal - IMO - solution would be to add a class-transformer shim that scans for Expose like the class-validator shim does and extends the array of decorators (currently only ApiHideProperty) used to skip a property to include Exclude. I see this idea has been shutdown multiple times.
> 
> Would you like to create a PR for this issue?

I would be happy to.

Would you be comfortable with an additional option `annotateDtoProperties` to enabled/disable the auto-annotate functionality? 

> > The optimal - IMO - solution would be to add a class-transformer shim that scans for Expose like the class-validator shim does and extends the array of decorators (currently only ApiHideProperty) used to skip a property to include Exclude. I see this idea has been shutdown multiple times.
> 
> Would you like to create a PR for this issue?

I definitely can and will, thank you.

**Comment by mateussaggin** [comment]
This is indeed extremely necessary.
@kurt-west did you have the opportunity to take a look and crate the PR?
