### ISSUE TITLE
Mapped Types not working in the webpack browser shim

### ISSUE THREAD

**Issue by maciejgoscinski** [nestjs/swagger#2610]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Mapped types do not work in the browser with the browser shim from https://github.com/nestjs/swagger/pull/1505

In the shim:
```
exports.PartialType = PartialType;
function PickType() {
    return () => { };
}
```
Usage as per docs:

```
export class UpdateCatDto extends PartialType(CreateCatDto) {}
```
Results in
```
Uncaught TypeError: Class extends value () => {} is not a constructor or null
```

### Describe the solution you'd like

DTOs should be usable outside of the backend.
The browser shim should at least properly return blank extendable classes to allow sharing the dto package with frontends.
Even better, the swagger annotations should be a separate module without dependencies on nestjs core etc.

### What is the motivation / use case for changing the behavior?

Using DTOs outside of the backend project.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? Replacing `return () => {}` with `return class {}` should be sufficient
