### ISSUE TITLE
Problem with double "$" sign in @ApiProperty example.

### ISSUE THREAD

**Issue by kusmierczykw** [nestjs/swagger#2626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I enter example for password, when I will use double $$ sign:

```typescript
@ApiProperty({
  example: 'pa$$w0rd',
  description: 'Hasło użytkownika',
})
@IsString()
public password: string;
 ```

After generate Swagger documentation we have:
<img width="1402" alt="image" src="https://github.com/nestjs/swagger/assets/18058760/24d0b07c-31b2-4197-8719-a1d3bc310436">

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-swagger-protect-express-2xdpvh?file=src%2Fapp.controller.ts

### Expected behavior

The same number of "$" characters as entered for the @ApiProperty example field.

### Package version

7.1.12

### NestJS version

10.2.5

### Node.js version

18.17.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by kusmierczykw** [comment]
In schema.json its correct value, but maybe swagger ui generate incorrect example.

**Comment by kamilmysliwiec** [comment]
![image](https://github.com/nestjs/swagger/assets/23244943/1095c35f-9b0f-4e3c-9e92-f9b4f7bf0267)

`/api-json` looks fine which means that this issue originates from [swagger-ui-dist](https://github.com/swagger-api/swagger-ui)

Could you report this issue in their repository?
