### ISSUE TITLE
Can't use nestjs/swagger plugin when using module": "NodeNext"

### ISSUE THREAD

**Issue by JonasVannieuwenhuijsen** [nestjs/swagger#2628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

- In tsconfig.json: "compilerOptions": {
    "module": "NodeNext",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "esnext",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "moduleResolution": "NodeNext",
  }

- in package.json: "type": "module"

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-i2qmu3?file=tsconfig.json

### Expected behavior

Docs generated through @Body and @ApiCreatedResponse({ type: UserTransformerResponse }) and no errors

### Package version

7.1.12

### NestJS version

10.2.4

### Node.js version

20.3.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/issues/1450
