### ISSUE TITLE
Duplicated query parameters inside swagger docs

### ISSUE THREAD

**Issue by emir7** [nestjs/swagger#2633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It seems like a combination of `@ApiQuery` and `@Query` decorator with a specific class validator object results in duplicated query parameter documentation. Code sample:

```
export class ExampleQueryDto {
  @IsOptional()
  @IsString()
  @ApiPropertyOptional({
    example: 'test',
  })
  public test: string;
}
```

```
  @Get()
  @ApiQuery({ type: ExampleQueryDto })
  public myRoute(@Query() exampleQueryDto: ExampleQueryDto) {
    return {
      m: 'ok',
    };
  }
```
The code above will produce an example object in swagger docs where property named "test" will be duplicated.
However, after omitting `@Query` from the function above generated docs are correct.
In this particular example I am explicitly defining api query parameters with the `@ApiQuery` decorator due to the fact that I have stumbled upon a problem where `@Query` did not register any parameters at all (the case being where we have multiple registered route modules).  

### Minimum reproduction code

https://github.com/emir7/nestjs-swagger-example

### Steps to reproduce

1. npm install
2. npm start
3. navigate to `http://localhost:3000/docs/example` (to view swagger ui) or `http://localhost:3000/docs/example-json` (to preview raw json object)

### Expected behavior

Inside the generated swagger docs provided example query object should include only fields listed inside `ExampleQueryDto` (property test should not be duplicated). 

### Package version

7.1.12

### NestJS version

9.0.0

### Node.js version

19.0.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [x] Linux

**Comment by iamnnort** [comment]
I have the same issue

**Comment by iamnnort** [comment]
Hey, @emir7 

I've had the same issue, just remove `@ApiQuery({ type: ExampleQueryDto })` and the error will gone. It duplicates because you define `ExampleQueryDto` twice: manually in `@ApiQuery` and automatically in `@Query()`.

**Comment by emir7** [comment]
Hi @iamnnort, 
I am afraid that sometimes `@Query` doesn't show any parameter at all. I think this might happen when importing routes from multiple different modules. I can also try to reproduce this bug in the same example repository I provided earlier and let you know if the issue still persists. (in my case simply removing `@ApiQuery` results in all the other routes to show 0 params)

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/issues/2633#issuecomment-1736382400
