### ISSUE TITLE
PickType ignore parent's @Transform when grandparent use @Transform

### ISSUE THREAD

**Issue by KuanWenChen** [nestjs/swagger#2659]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

My ValidationPipe setting is
```typescript
app.useGlobalPipes(new ValidationPipe({ transform: true }));
```

My Dto is 
```typescript
import { PickType } from '@nestjs/swagger';
import { Expose, Transform } from 'class-transformer';

export class TestDto1 {
  @Expose()
  @Transform(() => {
    console.log('TestDto1 Transform');
    return 1;
  })
  version!: number;
}

export class TestDto2 extends PickType(TestDto1, ['version']) {
  @Transform(() => {
    console.log('TestDto2 Transform');
    return 2;
  })
  version!: number;
}

export class TestDto3PickTypeVersion extends PickType(TestDto2, ['version']) {
  @Transform(() => {
    console.log('TestDto3 Transform');
    return 3;
  })
  version!: number;
}

export class TestDto3ExtendVersion extends TestDto2 {
  @Transform(() => {
    console.log('TestDto3 Transform');
    return 3;
  })
  version!: number;
}
```

My Controller is
```typescript
@Controller('test')
export class TestController {
  @Post('/pick-type-version')
  test1(@Body() testDto3PickTypeVersion: TestDto3PickTypeVersion) {
    return testDto3PickTypeVersion;
  }

  @Post('/extend-version')
  test2(@Body() testDto3ExtendVersion: TestDto3ExtendVersion) {
    return testDto3ExtendVersion;
  }
}
```

When I call 「http://localhost:3000/pick-type-version」
![image](https://github.com/nestjs/swagger/assets/63909422/6569e84a-7557-4a9e-8034-f80ea0f168f1)

TestDto3PickTypeVersion ignore TestDto2's @Transform.

When I call 「http://localhost:3000/extend-version」
![image](https://github.com/nestjs/swagger/assets/63909422/dcebbcb4-76bf-4546-a11f-22bbd0455fa2)

TestDto2's @Transform would work.

If I change TestDto1 as
```typescript
export class TestDto1 {
  @Expose()
  version!: number;
}
```
TestDto2's @Transform would be work too.

### Minimum reproduction code

https://github.com/KuanWenChen/swagger-issue

### Steps to reproduce

npm install
npm run start:dev

goto website http://localhost:3000/swagger
![image](https://github.com/nestjs/swagger/assets/63909422/778b128b-ba88-41d2-84f4-2fa4f7aa9aee)

Call Api and See log.

### Expected behavior

When I call「http://localhost:3000/pick-type-version」, I need to see 「TestDto2 Transform」

TestDto3PickTypeVersion should not ignore TestDto2's @Transform.

### Package version

^7.1.13

### NestJS version

10.2.7

### Node.js version

v18.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by KuanWenChen** [comment]
OK, I has found the problem is happen at mapped-types function [inheritTransformationMetadata](https://github.com/nestjs/swagger/blob/18cc84bf2ac4dd52cbe0bd8284ca60172308ebd4/lib/type-helpers/pick-type.helper.ts#L34)

The problem is occurring at [existingRules, and targetMetadataEntries are overwriting values taht with the same key](https://github.com/nestjs/mapped-types/blob/64b8889e4134e0261f3a6b39974347fde91ee5c7/lib/type-helpers.utils.ts#L156C15-L156C18) ; they should merge.

I have created [another issue](https://github.com/nestjs/mapped-types/issues/1212) for this problem.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/mapped-types/issues/1212
