### ISSUE TITLE
Add integrity hash on swagger-ui inline scripts

### ISSUE THREAD

**Issue by tafaust** [nestjs/swagger#2667]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I enabled CSP in my apps and I have issues with the redirect from `/oauth2-redirect.html` within my OIDC flow in swagger-ui for my non-prod workflows. My current workaround looks like this:
```
  let helmetOptions: Readonly<HelmetOptions> = {
    contentSecurityPolicy: {
      directives: {
        ...helmet.contentSecurityPolicy.getDefaultDirectives(),
        'default-src': ["'self'", 'token issuer url'],
        'script-src': ["'self'"],
        'connect-src': ["'self'", 'token issuer url'],
      },
    },
  };
  if (config.getOrThrow<string>('NODE_ENV') !== 'production') {
    helmetOptions = {
      contentSecurityPolicy: {
        directives: {
          ...helmet.contentSecurityPolicy.getDefaultDirectives(),
          'default-src': ["'self'", 'token issuer url'],
          'script-src': ["'self'", "'unsafe-inline'"],
          'connect-src': ["'self'", 'token issuer url'],
        },
      },
      crossOriginOpenerPolicy: {
        policy: 'unsafe-none',
      },
    };
  }

  app.use(helmet(helmetOptions));
```

### Describe the solution you'd like

I'd like to have the `integrity` attribute on the script tags as described in https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity.

https://github.com/nestjs/swagger/blob/c20bd9b361aff124e3f8d298c07d407654912d74/lib/swagger-ui/constants.ts#L73-L75

### Teachability, documentation, adoption, migration strategy

Users can use it as follows in their code when using CSP:
```
  let helmetOptions: Readonly<HelmetOptions> = {
    contentSecurityPolicy: {
      directives: {
        ...helmet.contentSecurityPolicy.getDefaultDirectives(),
        'default-src': ["'self'", 'token issuer url'],
        'script-src': ["'self'", "'shaXXX-XXXXXXXXXXXXXX...'"],
        'connect-src': ["'self'", 'token issuer url'],
      },
    },
    crossOriginOpenerPolicy: {
      policy: 'unsafe-none',
    },
  };
  app.use(helmet(helmetOptions));
```
where `shaXXX-XXXXXXXXXXXXXX...` resembles the integrity hash from the oauth2-redirect.html.

### What is the motivation / use case for changing the behavior?

As mentioned above, I want to use CSP headers and the swagger-ui is giving me a hard time with the inline scripts without the integrity hash that could be whitelisted in CSP.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by tafaust** [comment]
@kamilmysliwiec Yeah, do you want me to hardcode (= kind of a burden when the https://github.com/nestjs/swagger/blob/master/package.json#L31 dependency is upgraded) or dynamically compute the integrity (adds a new dependency https://github.com/zkat/ssri#from-data)?

**Comment by kamilmysliwiec** [comment]
I'd rather steer clear of adding more external dependencies to this package

**Comment by tafaust** [comment]
@kamilmysliwiec May I have some preliminary feedback on https://github.com/nestjs/swagger/pull/2680 before writing tests?

I am particularly interested about your thoughts for this commit: https://github.com/nestjs/swagger/pull/2680/commits/b29efb079b0ec05350af8201f5dce5a064f7e674

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2680
