### ISSUE TITLE
Expand extension support to Document and Schema objects

### ISSUE THREAD

**Issue by drewish** [nestjs/swagger#2683]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In https://github.com/nestjs/swagger/issues/195 partial support for extensions was added, but it didn't apply to some other places you'd commonly want to use it.

### Describe the solution you'd like

Extend https://github.com/nestjs/swagger/issues/195 to apply to the DocumentBuilder and Schema objects, rather than just Operations. 

### What is the motivation / use case for changing the behavior?

Trying to use [Redocly's extensions](https://redocly.com/docs/redoc/redoc-vendor-extensions/) on the top level Document (for [x-tag-groups](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tag-groups/)) and Schema  (for [x-tags](https://redocly.com/docs/api-reference-docs/specification-extensions/x-tags/)) objects.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2684

**Comment by drewish** [comment]
Yeah turned out to be easier than I thought to get the PR working.
