### ISSUE TITLE
classValidatorShim ignores class-validator decorators

### ISSUE THREAD

**Issue by its-dibo** [nestjs/swagger#2698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

decorators from class-validator are ignored by Nest

### Minimum reproduction code

.

### Steps to reproduce

1- add the plugin and enable `classValidatorShim`
```
   "plugins": [
      {
        "name": "@nestjs/swagger",
        "options": {
          "introspectComments": true,
          "classValidatorShim": true
        }
      }
    ]
```

2- create an entity, and attach `@IsEmail()` to a property
```
@Entity()
class Users{
  @Column({ unique: true })
  @IsMobilePhone()
  @Matches(/^\+/)
  mobile: string;
}
```
3- open swagger and create a new user (via a POST request) and perform an intented violations for the email field.
no one of the attached decorators from class-validation is working 
only `unique` is considered by TypeORM

### Expected behavior

the email violations are catched

### Package version

7.1.14

### NestJS version

10

### Node.js version

20

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
