### ISSUE TITLE
CLI plugin incompatible with application that uses ESM modules only

### ISSUE THREAD

**Issue by sr258** [nestjs/swagger#2715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My application uses ES modules (2022) only and I can't get the CLI plugin to work with this setup. The reason is that the plugin generates code like this in my generated `.js` files (the ):

```js
__decorate([
    Get(':provider/search/:query'),
    openapi.ApiResponse({ status: 200, type: [require("../common/image-search-result.dto").ImageSearchResult] }),
```
As `require` is not allowed in ESM modules, I get this error when starting nest (note that I use a custom esm-loader):

```
> nest start --exec 'node --loader=./esm-loader.js'

(node:173891) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("./esm-loader.js", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/sebastian/Dokumente/vocab2/packages/server/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

### Minimum reproduction code

https://github.com/sr258/esm-swagger-cli

### Steps to reproduce

1. npm i
2. npm start

### Expected behavior

The generated code uses ES imports.

### Package version

7.1.16

### NestJS version

10.2.9

### Node.js version

20.8.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
