### ISSUE TITLE
How can we create a "ApiModelProperty" for an Interface

### ISSUE THREAD

**Issue by naithagoni** [nestjs/swagger#273]
I have an interface something like this:
**test.interface.ts**
```
import {IValues} from './values.interface';

export interface ITest {
   name: (string | IValues);
}
```
Here, ```name``` sometimes be a 'string' or an 'object'.
Where as, ```IValues``` an another object:
**values.interface.ts**
```
export interface IValues {
   age: number;
}
```
How can I create a ```ApiModelProperty``` for an Interface like ```ITest```?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/issues/191
