### ISSUE TITLE
Parameter not marked as optional, when using optional type

### ISSUE THREAD

**Issue by paulwer** [nestjs/swagger#2732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

  I provide an additional parameter to the ApiProperty Decorator, to achieve the right behavior.

```
  @ApiProperty({ required: false }) // isOptional is not reconized by swagger in this case?!
  @IsOptional()
  @IsObject()
  meta?: {
    [key: string]: any;
  }
```

### Minimum reproduction code

none? but I can provide, if realy needed

### Steps to reproduce

1. create a DTO with a property with dynamic keys.
2. view output of swagger-file

### Expected behavior

should detect, that the parameter is optional.

### Package version

7.1.16

### NestJS version

10.2.10

### Node.js version

18.16.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by paulwer** [comment]
https://stackblitz.com/edit/nestjs-typescript-starter-hevk9d?file=src%2Ftest%2Fdto%2Fcreate-test.dto.ts
