### ISSUE TITLE
[feature]add Two new features by fastify

### ISSUE THREAD

**Issue by wintsa123** [nestjs/swagger#2743]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

1. Unable to export and generate interface documentation in fastify,i use @nestjs/swagger @fastify/swagger. (word/json/pdf/yaml)
2. I think we can add some password protection, before using swagger, you need to log in with a password if it's not local access

### Describe the solution you'd like

1.add password protection
2.add export and generate interface documentation in fastify

### What is the motivation / use case for changing the behavior?

In the project handover, I want to produce documents to the party, I can not open the whole swagger port, I want to share some interfaces to generate documents

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
