### ISSUE TITLE
swagger has some problem

### ISSUE THREAD

**Issue by techaks** [nestjs/swagger#277]
> the "swagger-ui-express" package is missing. Please, make sure to install this library ($ npm install swagger-ui-express) to take advantage of SwaggerModule.

i have installed many time  still not working 

```
    "@nestjs/swagger": "^3.0.2",
 "swagger-ui-express": "^4.0.6",
```

**Comment by techaks** [comment]
@ofavre @crdrost @vkartaviy @mrgusev

**Comment by zodiac1214** [comment]
@techaks  do you have "@storybook/react" in dependency? I had the same issue and find that @storybook/react is somehow conflict with swagger-ui-express... i am not sure why (will take a look when i got time), but remove @storybook/react fixed the issue for me.

FYI, this only happens to me when i use "yarn install --production", it works fine with "yarn install"

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
