### ISSUE TITLE
ApiHeader overwrites schema type

### ISSUE THREAD

**Issue by fermentfan** [nestjs/swagger#2771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The API header options type tells me there is a `$schema.type` option that I can pass OpenAPI Data types to. Sadly it overwrites the type always with `string`. It doesn't seem like this is needed and just limits us from using accurate types here?

Code where it happens:
https://github.com/nestjs/swagger/blob/2d999bd8940e6254755d9c5e7665b773bfb475aa/lib/decorators/api-header.decorator.ts#L30C1-L30C23

### Minimum reproduction code

https://github.com/nestjs/swagger

### Expected behavior

I'd expect it to respect the user given type when building the OpenAPI yaml.

### Package version

7.1.15

### NestJS version

10.2.1

### Node.js version

9.8.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

Please allow me to submit more simple bug reports

**Comment by dotenorio** [comment]
🆙

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2774
