### ISSUE TITLE
Wrong Behavior at @Query Optional Parameter

### ISSUE THREAD

**Issue by ruslanguns** [nestjs/swagger#280]
## Current behavior

I have created a request which I expect that could receive a **OPTIONAL** parameter via the @Query() decorator, however I get this error when parameter `limit` is undefined: 
```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "No data submitted"
}
```

## Input Code

```typescript
    @Get('myMethod')
    async myMethod(
        @Query('limit') limit?: number,
    ): Promise<void> {
        if (limit === undefined) {
            console.log(`Limit undefined is: ${limit}`); // undefined
        } else {
            console.log(`Limit defined is: ${limit}`);
        }
    }
```

## Expected behavior

First I expect that this ? symbol at `@Query('limit') limit?: number,` works as to mark the parameter as optional. Then: I expect to receive the proper console log when is undefined or not.

Also I want to initialize it with some value. BUT is not really important at the moment.
```typescript
@Query('limit') limit?: number = 0, // BUT I GET A RED ERROR WITH TSLINT
```

## Environment

<pre><code>
Nest version: 6.5.0

 
For Tooling issues:
- Node version: v12.3.1  
- NPM version: 6.9.2
- Platform:  Windows

</code></pre>

**Comment by ruslanguns** [comment]
@kamilmysliwiec I didn't know that it was related to swagger since the use of the decorator: @Query ...

**Comment by ruslanguns** [comment]
Thanks to @hellraisercenobit and @ThomRick I found a work around passing DTO Validations to query params.

For anyone who would need to know more about it I put my code here.

Controllers:
```ts
    @Get('test/queryDto')
    async queryDto(
        @Query() query: QueryDTO,
    ) {
        if (!query.limit) {
            console.log(`Limit undefined is: ${query.limit}`); // undefined
        } else {
            console.log(`Limit defined is: ${query.limit}`);
        }
    }
```

@Query decorator requires DTO transform for limit:

QueryDTO:
```ts
import { Optional } from '@nestjs/common';
import { Transform } from 'class-transformer';

export class QueryDTO {
    @Optional()
    @Transform(limit => {
        limit = Number(limit);
        if (isNaN(limit)) { return limit = 0; }
        return limit;
    })
    limit: number = 0;
}
```

To permit transformation we have to add GlobalPipes on bootstrap:

main.ts:
```ts
...
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.useGlobalPipes(new ValidationPipe({
    transform: true,
  }));
...
```

**Comment by kamilmysliwiec** [comment]
Swagger cannot recognize whether your parameter is optional or not (TypeScript doesn't leave metadata about this) and thus, every query parameter is required by default. In order to forcefully make it optional, you have to use `@ApiImplicitQuery()`.
