### ISSUE TITLE
Enums with enumName field and additional fields generate non-functional swagger file

### ISSUE THREAD

**Issue by Algram** [nestjs/swagger#2806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you have a look at my gist, I added additional fields like `deprecated` or `description` to an enum that also has `enumName`.
In this case, the resulting swagger file is not really functional since as per swagger specification, siblings to refs get ignored completely: https://swagger.io/docs/specification/using-ref/#sibling

Since there is no way to use decorators with enums, it is currently impossible to be swagger-spec compliant. I think the generation would have to move the additional fields to the referenced enum instead of keeping it in place.

### Minimum reproduction code

https://gist.github.com/Algram/5e95133afd8750bd4f936cd846f51639

### Expected behavior

The additional fields are part of the referenced enum.

### Package version

7.2.0

### NestJS version

10.3.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/2816
