### ISSUE TITLE
typeorm: 0.3.20 introduces issues with @ApiProperty on some DTOs

### ISSUE THREAD

**Issue by OSA413** [nestjs/swagger#2811]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

So, I recently updated packages and Swagger started to throw errors related to @ApiProperty (Optional) and circular dependency though a week ago it was just fine.

After investigation I figured out that downgrading typeorm from 0.3.20 to 0.3.19 fixes the issue.

### Minimum reproduction code

https://github.com/OSA413/nestjs-bug-swagger-api-property

### Expected behavior

For the error to not be thrown.

### Other

Some more details of the issue can be found in NestJS' Discord and in this issue:

https://github.com/typeorm/typeorm/issues/10671

**Comment by micalevisk** [comment]
we can close this as this is not related to `@nestjs/swagger` but `typeorm` 0.3.20

**Comment by OSA413** [comment]
> we can close this as this is not related to `@nestjs/swagger` but `typeorm` 0.3.20

As you mentioned in the [comment](https://github.com/typeorm/typeorm/issues/10671#issuecomment-1921086848), this may be related to updating `reflect-metadata`.

**Comment by OSA413** [comment]
Looks like this issue is related to other issues with the update of `reflect-metadata` like:
* https://github.com/nestjs/nest/issues/13107
* https://github.com/nestjs/nest/issues/13146

**Comment by OSA413** [comment]
I guess that this issue can be closed as duplicate of https://github.com/nestjs/nest/issues/13107

Dev response: https://github.com/nestjs/nest/issues/13107#issuecomment-1921234278

Explanation and temporal fix: https://github.com/nestjs/nest/issues/13107#issuecomment-1921364281

**Comment by OSA413** [comment]
Fixed with 
```
"@nestjs/common": "^10.3.2",
"@nestjs/core": "^10.3.2",
```
