### ISSUE TITLE
Allow multiple schemas with same name

### ISSUE THREAD

**Issue by bc-m** [nestjs/swagger#2826]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In our project we reuse name patterns like "FindOneDto" or "FindAllDto". We now have the problem that the Swagger docs reuse one of the DTOs (perhaps the first one calculated) and display the same DTO as schema in all places where a different DTO with the same name should be displayed.

### Describe the solution you'd like

Maybe a solution like in [NestJS v8](https://github.com/nestjs/nest/releases/tag/v8.0.0) is possible, where the class reference is used as key instead the name.

Or the build process should throw a warning/error if unique schema names are still required. Now the build will continue with an incorrect result.

### Teachability, documentation, adoption, migration strategy

Mention as new feature (or bugfix?) in changelog.

### What is the motivation / use case for changing the behavior?

Avoidance of a pitfall for nestjs-swagger users.

**Comment by Stono** [comment]
Ahh this is exactly the issue i'm having (associated issue: https://github.com/hey-api/openapi-ts/issues/42).

You can see here using the metadata generation we have two controllers that both implement their own `ListDeviceResponse`:

<img width="647" alt="Screenshot 2024-04-17 at 08 22 50" src="https://github.com/nestjs/swagger/assets/1486729/2664f4f3-dce5-4607-9660-a1b032b2c4a0">

This subsequently means the swagger actually only ends up with a single definition, which as @bc-m pointed out looks to be the first one.

<img width="356" alt="Screenshot 2024-04-17 at 08 23 43" src="https://github.com/nestjs/swagger/assets/1486729/75a9f66d-e873-4053-a6e6-2fe0a182bd76">

Which then obviously leads to downstream issues when clients are generated from the swagger etc, they're returning the wrong types.

This is a frustrating gotcha/limitation that will totally catch people off guard, as it doesn't result in any sort of compilation error or warning.  For now i'm going to try and write some sort of linting to enforce dto names are unique across a project.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/2427

**Comment by Stono** [comment]
:wave: @kamilmysliwiec - thanks for doing this, I still think the problem will bite people.

`@ApiSchema` certainly allows you to control the type name, however it still relies on a dev to realise they have a type name conflict in the first place.  More common I find is that an app with many controllers will have an overlapping DTO by chance, and the devs completely unaware that the type was basically FIFO.

Instead I feel it'd be great to have an option, which when turned on, ensure that type definitions were never shared?  Like automatically prefixed with the OperationId?  It'd lead to more duplication for sure, but it'd guarantee you never got accidental conflict.
