### ISSUE TITLE
[Map] When using additional property with a map, objects transformation is broken

### ISSUE THREAD

**Issue by SergioArrighi** [nestjs/swagger#2833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I define two objects.

A basic one with a single property marker with **@Excluded**
<img width="500" alt="image" src="https://github.com/nestjs/swagger/assets/10941512/f432895d-1656-448d-a6ba-57e49c82a2c6">

And a container one with a Map property <string, Think> (an index)
<img width="643" alt="image" src="https://github.com/nestjs/swagger/assets/10941512/4198abd5-a05d-4a80-9e24-1b313889c82d">

Then I return a dummy object from the controller
<img width="365" alt="image" src="https://github.com/nestjs/swagger/assets/10941512/87280e40-2ebf-4e90-8e45-b93441a753d2">

The swagger doc looks like this
<img width="585" alt="image" src="https://github.com/nestjs/swagger/assets/10941512/6596b679-2f23-4f6d-87c3-f9de6d553930">

And the output
<img width="127" alt="image" src="https://github.com/nestjs/swagger/assets/10941512/b52e5104-437a-4970-b101-8961ce507c4c">

In both the id field, marked as excluded, is displayed.

If you use an array
**Thing[]**
You will see that exclusion is correctly perfomed

### Minimum reproduction code

https://gist.github.com/SergioArrighi/8c239e2f7e4e4f5f34261c95470b6b90

### Steps to reproduce

1. Create nest app: nest new things
2. Add two provided files: **thing.ts** and **things.ts**
3. In the controller add /test endpoint from file **things.controller.ts**
4. Check specs and output

### Expected behavior

I would expect that fields tagged with @Exclude are hidden in this case too

### Package version

7.1.17

### NestJS version

10.0.0

### Node.js version

16.19.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Thanks for the awesome library!

**Comment by kamilmysliwiec** [comment]
> I would expect that fields tagged with @exclude are hidden in this case too

Fields with `@Exlude` are generally not hidden in any case. `@nestjs/swagger` does not even take them into account unless you use a NestJS CLI Plugin with non-default settings 

From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
