### ISSUE TITLE
PartialType can lead to 500 Internal Server Error

### ISSUE THREAD

**Issue by KuanWenChen** [nestjs/swagger#2843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Issue [nestjs/swagger#2623](https://github.com/nestjs/swagger/issues/2623) has not been fixed in nestjs/swagger.
nestjs/mapped-types added the option [skipNullProperties](https://github.com/nestjs/mapped-types/pull/1274/commits/981c4cad0291fcdfe72c2535791d6bbdea5b3b3a) to PartialType, but [nestjs/swagger did not](https://github.com/nestjs/swagger/blob/master/lib/type-helpers/partial-type.helper.ts).

### Minimum reproduction code

https://github.com/KuanWenChen/swagger-issue

### Steps to reproduce

1. npm install
2. npm run start:dev
3. go to website http://localhost:3000/swagger
4. POST /test/should-not-nullable with payload {"value": null}

### Expected behavior

It should throw BadRequestError with error message "value must be a number conforming to the specified constraints"

### Package version

7.3.0

### NestJS version

10.3.3

### Node.js version

v20.9.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
