### ISSUE TITLE
The file upload example in the official document is not working properly

### ISSUE THREAD

**Issue by dongwa** [nestjs/swagger#2846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/nestjs/swagger/assets/38457491/8b7d0635-1762-460a-8402-4124628fe59b)

![image](https://github.com/nestjs/swagger/assets/38457491/582e14bd-c3b6-4545-9ec8-33b36438c30e)

The example in the official document is not working properly

Error: A circular dependency has been detected (property key: "file"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").

### Minimum reproduction code

https://docs.nestjs.com/openapi/operations#file-upload

### Expected behavior

`npm run start:dev` work will and swagger can  upload file

### Package version

7.3.0 

### NestJS version

10.3.3

### Node.js version

18.19.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by dongwa** [comment]
I solved this problem by modifying "reflect-metadata": "^0.1.13" to "reflect-metadata": "^0.2.1" .
