### ISSUE TITLE
Include for controllers instead of modules

### ISSUE THREAD

**Issue by kareemalkoul** [nestjs/swagger#2850]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

 My modules are shared for admin and user and I want to create two swagger API like in the [docs](https://docs.nestjs.com/openapi/other-features#multiple-specifications) one for admin and another for user, so i want to make the include functionality for **controllers** instead of **modules**

### Describe the solution you'd like

i would to do 
```
  const document = SwaggerModule.createDocument(app, config, {
    include: [PostController],
  });
  ```

### What is the motivation / use case for changing the behavior?

Make the include functionality for **controllers** instead of **modules**

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
