### ISSUE TITLE
When I use SWC compilation, the service will restart twice

### ISSUE THREAD

**Issue by liaorg** [nestjs/swagger#2868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

nest start -w -b swc --type-check

![$EUQ@OD$3@{HS60EF4}$ACQ](https://github.com/nestjs/swagger/assets/7478660/6e0e30f0-3d5e-45ac-984a-85c69e8661e2)

### Minimum reproduction code

https://github.com/liaorg/dasplus

### Expected behavior

restart once

### Package version

^7.3.0

### NestJS version

^10.3.3

### Node.js version

v18.14.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by liaorg** [comment]
DTO not recognized in the document
![2$IO ID70 BPN8TQ6C8}_VE](https://github.com/nestjs/swagger/assets/7478660/8c2799f7-657d-43c1-98e0-9612b5bcca81)

**Comment by liaorg** [comment]
nest-cli.json

....
"plugins": [
            {
                "name": "@nestjs/swagger",
                "options": {
                    "dtoFileNameSuffix": [".dto.ts"],
                    "classValidatorShim": false,
                    "introspectComments": true,
                    "controllerKeyOfComment": "summary",
                    "debug": false
                }
            }
        ]
....

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
