### ISSUE TITLE
properties decorated with `@ApiHideProperty()` are being displayed in swagger UI

### ISSUE THREAD

**Issue by its-dibo** [nestjs/swagger#2901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use `@ApiHideProperty()` to decorate some properties, but I see them displayed in swagger UI

this is my Entity
```
@Entity('users')
export class UserEntity {
  @PrimaryGeneratedColumn('uuid')
  @ApiHideProperty()
  @Exclude()
  id: string;

// other props
}
```

this is Swagger setup
```
 let app = await NestFactory.create(AppModule);
 let swaggerConfig = new DocumentBuilder() .build();
 let document = SwaggerModule.createDocument(app, swaggerConfig);
 SwaggerModule.setup('', app, document);
app.listen(3000)
```

### Minimum reproduction code

.

### Expected behavior

the `id` property is hidden from the schema, particularly when creating a resource i.e. `POST /users`

![image](https://github.com/nestjs/swagger/assets/57308531/a90ac4da-2f3e-4188-9d9b-f6a3d38509d7)

### Package version

7.1.16

### NestJS version

10.2.10

### Node.js version

20.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
