### ISSUE TITLE
Detect schema in monorepo

### ISSUE THREAD

**Issue by asijoumi** [nestjs/swagger#2905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi !

Thank you for this repository. However, I have an issue using monorepo.

As you can see in the example code, Swagger can detect classes inside the api apps. However, it cannot detects classes from libraries.

```typescript
const app = await NestFactory.create(ApiModule);

const config = new DocumentBuilder().build();

const document = SwaggerModule.createDocument(app, config);
SwaggerModule.setup('doc', app, document);
```

Here, we initialize the app and pass it to the swagger document. I understand why Swagger cannot detect library classes, but How can we add an other app ?

For example, something like that : 

```typescript
const app = await NestFactory.create(ApiModule);
const database = await NestFactory.create(DatabaseModule); // External library

const config = new DocumentBuilder().build();

const document = SwaggerModule.createDocument([app, database], config);
SwaggerModule.setup('doc', [app, database], document);
```

Is that realistic ?

### Minimum reproduction code

https://github.com/asijoumi/swagger-monorepo

### Steps to reproduce

1. `npm i`
2. `npm start:dev`
3. Go to `http://localhost:3000/doc`

### Expected behavior

We expect Swagger detects classes from libraries.

### Package version

7.3.1

### NestJS version

10.0.0

### Node.js version

18.19.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
