### ISSUE TITLE
Swagger decorator @ApiHeader is not including header on request

### ISSUE THREAD

**Issue by douglasjunior** [nestjs/swagger#2906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Swagger decorator @ApiHeader is not including header on request

## Code

```ts
@Controller('template')
export class TemplateController {

  @Get('test')
  @ApiHeader({
    name: 'accept',
  })
  async test(@Headers('accept') acceptHeader: string) {

    return `ok: ${acceptHeader}`;
  }

}
```

## Result

![image](https://github.com/nestjs/nest/assets/1512341/1a544741-bd61-4617-b23a-5f35750c37f7)

### Minimum reproduction code

https://codesandbox.io/p/devbox/green-cache-5xjgvc

### Steps to reproduce

Just create a new NestJS project and add a new Controller like `TemplateController` above.

### Expected behavior

Expect that Swagger UI to include the proper `accept` value on request.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/swagger

### NestJS version

10.3.3

### Packages versions

```json
    "@nestjs/common": "10.3.3",
    "@nestjs/config": "3.2.0",
    "@nestjs/core": "10.3.3",
    "@nestjs/platform-express": "10.3.3",
    "@nestjs/swagger": "7.3.0",
    "class-transformer": "0.5.1",
    "class-validator": "0.14.1",
```

### Node.js version

18.12.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by letsaguiar** [comment]
this problem is specifically related to the 'accept' header. It works fine with other headers, but it doesn't with the accept header

![Screenshot from 2024-04-15 11-16-52](https://github.com/nestjs/swagger/assets/26053703/a7ad4386-44cb-4290-8b63-f4924471ae5e)

![Screenshot from 2024-04-15 11-17-20](https://github.com/nestjs/swagger/assets/26053703/e0e64b37-633d-493b-b3a4-2d4c9a7bd720)

**Comment by douglasjunior** [comment]
Confirmed in the provided example: https://codesandbox.io/p/devbox/green-cache-5xjgvc

![image](https://github.com/nestjs/swagger/assets/1512341/3911de08-cd3a-4bf6-bdfd-e264535205d4)

**Comment by micalevisk** [comment]
the OpenAPI spec generated looks like this:

```yaml
openapi: 3.0.0
paths:
  /test:
    get:
      operationId: AppController_test
      parameters:
        - name: accept
          required: true
          in: header
          schema:
            type: string
      responses:
        '200':
          description: ''
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
tags:
  - name: cats
    description: ''
servers: []
components:
  schemas: {}
```

![image](https://github.com/user-attachments/assets/1398ac23-5a6e-4c3f-beb5-de8cd4e270ba)

And this is related with https://github.com/swagger-api/swagger-ui/issues/5567

**Comment by micalevisk** [comment]
so according with the spec, we are not supposed to define `"Accept"` ourselves. So I'd say that this is more a misuse of `@ApiHeader()` than a bug on `@nestjs/swagger` 

![image](https://github.com/user-attachments/assets/dd016a13-bd57-4fb3-b3ab-dc448db8927f)
