### ISSUE TITLE
@ApiProperty() enum can display keys in the UI instead of just values.

### ISSUE THREAD

**Issue by mstar-kk** [nestjs/swagger#2914]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

enum define 
```
enum ReplyStatusEnum {
  STATELESS = 0,
  REPLIED = 1,
  CONTENT_FILTER = 2,
  RATE_FILTER = 3,
}
```
Request Body define
```
class BodyDto {
  @IsOptional()
  @IsEnum(ReplyStatusEnum)
  @ApiProperty({ description: '', enum: ReplyStatusEnum, required: false, type: 'array', enumName: 'ReplyStatusEnum' })
  replyStatus: ReplyStatusEnum;
}
```
swagger ui
![image](https://github.com/nestjs/swagger/assets/18113203/14f948ce-6cc1-4848-bcb7-53867762ab69)

### Describe the solution you'd like

Is it possible to display key values in the UI, rather than just the values, enabling API documentation readers to clearly understand the meaning of each?
![image](https://github.com/nestjs/swagger/assets/18113203/8176cfbb-106c-4f2a-8cce-967702d62633)

### What is the motivation / use case for changing the behavior?

Enhance the UI reading experience for better comprehension.

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the swagger-ui-dist repository
