### ISSUE TITLE
'name' is specified more than once, so this usage will be overwritten.

### ISSUE THREAD

**Issue by icazemier** [nestjs/swagger#2921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

I am not sure, but it seems according to the types in this piece of code in the `@ApiParam()` decorator:

```typescript
  const param: ApiParamMetadata & Record<string, any> = {
    name: isNil(options.name) ? defaultParamOptions.name : options.name,  // <=== redundant?
    in: 'path',
    ...omit(options, 'enum') // <=== As this will overwrite param.name in any case?
  };
```

because when I use this code, my linter is complaining about:
<img width="640" alt="image" src="https://github.com/nestjs/swagger/assets/64091093/f570bf8c-e12a-4998-8615-828d4c0821cb">

In current master: https://github.com/nestjs/swagger/blob/master/lib/decorators/api-param.decorator.ts
Commit: f2bc18a3706dedee4455ebb52129721d1fadd287

### Minimum reproduction code

https://github.com/nestjs/swagger/blob/master/lib/decorators/api-param.decorator.ts

### Steps to reproduce

1. I copied code over to our code base
2. Linter shows issue

### Expected behavior

No linter issues 😅

### Package version

^7.3.1

### NestJS version

^10.3.7

### Node.js version

20.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

- VSCode
- Yarn

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
