### ISSUE TITLE
NestJS 10 is incorrectly parsing the jsdocs comments to generate swagger docs

### ISSUE THREAD

**Issue by samaratungajs** [nestjs/swagger#2927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We are upgrading our app from NestJS9 to NestJS10. While doing the upgrade we noticed the following. As in the Screenshot now the JSDocs comments are parsed as just literals and include @ type & @ memberof in the swagger doc this worked fine before v10 of NestJS creating swagger docs without messing up with other jsdocs attributes.

Upgraded @nestjs/swagger v 6.0.4 to 7.3.1

<img width="1340" alt="Screenshot 2024-04-24 at 12 26 21" src="https://github.com/nestjs/swagger/assets/68687791/59dded8c-f38f-4022-82a5-65a7ab8123ef">

cli config
```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/swagger",
        "options": {
          "classValidatorShim": true,
          "introspectComments": true
        }
      }
    ]
  }
}
```
affected jsdoc
```typescript
export class UserListFilterDto extends OffsetPaginationBaseDto {
  /**
   * Filter users by firstname lastname or email
   * @example 'q'
   * @type {string}
   * @memberof UserListFilterDto
   */
  @IsOptional()
  @IsString()
  query?: string;

  /**
   * Filter by user role
   *
   * @type {Roles}
   * @memberof UserListFilterDto
   */
  @IsOptional()
  @IsEnum(Roles)
  role?: Roles;

  /**
   * Sort users, defaulted to `desc` by `created at`
   *
   * @type {SortOrder}
   * @memberof UserListFilterDto
   */
  @IsOptional()
  @IsEnum(SortOrder)
  order?: SortOrder = SortOrder.DESC;

  /**
   * Sort users
   *
   * @type {UserListSortBy}
   * @memberof UserListFilterDto
   */
  @IsOptional()
  @IsEnum(UserListSortBy)
  sortBy?: UserListSortBy = UserListSortBy.CREATED_AT;
}
```

### Minimum reproduction code

https://gist.github.com/samaratungajs/79efceb03d722c66cf17b40e096f217a

### Expected behavior

swagger docs without unnecessary literals

behavior before upgrade 
<img width="1275" alt="Screenshot 2024-04-24 at 12 21 05" src="https://github.com/nestjs/swagger/assets/68687791/665c7eac-2f79-4c40-a07d-bb265587fe59">
literal

### Package version

7.3.1

### NestJS version

10.3.7

### Node.js version

20.12.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I just tested with nestjs v10 (`@nestjs/swagger@7`) and nestjs v9 (`@nestjs/swagger@6`)

![image](https://github.com/user-attachments/assets/49b388f2-d8f4-4ff1-bfe3-b438ca50f9cd)
![image](https://github.com/user-attachments/assets/0eb6ea35-63df-446d-9315-b7e20f6a175b)

So I don't think that this is a regression
