### ISSUE TITLE
Oauth2 Redirect url not working correctly without trailing path

### ISSUE THREAD

**Issue by descampsk** [nestjs/swagger#2939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If the swagger path is `docs`, the redirect url is `redirect_uri=https%3A%2F%2Fv9r2t3-3000.csb.app%2FFoauth2-redirect.html`  but it should be `redirect_uri=https%3A%2F%2Fv9r2t3-3000.csb.app%2Fdocs%2Foauth2-redirect.html`

It works if the path is `docs/`

### Minimum reproduction code

https://codesandbox.io/p/devbox/swagger-oauth2-issue-v9r2t3

### Steps to reproduce

Create a swagger with the following configuration

```ts
  const issuerBaseUrl = "https://kevindescamps.eu.auth0.com"
  const audience = "https://nestjs-playground.kevindescamps.com"
  const clientId = "clientId"

  const swaggerConfig = new DocumentBuilder()
    .setTitle('API')
    .setDescription('API')
    .setVersion('1.0')
    .addOAuth2(
      {
        type: 'oauth2',
        scheme: 'bearer',
        in: 'header',
        bearerFormat: 'JWT',
        flows: {
          implicit: {
            authorizationUrl: `${issuerBaseUrl}/authorize?audience=${audience}`,
            tokenUrl: `${issuerBaseUrl}/oauth/token`,
            scopes: {
              openid: 'openid',
            },
          },
        },
      },
      'Auth0',
    )
    .build();

  const document = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup('docs/', app, document, {
    swaggerOptions: {
      initOAuth: {
        clientId,
      },
    },
  });
```

### Expected behavior

The redirect url shoud be correct even if there is no trailing slash at the end.

### Package version

7.3.1

### NestJS version

10.3.2

### Node.js version

20.x

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the swagger-ui-dist repository
