### ISSUE TITLE
Wrong swagger generation for @Query with array of objects

### ISSUE THREAD

**Issue by wilker7ribeiro** [nestjs/swagger#2945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to create a GET endpoint with a inner object inside query params:

``` typescript
export class QueryParamsSubObject {
  @ApiProperty()
  subObjectStringParam: string;
}

export class QueryParams {
  @ApiProperty()
  stringParam: string;

  @ApiProperty({ type: QueryParamsSubObject })
  subObject: QueryParamsSubObject;
}

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('/bugged')
  getHelloBugged(@Query() queryParams: QueryParams): string {
    console.log(queryParams);
    return this.appService.getHello();
  }
}
```

The swagger definition is bugged, having all parameters from `QueryParamsSubObject` inside `QueryParams` instead of `QueryParams.subObject`:

![image](https://github.com/nestjs/swagger/assets/21000731/dbcdfe0c-ed2d-4ad4-83cc-07defd972956)

The definition is generated correctly when using `@ApiQuery` instead of `@Query`:

```typescript
@Get('/correct')
@ApiQuery({
  type: QueryParams,
})
getCorrectlyGenerated(): string {
  return this.appService.getHello();
}
```
![image](https://github.com/nestjs/swagger/assets/21000731/4c15ae2a-f80e-4873-b46a-0e5218428de1)

### Minimum reproduction code

[Codesandbox](https://codesandbox.io/p/devbox/pedantic-tess-dhxjwl?file=%2Fsrc%2Fmain.ts%3A13%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvze56ju00073j6iktrk1rzz%2522%252C%2522sizes%2522%253A%255B88.7571921749137%252C11.242807825086302%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvze56ju00023j6iqm6ipkut%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvze56ju00043j6i60pk8c98%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvze56ju00063j6ict7jdnsn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvze56ju00023j6iqm6ipkut%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvze56jt00013j6i20820cug%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvzewa5601tn3j6grglofoyd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A14%257D%255D%257D%255D%252C%2522id%2522%253A%2522clvze56ju00023j6iqm6ipkut%2522%252C%2522activeTabId%2522%253A%2522clvzewa5601tn3j6grglofoyd%2522%257D%252C%2522clvze56ju00063j6ict7jdnsn%2522%253A%257B%2522id%2522%253A%2522clvze56ju00063j6ict7jdnsn%2522%252C%2522activeTabId%2522%253A%2522clvzeojes00zs3j6go2kti5wn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clvzeojes00zs3j6go2kti5wn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fapi%2523%252Fdefault%252FAppController_getCorrectlyGenerated%2522%257D%255D%257D%252C%2522clvze56ju00043j6i60pk8c98%2522%253A%257B%2522id%2522%253A%2522clvze56ju00043j6i60pk8c98%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvze56ju00033j6iubihfpjj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvze56ju00033j6iubihfpjj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
https://github.com/wilker7ribeiro/nest-swagger-query-object-param-issue

### Steps to reproduce

1. `npm install`
2. `npm start`
3. open `http://localhost:3000/api`

### Expected behavior

`@Query` should correctly generate the swagger definition as `@ApiQuery` does.

### Package version

7.3.1

### NestJS version

10.3.2

### Node.js version

10.3.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by wonderbeel** [comment]
Can confirm this issue too, experimenting a little I found out that basically it is flattening too much: I forked OP repro to show it ( https://codesandbox.io/p/github/wonderbeel/nest-swagger-query-object-param-issue/ and https://github.com/wonderbeel/nest-swagger-query-object-param-issue ).

**Comment by satokenta940** [comment]
Have you resolved the issue yet? I am currently using [Apidog ](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1)to generate API documentation, and it's working well for me.

**Comment by abdulkaderelrawas** [comment]
I have a FilterDto like so

`class FilterDto {
  @IsString()
  column: string;

  @IsEnum({
    equals: 'equals',
    neq: 'not',
    gt: 'gt',
    lt: 'lt',
    gte: 'gte',
    lte: 'lte',
    in: 'in',
    nin: 'not',
  })
  operator: string;

  @IsString()
  value: string;
}`

and an Query param like so 

`
  @ApiProperty({ type: FilterDto, isArray: true })
  @IsOptional()
  @IsArray()
  @Type(() => FilterDto)
  @ValidateNested({ each: true })
  readonly filters: FilterDto[];
 `
 
 This doesn't generate it right unless i put the FilterDto in an array `@ApiProperty({ type: [FilterDto], isArray: true })`, and when i do it puts it as an array of arrays instead of array of objects
 
 I tried   `@ApiProperty({ type: [FilterDto] })`, doesn't work
 I tried to specify the type inside, doesn't work
 I tried to auto generate it using the plugin in nestcli, doesn't work
 
 any news about this?

**Comment by marefati110** [comment]
I have same issue.

**Comment by sixtusDev** [comment]
I am facing the same issue with array of objects

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/1113
