### ISSUE TITLE
Setting the name attribute results in a schema change

### ISSUE THREAD

**Issue by clintonb** [nestjs/swagger#2951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Setting the `name` attribute on the `ApiProperty` decorator changes the generated OpenAPI JSON. For example, say I have a property named `lane`. If I do not set the `name` attribute, I get:
```
"lane": {
  "$ref": "#/components/schemas/NestedLaneDto"
}
```
If I do set the attribute, I get:
```
"lane": {
  "allOf": [
    {
      "$ref": "#/components/schemas/NestedLaneDto"
    }
  ]
}
```

These are _roughly_ equivalent, but the `allOf` declaration can have issues as mentioned in https://github.com/nestjs/swagger/issues/2948.

### Minimum reproduction code

https://gist.github.com/clintonb/16195739bf913e636f9ef4ead4bbbbdb

### Steps to reproduce

1. Create a DTO that references another type/DTO.
2. Set the `name` attribute on the `ApiProperty` decorator.

### Expected behavior

The generated output should not change.

### Package version

7.3.1

### NestJS version

10.3.0

### Node.js version

20.12.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by clintonb** [comment]
The root cause is the same as #2948. Moving the discussion there.

**Comment by clintonb** [comment]
Reopening because fixing this exact issue should be easier—require less OpenAPI spec research—than `nullable`.

**Comment by kamilmysliwiec** [comment]
This will be fixed in the next version

![image](https://github.com/user-attachments/assets/663ecfc9-849d-48ac-baae-4052b02b0668)
![image](https://github.com/user-attachments/assets/b813a65c-7092-4061-a68d-c17c149662e6)
