### ISSUE TITLE
Issues with typescript >= 5.5

### ISSUE THREAD

**Issue by shiftgeist** [nestjs/swagger#3009]
### Did you read the migration guide?

- [x] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

7.4.0

### Describe the regression

There is a major differences between typescript 5.4.5 and 5.5.1-rc to the point that the spec is no longer representative to what is defined.

I can't share any code or diffs but I can give you a list what changed when using > 5.4.5

- Multiple schema objects removed
- Response codes 201 removed
- get.parameters emptied (`"parameters": [],`)
- get.parameters[0].schema.default removed
- get.parameters removed (eg: before: 5 obj in list, after: 2)
- Some component.schemas removed
- Properties removed
- Some schema `required` missing in list

This feels like magical third level dependency entanglement.

Fix for now is to use typescript version 5.4.5 (`"=5.4.5"`).

### Minimum reproduction code

```json
"typescript": "=5.5.1-rc",
```

### Expected behavior

Output of openapi.json is same as before.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by CakeWithDivinity** [comment]
We found the issue for this, but I don't think it has something to do with @nestjs/swagger. Here is what we found out:

Our setup is a pnpm and turbo monorepo. The typescript dependency is installed as a dependency in the root `package.json`.
When we also add typescript as a `devDependency` to our `apps/backend/package.json`, the generator works fine again.
