### ISSUE TITLE
default @ApiTag to controller name

### ISSUE THREAD

**Issue by nhomble** [nestjs/swagger#3011]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The current strategy (or lack thereof) doesn't give nestjs adopters a way to easily lead developments teams to easily group their api routes in a service. We would like to guide developers with better convention, and a common solution we have seen is grouping by the controller name.

We see this grouping inherent to the controller class you have registered in the nest module, so redefining an `ApiTag` decorator is not appealing.

### Describe the solution you'd like

I think another parameter could be added to `SwaggerCustomOptions` like

```
{
  apiTagStrategy?: { strategy: 'NONE' } | { strategy: 'CONTROLLER_NAME' }
}
```

when it's undefined, fallback to the existing `NONE` strategy

### Teachability, documentation, adoption, migration strategy

The change is backwards compatible so no migration necessary, and this could added to the existing nestjs swagger recipe section.

### What is the motivation / use case for changing the behavior?

For services with enough routes, it is disorganized to have all definitions under the `default` group. So far, all of our use cases are sufficed by annotating the controllers (with `@ApiTag`) with our controller name. 

---

It's tedious to ask developers to re-annotate their controllers with another grouping when they've already done a reasonable grouping at the class level in the first place.

**Comment by kamilmysliwiec** [comment]
Sounds useful

Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/3017
