### ISSUE TITLE
Help: Need to add basic authentication to access swagger url in fastify nestjs application

### ISSUE THREAD

**Issue by adityavyas-emeritus** [nestjs/swagger#3014]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

Need Help, if we could add an basic authentication before showing the api's in browser

### Minimum reproduction code

```ts

```

### Expected behavior

NA

**Comment by adityavyas-emeritus** [comment]
<img width="758" alt="image-20240221-051328" src="https://github.com/user-attachments/assets/8e30dcba-6724-4cda-906a-1dab3a088abf">
Need to add such thing while accessing

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
