### ISSUE TITLE
Using Types with the metadata generator plugin doesn't seem to work

### ISSUE THREAD

**Issue by Stono** [nestjs/swagger#3016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm not sure if this _should_ work, given this example:

```
export type Thing = {
  someNumber?: number
}

export class Test {
  public test2?: Thing

  public test3?: {
    someNumber?: number
  }
}
```

You get:

```
    '@nestjs/swagger': {
      models: [
        [
          import('lib/modules/chart-values/response'),
          {
            Test: {
              test2: { required: false, type: () => Object },
              test3: {
                required: false,
                type: () => ({
                  someNumber: { required: false, type: () => Number }
                })
              }
            }
```

Notice how the type is correct for `test3` but not for `test2`, that just defaults to `Object`.  This stops me reusing existing `Types` in the app and forces me to write a class version of them all.

Even weirder is if you change the `type Thing` to an `interface`, the property `test2` doesn't get generated in the metadata at all.

### Minimum reproduction code

See above

### Expected behavior

Types to be honoured when generating metadata

### Package version

7.3.1

### NestJS version

10.3.9

### Node.js version

22

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
`type` and `interface` "types" are not auto-converted to classes by the plugin

Please search through some of our old issues on this (this has been discussed several times in the past).
