### ISSUE TITLE
OpenAPI 2 fork

### ISSUE THREAD

**Issue by czeidler** [nestjs/swagger#3019]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am working on an API that use @nestjs/swagger 3.1.0 (the last version that uses OpenAPI 2). I tried to migrate to a newer version but there are some subtle differences which break our APIs. Possible these problems are fixable but would require lots of careful testing. Thus I try to avoid a migration to OpenAPI 3.

Since the api is in a mono repo it also blocks us from mixing OpenAPI 2 and OpenAPI 3 services.

### Describe the solution you'd like

A solution would be to fork @nestjs/swagger 3.1.0 and make it working with the latest @nestjs version (some smaller fixes are needed). This seem to work in a local setup. Instead of publishing this fork under a new org I wonder if it should be published under `@nestjs/swagger-legacy` or similar? If this would be an option I can provide a branch with my changes.

### What is the motivation / use case for changing the behavior?

Having two separate packages would allow users to mix OpenApi 2  and OpenApi 3 endpoints in the same mono repo.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
