### ISSUE TITLE
ApiProperty containing a key as an array of objects

### ISSUE THREAD

**Issue by abdulkaderelrawas** [nestjs/swagger#3041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is related to the following issues: [2945](https://github.com/nestjs/swagger/issues/2945), [2418](https://github.com/nestjs/swagger/issues/2418), [1112](https://github.com/nestjs/swagger/issues/1112), [1113](https://github.com/nestjs/swagger/pull/780), [2418](https://github.com/nestjs/swagger/issues/780), [735](https://github.com/nestjs/swagger/issues/735), [90](https://github.com/nestjs/swagger/issues/90).

I have these 2 classes:
```
class FilterParamDto {
  @IsString()
  filterBy: string;

  @IsString()
  operator: string;

  @IsString()
  value: string;
}

export class SortAndFilterDto extends SortParamsDto {
  @ApiProperty({ type: FilterDto, isArray: true })
  readonly filters: FilterParamDto[];
}
```

I am getting this

![image](https://github.com/user-attachments/assets/5fb7a507-a2d6-4d0f-be22-3a0722309a79)

I tried the following:

- plugin in nest cli and added all the necessary decorators to filters and not use the `@ApiProperty`: **doesn't work**.
- `@ApiProperty({ type: [FilterDto]})` instead of `@ApiProperty({ type: FilterDto, isArray: true })`: **doesn't work**.
- changed the type of `FilterDto` to get an array of strings: **works**

So I figured the problem is somewhere in reading array of objects only.

I read some workarounds using $ref and @ApiQuery over the controller directly, but it doesn't make sense to do workarounds that will disorganize the code when there might be a bug that needs fixing.

### Minimum reproduction code

[Reproduction repo](https://github.com/abdulkaderelrawas/nestjs-swagger-bug)

### Expected behavior

the expected behaviour should be like the image

![image](https://github.com/user-attachments/assets/87988f24-4f35-4c00-bc19-77e06bbac2aa)

### Package version

7.4.0

### NestJS version

9.4.3

### Node.js version

20.11.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

This has been reported in more than 5 other issues since 2018, is there anything we can do to fix? there is even an open PR

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by abdulkaderelrawas** [comment]
@kamilmysliwiec 

here's a minimal repro

[Reproduction Repo](https://github.com/abdulkaderelrawas/nestjs-swagger-bug)

how to setup

1. clone
2. npm/yarn/pnpm i
3. pnpm start:dev
4. go to http://localhost:3000/docs
5. go to app -> bug endpoint
6. try it out
7. there is no filters array of objects

can we return it to (bug)(needs triage) instead of needs clarification? thank you :)

**Comment by abdulkaderelrawas** [comment]
Ping

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/pull/1113
