### ISSUE TITLE
refactor typeFileNameSuffix to be available in REST aswell

### ISSUE THREAD

**Issue by LhonRafaat** [nestjs/swagger#3048]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When using response type decorators they expect a class to be used as a type, so creating a class and adding all the swagger decorators is too much boilerplate. I see that typeFileNameSuffix is already available for Graphql but not in REST so it will be really helpful to avoid alot of boilerplate. Although you can work around this by adding the type file extension inside dtoFileNameSuffix, but this wouldnt make much sense because models are not DTOs.

### Describe the solution you'd like

dtoFileNameSuffix to accept an array of suffixes so the model files can be pointed.

### What is the motivation / use case for changing the behavior?

to avoid boilerplate.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/blob/39a5a15e0df2f3d217f6d8335beb7bda335acaa1/lib/plugin/merge-options.ts#L4-L5
