### ISSUE TITLE
@ApiBody "example" property of OpenAPI missing

### ISSUE THREAD

**Issue by nick-loginov** [nestjs/swagger#3052]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's only possible to use examples of @ApiBody, it should be possible to assign unnamed single example

### Describe the solution you'd like

It's possible that this field missing somewhere else, at least add it to @ApiBody

### What is the motivation / use case for changing the behavior?

In real case scenario it would be usefull to have ability of assigning examples to request body inside of controllers

**Comment by kamilmysliwiec** [comment]
It does work

![image](https://github.com/user-attachments/assets/039511b9-fd99-40d2-8d96-614ccdef527d)
![image](https://github.com/user-attachments/assets/fa117893-1fb5-4777-ae56-d1c45d9abbb9)
