### ISSUE TITLE
ApiParam with nested type is transformed in query instead of path

### ISSUE THREAD

**Issue by thiagotognoli** [nestjs/swagger#3061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use ApiParam with a Class as type the ApiProperties of the Class are mapped as query instead of 'path'.
`
"/cats/{id}": {
"get": {
"operationId": "CatsController_findOne",
"parameters": [
{
"required": true,
"name": "id",
"in": "query",
"schema": {
"type": "string"
}
}
],
"responses": {
"200": {
"description": "The found record"
}
},
"tags": [
"cats"
]
}
}
`
### Minimum reproduction code

https://github.com/thiagotognoli/nestjs_swagger_apiparam_bug_sample

### Steps to reproduce

1. npm i
2. npm start:dev
3. http://localhost:3000/api-json

### Expected behavior

Class ApiProperties must be mapped as in: "path"

### Package version

7.4.0

### NestJS version

10.4.1

### Node.js version

20

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/3062
