### ISSUE TITLE
Updating path-to-regexp to the last version

### ISSUE THREAD

**Issue by mallowigi** [nestjs/swagger#3066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Today, a new vulnerability fix have been issued about the `path-to-regexp` library which is used in a lot of modules, including this one. As this is a high vulnerability, it is expected to the libraries to update their dependencies to include this fix.

I've tried to manually force update the path-to-regexp dependency but unfortunately this library is using functionality from the current version (3.2.0) that is apparently not present in the latest version.

### Minimum reproduction code

http://www.github.com

### Steps to reproduce

- Update the path-to-regexp to 8.1.0
- Try to run the project
- Encounter an issue `pathToRegexp.parse is not a function`

### Expected behavior

Update the path-to-regexp dependency to latest

### Package version

7.4.0

### NestJS version

10.4.1

### Node.js version

22.7.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by aasimsayyad07** [comment]
We override dependents packages to handle the `path-to-regexp` vulnerability issue but can still reproduce the issue.

"overrides": {
    "body-parser": "^1.20.3",
    "path-to-regexp": "^8.1.0",
 }
 
 Can see this error in logs, while running the application locally - 
 
 `TypeError: pathRegexp is not a function`

**Comment by aasimsayyad07** [comment]
Does anyone know Workaround for this issue??

**Comment by agrawalrohant** [comment]
I am also looking for the fix. Anyone aware ?

**Comment by stefanfeldner** [comment]
Same problem here!

```
node_modules/@nestjs/swagger/dist/swagger-explorer.js:180

for (const item of pathToRegexp.parse(path)) {
                                        ^
TypeError: pathToRegexp.parse is not a function or its return value is not iterable
```

**Comment by ErikMartensson** [comment]
You should be able to manually specify version 3.3.0 of `path-to-regexp` to fix it. Version 3.3.0 was released yesterday and is listed as patched version on the GitHub advisory page for this vulnerability https://github.com/advisories/GHSA-9wv6-86v2-598j

If you're using NPM you could use the [overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#overrides) feature for this (haven't tested myself) by adding the following to your package.json:
```
"overrides": {
  "@nestjs/swagger": {
    "path-to-regexp": "^3.3.0"
  }
}
```

If you're using Yarn you can instead use [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) which I can confirmed worked for me. Add this to your package.json:
```
"resolutions": {
  "**/@nestjs/swagger/path-to-regexp": "^3.3.0"
}
```

Afterwards run npm/yarn install and verify with npm/yarn audit.

**Comment by kamilmysliwiec** [comment]
Fixed in 7.4.1

**Comment by sfigueroam** [comment]
Fix but with high vulnerabilities:

npm audit fix

up to date, audited 781 packages in 8s

118 packages are looking for funding
  run `npm fund` for details

# npm audit report

path-to-regexp  0.2.0 - 1.8.0
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
fix available via `npm audit fix --force`
Will install @nestjs/serve-static@2.2.2, which is a breaking change
node_modules/@nestjs/serve-static/node_modules/path-to-regexp
  @nestjs/serve-static  2.0.0-next.1 - 2.0.0 || >=3.0.0
  Depends on vulnerable versions of path-to-regexp
  node_modules/@nestjs/serve-static

2 high severity vulnerabilities

**Comment by sfigueroam** [comment]
fix s for my:

  "overrides": {
    "glob": "^11.0.0",
    "@nestjs/swagger": {
      "path-to-regexp": "^6.3.0"
    },
    "@nestjs/serve-static": {
      "path-to-regexp": "^3.3.0"
    }
  }
