### ISSUE TITLE
[Feature Request] Base URL according to X-Forwarded-XXX header 

### ISSUE THREAD

**Issue by dannyhuly** [nestjs/swagger#307]
# Feature Request

## Current behavior
Swagger `Base URL` is set to a fixed path (via `DocumentBuilder.setBasePath()`) 

## Expected behavior
Swagger should be able inherit `Base URL` from a `X-Forwarded-XXX` header.

## What is the motivation / use case for changing the behavior?
This will enable to serve the swagger-ui when using a reverse_proxy (like Nginx).

Similar issue for `NSwag` (https://github.com/RicoSuter/NSwag/issues/1892)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by jonasbeyer** [comment]
Is this an issue related to Swagger or to Nest.js? Nevertheless, the `x-forwarded-prefix` attribute specified by a reverse proxy like Nginx is ignored, so redirection won't work.

Swagger issue: https://github.com/swagger-api/swagger-core/issues/3161

**Comment by kamilmysliwiec** [comment]
There's currently no bandwidth to fix this issue/implement this feature, unfortunately. Since we don't plan to address this in the foreseeable future, I'm gonna close this issue.
