### ISSUE TITLE
Support usage of fields like "oneOf", "anyOf", or "examples" within a parameter

### ISSUE THREAD

**Issue by alex-statsig** [nestjs/swagger#3078]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When defining a parameter with a "type" property, the "type" is correctly nested within the "schema" field. However, there are several fields that you can reference (in particular, I'm using [zod-nestjs](https://github.com/anatine/zod-plugins/tree/main/packages/zod-nestjs) to automatically generate the types) which will not be properly moved into the "schema" field. Some examples include "oneOf", "anyOf", or "examples".

### Describe the solution you'd like

I believe the fix should be a simple change to include more fields (like "oneOf") in this list of schema keys, but I don't have the full context of if the change makes sense here (locally patching this fixed all of my issues): https://github.com/nestjs/swagger/blob/276b4fa8cb0ffc597d816ed0e245c2cd7c7ca3f8/lib/services/swagger-types-mapper.ts#L142-L160

### What is the motivation / use case for changing the behavior?

The current spec generated will not be valid if a parameter uses a feature like "oneOf" or "examples" (I believe "examples" is specific to 3.1.0, but "oneOf" is valid in 3.0.0)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/3129
