### ISSUE TITLE
ApiOperation overrideExisting leaves existing data

### ISSUE THREAD

**Issue by SmallhillCZ** [nestjs/swagger#3109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I provide `overrideExisting: true` some existing ApiOperation data is preserved.

This prevents using
```ts
@ApiOperation({
  $ref: "..."
})
```
because when using $ref you cannot have any other fields.

### Minimum reproduction code

Can create if needed, but the issue is pretty straightforward

### Steps to reproduce

1) Put ApiOperation decorator on a method.
```ts
@ApiOperation({
  ...
})
```

2) Open the generated OpenAPI JSON

3) See that there are other things in the operation that the ones provided in the decorator

### Expected behavior

Only the provided data in ApiOperation would be in OpenAPI document if I choose `overrideExisting: true` 

### Package version

7.4.2

### NestJS version

10.4.4

### Node.js version

22

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
