### ISSUE TITLE
did not generate the query params type in jsonDocumentUrl

### ISSUE THREAD

**Issue by quxiaodong** [nestjs/swagger#3118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I define two dto types for `@Query` and `@Body` function, when I open the jsonDocumentUrl (localhost:3000/api/json), I can only find the body dto type, but miss the query dto type
<img width="373" alt="image" src="https://github.com/user-attachments/assets/0cc01b53-fd69-4ef4-8b68-ad6b3252d60a">

### Minimum reproduction code

https://github.com/quxiaodong/nestjs-test.git

### Expected behavior

generate the `@Query` dto type

### Package version

7.4.2

### NestJS version

10.0.0

### Node.js version

20.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
