### ISSUE TITLE
Proper release notes

### ISSUE THREAD

**Issue by alex-deity** [nestjs/swagger#3133]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I've been working with NestJS for several years now - I like it, but release notes on every release are almost useless (not just for this repo, but the entire lineup of NestJS packages).

https://github.com/nestjs/swagger/releases/tag/8.0.0:
- how do I know what caused this to become a major ver bump? 
- why do I need to visually scan through 15 updates of types/node? (is it important to mention all 15 updates?) or a bunch of other internal stuff that doesn't affect my project directly

@kamilmysliwiec [mentioned](https://github.com/nestjs/swagger/issues/229#issuecomment-579146850) some time ago that release notes are automatically generated now, but they are practically useless. 

### Describe the solution you'd like

With all the AI-assisted tools github has to offer - there **must** be a better way to provide a meaningful summary for the release.

I'd like to see well-structured, concise release notes. 

### What is the motivation / use case for changing the behavior?

I got a dependabot PR, I see no dep updates for swagger - what's changed?  

<img width="1632" alt="Screenshot 2024-10-29 at 09 04 50" src="https://github.com/user-attachments/assets/8d44f14a-f383-4d46-8268-ecc3038fab3d">

**Comment by kamilmysliwiec** [comment]
Updated both releases, configured release-it to use lerna-changelog moving forward (although we might need to just move to automated github release notes generation)
