### ISSUE TITLE
HttpCode decorator in applyDecorators not working after enable @nestjs/swagger plugin

### ISSUE THREAD

**Issue by Esimorp** [nestjs/swagger#3150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

HttpCode decorator on controller method always will work even enable @nestjs/swagger plugin. 
HttpCode decorator in applyDecorators is working without @nestjs/swagger plugin
But the HttpCode decorator in applyDecorators not working after enable @nestjs/swagger plugin

### Minimum reproduction code

https://codesandbox.io/p/devbox/lingering-dew-9nxvd7?workspaceId=601df79b-8347-44ab-a9d1-9d84effdec64

### Steps to reproduce

1. npn run start
2. view swagger docs in {{HOST}}/docs

### Expected behavior

But the HttpCode decorator in applyDecorators should working after enable @nestjs/swagger plugin

### Package version

^8.0.1

### NestJS version

^10.4.6

### Node.js version

20.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/3151
