### ISSUE TITLE
Extra schema field is emitted for response 

### ISSUE THREAD

**Issue by shuluster** [nestjs/swagger#3152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Extra `schema` field is add to response object aside by the `content` field.

The issue was introduced here https://github.com/nestjs/swagger/commit/417369307c43a06cf2e9ba7b856594c5bb650013#r148799969

### Minimum reproduction code

https://gist.github.com/shuluster/821a8a4b7533f2a65ac30e7e98bc1710

### Expected behavior

The schema field should not be output

### Package version

8.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thanks for reporting!

Let's track this here https://github.com/nestjs/swagger/pull/3153
