### ISSUE TITLE
OpenAPI metadata required relative paths are broken since v8

### ISSUE THREAD

**Issue by bladx** [nestjs/swagger#3154]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

7.4.2 -> 8.0.0

### Describe the regression

In the dist folder, the OpenAPI metadata required relative paths are broken since the v8.
I have a DTO with a property of type enum (file declared in another folder).
With the 7.4.2 I had: `enum: require('../../other-module/some-enum')`, but with the 8.0.0 or later I now get: `enum: require('./src/modules/other-module/some-enum')`.
This is breaking my built app as the path is wrong.
Having the `"preserveSymlinks": true` tsconfig option or not does not change anything.

For now, I stay on v7.4.2 for this reason.
But I feel like this is a regression that should be fixed.

### Expected behavior

I would expect the same behavior as before so having a relative path (starting with `../..`) instead of the new one (starting with `./src`).

**Comment by kamilmysliwiec** [comment]
Does this happen with v8.0.0 (or v8.0.2 etc)?

Could you provide a minimum reproduction repository?

**Comment by bladx** [comment]
I tried with at least v8.0.0, v8.0.2 and v8.0.3 and got the same error as described.
Regarding the minimum reproduction repository, I'll try to do it as soon as I find time but currently I don't really have time sorry.

**Comment by kamilmysliwiec** [comment]
We unfortunately can't help without a reproduction repository

**Comment by bladx** [comment]
I started, but I cannot find what produce the following in my app DTO: `static _OPENAPI_METADATA_FACTORY() {`.
In my minimum reproduction repository, I have an empty DTO class (so no issue), but in my real app I do have this metadata factory with the new regression.
Would you know what causes the generation of this particular function?

**Comment by kamilmysliwiec** [comment]
Could you test with v8.0.4?

**Comment by bladx** [comment]
It actually does fix the issue!
Thanks a lot for the reactivity and the precious help on that, really appreciate.

**Comment by gwen1230** [comment]
@kamilmysliwiec I have same issue in a monorepo when the imported type is in another module.

**Comment by norbornen** [comment]
@kamilmysliwiec I have same issue in a monorepo when the imported type is in another module.

Expected:
```
const foo_entities_1 = require("@foo/entities");
...
openapi.ApiResponse({ status: 201, type: require("@foo/entities").Item }),
or
openapi.ApiResponse({ status: 201, type: foo_entities_1.Item }),
```

Obtained:
```
const foo_entities_1 = require("@foo/entities");
...
openapi.ApiResponse({ type: require("../../../../libs/foo-entities/dist/entities/item.entity").Item }),
```

For windows:
../../../../../../../../E:/Dev/eurochem/forge/libs/sposs-entities/dist/entities/items.entity
```

**Comment by norbornen** [comment]
@kamilmysliwiec I have same issue in a monorepo when the imported type is in another module.

Expected:
```
const foo_entities_1 = require("@foo/entities");
...
openapi.ApiResponse({ status: 201, type: require("@foo/entities").Item }),
or
openapi.ApiResponse({ status: 201, type: foo_entities_1.Item }),
```

Obtained:
```
const foo_entities_1 = require("@foo/entities");
...
openapi.ApiResponse({ type: require("../../../../libs/foo-entities/dist/entities/item.entity").Item }),
```

For windows:
```
../../../../../../../../E:/....../libs/foo-entities/dist/entities/item.entity
```
