### ISSUE TITLE
Add option sto disable json and yaml API definition serving

### ISSUE THREAD

**Issue by wiliamsouza** [nestjs/swagger#3157]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is no way to disable json and yaml API definition endpoints.

### Describe the solution you'd like

An option like exist for enable or disable swagger UI.

### Teachability, documentation, adoption, migration strategy

Some times you do not want to make your API public available for any reason. 

### What is the motivation / use case for changing the behavior?

I need to create a work around to disable those endpoint:

```typescript
  const enable = false;

  SwaggerModule.setup("api", app, swaggerDocument(app), {
    swaggerUiEnabled: enable,
    patchDocumentOnRequest: (_req, _res, document) => {
      if (enable) {
        return document;
      }
      return {
        openapi: "3.0.0",
        info: {
          title: "You shall not pass! Just kidding, not found ;D",
          version: "1.0",
        },
        paths: {},
      };
    }
  });
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by mag123c** [comment]
If possible, is it okay if I try to work on this issue?

**Comment by mag123c** [comment]
https://github.com/nestjs/swagger/pull/3185 I made PR!!

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/3185
