### ISSUE TITLE
@ApiSchema not working as expected when inheriting

### ISSUE THREAD

**Issue by arabold** [nestjs/swagger#3160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Assume you define two DTOs that inherit from each other:
```ts
@ApiSchema({ name: 'BaseResponse' })
class BaseResponseDto {
}

@ApiSchema({ name: 'Response' })
class ResponseDto extends BaseResponse {
}
```

Then use this class in your controller:
```ts
@Controller()
class MyController() {
   @Get()
   @ApiOkResponse({ type: ResponseDto })
   async doSomething(): Promise<ResponseDto> {
     // ...
   }
}
```

In the resulting OpenAPI spec you would expect that the response schema for `doSomething` is `Reponse`, the specialized subclass `ResponseDto`. However, the OpenAPI spec uses `BaseResponse` instead, the parent class.

### Minimum reproduction code

Example in the description above

### Expected behavior

For inherited classes I would expect the schema name of the subclass to be used, not of the parent class.

The error lies in the following piece of code in [lib/services/schema-object-factory.ts](https://github.com/nestjs/swagger/blob/7acedba5c8738a75e54c209c60173ea57639e99a/lib/services/schema-object-factory.ts#L295):

```ts
    const schemaName = customSchema[0].name;
```

It should be replaced by

```ts
    const schemaName = customSchema[customSchema.length - 1].name;
```

to use the schema name of the subclass.

### Package version

8.0.5

### NestJS version

10.4.7

### Node.js version

20.11.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
