### ISSUE TITLE
OpenAPI metadata required another package in monorepo are broken since v8

### ISSUE THREAD

**Issue by gwen1230** [nestjs/swagger#3161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have the same problem as https://github.com/nestjs/swagger/issues/3154 but in the case of a monorepo.
In my monorepo, I have 2 repositories : Server, Types.

If I have a DTO  in Server repository with type that come from package Types, the generated js is not correct (path inrequire is a relative path).

I had same problem with types from same packages before 8.0.4 and this MR (https://github.com/nestjs/swagger/pull/3155) fix the issue  but the issue remains with cross packages.

### Minimum reproduction code

No response

### Expected behavior

I would expect the same behavior as before so not transforming path when i import another repository.

### Package version

8.1.5

**Comment by kamilmysliwiec** [comment]
Fixed in 8.0.6
