### ISSUE TITLE
`@ApiProperty` with `type: 'object'` does not compile in some cases

### ISSUE THREAD

**Issue by flovouin** [nestjs/swagger#3163]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

92df1991c799f39503c6506d77b1145ee0fe804b

### Versions

7.4.2 -> 8.0.0

### Describe the regression

`SchemaObjectMetadata`, which is used by the `@ApiProperty` decorator, has become more restrictive. Previously, `type` could be any `string` (amongst others). Now, if the `type` is `'object'`, it must also provide `properties`, and `required` applies to... the properties of the object itself?
I would assume the minimum reproduction code is a valid JSONSchema. How do I express it using the `@ApiProperty` decorator?

### Minimum reproduction code

```ts
@ApiProperty({
    required: true,
    description: 'Some description.',
    type: 'object',
    additionalProperties: { type: 'boolean' },
})
```

### Expected behavior

The minimum reproduction code compiles.

**Comment by kamilmysliwiec** [comment]
> Now, if the type is 'object', it must also provide properties, and required applies to... the properties of the object itself?

Correct

What would you like to accomplish that's not doable with the current API?

**Comment by flovouin** [comment]
I'd like to express something similar to the minimum reproduction code: the property is of type object, and this object only defines `additionalProperties`. For example the TypeScript class and resulting JSONSchema would be something like:

```ts
class MyEntity {
  @ApiProperty({
    // This does not compile with version 8.
    required: true,  // In this example, `required` is `true`, but it could be `false` (in which case the property could have the value `undefined`).
    type: 'object',
    additionalProperties: { type: 'boolean' },
  })
  myObjectProperty: Record<string, bool>;
}
```

```yaml
title: MyEntity
type: object
properties:
  myObjectProperty:
    type: object
    additionalProperties:
      type: boolean
    description: The money validation results.
required:
  - myObjectProperty
```

Depending on the use case, I want to be able to declare `myObjectProperty` as `required` or not.

**Comment by kamilmysliwiec** [comment]
Ah pardon me, I forgot to update the types to include the newly added `selfRequired` attribute that you can use for this. Fixed in this PR https://github.com/nestjs/swagger/pull/3169
