### ISSUE TITLE
using a redirect with a setBasePath api endpoints won't work, license, version and text wont show up

### ISSUE THREAD

**Issue by albjeremias** [nestjs/swagger#3176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/user-attachments/assets/9d26d938-9421-4715-9e97-4b7b6d4da850)
https://github.com/helpbuttons/helpbuttons/blob/dev/api/src/main.ts#L129

I'm trying to set a custom basepath for the swagger-ui to do the requests...

related:
https://github.com/nestjs/swagger/issues/448
https://github.com/nestjs/swagger/issues/2297

### Minimum reproduction code

https://dev.helpbuttons.org/api/

### Steps to reproduce

```
      const title = 'Helpbuttons API documentation'
  const config = new DocumentBuilder()
    .setTitle(title)
    .setDescription('You chan check more about helpbuttons in our website helpbuttons.org')
    .addTag('hb')
    .addBearerAuth()
    .addServer('/api')
    .setBasePath('/api')
    // .setTermsOfService('/Faqs')
    .setContact('Helpbuttons Team', 'https://heplbuttons.org', 'help@helpbuttons.org')
    .setLicense('CC BY-SA-4.0', 'https://creativecommons.org/licenses/by-sa/4.0/')
    .build();

  const document = SwaggerModule.createDocument(app, config, { ignoreGlobalPrefix: true });
  SwaggerModule.setup('/', app, document, { customSiteTitle: title});
  ```
  
  run this open the swagger-ui and do pick an endpoint, do "Try out" > "Execute" and swagger-ui will fail the request cause it's not using the correct base path  for the api requests. 

### Expected behavior

I expected that when I do a Try out > Execute
that swagger uses the correct base path for the api requests

### Package version

^8.0.7

### NestJS version

^8.0.0

### Node.js version

v22.8.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by albjeremias** [comment]
ok, i found out more stuff! Im using nextjs to do a rewrite of all api requests from /api/ to the apiIp:3001/

if i go directly to the api webpage with the swagger-ui: http://localhost:3001/ it works, everything!
![image](https://github.com/user-attachments/assets/e174744d-3a3c-4162-8600-757b2ec3f66b)

if i go to the web rewrite by nextjs webpage with the swagger-ui: http://localhost:3000/api/ it wont show up the license, version, servers list... why? I don't get any error on the console of the browser.
![image](https://github.com/user-attachments/assets/04279f17-d564-4f1e-9215-bee7b301fe15)

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
