### ISSUE TITLE
followup issue: #3176

### ISSUE THREAD

**Issue by albjeremias** [nestjs/swagger#3178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i can't communicate with you from any other way, because the issue was locked. 
I don't have discord, and i would love if you can please point me to some ideas or solutions.

### Minimum reproduction code

https://github.com/nestjs/swagger/issues/3176

### Expected behavior

I expect to be able to open an issue and get input on how-to solve it 

### Package version

8.1.3

### NestJS version

8.1.3

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
