### ISSUE TITLE
ApiParam not overwriting type from @Param

### ISSUE THREAD

**Issue by dariozachow** [nestjs/swagger#3191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm trying to create a custom pipe which takes the id of an entity as an url param. The Pipe now checks if the entity exists returns it. The code of the pipe looks like this:

```typescript
@Injectable()
export class TransformAssetPipe implements PipeTransform<string, Promise<AssetEntity>> {
  constructor(private readonly assetService: AssetService) {}
  async transform(assetId: string, _metadata: ArgumentMetadata): Promise<AssetEntity> {
    const asset = await this.assetService.findOne(assetId);

    if (!asset) {
      throw new AssetNotFoundException(assetId);
    }

    return asset;
  }
}
```
Used by the following controller:

```typescript
 @Get('assets/:assetId')
  @ApiParam({type: "string", name: "assetId")
  async findOne(
    @Param('assetId', ParseUUIDPipe, TransformAssetPipe) asset: AssetEntity
  ): Promise<AssetEntity> {
    return asset
  }
```
Now the Swagger generates ULR-Params for each field of the entity 

![image](https://github.com/user-attachments/assets/ed9f14e7-dd24-41bd-8abb-524e497f662e)

### Minimum reproduction code

https://github.com/nestjs/swagger

### Expected behavior

@ApiParam should overwrite the type from the @Param so you can specify your own type if you want over the @ApiParam, but have a custom Mapping in a pipe.

### Package version

8.0.7

### NestJS version

10.4.1

### Node.js version

22

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by dariozachow** [comment]
https://stackblitz.com/edit/nestjs-typescript-starter-cjfte3?file=src%2Fapp.controller.ts and open die /swagger endpoint

**Comment by kamilmysliwiec** [comment]
![image](https://github.com/user-attachments/assets/fbdc7a2d-77e5-4f09-905a-06982d05e85c)

**Comment by dariozachow** [comment]
I'm kinda confused now, but seems like it's working now 😁 . Thanks for your fast replies
