### ISSUE TITLE
Can be true value and not  type like boolean, string and other?

### ISSUE THREAD

**Issue by Makkalay** [nestjs/swagger#3206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/nestjs/swagger/blob/579b3cde09e5f922d3b85a62d72f6f850bd2caf0/lib/services/parameter-metadata-accessor.ts#L27

Can be true value and not  type like boolean, string and other?

### Minimum reproduction code

https://github.com/nestjs/swagger/blob/579b3cde09e5f922d3b85a62d72f6f850bd2caf0/lib/services/parameter-metadata-accessor.ts#L27

### Expected behavior

-

### Package version

latest

### NestJS version

latest

### Node.js version

20

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Makkalay** [comment]
ok, https://github.com/nestjs/swagger/pull/3208/files

**Comment by Makkalay** [comment]
https://github.com/nestjs/swagger/issues/3204

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/swagger/pull/3208
