### ISSUE TITLE
Please add migration to v8 guide...

### ISSUE THREAD

**Issue by lu-perfect** [nestjs/swagger#3213]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Please add migration to v8 guide...

### Describe the solution you'd like

Please add migration to v8 guide...

### Teachability, documentation, adoption, migration strategy

Please add migration to v8 guide...

### What is the motivation / use case for changing the behavior?

Please add migration to v8 guide...

**Comment by kamilmysliwiec** [comment]
Breaking changes in v8 shouldn't require code changes for 99% of framework users

https://github.com/nestjs/swagger/releases/tag/8.0.0
