### ISSUE TITLE
Make possible to use in environment in wich emitDecoratorMetadata can't be used

### ISSUE THREAD

**Issue by Makkalay** [nestjs/swagger#3214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
 ParameterMetadataAccessor {
    const parametersWithType: ParamsWithType = mapValues(
      reverseObjectKeys(routeArgsMetadata),
      (param: ParamMetadata) => ({
        type: types[param.index], // Here
        name: param.data,
        required: true
      }) as unknown as ParamsWithType
```

it throw error if work in environment what not support emit decorator metadata.

### Minimum reproduction code

https://github.com/nestjs

### Expected behavior

To work when emitDecoratorMetadata is not possible to use (esbuild) and api property type is set manually via type = 'string' and so on. 

### Package version

10

### NestJS version

10

### Node.js version

20

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Makkalay** [comment]
https://github.com/nestjs/swagger/issues/3214

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
