### ISSUE TITLE
ApiModelProperty example field

### ISSUE THREAD

**Issue by ericzon** [nestjs/swagger#34]
It would be nice to have an optional example field, allowing to customize the output on the example value (i.e: at this moment, any Date type on Model has to be defined as String on ApiModelProperty, and this issue is reflected as "string" on the example). Other case is when you want to suggest a list of default values.

I've tested on Swagger editor and it works: https://imgur.com/a/wolXA

The same field could be on ApiImplicitBody & ApiResponse.

**Comment by sebastiendan** [comment]
Any news on this? This feature would be an awesome change!

**Comment by sebastiendan** [comment]
Ok, it's actually already there...

Just need to pass `example` key to @ApiModelProperty decorator metadata.

```
@ApiModelProperty({example: 'test'})
name: string;
```

Latest version from npm doesn't provide `example` key in the decorator metadata class definition even though it is present on master branch. But all metadata are passed to swagger anyway, so it's working fine.

**Comment by kamilmysliwiec** [comment]
PR merged, I'll publish it soon!
