### ISSUE TITLE
Required property in dto gets ignored when posting new document

### ISSUE THREAD

**Issue by alexandruluca** [nestjs/swagger#349]
I have a very simple example where I try to create a new document via a post route.
My dto object is as follows

```
export class CreateArticleDto {
    @ApiModelProperty({
      required: true
    })
    readonly name: string;
}
```
My controller post route is like this

```
  @ApiOperation({ title: 'Create article' })
  @ApiResponse({ status: 201, description: 'The article has been successfully created.'})
  @ApiResponse({ status: 403, description: 'Forbidden.' })
  @Post()
  async create(@Body() articleData: CreateArticleDto) {
    return this.service.create(articleData);
  }
```

If I do a post, I would expect the request to be validated before it invokes the controller and validate the body based on the defined dto (in this case it is missing a required name property)
I do not get a swagger error if I post an empty object. It would be expected that the request fails with a missing property error (or similar).

Or maybe I misunderstand the scope of the module and in fact it doesn't support validation

**Comment by jsduncan2** [comment]
To get validation working, you're going to want to look here: https://docs.nestjs.com/techniques/validation.

Basically you need to tell NestJS to start performing validation (it is not enabled by default).

Then you also need to decorate the DTO's fields with validation logic (for example `@IsString()`).

**Comment by alexandruluca** [comment]
Thanks. I thought this was leveraged by the swagger module itself, now as I've read a little bit more careful, it's just to generate code.
