### ISSUE TITLE
ApiResponse hierarchy

### ISSUE THREAD

**Issue by ericzon** [nestjs/swagger#36]
First of all, nice work integrating Swagger, I'll use it on my next project.

This is a possible feature. At this moment, if you use ApiResponse decorator at controller level, when you add additional ApiResponse at method level, you loose the main api responses configured before.

Example
dummy.controller.ts
````
@Controller('dummy')
@ApiResponse({ status: 400, description: 'Bad request'})
@ApiResponse({ status: 403, description: 'Forbidden.'})
export class DummyController {
    @Post()
    @ApiResponse({ status: 201, description: 'Created'})
    public getItems(@Req() req, @Res() res) {
        ...
    }
}
````

In this case, Swagger only displays the status 201 as response. Maybe it would be more helpful to inherit main controller responses, displaying 201, 400 & 403.

What do you think?

**Comment by thohoh** [comment]
@fwoelffel any info on this issue?

**Comment by lvalencia** [comment]
I'm also having this issue

**Comment by kamilmysliwiec** [comment]
Fixed. I'll push it soon. 🙂
