### ISSUE TITLE
how to custom request headers

### ISSUE THREAD

**Issue by SeongBrave** [nestjs/swagger#376]
i need add options to request headers like this:

https://github.com/swagger-api/swagger-ui/issues/3605

![image](https://user-images.githubusercontent.com/10784393/68171863-6c6e3680-ffb0-11e9-916a-c604de9f7fd1.png)
https://alexdunn.org/2018/06/29/adding-a-required-http-header-to-your-swagger-ui-with-swashbuckle/

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/recipes/swagger#headers
