### ISSUE TITLE
ApiImplicitHeaders add default

### ISSUE THREAD

**Issue by SeongBrave** [nestjs/swagger#377]
You can add a default field ,like：

  @ApiImplicitHeaders([
    { name: 'appVersion', required: true，default:1.1.0 },
    { name: 'platform', required: true ,default:iOS},
  ])

**Comment by kamilmysliwiec** [comment]
According to the specification, there is no `default` field available https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md
