### ISSUE TITLE
Use example

### ISSUE THREAD

**Issue by imkarma** [nestjs/swagger#4]
Hi,all

Can some one provide some use example? plz ;)

**Comment by Jorgevillada** [comment]
I'm using it that way, I do not know if it's the right way, but it works.

in server.ts
I tell him to generate the json with the methods.
```javascript
instance.get('/api-docs.json', function (req, res) {
      res.setHeader('Content-Type', 'application/json');
      res.send(SwaggerModule.createDocument(app,
        {
          info: {
            title: "My App", description: "My App Description",
            contact: { email: "email@email.com" }
          },
          securityDefinitions: { bearer: { type: "apiKey", name: "Authorization", in: "header" } }
        }));
    });
```
in controller
```javascript
    @ApiOperation({ description: "Disable Company", operationId: "disable", title: "Disable Company" })
    @ApiImplicitBody({ name: "company", required: true, type: CompanyId })
    @ApiResponse({ status: 400, description: "Missing info: compId" })
    @ApiResponse({ status: 200, description: "disable OK", type: Company })
    @Post("disable")
    public async disable( @Req() req, @Res() res: Response) {
 
    }
```
```javascript
instead of @ApiImplicitBody(), you can use @Body() as parameter in function
```

```javascript
//in Body Type. @ApiModelProperty()
export class CompanyId {
    @ApiModelProperty()
    compId: number;
}
```

all decorators are in

import { APIXX } from '@nestjs/swagger';


http://localhost:8080/api-docs.json (assuming 8080 is the port of your app )
this url I place it in swagger-ui and it already shows the information of the api.
http://petstore.swagger.io/ (you can try localhost url)

**Comment by mildbreakfast** [comment]
You can also use 'swagger-ui-express':
```typescript
  const documentBuilder = new DocumentBuilder();
  documentBuilder.addBearerAuth('Authorization', 'header');
  const document = SwaggerModule.createDocument(nestApp, documentBuilder.build());
  expressApp.use('/swagger', swaggerUI.serve, swaggerUI.setup(document));
  expressApp.use('/api-docs', (req, res, next) => res.send(document));
```

**Comment by Matonen** [comment]
I tried this but i get  `TypeError: Cannot read property 'path' of undefined` when starting the server.

**Comment by Jorgevillada** [comment]
can you put your server.ts? and the controller where are you using them?

**Comment by Matonen** [comment]
server.ts
```
    await app.listen(port);
    const config = new DocumentBuilder().addBearerAuth().build();
    const document = SwaggerModule.createDocument(app, config);
    instance.get('/api-docs.json', (req, res) => {
        res.setHeader('Content-Type', 'application/json');
        res.send(SwaggerModule.createDocument(app, document));
    });
```

```
@ApiOperation({ title: 'Get all' })
@ApiResponse({ status: 200, description: 'Items', type: XXX })
@Get()
public async getAll( @Req() req):

```

**Comment by Jorgevillada** [comment]
you are creating the document twice. `SwaggerModule.createDocument`

`const document = SwaggerModule.createDocument (app, config);`

res.send (SwaggerModule.createDocument (app, document));

**Comment by Matonen** [comment]
Good point (copy-paste daah).  I changed ` res.send(document);` but i still same issue. The problem seems to be `SwaggerModule.createDocument(app, config)` . I don't need to use any decorators to get that error. Also  `documentBuilder.setBasePath` does not have any effect.

**Comment by panuhorsmalahti** [comment]
And if anyone else is wondering, you can import SwaggerModule with `import { SwaggerModule } from "@nestjs/swagger";`

**Comment by kamilmysliwiec** [comment]
Here's an example https://docs.nestjs.com/recipes/swagger 🙂

**Comment by sebilasse** [comment]
A real world example can also be found here : https://github.com/nartc/nest-mean

**Comment by kentloog** [comment]
Nest + sequelize-typescript + JWT + Jest + Swagger
https://github.com/kentloog/nestjs-sequelize-typescript
