### ISSUE TITLE
What to use instead of setSchemes in latest NestJs/Swagger

### ISSUE THREAD

**Issue by amit12cool** [nestjs/swagger#424]
Im using the latest version of nestjs/Swagger 4.0.9 and see now setSchemes function is deprecated. Please suggest what is the new function to be called instead of setScheme. I coudn't find it anywhere in the nestjs documentation or Internet.

My main use case which was fulfilled by setSchemes function previously was that in local dev environment i using scheme as http and in production i was using https. Please suggest.

**Comment by nartc** [comment]
`addServer()` would solve your issue.

**Comment by amit12cool** [comment]
That helps.Thanks

**Comment by vegerot** [comment]
@nartc @amit12cool for a dummy like me how should I use `addServer` to replicate the behavior of `setSchemes('http','https')`?

**Comment by 0xb4lamx** [comment]
@vegerot try something like:
```ts
new DocumentBuilder()
.addServer('http://')
.addServer('https://')
...
```
full details [here](https://swagger.io/specification/#server-object).

**Comment by vegerot** [comment]
Thanks, that's what I ended up doing
