### ISSUE TITLE
@UploadedFile not working with @Body

### ISSUE THREAD

**Issue by iaakash** [nestjs/swagger#428]
## Bug Report
So the intention is pretty simple here. want to upload image and store the image url in collection
## Input Code

```ts
  @Post()
  @UsePipes(ValidationPipe)
  @UseInterceptors(FileInterceptor('additional_image'))
  async createCourse(@UploadedFile() files, @Body() createCourseDto: CreateCourseDto
                    ) {
                      console.log('Files::', files);
                      console.log('createCourseDto::', createCourseDto);
  
  } 
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
so this code doesn't upload image and provide any url. what's the nest way to achieve this?
</code></pre>

**Comment by kamilmysliwiec** [comment]
See https://github.com/nestjs/swagger/issues/417

**Comment by iaakash** [comment]
Hello @kamilmysliwiec thanks for pointing me to direction but it didn't solve the issue.

`  @Post()
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          format: 'binary',
        },
      },
    },
  })

  @UseInterceptors(FileInterceptor('additional_image'))
  async createCourse(
    @UploadedFile('additional_image') additional_image,
    @Body() createCourseDto: CreateCourseDto,
  ) {
    console.log('Files::', additional_image);
    console.log('createCourseDto::', createCourseDto);
  }`

Not uploading images in **UPLOADS** folder. but logging courseDTO. Any clue what am i doing wrong here?

**Comment by nartc** [comment]
@iaakash I don't know whether you've solved the issue but you need to set `properties: { 'additional_image': {...} }` instead of `properties: { file: {...} }`

**Comment by ilyassFouih** [comment]
hey @nartc i'm using [this decorator ](https://github.com/nestjs/swagger/issues/417#issuecomment-590988354) for multiple files .
it work fine .
But when adding @Body() with associated DTO swagger doesn't detect it 


my controller 
```typescript
    @Post('create-files')
    @ApiOperation({
        summary: "creating multiple files with info ",
    })
    @ApiConsumes('multipart/form-data')
    @ApiMultiFile("files") 
    @myFileInterceptor()
    async uploadMultipleFiles(
        @UploadedFiles() files ,
        @Body() createFilesDto:CreateFileDto) {
        return this.myService.create(files,createFilesDto)
    }

```
apiMultiFile decorator 
```typescript
import { ApiBody } from '@nestjs/swagger';

export const ApiMultiFile = (fileName: string = 'files'): MethodDecorator => (
    target: any,
    propertyKey: string,
    descriptor: PropertyDescriptor,
) => {
    ApiBody({
        type: 'multipart/form-data',
        required: true,
        schema: {
            type: 'object',
            properties: {
                [fileName]: {
                    type: 'array',
                    items: {
                        type: 'string',
                        format: 'binary',
                    },
                },
            },
        },
    })(target, propertyKey, descriptor);
};
```
***PS*** : CreateFilesDto  work fine with other route
