### ISSUE TITLE
[regression] i no longer can specify base path

### ISSUE THREAD

**Issue by constb** [nestjs/swagger#435]
## I'm submitting a regression report
<pre><code>
[x] Regression
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
`setBasePath` is no longer available at DocumentBuilder.

In my project URL prefixes exist, but are being stripped by an API Gateway. Nest Swagger v4 requires you to set global prefix in order to have the base path, but in my case it *must not* be set in nest application, and it *must* be present in swagger.

## Expected behavior
`setBasePath` available on DocumentBuilder, allowing to override global prefix setting.

This probably relates to #307 to some extent, although that issue is about swagger url itself, whereas my problem is with the api descriptions.

**Comment by kamilmysliwiec** [comment]
Just use `addServer` instead
