### ISSUE TITLE
Is there any way to use the @ApiResponse() decorator on global level

### ISSUE THREAD

**Issue by Gowtham029** [nestjs/swagger#439]
Hi All,

Is there any way to use the @ApiResponse() decorator on global level.

Currently I am using @ApiResponse() decorator on controller level.

Please Provide some examples if possible.

Thanks.

**Comment by kamilmysliwiec** [comment]
You can create a composed decorator and apply it to every controller https://docs.nestjs.com/custom-decorators#decorator-composition
