### ISSUE TITLE
Setting Example data

### ISSUE THREAD

**Issue by harry-sm** [nestjs/swagger#45]
Hello, 
Is there a decorator for setting the example values for swagger as seen below?

![image](https://user-images.githubusercontent.com/15040197/35612170-c6152156-0635-11e8-9c0e-6155d3d2fa19.png)

Thanks.

**Comment by kamilmysliwiec** [comment]
Thanks to this PR https://github.com/nestjs/swagger/pull/46, you'll be able to pass `example` value to each property. I'll publish it soon

**Comment by harry-sm** [comment]
Fantastic!
