### ISSUE TITLE
UI won't acknowledge required parameter value

### ISSUE THREAD

**Issue by tomdeman** [nestjs/swagger#47]
I am trying to use the swagger ui. it works as expected when a data model is provided for the parameters.

However, when there are route param set via decorators @Get(':id'), entering a value does not satisfy the required validation

the field input takes on the styling of an empty required field and you cannot execute the request regardless of there being a value entered in the input

**Comment by kamilmysliwiec** [comment]
Could you show code/share screenshot of swagger UI?
