### ISSUE TITLE
@ApiHideProperty cannot be wrapped in a custom decorator unlike @ApiProperty

### ISSUE THREAD

**Issue by aravindanve** [nestjs/swagger#493]
# Bug report

## Current behavior
I'm using TypeORM and OpenAPI (Swagger) together in a NestJS project. I realized that for every property of TypeORM entity I decorate with `@Exclude()`, I have to also decorate it with `@ApiHideProperty()`. For every property I decorate with `@Expose()`, I have to also decorate it with `@ApiProperty()`.

I decided to override `class-validator`'s `Expose` with my own function:

```ts
import * as ct from 'class-transformer';
import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';
```

```ts
// infer @ApiProperty when @Expose is used
((_Expose: any, _ApiProperty: any) => (ct as any).Expose = (...args) => {
  const _expose = _Expose(...args);
  const _apiProperty = _ApiProperty(...args);
  return (target: Object, propertyKey: string | symbol) => {
    _expose(target, propertyKey);
    _apiProperty(target, propertyKey);
  };
})(ct.Expose, ApiProperty);
```

This works as expected. TypeORM includes the property when serializing to JSON and swagger shows the property in the docs. However, this does not seem to work with `@ApiHideProperty()`

```ts
// infer @ApiHideProperty when @Exclude is used
((_Exclude: any, _ApiHideProperty: any) => (ct as any).Exclude = (...args) => {
  const _exclude = _Exclude(...args);
  const _apiHideProperty = _ApiHideProperty(...args);
  return (target: Object, propertyKey: string | symbol) => {
    _exclude(target, propertyKey);
    _apiHideProperty(target, propertyKey);
  };
})(ct.Exclude, ApiHideProperty);
```

## Expected behavior
`@ApiHideProperty` must behave as `@ApiProperty` does when wrapped in another decorator.

## Probable Cause
After some digging around, I found that ApiHideProperty is an empty function that does nothing. It appears that the visitor checks if the property is simply decorated with ApiHideProperty, instead of going by the metadata.

https://github.com/nestjs/swagger/blob/bf533bb85067a9579a7a6b5d631fbffbf41c5f39/lib/plugin/visitors/model-class.visitor.ts#L39-L45

## Environment
Nest version: 12.8.0
nestjs/swagger version: 4.1.12
nestjs/typeorm version: 6.2.0
TypeORM driver: pg

**Comment by kamilmysliwiec** [comment]
> After some digging around, I found that ApiHideProperty is an empty function that does nothing. It appears that the visitor checks if the property is simply decorated with ApiHideProperty, instead of going by the metadata.

Yes, that's true. The plugin uses AST and never lookups the runtime metadata. Hence, you shouldn't use `@ApiHideProperty()` in composed decorators. We should add a note about this in the docs. Let's track this here https://github.com/nestjs/docs.nestjs.com/issues/941
