### ISSUE TITLE
[Help] ApiResponse, getAll, list of a type

### ISSUE THREAD

**Issue by otroboe** [nestjs/swagger#50]
Hello guys !

I'm nest with NestJS, and new with TS also. I'm trying to implement a basic API, and I have trouble to use the `@ApiResponse` while defining a list.

I was looking at this issue: https://github.com/nestjs/swagger/issues/41
But I clearly don't understand what's happening.

I'm trying something like this:
```javascript
import { ApiModelProperty } from '@nestjs/swagger';

export class Location {
  @ApiModelProperty()
  id: string;

  @ApiModelProperty()
  name: string;
}
```

```javascript
  @Get()
  @ApiResponse({
    type: Location[],
  })
  findAll() {}
```
And I don't know how to configure the `type` to understand that I want a list of `Location`.

Thank you !

**Comment by fwoelffel** [comment]
You should use set the `isArray` property to `true` ;)

```js
  @Get()
  @ApiResponse({
    type: Location,
    isArray: true
  })
  findAll() {}
```

**Comment by otroboe** [comment]
So simple ! Thank you very much !
