### ISSUE TITLE
Swagger-Codegen

### ISSUE THREAD

**Issue by tx4x** [nestjs/swagger#51]
Hi,
I am not sure I understand this all but how I am suppose to be generating the client files via 'swagger-codegen' ? It seems to require a config but I can't find anything about in the repo here.

thanks in advance

**Comment by tx4x** [comment]
got it,

1. server.use('/json',(req,res,next)=> res.send(document));
2. then use that url for swagger-codege

**Comment by below-1** [comment]
How do you get "document"?

**Comment by below-1** [comment]
Sorry, got it.
