### ISSUE TITLE
It’s not been called Swagger for years 

### ISSUE THREAD

**Issue by philsturgeon** [nestjs/swagger#539]
Howdy! Somebody submitted this tool to [openapi.tools](http://OpenAPI.tools) (https://github.com/apisyouwonthate/openapi.tools/pull/168) but we noticed you’ve called it swagger. The specification has been called “OpenAPI” not Swagger since 2016, and now Swagger just refers to the SmartBear tool suite: Swagger UI, Swagger Editor, etc. 

Could you folks give this a more appropriate name whenever you get the chance? It’ll help people find it, as swagger is outdated now. Cheers!

**Comment by kamilmysliwiec** [comment]
We updated the description, README, and documentation. We won't change the name of this repo nor the name of NPM package to avoid introducing unnecessary breaking changes.

**Comment by philsturgeon** [comment]
Thank you. Could I recommend the next major version is a new NPM module, with the old one being deprecated and pushing people to the new one? GitHub repos can just be renamed without any trouble as everything redirects.
