### ISSUE TITLE
nest-cli swagger plugin don't work

### ISSUE THREAD

**Issue by ES-SOFYANY** [nestjs/swagger#558]
my nest-cli.json:

```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      "@nestjs/swagger/plugin"
    ]
  }
}

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by ES-SOFYANY** [comment]
for example, the model that I want to expose is:

```
export class PersonDto {
    @ApiProperty()
    fullname: string;

    @ApiProperty()
    age: number;

    @ApiProperty()
    birthDate: Date;
}
```

I add the configuration above in nest-cli.json and I remove @ApiProperty from my model:

```
export class PersonDto {
    fullname: string;
    age: number;
    birthDate: Date;
}
```

but the plugin don't work: my swagger-ui dont display the fields of PersonDto.
```
nest -version: 6.14.2

 "dependencies": {
    "@nestjs/common": "^6.7.2",
    "@nestjs/core": "^6.7.2",
    "@nestjs/platform-express": "^6.7.2",
    "@nestjs/swagger": "^4.1.12",
    "@nestjs/typeorm": "^6.2.0",
    "class-transformer": "^0.2.3",
    "class-validator": "^0.11.0",
    "mysql": "^2.17.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.0",
    "rxjs": "^6.5.3",
    "swagger-ui-express": "^4.1.2",
    "typeorm": "^0.2.22"
  }

```

**Comment by kamilmysliwiec** [comment]
Please, remember to use `nest build` to build your sources instead of `ts-node` or `tsc`. This is a requirement to use a plugin

**Comment by ES-SOFYANY** [comment]
Firstly thank you for your response.
I used ``` nest build```  then i launched the app ``` nest start```  but doesn't work.
I used ``` nest build```  then i launched the app ``` nest start:prod```  but doesn't work.

**Comment by Brian611** [comment]
I have the exact same issue this does not work at all.
