### ISSUE TITLE
nest-cli swagger plugin don't work

### ISSUE THREAD

**Issue by Brian611** [nestjs/swagger#568]
Nest cli json file

`{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      "@nestjs/swagger/plugin"
    ]
  }
}`

Dto

`export class CustomerDto {
    fullname: string;
    age: number;
}`

My package json
`
"dependencies": {
    "@nestjs/common": "^6.7.0",
    "@nestjs/core": "^6.7.0",
    "@nestjs/passport": "^6.1.0",
    "@nestjs/platform-express": "^6.8.3",
    "@nestjs/swagger": "^4.2.9",
    "@nestjs/typeorm": "^5.3.0",
    "@types/bcrypt": "^3.0.0",
    "@types/dotenv": "^6.1.1",
    "bcrypt": "^3.0.6",
    "class-transformer": "^0.2.3",
    "class-validator": "^0.9.1",
    "cross-env": "^7.0.0",
    "dotenv": "^6.2.0",
    "mssql": "^6.0.1",
    "reflect-metadata": "^0.1.12",
    "rimraf": "^2.6.2",
    "rxjs": "^6.2.2",
    "swagger-ui-express": "^4.1.3",
    "typeorm": "^0.2.14",
    "typescript": "^3.0.1"
  }
`

i tried deleting dist and doing nest build. But still my dto's do not get shown on swagger.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by Brian611** [comment]
Company repo my apologies please try to create a project with the versions provided. Seems this bug is not present on a brand new nest project. 

Side note updating to latest does not fix it either so only a nest new project does.

**Comment by kamilmysliwiec** [comment]
> Company repo my apologies please try to create a project with the versions provided

So please, prepare a **minimal** repository without your private company code which reproduces your issue. There's certainly something wrong with your configuration, it's not a bug.

**Comment by Brian611** [comment]
Ohk will do. Thanks for the swift response.

**Comment by dsyncerek** [comment]
@Brian611 maybe your entity/dto file names don't end with `.entity.ts`/`.dto.ts`, because only these files are loaded by plugin by default.

**Comment by Brian611** [comment]
i gave up and ended up creating a new project with nest new which has nest build and other updated packake.json commands.

Older projects seem to have an issue. You can have a look at numerous bugs logged relating to this most didn't solve this.

**Comment by kamilmysliwiec** [comment]
> You can have a look at numerous bugs logged relating to this most didn't solve this.

Please, point us at these "numerous bugs" and solutions you've tried. Also, I asked twice for sharing the reproduction repo. I'm pretty sure your configuration is wrong.
