### ISSUE TITLE
Feature Request: Export to JSON

### ISSUE THREAD

**Issue by cdiaz** [nestjs/swagger#57]
It would be very useful can export the Swagger documentation to JSON for external use, or exchange among other tools.

[example
](http://petstore.swagger.io/v2/swagger.jsonl)

**Comment by malbertSC** [comment]
It would probably be useful to add to the docs, but if you're just asking for how to do this:

```
    const app = await NestFactory.create(ApplicationModule);
    const options = new DocumentBuilder()
        .setTitle("Title")
        .setDescription("description")
        .setVersion("1.0")
        .build();
    const document = SwaggerModule.createDocument(app, options);

    fs.writeFileSync("./swagger-spec.json", JSON.stringify(document));
    SwaggerModule.setup("/api", app, document);

    await app.listen(80);
```

**Comment by cdiaz** [comment]
thanks @malbertSC

**Comment by TristanMarion** [comment]
Or try to add -json at the end of your URL path, there is a hint about this in the doc : https://docs.nestjs.com/recipes/swagger

(Works with custom path, always add -json at the end of your URL)
