### ISSUE TITLE
Allow more options in ApiResponseProperty

### ISSUE THREAD

**Issue by tsapko3628** [nestjs/swagger#570]
https://github.com/nestjs/swagger/blob/46795f0876bfb0176ca2304b1c51eb01559f1980/lib/decorators/api-property.decorator.ts#L34

Remove `Pick` from ApiResponseProperty options types. Allot of options like `isArray` i cannot pass, cause typescript throw error

**Comment by kamilmysliwiec** [comment]
You can always use `ApiProperty` instead (they behave equally)

**Comment by tbrannam** [comment]
there seems to be a difference in the implementation - specifically `ApiResponseProperty` seems to internally add `{ readOnly: true }` to options, which isn't in the ApiProperty options either.  Without this readonly property, I don't see a way to mask fields that aren't available during create/update but may be present on the return values.
