### ISSUE TITLE
Decorator APIProduces doesn't work

### ISSUE THREAD

**Issue by VaultDeveloper** [nestjs/swagger#626]
## I'm submitting a Potential bug
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I use `nestjs/swagger` with `swagger-ui-express`.
I set the decorator `@ApiProduces("text/csv")` but nothing is displayed in Swagger-ui.
I check the produced specs using F12 on Swagger-UI and nothing, in the specs, involved "Produces".

## Expected behavior
The user can choose the Content-Type of the Response in Swagger-UI. As shown on the image below. This image is generated with YAML.
![image](https://user-images.githubusercontent.com/1583606/77440103-30fdc880-6de8-11ea-8f0d-635cf9c11e73.png)

The `GET` attribute has :
```
produces:
        - application/json
        - text/csv
```

## Minimal reproduction of the problem with instructions
Insert this function in a controller.
```
@Get('thing')
@ApiProduces("text/csv")
// @ApiProduces("text/csv", "application/json")
public test(): any {
	return {
		id: "id",
		name: "name"
	};
}
```

## Environment

Last version.
<pre><code>
"@nestjs/common": "^6.7.2",
"@nestjs/config": "0.0.9",
"@nestjs/core": "^6.7.2",
"@nestjs/platform-express": "^6.7.2",
"@nestjs/swagger": "^4.4.0",
"swagger-ui-express": "^4.1.4"
 
For Tooling issues:
- Platform: Windows
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by VaultDeveloper** [comment]
I created a repo: https://github.com/VaultDeveloper/SwaggerAPIProduces/tree/master
Install process in the readme :

```
git clone https://github.com/VaultDeveloper/SwaggerAPIProduces.git
cd repro
npm i
npm install --save reflect-metadata rxjs
npm run start
```

Impossible to check produced type.

![image](https://user-images.githubusercontent.com/1583606/77454006-45e25800-6df8-11ea-8f18-050bc9d7bf6a.png)

**Comment by kamilmysliwiec** [comment]
@VaultDeveloper https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md
The latest version of OpenAPI specification doesn't include `produces` key anymore. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by zachgoll** [comment]
@kamilmysliwiec I am running into this issue as well.  The `ApiProduces()` and `ApiConsumes()` decorators work at the method level, but not the controller level as [stated in the documentation](https://docs.nestjs.com/recipes/swagger#decorators).

I understand that the [new OpenApi Spec](https://swagger.io/docs/specification/media-types/) does not include the key, but what should I be using to define the media type in the NestJS API?

Specifically, I am using the `application/vnd.api+json` media type from the JSON API spec.

Any guidance here would be appreciated.

**Comment by VaultDeveloper** [comment]
@kamilmysliwiec Is there a way to downgrade the version of OpenAPI we are using ?

**Comment by VaultDeveloper** [comment]
@zachgoll I found a way.

```typescript
@Get(':id')
@ApiProduces("application/json", "application/vnd.api+json")
@ApiCreatedResponse({
	type: MyModel
})
public getModel(@Param('id') psModelId: string): MyModel {
	return {
		id: "123456789-12",
		body: ""
	};
}
```
MyModel is a classic Typescript class containing attribute `id` and `body`.
```typescript
export class MyModel {
	@ApiProperty()
	id: string;

	@ApiProperty()
	body: string;
}
```

**Comment by CodalReef** [comment]
I made a tweak to make this work for Swagger 3 with the JS Codegen tool:

```typescript
  @ApiProduces('image/png')
  @ApiResponse({
    status: 200,
    schema: {
      type: 'string',
      format: 'binary',
    },
  })
```

The Swagger JSON produced looks like this:  
```json
{
"responses":{"200":{"description":"","content":{"image/png":{"schema":{"type":"string","format":"binary"}}}}}
}
```

Which matches the Swagger 3 Docs for Binary Files:  https://swagger.io/docs/specification/basic-structure/
