### ISSUE TITLE
@ApiModelProperty - Disable option when extends 

### ISSUE THREAD

**Issue by UnknownHero** [nestjs/swagger#64]
Hello!

I want to extend basic model, something like "class UpdateUserModel extands UserModel"
And i want to hide some properties like "id" or "email" for documentation in UpdateUserModel

Now i find only one way - don't extends basic class and copy shared properties and don't copy excluded properties.

**Comment by kamilmysliwiec** [comment]
That's a bit weird that you want to extend something and then hide its properties. IMHO it's better to copy & paste properties instead of this kind of improper class hierarchy.

**Comment by harishanchu** [comment]
I have a use case for this.

Lets say I create a nestjs library module with all the authentication code which can be imported to any nest js project to have authentication support(registration, login, reset password etc).

Now the project that imports this authentication module may not need some of the fields that are  defined(and decorated with swagger `@ApiProperty`) in the auth library module `Registration.dto.ts` file. So when I extend the `Registration.dto.ts` to incorporate project specific needs (remove some fields) I can remove that field using `@Exclude` decorator of class-validator. But currently there is no way to get rid of swagger metadata defined in the super class for the property .

**Comment by kamilmysliwiec** [comment]
> Now the project that imports this authentication module may not need some of the fields that are defined(and decorated with swagger @ApiProperty) in the auth library module Registration.dto.ts file. So when I extend the Registration.dto.ts to incorporate project specific needs (remove some fields) I can suppress user input for that field using @Exclude decorator of class-validator. But currently there is no way to get rid of swagger metadata defined in the super class for the property, hence property will be still visible in the final swagger specification generated .

So if you want to use a class which defines more properties than you need, you shouldn't use the class in the first place.

**Comment by harishanchu** [comment]
I'm currently using a decorator of my own:

```typescript
import { DECORATORS } from '@nestjs/swagger/dist/constants';

export function ApiRemoveProperty(): PropertyDecorator {
  return removePropertyDecorator(
    DECORATORS.API_MODEL_PROPERTIES,
  );
}

function removePropertyDecorator(metakey: string): PropertyDecorator {
  return (target: object, propertyKey: string) => {
    const properties =
      Reflect.getMetadata(DECORATORS.API_MODEL_PROPERTIES_ARRAY, target) || [];
    const key = `:${propertyKey}`;

    if (properties.includes(key)) {
      properties.splice(properties.indexOf(key), 1);
    }

    Reflect.deleteMetadata(metakey, target, propertyKey);
  };
}

```

**Comment by harishanchu** [comment]
> > Now the project that imports this authentication module may not need some of the fields that are defined(and decorated with swagger @ApiProperty) in the auth library module Registration.dto.ts file. So when I extend the Registration.dto.ts to incorporate project specific needs (remove some fields) I can suppress user input for that field using @exclude decorator of class-validator. But currently there is no way to get rid of swagger metadata defined in the super class for the property, hence property will be still visible in the final swagger specification generated .
> 
> So if you want to use a class which defines more properties than you need, you shouldn't use the class in the first place.

It's not that I don't want some properties from parent class. I don't want user to supply it through rest API. I don't want it to be displayed in swagger rest specification as a property in the request body schema.
