### ISSUE TITLE
OpenAPI 3 Cookie Authentication Support

### ISSUE THREAD

**Issue by rafaelkallis** [nestjs/swagger#649]
## Feature Request (PR #650 + [docs PR](https://github.com/nestjs/docs.nestjs.com/pull/1131))

OpenAPI 3 supports [Cookie Authentication](https://swagger.io/docs/specification/authentication/cookie-authentication/). The `@nestjs/swagger` module currently only supports that through the `@ApiSecurity()` decorator. 

Cookie authentication support could be improved by having an api similar to other existing authentication mechanisms:

```
// main.ts
const options = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .addCookieAuth() // <- adds cookie authentication
    .build();

// cats.controller.ts
@ApiCookieAuth() // <- adds cookie authentication
@Controller('cats')
export class CatsController {}
```

**Comment by kamilmysliwiec** [comment]
Merged! Will be available in the next minor release :)

**Comment by SathursanS** [comment]
Is cookie authentication fully functional in nest, according to https://swagger.io/docs/specification/authentication/cookie-authentication/, cookie authentication for "try it out" is no supported is this the same case for nest?

**Comment by hl-a-k** [comment]
> 

I have tested it.  It is not fully functional. Same reason to https://github.com/swagger-api/swagger-editor/issues/1951
Any plan for it ?

**Comment by alereca** [comment]
As an alternative solution relying on ```withCredentials: true``` in ```SwaggerCustomOptions``` worked for me
```javascript
  const customOptions: SwaggerCustomOptions = {
    swaggerOptions: {
      withCredentials: true,
    },
  };

  SwaggerModule.setup('api', app, document, customOptions);
```
As a reference: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#withCredentials
> withCredentials -> Boolean=false If set to true, enables passing credentials, [as defined in the Fetch standard](https://fetch.spec.whatwg.org/#credentials), in CORS requests that are sent by the browser. ***Note that Swagger UI cannot currently set cookies cross-domain (see [swagger-js#1163](https://github.com/swagger-api/swagger-js/issues/1163)) - as a result, you will have to rely on browser-supplied cookies (which this setting enables sending) that Swagger UI cannot control.***

So each time I make a request to ***/app/auth/login*** or ***/app/auth/login*** an http-only same-site cookie is stored by the browser and then it will be appended to each following request (so this approach avoids setting the authorization Swagger UI field)
``` javascript
  @Post('login')
  @HttpCode(200)
  async login(
    @Body(AppValidationPipe) loginDto: LoginDto,
    @Res() response: Response,
  ) {
    const loggedUser = await this.authService.login(loginDto);
response.cookie('accessToken', loggedUser.accessToken, {
      expires: addMinutes(new Date(), loggedUser.accessTokenExpiration),
      httpOnly: true,
      sameSite: 'strict',
    });
}
```
After that ```IsAuthGuard``` can parse the cookies attached to request. (remeber installing cookie-parser as stated in nestjs docs https://docs.nestjs.com/techniques/cookies)
```javascript
  async canActivate(context: ExecutionContext) {
    const request: RequestWithUser = context.switchToHttp().getRequest();

    const fullInputToken: string | undefined = request.cookies['accessToken'];
    if (!fullInputToken) throw new Unauthorized('Token not provided');

    const tokenWithoutPrefix = fullInputToken.replace('Bearer ', '');
}
```
