### ISSUE TITLE
Array in query string parameters

### ISSUE THREAD

**Issue by malbertSC** [nestjs/swagger#66]
Per the swagger spec, query string params can be specified as an array by using `type: "array"` along with `items: [type of array items]`.  This doesn't appear to be possible with the existing `ApiImplicitQuery` options.  Is there another way or recommended approach for how to support query string params that are arrays?

Thanks!

**Comment by malbertSC** [comment]
I ended up making a PR for this: https://github.com/nestjs/swagger/pull/67

**Comment by kamilmysliwiec** [comment]
Merged, thanks! 🔥
