### ISSUE TITLE
MIME-Types for produces and consumes are created twice

### ISSUE THREAD

**Issue by arkraft** [nestjs/swagger#69]
When creating a swagger documentation, i get the following error in Swagger-Editor:

```
Schema error at paths['/health'].get.consumes
should NOT have duplicate items (items ## 0 and 1 are identical)
```
## How to Reproduce

As a minimal example i used this method:

```javascript
@Controller()
export class HealthController {

    @ApiResponse({ status: HttpStatus.OK})
    @Get("health")
    public async health() {
        return { status: "OK" };
    }
}
```
## What do you expect?

As i did not use the `ApiProduces` decorator, i expect the default `application/json` MIME-Type to be used.

## What actually happens?

I get the following output in swagger:

```yaml
paths:
  /health:
    get:
      responses:
        '200':
          description: when the server is reachable
      produces:
        - application/json
        - application/json
      tags:
        - health
      consumes:
        - application/json
        - application/json
```

As you can see the produces and consumes are there twice.
Also, when defining a custom MIME-Type with `@ApiProduces("text/csv")`, i have the custom MIME-Type, but also `application/json` in the swagger docs.

```yaml
produces:
        - application/json
        - text/csv
```

**Comment by kamilmysliwiec** [comment]
Fixed in `v1.3.0.
