### ISSUE TITLE
@ApiBearerAuth() does not work on Method level

### ISSUE THREAD

**Issue by nartc** [nestjs/swagger#70]
![image](https://user-images.githubusercontent.com/25516557/38385228-f4765afa-38d6-11e8-8815-d4f8754a0280.png)
![image](https://user-images.githubusercontent.com/25516557/38385238-fd0f2372-38d6-11e8-8b22-6ec278982349.png)
As title said, the `@ApiBearerAuth()` decorator does not work properly on `method` level. It does work correctly on `Controller` level. The documentations states that the decorator can work on either Method or Controller level. I was just wondering if this's a bug or I didn't implement it correctly.

![image](https://user-images.githubusercontent.com/25516557/38385279-13168070-38d7-11e8-9459-2ed4cb889efa.png)
Worked on Controller level

**Comment by milescui** [comment]
I also encountered the same problem

**Comment by shekohex** [comment]
reverted back to `v1.1.4` and it seems works at this version.

**Comment by nartc** [comment]
Thanks but I do not consider reverting to an older version a solution. I need the `enum` from the current versions as well.

**Comment by mmenik** [comment]
Same problem for me

**Comment by kamilmysliwiec** [comment]
Fixed due to #79 and published as a `v1.3.0` already.

**Comment by jienco** [comment]
I am having this issue again, using @nestjs/common 5.0.0, @nestjs/core 5.0.0 and @nestjs/swagger 2.0.0

**Comment by careuno** [comment]
I have it in controller level

`@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
export class AdminController {`

version 5.1.0

**Comment by trileou** [comment]
I fixed it by add this line to main.ts (or wherever you register nestjs-swagger)

`  const options = new DocumentBuilder()
    **.addBearerAuth()**
    .setTitle('Payment Request Management')
    .setDescription('The payment request management API description')
    .setBasePath('api')
    .setVersion('1.0')
    .build();
    
    
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('v1', app, document);
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      whitelist: true,
    }),
  );`

**Comment by nartc** [comment]
@trileou thanks but this was a really old issue and it got addressed (fixed) a couple major versions back.

**Comment by nyrrrr** [comment]
still not working on current version

**Comment by loban** [comment]
> still not working on current version

Yeah, I was facing this problem, and I just figured out the bug.

It was introduced in an erroneous commit at https://github.com/nestjs/swagger/commit/916be52418600c3ec5fa984d0ae323e004f43cbd#diff-b0ad145a500347ad4d7404490dbce088L24 

I'll file a new issue (since this is old and closed), and make a PR to fix it.

**Comment by loban** [comment]
https://github.com/nestjs/swagger/issues/522
