### ISSUE TITLE
Preserve auth token in localStorage

### ISSUE THREAD

**Issue by oleksii-shnyra** [nestjs/swagger#71]
Hello, currently after pressing the authorize button JWT token sent along with requests until a user refreshes a page.

After **each page refresh** user should authorize again.

I think it's a bug and _token should be saved in localStorage_ or sessionStorage (for security reasons).

But at least I want to have a checkbox "remember me" in authorization modal window so I can easily use just Swagger without any additional tools like Modheader.

**Comment by kamilmysliwiec** [comment]
Hi @oleksii-shnyra,
This is rather a feature request to the underlying swagger-ui-express library.

**Comment by waynebloss** [comment]
Solution: https://github.com/scottie1984/swagger-ui-express/issues/44#issuecomment-605088470

**Comment by sagic** [comment]
if anyone still need a simple solution:

```
  SwaggerModule.setup('api', app, document, {
    swaggerOptions: {
      persistAuthorization: true,
    },
  });
```

**Comment by SathursanS** [comment]
> if anyone still need a simple solution:
> 
> ```
>   SwaggerModule.setup('api', app, document, {
>     swaggerOptions: {
>       persistAuthorization: true,
>     },
>   });
> ```

Does this solution work for Swagger's BearerAuth, based on my testing this doesn't work.

**Comment by sagic** [comment]
> > if anyone still need a simple solution:
> > ```
> >   SwaggerModule.setup('api', app, document, {
> >     swaggerOptions: {
> >       persistAuthorization: true,
> >     },
> >   });
> > ```
> 
> Does this solution work for Swagger's BearerAuth, based on my testing this doesn't work.

yep

**Comment by vahidvdn** [comment]
@sagic Thanks. It works fine.

**Comment by VaultDeveloper** [comment]
> 
> 
> > if anyone still need a simple solution:
> > ```
> >   SwaggerModule.setup('api', app, document, {
> >     swaggerOptions: {
> >       persistAuthorization: true,
> >     },
> >   });
> > ```
> 
> Does this solution work for Swagger's BearerAuth, based on my testing this doesn't work.

Took my one reload to understand that it then works.
