### ISSUE TITLE
Feature Request:  Provide simple way to automatically download JSON docs

### ISSUE THREAD

**Issue by jaufgang** [nestjs/swagger#72]
There have been a couple previous questions asked about obtaining the swagger documentation in JSON format (see #21 and #57), and responses to these issues show how to add code to serve the JSON or save it to a file.

I think it would be a great improvement if the SwaggerModule could simply serve the JSON for any doc without any additional code based on an additional path param or query string param in the URL.  For example, if you set up your documentation like this: 

```
 SwaggerModule.setup('/api', app, document);
```

Then maybe by getting `/api/json` or `/api?json` or `/api?json=true`, it would serve the docs in JSON format instead of the HTML version.  

This could be enabled automatically for any doc, and existing projects using `@nestjs/swagger` would gain this feature by upgrading to a new release without making any code changes at all.  :)

**Comment by kamilmysliwiec** [comment]
This feature is available in `v1.3.0`. Simply add `-json` as a suffix, for example:
```
/api-json
```
