### ISSUE TITLE
How to hide Schemas models that shown in last of swagger documentation page

### ISSUE THREAD

**Issue by leefordjudes** [nestjs/swagger#722]
How to hide Schemas models that shown in last of the swagger documentation page

Is there any way to hide Schemas models that shown in last of swagger documentation page

**Comment by kamilmysliwiec** [comment]
It isn't possible ATM. We don't plan to release such a feature any time soon.

**Comment by Semyonic** [comment]
To help whom came here for hiding schemas/models

For `"@nestjs/swagger": "^4.6.1"`

It can be done by giving prop as below:

```ts
SwaggerModule.setup('swagger', app, document, {
    swaggerOptions: { defaultModelsExpandDepth: -1 },
  });
```

**Comment by AvantaR** [comment]
Thanks, @Semyonic! It would be great to add that to the docs.

**Comment by leefordjudes** [comment]
you can use this also: 

 const administrationOptions = new DocumentBuilder()
    .setTitle('Administration API')
    .addTag('User')
    .setDescription('Administration API description')
    .setVersion('1.0')
    .build();
  const administrationDocument = SwaggerModule.createDocument(app, administrationOptions, {
    include: [AdministrationModule],
    deepScanRoutes: true,
  });

const swaggerCustomOptions = { customCss: '.swagger-ui section.models { visibility: hidden;}' };
  SwaggerModule.setup('/api/v1/docs/administration', app, administrationDocument, swaggerCustomOptions);
