### ISSUE TITLE
Links not available through decorators

### ISSUE THREAD

**Issue by Mark-McCracken** [nestjs/swagger#729]
Reopening of #157 

This was closed 18 months ago, as the library did not support OAS 3 at the time.

Can this be implemented now that we support OAS 3?

Need any help? Can't imagine this is really difficult, as the typescript definitions already appear to exist.

Regards,
Mark

**Comment by kamilmysliwiec** [comment]
You can pass the `links` property via the `@ApiResponse` decorator https://github.com/nestjs/swagger/blob/master/lib/interfaces/open-api-spec.interface.ts#L155

We don't plan to add more abstraction on top of this feature.
