### ISSUE TITLE
Allow to chose Execution or Explorer oriented modes

### ISSUE THREAD

**Issue by oleksii-shnyra** [nestjs/swagger#73]
Hello, current version of Swagger UI is modern but not so practical as older versions.

Currently, when we expand endpoint documentation first we see this button `try it out`

<img width="619" alt="screen shot 2018-04-19 at 12 35 57 am" src="https://user-images.githubusercontent.com/24607667/38959570-ce0561b6-4369-11e8-90f1-e3dca775f13f.png">

And only after pressing `try it out` button new buttons `execute` and `clear` appeared:

<img width="617" alt="screen shot 2018-04-19 at 12 36 16 am" src="https://user-images.githubusercontent.com/24607667/38959645-148062da-436a-11e8-8812-b0d7afacf190.png">

# Desired behaviour

I want to have ability to avoid this redundant step of `try it out` clicking and see `execute` button right away after expending the endpoint. This is a much more convenient way to use Swagger.

I didn't find how to do this. Is it possible already?

Please allow to use much more convenient way to use Swagger like this:

```js
const options = new DocumentBuilder()
        .setMode('execution' || 'explorer')
        .build();

/*
Execution mode steps:
1. Expand
2. Execute

Explorer mode steps:
1. Expand
2. Try it out
3. Execute
*/
```

**Comment by kamilmysliwiec** [comment]
Hi @oleksii-shnyra,
This is rather a feature request to the underlying [swagger-ui-express](https://github.com/scottie1984/swagger-ui-express) library.
