### ISSUE TITLE
Export documentation

### ISSUE THREAD

**Issue by menme95** [nestjs/swagger#75]
I'd want to export my api documentation from swagger, are there any way?
If it isn't, will be it possible?

**Comment by arkraft** [comment]
@malbertSC described this in another issue: https://github.com/nestjs/swagger/issues/57#issuecomment-368238060

**Comment by menme95** [comment]
That works perfecly, thax!

**Comment by TristanMarion** [comment]
Or try to add `-json` at the end of your URL path, there is a hint about this in the doc : https://docs.nestjs.com/recipes/swagger
