### ISSUE TITLE
Allow @body on GET Request

### ISSUE THREAD

**Issue by nil1990** [nestjs/swagger#779]
Please Allow body on get method

@Get()
 async getReviews(@Query() paginationDto: PaginationDto,@Body() filter: FilterDto[]) {
        console.log(filter);
        const result = await this.reviewService.getReviews(paginationDto);
        return { data: result };
}

When i tryed to user body to filter paginate data its not allowing Body on GET request.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
