### ISSUE TITLE
swagger middleware

### ISSUE THREAD

**Issue by maugenst** [nestjs/swagger#8]
In our project we are using swagger-express-mw to, on the one hand, describe our API and get an out-of-the box API documentation, and on the other hand, getting the validation magically against our swagger definition. 

By cross reading the code I am a bit confused on how this could incorporate since it is written as a "module" and not as a "middleware" which I thought it should since it should have access to req/res beforehand. Is this module meant to be something like the swagger-express-mw that does all the "magic" with, routing, parameter handling...? And if so, how is it initialized? And even better... do you support also swagger definitions written in yaml?

**Comment by kamilmysliwiec** [comment]
Hi @maugenst,
yeah, this module does all the "magic", the issue is that I can't find some spare time to describe all of the available API 🙁

**Comment by kamilmysliwiec** [comment]
Here's an example https://docs.nestjs.com/recipes/swagger 🙂
