### ISSUE TITLE
Abstract Document Generator

### ISSUE THREAD

**Issue by patrickhousley** [nestjs/swagger#81]
Feature Request:
Abstract away the code that actually generates the swagger document.

Why:
Abstracting the document generation will open the door to more easily supporting other document formats like Swagger v3 and Raml without taking away the Swagger v2 support. This could also lead to allowing users to implement their own document generator if they wish to.

**Comment by QuestionAndAnswer** [comment]
To add my five cents into this discussion, I would like to raise a topic about separate typescript compiler specifically for swagger module. In this case we might remove all ridiculous things, like explicit array flags set and type definitions when documenting API through decorators. 

This might be done in form of separate build tool, which utilizes functionality of typescript compiler API. We might traverse the tree, find required decorators, which will say what should be included into documentation and then extract all the types out of it. In the final solution it might work just as additional build step, which actually may be executed in parallel with ts compilation. 

Also, we might try to have this compilation plugin just to inject missing type information into run-time, in case if you wouldn't like the idea of complete generator extraction. In this case all the decorators will stay same, except, that we wouldn't need to specify any of optional or array types clarification, as well, as we might extract controller return type from definition.

I'm writing this first, just to get understanding, if it suitable for the format of nest, until I get started. What do you think?

**Comment by myflowpl** [comment]
I'm also for moving the swagger generation to build time where we have more information from typescript and then we will be able to drop all @ApiModelProperty decorators

The ideal world would be to just not invent the wheel again, and be able to user project like TSOA to do the job: https://github.com/lukeautry/tsoa
this library uses decorators only in controllers, models stay pure TS classes or interfaces

I'm not TypeScript master (yet), but the idea for me would be easy, just configure TSOA library to understand the nestjs decorators on the controllers and and it will be ready to generate the swagger document on build time 

any TypeScript wizard to put my idea into practice ?

**Comment by kamilmysliwiec** [comment]
The code has been heavily refactored. Although it's still far from being perfect, it should be much easier to contribute now.
