### ISSUE TITLE
Cannot use interface in @ApiProperty type

### ISSUE THREAD

**Issue by guizoxxv** [nestjs/swagger#812]
## I'm submitting a...
<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior

In `@ApiProperty` annotation, if I have an array of custom type as a property, I must provide a `type` with a class as the first element of an array in order for the schema to be mapped.

## Expected behavior

I expected to be able to use interfaces also.

## Minimal reproduction of the problem with instructions

Following the example in [https://docs.nestjs.com/recipes/swagger#arrays](https://docs.nestjs.com/recipes/swagger#arrays)
```
@ApiProperty({ type: [String] })
names: string[];
```
I used the following:
```
@ApiProperty({ type: [Cat] })
cats: Cat[];
```
If `Cat` is an interface I get the following error:

> 'Cat' only refers to a type, but is being used as a value here.

## What is the motivation / use case for changing the behavior?

I believe this is related to Typescript interface nature. If so, it would be nice to have a specification about the need to use classes or an explanation about why interfaces do not work here. 

## Environment
<pre><code>
Nest version: 7.1.3
 
For Tooling issues:
- Node version: 12.2.0
- Platform:  Linux
</code></pre>

**Comment by kamilmysliwiec** [comment]
This issue has been discussed many times in the past already - it's a TypeScript "limitation".
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by guizoxxv** [comment]
Hello, thank you for the quick response. I've searched past issues in this repository and in Stackoverflow with `nestjs` tag and did not find mention about this topic. If it was discussed in  Discord, I do not think that the tool is good for searching past issues. Also you could add a link to the Discord channel in the readme and/or GitHub `New issue` template.

I still believe that the documentation could mention this Typescript "limitation". I intended to open a pull request to the documentation with the following section but it is best to check here first.

> If you need a custom object as the type provide a class as interface type cannot be checked at runtime in Typescript.

**Comment by picbenoit** [comment]
Same question as you @guizoxxv and I didnot find answer on different forum.
The solution I found is to transform my interfaces to class.
But I still have a "type" that I cannot transform to class.

type MyType = MyClass1 & MyClass2 & MyClass3

If someone have a answer or a track for that, it will be great !
