### ISSUE TITLE
Swagger 2.0.0 throws empty page response with error in swagger-init-ui.js file.

### ISSUE THREAD

**Issue by ASTHASINGH2511** [nestjs/swagger#834]
![15937758130802977743839604366841](https://user-images.githubusercontent.com/37468518/86465134-b0d3f100-bd4e-11ea-9aa1-27a724ef03d2.jpg)

I am facing issue in generating a swagger page with all specs. Right now it's giving empty page. The error in browser console is "Uncaught exception : Unexpected identifier".

For my other APIs, Same code is working properly and I am getting my swagger page. 
![15937760576606193927116734638522](https://user-images.githubusercontent.com/37468518/86465449-41aacc80-bd4f-11ea-991f-824a42910fae.jpg)

Firiing api localhost:port/swagger
I am running the APIs through nodejs, version 12.0
Swagger is ran through node and checked in browser.

PS : I am new in all this.

**Comment by kamilmysliwiec** [comment]
Can you please share a minimum reproduction repository (with this issue)?

**Comment by LucaSiviero** [comment]
The post is super old, but usually the problem relies in using TS or JS objects inside DTO files.
In my case, I was using a plain zod enum to expose possible choices in a DTO. Either use a plain array, otherwise, with zod, use .options from the zod enum object
