### ISSUE TITLE
OpenAPI spec version

### ISSUE THREAD

**Issue by mmenik** [nestjs/swagger#85]
if I have not misunderstood, at this moment is implemented the specification 2.0, in the future do you think to implement the 3.0?

**Comment by kamilmysliwiec** [comment]
That's very likely

**Comment by ofavre** [comment]
I there any issue we could subscribe to, to get notified when it's ready?

**Comment by alexfrad** [comment]
Any update on that?

**Comment by Cobrand** [comment]
Does anyone have an estimate for when this might be implemented, if ever? Can we hope for 2019?

**Comment by affanshahid** [comment]
Any update on this?
