### ISSUE TITLE
Target es5 breaks nestjs/swagger

### ISSUE THREAD

**Issue by nodren** [nestjs/swagger#88]
If you take the nestjs/typescript-starter repo, and changing the `target` to es5 in tsconfig(and adding `lib: ['es6']`)

ApiModelProperty defined properties no longer are described in swagger.  running this correctly gives me a /api route with swagger ui, but the TestBody definition doesn't exist

app.controller.ts File:
```import { Get, Controller, Post, Body, Req } from '@nestjs/common';
import { AppService } from './app.service';
import { ApiModelProperty, ApiOperation } from '@nestjs/swagger';

export class TestBody {
  @ApiModelProperty() readonly email: string;
  @ApiModelProperty() readonly password: string;
}
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  root(): string {
    return this.appService.root();
  }

  @Post()
  async test(@Req() request, @Body() body: TestBody) {}
}
```

tsconfig.json file:
```
{
  "compilerOptions": {
    "lib": ["es6"],
    "module": "commonjs",
    "declaration": true,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

**Comment by kamilmysliwiec** [comment]
Why would you like to target `es5` when Nest is compiled to `es6`?

**Comment by nodren** [comment]
when using typescript client side via ts-loader & webpack, need to target es5 for browser compatibility.

my work around was to have two different tsconfig files, one webpack listens to, and another nest listens to

**Comment by kamilmysliwiec** [comment]
```
my work around was to have two different tsconfig files, one webpack listens to, and another nest listens to
```
This is the only possible solution actually.

**Comment by patrickhousley** [comment]
@kamilmysliwiec Would you please please please make note of this in the README.md. I just spent hours debugging Nest to find that the issue was caused by the target in the tsconfig. It is pretty common for angular/nest repos to have a target of es5 in the root of the project.
