### ISSUE TITLE
New NPM release, please.

### ISSUE THREAD

**Issue by AeroNotix** [nestjs/swagger#888]
Please can you make a new release on npm?

**Comment by kamilmysliwiec** [comment]
What's the reason?

**Comment by xStoryTeller** [comment]
$ npm i --save @nestjs/swagger
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nestjs%2fswagger - Not found
npm ERR! 404
npm ERR! 404  '@nestjs/swagger@^4.5.12' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by kamilmysliwiec** [comment]
This seems to be an issue with NPM, not the package itself (all good here: https://www.npmjs.com/package/@nestjs/swagger)

**Comment by AeroNotix** [comment]
You updated lodash: https://github.com/nestjs/swagger/commit/ba0954c96fbb194ea8ba3b1256f0a1cbab147f80

It was a CVE/npm audit fails with the older version of lodash. Nestjs/swagger is the only one of our deps which brings this in.

ergo, make a release, please.

**Comment by xStoryTeller** [comment]
This release is a month old, this is probably related to the current NPM status: https://status.npmjs.org/ 
"The ongoing issue may also affect installation of scoped packages. We continue investigating these issues."

**Comment by harrisonmuskat** [comment]
Lodash _was_ version-bumped in the commit here: https://github.com/nestjs/swagger/commit/91b054b7faf87df9bb036efda0f2fb1e3181f4cf - but there has not been a release since 6/29 and the master release is still using the old lodash dependency.

**Comment by eddiemonge** [comment]
@kamilmysliwiec ^^

**Comment by kamilmysliwiec** [comment]
Just published

**Comment by AeroNotix** [comment]
Dzieki!
