### ISSUE TITLE
Common swagger doc for multiple api's?

### ISSUE THREAD

**Issue by amit12cool** [nestjs/swagger#962]
Is there a way to have a single swagger doc for.multiple api's? May be selecting api's in a dropdown in swagger loads the respective api swagger doc.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by amit12cool** [comment]
Raised this there too yesterday, but no response yet.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
